import { person } from './helpers';

/** 全球跨区域公众人物 */
export const GLOBAL_PERSONS = [
  // ── 国际组织领袖 ──
  person('per-g-1', '安东尼奥·古特雷斯', '联合国秘书长', '政治', ['global'], -73.97, 40.75, '葡萄牙前总理，2017 年起任联合国秘书长，主导全球气候与和平议程。', { since: 2017, birthYear: 1949, nationality: '葡萄牙', wikipedia: 'https://zh.wikipedia.org/wiki/安东尼奥·古特雷斯' }),
  person('per-g-2', '乌尔苏拉·冯德莱恩', '欧盟委员会主席', '政治', ['global', 'western_europe'], 4.35, 50.85, '欧盟行政首脑，推动绿色协议与对华经贸政策协调。', { since: 2019, birthYear: 1958, nationality: '德国', wikipedia: 'https://zh.wikipedia.org/wiki/乌尔苏拉·冯德莱恩' }),
  person('per-g-3', '克里斯蒂娜·拉加德', '欧洲央行行长', '经济', ['global', 'western_europe'], 2.35, 48.86, '前 IMF 总裁，主导欧元区货币政策与通胀应对。', { since: 2019, birthYear: 1956, nationality: '法国', wikipedia: 'https://zh.wikipedia.org/wiki/克里斯蒂娜·拉加德' }),
  person('per-g-4', '杰罗姆·鲍威尔', '美联储主席', '经济', ['global', 'north_america'], -77.04, 38.90, '美国联邦储备委员会主席，设定美元利率与全球流动性基调。', { since: 2018, birthYear: 1953, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/杰罗姆·鲍威尔' }),
  person('per-g-7', '延斯·斯托尔滕贝格', '北约秘书长', '军事', ['global', 'western_europe'], 4.35, 50.85, '前挪威首相，协调北约东扩与乌克兰援助。', { since: 2014, birthYear: 1959, nationality: '挪威', wikipedia: 'https://zh.wikipedia.org/wiki/延斯·斯托尔滕贝格' }),
  person('per-g-8', '谭德塞', '世卫组织总干事', '社会', ['global'], 6.14, 46.20, '埃塞俄比亚公共卫生专家，主导全球卫生应急与疫苗公平。', { since: 2017, birthYear: 1965, nationality: '埃塞俄比亚', wikipedia: 'https://zh.wikipedia.org/wiki/谭德塞' }),
  person('per-g-25', '中满泉', '联合国裁军事务副秘书长', '政治', ['global'], -73.97, 40.75, '日本外交官，推动核不扩散与裁军议程。', { since: 2017, nationality: '日本', wikipedia: 'https://en.wikipedia.org/wiki/Izumi_Nakamitsu' }),
  person('per-g-26', '拉斐尔·格罗西', '国际原子能机构总干事', '政治', ['global'], 16.36, 48.21, '监督全球核能安全与伊朗核查。', { since: 2019, birthYear: 1961, nationality: '阿根廷', wikipedia: 'https://zh.wikipedia.org/wiki/拉斐尔·格罗西' }),
  person('per-g-28', '菲利蒙·扬', '联合国大会主席(第79届)', '政治', ['global'], -73.97, 40.75, '喀麦隆前总理，主持第79届联大议程。', { since: 2024, nationality: '喀麦隆' }),
  person('per-g-29', '瓦妮莎·弗雷泽尔', '联合国大会主席(第78届)', '政治', ['global'], -73.97, 40.75, '特立尼达和多巴哥外交官，推动多边主义改革。', { since: 2023, nationality: '特立尼达和多巴哥' }),
  person('per-g-30', '恰巴·柯罗希', '联合国大会主席(第77届)', '政治', ['global'], -73.97, 40.75, '匈牙利外交官，主持可持续发展议程。', { since: 2022, nationality: '匈牙利' }),
  person('per-g-31', '阿明娜·穆罕默德', '联合国常务副秘书长', '政治', ['global'], -73.97, 40.75, '肯尼亚外交官，协调联合国改革与可持续发展目标。', { since: 2017, birthYear: 1961, nationality: '肯尼亚' }),
  person('per-g-32', '沃尔坎·博兹克尔', '联合国经社理事会主席', '政治', ['global'], -73.97, 40.75, '土耳其外交官，推动发展融资与国际合作。', { since: 2024, nationality: '土耳其' }),
  person('per-g-33', '法比安·马约拉尔', '国际劳工组织总干事', '社会', ['global'], 6.14, 46.20, '推动全球劳工标准与体面就业议程。', { since: 2022, nationality: '法国' }),
  person('per-g-34', '奥伯特·托因', '国际民航组织秘书长', '社会', ['global'], -73.57, 45.50, '墨西哥外交官，协调国际航空安全与减排。', { since: 2021, nationality: '墨西哥' }),
  person('per-g-35', '里德·普拉萨德', '国际电信联盟秘书长', '社会', ['global'], 6.14, 46.20, '推动全球数字基础设施与频谱管理。', { since: 2023, nationality: '美国' }),
  person('per-g-36', '因加·金加', '世界气象组织秘书长', '社会', ['global'], 6.14, 46.20, '阿根廷气象学家，协调全球气候监测与预警。', { since: 2024, nationality: '阿根廷' }),
  person('per-g-37', '奥德蕾·阿祖莱', '联合国教科文组织总干事', '文化', ['global'], 2.32, 48.87, '法国前文化部长，推动文化遗产保护与教育公平。', { since: 2017, birthYear: 1972, nationality: '法国', wikipedia: 'https://zh.wikipedia.org/wiki/奥德蕾·阿祖莱' }),
  person('per-g-38', '尼尔斯·安德森', '经合组织秘书长', '经济', ['global', 'western_europe'], 2.32, 48.87, '前丹麦财政部长，协调发达经济体政策研究。', { since: 2021, nationality: '丹麦' }),
  person('per-g-39', '马蒂亚斯·科曼', '国际能源署执行董事', '经济', ['global'], 2.32, 48.87, '比利时能源专家，协调全球能源安全与转型。', { since: 2023, nationality: '比利时' }),
  person('per-g-40', '恩戈齐·奥孔乔-伊韦阿拉', '世界贸易组织总干事', '经济', ['global'], 6.14, 46.20, '尼日利亚前财政部长，首位女性 WTO 总干事。', { since: 2021, birthYear: 1954, nationality: '尼日利亚', wikipedia: 'https://zh.wikipedia.org/wiki/恩戈齐·奥孔乔-伊韦阿拉' }),
  person('per-g-41', '法比奥·贝尔托内', '国际移民组织总干事', '社会', ['global'], 6.14, 46.20, '意大利外交官，协调全球移民保护与人道响应。', { since: 2023, nationality: '意大利' }),
  person('per-g-42', '艾米·波普', '国际移民组织总干事', '社会', ['global'], 6.14, 46.20, '美国律师，首位女性 IOM 总干事。', { since: 2024, nationality: '美国' }),
  person('per-g-43', '约翰·金', '联合国难民署高级专员', '社会', ['global'], 6.14, 46.20, '荷兰前外长，领导全球难民保护。', { since: 2020, nationality: '荷兰' }),
  person('per-g-44', '辛迪·霍恩', '联合国人道事务副秘书长', '社会', ['global'], -73.97, 40.75, '英国外交官，协调全球人道危机响应。', { since: 2024, nationality: '英国' }),
  person('per-g-45', '普拉米拉·帕滕', '联合国妇女署执行主任', '社会', ['global'], -73.97, 40.75, '毛里求斯律师，推动性别平等与妇女赋权。', { since: 2021, nationality: '毛里求斯' }),
  person('per-g-46', '莫罗·希梅内斯', '联合国开发计划署署长', '经济', ['global'], -73.97, 40.75, '前葡萄牙环境部长，推动全球可持续发展。', { since: 2024, nationality: '葡萄牙' }),
  person('per-g-47', '阿奇姆·施泰纳', '联合国开发计划署前署长', '经济', ['global'], -73.97, 40.75, '德国环境专家，推动气候融资与绿色转型。', { since: 2017, nationality: '德国' }),
  person('per-g-48', '英格尔·安德森', '联合国环境署执行主任', '社会', ['global'], -73.97, 40.75, '丹麦经济学家，主导全球环境治理与塑料公约。', { since: 2022, nationality: '丹麦' }),
  person('per-g-49', '西蒙·斯蒂尔', '联合国气候变化框架公约执行秘书', '社会', ['global'], 6.14, 46.20, '前格拉纳达环境部长，主持 COP 气候谈判。', { since: 2022, nationality: '格拉纳达' }),
  person('per-g-50', '优素福·纳达', '国际刑警组织秘书长', '社会', ['global'], 4.85, 45.76, '德国警务专家，协调跨国执法合作。', { since: 2024, nationality: '德国' }),
  person('per-g-51', '刘振民', '联合国主管经济事务副秘书长', '经济', ['global'], -73.97, 40.75, '中国外交官，推动可持续发展融资。', { since: 2022, nationality: '中国' }),
  person('per-g-52', '阿纳徳·库马尔', '国际海事组织秘书长', '经济', ['global'], -0.13, 51.50, '印度海事专家，协调全球航运安全与减排。', { since: 2024, nationality: '印度' }),
  person('per-g-53', '贾亚特玛·维克拉马纳亚克', '联合国青年特使', '社会', ['global'], -73.97, 40.75, '斯里兰卡活动家，推动青年参与可持续发展。', { since: 2023, nationality: '斯里兰卡' }),
  person('per-g-54', '阿卜杜拉·沙希德', '联合国大会前主席', '政治', ['global'], -73.97, 40.75, '马尔代夫外长，推动小岛屿国家议程。', { since: 2021, nationality: '马尔代夫' }),
  person('per-g-55', '阿明·侯赛因', '联合国贸发会议秘书长', '经济', ['global'], 6.14, 46.20, '前孟加拉国商务部长，推动发展中国家贸易。', { since: 2024, nationality: '孟加拉国' }),
  person('per-g-56', '塞西莉亚·阿科斯塔', '联合国工业发展组织总干事', '经济', ['global'], 16.36, 48.21, '玻利维亚外交官，推动包容性工业发展。', { since: 2022, nationality: '玻利维亚' }),
  person('per-g-57', '凯瑟琳·罗素', '联合国儿童基金会执行主任', '社会', ['global'], -73.97, 40.75, '美国政府前官员，推动全球儿童保护。', { since: 2022, nationality: '美国' }),
  person('per-g-58', '纳塔利娅·卡内姆', '联合国人口基金执行主任', '社会', ['global'], -73.97, 40.75, '巴拿马医生，推动生殖健康与人口议程。', { since: 2017, nationality: '巴拿马' }),
  person('per-g-59', '戴维·比斯利', '世界粮食计划署前执行干事', '社会', ['global'], -73.97, 40.75, '前南卡州长，协调全球粮食援助。', { since: 2017, nationality: '美国' }),
  person('per-g-60', '辛迪·麦凯恩', '世界粮食计划署执行干事', '社会', ['global'], -73.97, 40.75, '美国人道主义者，领导全球反饥饿行动。', { since: 2023, nationality: '美国' }),

  // ── 全球国家领袖（跨区）──
  person('per-g-10', '穆罕默德·本·萨勒曼', '沙特王储兼首相', '政治', ['global', 'middleeast'], 46.72, 24.69, '沙特实际统治者，主导 Vision 2030 与欧佩克+产量政策。', { since: 2017, birthYear: 1985, nationality: '沙特阿拉伯', wikipedia: 'https://zh.wikipedia.org/wiki/穆罕默德·本·萨勒曼' }),
  person('per-g-11', '纳伦德拉·莫迪', '印度总理', '政治', ['global', 'asia_pacific'], 77.21, 28.61, '印度人民党领袖，推动「印度制造」与印太战略参与。', { since: 2014, birthYear: 1950, nationality: '印度', wikipedia: 'https://zh.wikipedia.org/wiki/纳伦德拉·莫迪' }),
  person('per-g-14', '弗拉基米尔·普京', '俄罗斯总统', '政治', ['global', 'eastern_europe'], 37.62, 55.75, '俄罗斯最高领导人，主导对乌特别军事行动与能源外交。', { since: 2000, birthYear: 1952, nationality: '俄罗斯', wikipedia: 'https://zh.wikipedia.org/wiki/弗拉基米尔·普京' }),
  person('per-g-15', '习近平', '中国国家主席', '政治', ['global', 'china'], 116.40, 39.90, '中共中央总书记，提出中国式现代化与「一带一路」倡议。', { since: 2012, birthYear: 1953, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/习近平' }),
  person('per-g-16', '唐纳德·特朗普', '美国总统', '政治', ['global', 'north_america', 'middleeast'], -77.04, 38.90, '共和党籍总统，主导美国贸易、移民与中东军事政策。', { since: 2025, birthYear: 1946, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/唐納·川普' }),
  person('per-g-21', '本雅明·内塔尼亚胡', '以色列总理', '政治', ['global', 'middleeast'], 35.21, 31.77, '以色列政坛资深人物，主导对伊朗与黎巴嫩安全政策。', { since: 2022, birthYear: 1949, nationality: '以色列', wikipedia: 'https://zh.wikipedia.org/wiki/本雅明·内塔尼亚胡' }),

  // ── 全球科技与商业领袖 ──
  person('per-g-17', '埃隆·马斯克', '特斯拉/SpaceX CEO', '经济', ['global', 'north_america'], -118.24, 34.05, '科技企业家，影响电动车、航天与社交媒体舆论生态。', { since: 2002, birthYear: 1971, nationality: '美国/南非/加拿大', netWorthUsd: 350_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/埃隆·马斯克' }),
  person('per-g-61', '蒂姆·库克', '苹果公司 CEO', '经济', ['global', 'north_america'], -122.03, 37.33, '掌舵苹果全球供应链与服务生态，推动隐私与碳中和。', { since: 2011, birthYear: 1960, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/蒂姆·库克' }),
  person('per-g-62', '桑达尔·皮查伊', 'Alphabet/谷歌 CEO', '经济', ['global', 'north_america', 'asia_pacific'], -122.08, 37.42, '印度裔工程师，领导谷歌搜索、Android 与 AI 战略。', { since: 2015, birthYear: 1972, nationality: '美国/印度', wikipedia: 'https://zh.wikipedia.org/wiki/桑达尔·皮查伊' }),
  person('per-g-63', '萨蒂亚·纳德拉', '微软 CEO', '经济', ['global', 'north_america'], -122.13, 47.64, '印度裔高管，推动微软云计算与 AI（Copilot）转型。', { since: 2014, birthYear: 1967, nationality: '美国/印度', wikipedia: 'https://zh.wikipedia.org/wiki/萨蒂亚·纳德拉' }),
  person('per-g-64', '马克·扎克伯格', 'Meta 公司 CEO', '经济', ['global', 'north_america'], -122.15, 37.48, 'Facebook 创始人，主导社交网络与元宇宙战略。', { since: 2004, birthYear: 1984, nationality: '美国', netWorthUsd: 180_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/马克·扎克伯格' }),
  person('per-g-65', '杰夫·贝索斯', '亚马逊创始人', '经济', ['global', 'north_america'], -122.33, 47.61, '电商与云计算先驱，拥有《华盛顿邮报》与蓝色起源。', { since: 1994, birthYear: 1964, nationality: '美国', netWorthUsd: 200_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/杰夫·贝索斯' }),
  person('per-g-66', '黄仁勋', '英伟达 CEO', '经济', ['global', 'north_america', 'asia_pacific'], -122.10, 37.38, '台裔工程师，英伟达创始人，引领全球 GPU 与 AI 算力浪潮。', { since: 1993, birthYear: 1963, nationality: '美国/中国台湾', wikipedia: 'https://zh.wikipedia.org/wiki/黄仁勋' }),
  person('per-g-67', '比尔·盖茨', '微软联合创始人', '经济', ['global', 'north_america'], -122.13, 47.64, '微软联合创始人，比尔及梅琳达·盖茨基金会联合主席。', { since: 1975, birthYear: 1955, nationality: '美国', netWorthUsd: 130_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/比尔·盖茨' }),
  person('per-g-68', '伯纳德·阿诺特', 'LVMH CEO', '经济', ['global', 'western_europe'], 2.34, 48.87, '奢侈品帝国 LVMH 掌门人，多次登顶全球首富。', { since: 1989, birthYear: 1949, nationality: '法国', netWorthUsd: 200_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/贝尔纳·阿尔诺' }),
  person('per-g-69', '马云', '阿里巴巴创始人', '经济', ['global', 'asia_pacific', 'china'], 120.16, 30.27, '阿里巴巴创始人，中国电商与数字支付先驱。', { since: 1999, birthYear: 1964, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/马云' }),
  person('per-g-70', '马化腾', '腾讯 CEO', '经济', ['global', 'china'], 113.93, 22.54, '腾讯创始人，微信生态与中国互联网社交核心。', { since: 1998, birthYear: 1971, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/马化腾' }),
  person('per-g-71', '孙正义', '软银集团创始人', '经济', ['global', 'asia_pacific'], 139.77, 35.67, '韩裔日本企业家，软银愿景基金与全球科技投资。', { since: 1981, birthYear: 1957, nationality: '日本', wikipedia: 'https://zh.wikipedia.org/wiki/孙正义' }),
  person('per-g-72', '布赖恩·切斯基', '爱彼迎 CEO', '经济', ['global', 'north_america'], -122.42, 37.77, 'Airbnb 联合创始人，重塑全球短租与旅游经济。', { since: 2008, birthYear: 1981, nationality: '美国' }),
  person('per-g-73', '帕特·格尔辛格', '英特尔 CEO', '经济', ['global', 'north_america'], -121.96, 37.38, '英特尔 CEO，推动芯片制造复兴与代工战略。', { since: 2021, birthYear: 1961, nationality: '美国' }),
  person('per-g-74', '阿维德·克里希南', '微软 AI 主管', '经济', ['global', 'north_america'], -122.13, 47.64, '领导微软 Copilot 与 OpenAI 合作的产品化。', { since: 2023, nationality: '美国' }),
  person('per-g-75', '山姆·奥特曼', 'OpenAI CEO', '经济', ['global', 'north_america'], -122.42, 37.78, 'OpenAI CEO，ChatGPT 与生成式 AI 革命引领者。', { since: 2019, birthYear: 1985, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/山姆·奥特曼' }),
  person('per-g-76', '德米斯·哈萨比斯', 'Google DeepMind CEO', '经济', ['global', 'western_europe', 'north_america'], -0.13, 51.50, 'AlphaGo 与 Gemini 背后的 AI 先驱，诺贝尔化学奖得主。', { since: 2010, birthYear: 1976, nationality: '英国', wikipedia: 'https://zh.wikipedia.org/wiki/戴密斯·哈萨比斯' }),
  person('per-g-77', '达里奥·阿莫代伊', 'Anthropic CEO', '经济', ['global', 'north_america'], -122.42, 37.78, 'Anthropic 创始人，推动 AI 安全与 Claude 模型。', { since: 2021, nationality: '美国' }),
  person('per-g-78', '李在镕', '三星电子会长', '经济', ['global', 'asia_pacific'], 126.98, 37.57, '三星集团会长，掌舵全球半导体与电子产业。', { since: 2022, birthYear: 1968, nationality: '韩国', wikipedia: 'https://zh.wikipedia.org/wiki/李在镕' }),
  person('per-g-79', '张一鸣', '字节跳动创始人', '经济', ['global', 'china'], 116.40, 39.90, '字节跳动创始人，TikTok/抖音 全球短视频生态。', { since: 2012, birthYear: 1983, nationality: '中国' }),
  person('per-g-80', '雷军', '小米集团创始人', '经济', ['global', 'china'], 116.40, 39.90, '小米创始人，智能手机与电动汽车跨界。', { since: 2010, birthYear: 1969, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/雷军' }),
  person('per-g-81', '任正非', '华为创始人', '经济', ['global', 'china'], 114.06, 22.55, '华为创始人，全球通信设备与芯片自主化核心人物。', { since: 1987, birthYear: 1944, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/任正非' }),
  person('per-g-82', '王传福', '比亚迪创始人', '经济', ['global', 'china'], 114.06, 22.55, '比亚迪创始人，全球最大新能源汽车制造商掌门。', { since: 1995, birthYear: 1966, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/王传福' }),
  person('per-g-83', '迈克尔·戴尔', '戴尔科技创始人', '经济', ['global', 'north_america'], -97.74, 30.27, '戴尔公司创始人，推动企业级 IT 与服务器市场。', { since: 1984, birthYear: 1965, nationality: '美国' }),
  person('per-g-84', '阿尼尔·乔治', '谷歌云 CEO', '经济', ['global', 'north_america'], -122.08, 37.42, '领导谷歌云计算与企业服务。', { since: 2019, nationality: '美国' }),
  person('per-g-85', '亚当·诺伊曼', 'WeWork 前CEO', '经济', ['global', 'north_america'], -73.99, 40.72, 'WeWork 创始人，共享办公模式先驱。', { since: 2010, birthYear: 1979, nationality: '以色列/美国' }),
  person('per-g-86', '里德·霍夫曼', '领英联合创始人', '经济', ['global', 'north_america'], -122.17, 37.43, 'LinkedIn 联合创始人，Greylock 合伙人，AI 投资者。', { since: 2002, birthYear: 1967, nationality: '美国' }),
  person('per-g-87', '帕特里克·科里森', 'Stripe CEO', '经济', ['global', 'western_europe'], -6.26, 53.35, 'Stripe 联合创始人，全球在线支付基础设施。', { since: 2010, birthYear: 1988, nationality: '爱尔兰' }),
  person('per-g-88', '维托尔德·沃尼', '瑞银集团 CEO', '经济', ['global', 'western_europe'], 8.54, 47.37, '瑞银集团 CEO，管理全球最大财富管理平台。', { since: 2023, nationality: '波兰' }),
  person('per-g-89', '詹姆斯·戈曼', '摩根士丹利前CEO', '经济', ['global', 'western_europe', 'asia_pacific'], 151.21, -33.87, '摩根士丹利前董事长，澳大利亚裔银行家。', { since: 2010, birthYear: 1958, nationality: '澳大利亚/美国' }),
  person('per-g-90', '杰米·戴蒙', '摩根大通 CEO', '经济', ['global', 'north_america'], -74.01, 40.71, '摩根大通董事长兼 CEO，美国银行业最具影响力人物之一。', { since: 2005, birthYear: 1956, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/杰米·戴蒙' }),
  person('per-g-91', '拉里·芬克', '贝莱德 CEO', '经济', ['global', 'north_america'], -74.01, 40.71, '贝莱德创始人，全球最大资管公司掌门，ESG 投资倡导者。', { since: 1988, birthYear: 1952, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/拉里·芬克' }),
  person('per-g-92', '沃伦·巴菲特', '伯克希尔·哈撒韦 CEO', '经济', ['global', 'north_america'], -95.93, 41.26, '「奥马哈先知」，价值投资标杆，伯克希尔董事长。', { since: 1970, birthYear: 1930, nationality: '美国', netWorthUsd: 130_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/沃伦·巴菲特' }),
  person('per-g-93', '雷·达里奥', '桥水基金创始人', '经济', ['global', 'north_america'], -73.83, 41.13, '桥水基金创始人，《原则》作者，全球宏观投资先驱。', { since: 1975, birthYear: 1949, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/雷·达里奥' }),
  person('per-g-94', '乔治·索罗斯', '索罗斯基金管理创始人', '经济', ['global', 'north_america', 'eastern_europe'], -73.97, 40.76, '量子基金创始人，金融大鳄与开放社会基金会赞助人。', { since: 1970, birthYear: 1930, nationality: '美国/匈牙利', wikipedia: 'https://zh.wikipedia.org/wiki/乔治·索罗斯' }),
  person('per-g-95', '穆克什·安巴尼', '信实工业董事长', '经济', ['global', 'asia_pacific'], 72.88, 19.09, '信实工业掌门，印度能源、电信与零售巨头。', { since: 2002, birthYear: 1957, nationality: '印度', wikipedia: 'https://zh.wikipedia.org/wiki/穆克什·安巴尼' }),
  person('per-g-96', '高塔姆·阿达尼', '阿达尼集团创始人', '经济', ['global', 'asia_pacific'], 72.57, 23.02, '阿达尼集团创始人，印度港口、能源与基建巨头。', { since: 1988, birthYear: 1962, nationality: '印度', wikipedia: 'https://zh.wikipedia.org/wiki/高塔姆·阿达尼' }),
  person('per-g-97', '豪尔赫·保罗·雷曼', '3G 资本创始人', '经济', ['global', 'latin_america'], -46.63, -23.55, '巴西啤酒与食品巨头，百威英博、卡夫亨氏幕后。', { since: 1980, birthYear: 1939, nationality: '巴西' }),
  person('per-g-98', '卡洛斯·斯利姆', '美洲电信创始人', '经济', ['global', 'latin_america'], -99.13, 19.43, '墨西哥电信大亨，拉美首富。', { since: 1990, birthYear: 1940, nationality: '墨西哥', netWorthUsd: 90_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/卡洛斯·斯利姆' }),
  person('per-g-99', '阿里科·丹格特', '丹格特集团创始人', '经济', ['global'], 3.38, 6.52, '尼日利亚水泥与炼油大亨，非洲首富。', { since: 1981, birthYear: 1957, nationality: '尼日利亚', netWorthUsd: 15_000_000_000, wikipedia: 'https://zh.wikipedia.org/wiki/阿里科·丹格特' }),
  person('per-g-100', '约翰·里德', '世界银行前行长', '经济', ['global'], -77.04, 38.90, '美国企业家，领导世界银行减贫与发展融资。', { since: 2023, nationality: '美国' }),

  // ── 全球文化与知识界人物 ──
  person('per-g-18', '泰勒·斯威夫特', '歌手、词曲作者', '文化', ['global', 'north_america'], -86.78, 36.16, '全球流行文化符号，巡演经济与文化影响力巨大。', { since: 2006, birthYear: 1989, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/泰勒·斯威夫特' }),
  person('per-g-19', '格蕾塔·通贝里', '气候活动家', '社会', ['global', 'western_europe'], 18.07, 59.33, '瑞典青年气候运动领袖，推动全球减碳舆论。', { since: 2018, birthYear: 2003, nationality: '瑞典', wikipedia: 'https://zh.wikipedia.org/wiki/格蕾塔·通贝里' }),
  person('per-g-20', '马拉拉·优素福扎伊', '教育活动家', '社会', ['global', 'middleeast'], 73.05, 33.69, '诺贝尔和平奖得主，倡导女童教育权利。', { since: 2012, birthYear: 1997, nationality: '巴基斯坦', wikipedia: 'https://zh.wikipedia.org/wiki/马拉拉·优素福扎伊' }),
  person('per-g-22', '费利佩六世', '西班牙国王', '文化', ['global', 'western_europe'], -3.70, 40.42, '西班牙国家象征，在外交礼仪与拉美纽带中发挥软实力。', { since: 2014, birthYear: 1968, nationality: '西班牙' }),
  person('per-g-101', '宫崎骏', '动画导演', '文化', ['global', 'asia_pacific'], 139.69, 35.69, '吉卜力工作室创始人，奥斯卡终身成就奖得主。', { since: 1985, birthYear: 1941, nationality: '日本', wikipedia: 'https://zh.wikipedia.org/wiki/宫崎骏' }),
  person('per-g-102', '汉斯·季默', '电影配乐作曲家', '文化', ['global', 'western_europe'], 13.40, 52.52, '德国电影配乐大师，奥斯卡与格莱美得主。', { since: 1980, birthYear: 1957, nationality: '德国' }),
  person('per-g-103', '坂本龙一', '作曲家', '文化', ['global', 'asia_pacific'], 139.69, 35.69, '日本作曲家，《末代皇帝》配乐奥斯卡得主，2023年逝世。', { since: 1978, birthYear: 1952, deathYear: 2023, status: 'deceased', nationality: '日本', wikipedia: 'https://zh.wikipedia.org/wiki/坂本龙一' }),
  person('per-g-104', '杨紫琼', '演员', '文化', ['global', 'asia_pacific'], 101.69, 3.14, '马来西亚华裔演员，奥斯卡最佳女主角得主。', { since: 1980, birthYear: 1962, nationality: '马来西亚', wikipedia: 'https://zh.wikipedia.org/wiki/杨紫琼' }),
  person('per-g-105', '李安', '电影导演', '文化', ['global', 'asia_pacific', 'china'], 121.50, 25.03, '台湾电影导演，两度奥斯卡最佳导演得主。', { since: 1990, birthYear: 1954, nationality: '中国台湾', wikipedia: 'https://zh.wikipedia.org/wiki/李安' }),
  person('per-g-106', '克里斯托弗·诺兰', '电影导演', '文化', ['global', 'western_europe', 'north_america'], -0.13, 51.50, '英国电影导演，《奥本海默》奥斯卡最佳导演。', { since: 1998, birthYear: 1970, nationality: '英国/美国', wikipedia: 'https://zh.wikipedia.org/wiki/克里斯托弗·诺兰' }),
  person('per-g-107', 'BTS 防弹少年团', '音乐团体', '文化', ['global', 'asia_pacific'], 126.98, 37.57, '韩国男子音乐团体，K-pop 全球化的标志。', { since: 2013, nationality: '韩国' }),
  person('per-g-108', '比莉·艾利什', '歌手', '文化', ['global', 'north_america'], -118.24, 34.05, '美国流行歌手，多座格莱美奖得主。', { since: 2015, birthYear: 2001, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/比莉·艾利什' }),
  person('per-g-109', '村上春树', '作家', '文化', ['global', 'asia_pacific'], 139.69, 35.69, '日本作家，多次诺贝尔文学奖候选人选。', { since: 1979, birthYear: 1949, nationality: '日本', wikipedia: 'https://zh.wikipedia.org/wiki/村上春树' }),
  person('per-g-110', '奥尔罕·帕慕克', '作家', '文化', ['global', 'middleeast'], 28.98, 41.01, '土耳其作家，诺贝尔文学奖得主。', { since: 1982, birthYear: 1952, nationality: '土耳其', wikipedia: 'https://zh.wikipedia.org/wiki/奥尔罕·帕慕克' }),
  person('per-g-111', '石黑一雄', '作家', '文化', ['global', 'western_europe', 'asia_pacific'], 0.12, 51.50, '日裔英国作家，诺贝尔文学奖得主。', { since: 1982, birthYear: 1954, nationality: '英国/日本', wikipedia: 'https://zh.wikipedia.org/wiki/石黑一雄' }),
  person('per-g-112', '余华', '作家', '文化', ['global', 'china'], 120.16, 30.27, '中国当代作家，《活着》《许三观卖血记》作者。', { since: 1980, birthYear: 1960, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/余华' }),
  person('per-g-113', '阿莉·拉塞尔', '经济学家', '经济', ['global', 'north_america'], -0.13, 51.50, '行为经济学先驱，诺贝尔经济学奖得主。', { since: 1990, nationality: '美国' }),
  person('per-g-114', '埃丝特·迪弗洛', '经济学家', '经济', ['global', 'western_europe'], 2.35, 48.86, 'MIT 经济学家，最年轻诺贝尔经济学奖得主。', { since: 2000, birthYear: 1972, nationality: '法国/美国', wikipedia: 'https://zh.wikipedia.org/wiki/埃丝特·迪弗洛' }),
  person('per-g-115', '阿比吉特·班纳吉', '经济学家', '经济', ['global', 'asia_pacific'], 72.88, 19.09, 'MIT 经济学家，诺贝尔经济学奖得主，贫困研究。', { since: 1990, nationality: '美国/印度' }),
  person('per-g-116', '克劳迪娅·戈尔丁', '经济学家', '经济', ['global', 'north_america'], -71.12, 42.38, '哈佛经济学家，2023 诺贝尔经济学奖得主，女性劳动研究。', { since: 1990, birthYear: 1946, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/克劳迪娅·戈尔丁' }),
  person('per-g-117', '达隆·阿西莫格鲁', '经济学家', '经济', ['global', 'western_europe', 'north_america'], -71.12, 42.38, 'MIT 经济学家，2024 诺贝尔经济学奖得主，《国家为什么会失败》。', { since: 1990, nationality: '美国/土耳其', wikipedia: 'https://zh.wikipedia.org/wiki/达隆·阿西莫格鲁' }),
  person('per-g-118', '尤瓦尔·赫拉利', '历史学家', '文化', ['global', 'middleeast'], 35.22, 31.78, '以色列历史学家，《人类简史》系列全球畅销作者。', { since: 2011, birthYear: 1976, nationality: '以色列', wikipedia: 'https://zh.wikipedia.org/wiki/尤瓦尔·赫拉利' }),
  person('per-g-119', '弗朗西斯·福山', '政治学家', '文化', ['global', 'north_america'], -122.17, 37.43, '《历史的终结》作者，政治秩序研究。', { since: 1989, birthYear: 1952, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/弗朗西斯·福山' }),
  person('per-g-120', '彼得·蒂尔', '风险投资家', '经济', ['global', 'north_america'], -122.42, 37.78, 'PayPal 联合创始人，Founders Fund，《从0到1》作者。', { since: 1998, birthYear: 1967, nationality: '美国/德国', wikipedia: 'https://zh.wikipedia.org/wiki/彼得·蒂尔' }),

  // ── 全球科学家与思想家 ──
  person('per-g-121', '珍妮弗·杜德纳', '生物化学家', '文化', ['global', 'north_america'], -122.26, 37.87, 'CRISPR 基因编辑先驱，诺贝尔化学奖得主。', { since: 2012, birthYear: 1964, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/珍妮弗·杜德纳' }),
  person('per-g-122', '埃马纽埃尔·卡彭蒂耶', '微生物学家', '文化', ['global', 'western_europe'], 2.35, 48.86, 'CRISPR 共同发现者，诺贝尔化学奖得主。', { since: 2012, birthYear: 1968, nationality: '法国', wikipedia: 'https://zh.wikipedia.org/wiki/埃马纽埃尔·卡彭蒂耶' }),
  person('per-g-123', '卡塔琳·考里科', '生物化学家', '文化', ['global', 'eastern_europe', 'north_america'], -75.16, 39.98, 'mRNA 疫苗先驱，诺贝尔生理学或医学奖得主。', { since: 2020, birthYear: 1955, nationality: '美国/匈牙利', wikipedia: 'https://zh.wikipedia.org/wiki/卡塔琳·考里科' }),
  person('per-g-124', '德鲁·韦斯曼', '免疫学家', '文化', ['global', 'north_america'], -75.16, 39.98, 'mRNA 疫苗先驱，诺贝尔生理学或医学奖得主。', { since: 2020, birthYear: 1959, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/德鲁·韦斯曼' }),
  person('per-g-125', '杰弗里·辛顿', '计算机科学家', '文化', ['global', 'western_europe', 'north_america'], -79.38, 43.65, '「AI 之父」，深度学习先驱，2024 诺贝尔物理学奖得主。', { since: 1980, birthYear: 1947, nationality: '加拿大/英国', wikipedia: 'https://zh.wikipedia.org/wiki/杰弗里·辛顿' }),
  person('per-g-126', '杨立昆', '计算机科学家', '文化', ['global', 'western_europe', 'north_america'], 2.35, 48.86, '卷积神经网络之父，Meta 首席 AI 科学家，图灵奖得主。', { since: 1988, birthYear: 1960, nationality: '法国/美国', wikipedia: 'https://zh.wikipedia.org/wiki/杨立昆' }),
  person('per-g-127', '约书亚·本吉奥', '计算机科学家', '文化', ['global', 'north_america'], -73.57, 45.50, '深度学习先驱，蒙特利尔大学教授，图灵奖得主。', { since: 1990, birthYear: 1964, nationality: '加拿大', wikipedia: 'https://zh.wikipedia.org/wiki/约书亚·本吉奥' }),
  person('per-g-128', '安德鲁·吴', '计算机科学家', '文化', ['global', 'north_america', 'asia_pacific'], -122.17, 37.43, '斯坦福教授，Coursera 联合创始人，AI 教育先驱。', { since: 2011, birthYear: 1976, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/吴恩达' }),
  person('per-g-129', '李飞飞', '计算机科学家', '文化', ['global', 'north_america'], -122.17, 37.43, 'ImageNet 创立者，斯坦福以人为本 AI 研究院联席院长。', { since: 2009, birthYear: 1976, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/李飞飞' }),
  person('per-g-130', '安德烈·海姆', '物理学家', '文化', ['global', 'western_europe'], -2.24, 53.48, '石墨烯发现者，诺贝尔物理学奖得主。', { since: 2004, nationality: '英国/俄罗斯' }),
  person('per-g-131', '米歇尔·马约尔', '天体物理学家', '文化', ['global', 'western_europe'], 6.14, 46.20, '首颗系外行星发现者，诺贝尔物理学奖得主。', { since: 1995, nationality: '瑞士' }),
  person('per-g-132', '迪迪埃·奎洛兹', '天体物理学家', '文化', ['global', 'western_europe'], 6.14, 46.20, '系外行星共同发现者，诺贝尔物理学奖得主。', { since: 1995, nationality: '瑞士' }),
  person('per-g-133', '基普·索恩', '理论物理学家', '文化', ['global', 'north_america'], -118.13, 34.14, 'LIGO 引力波探测先驱，诺贝尔物理学奖得主。', { since: 2015, nationality: '美国' }),
  person('per-g-134', '彭妮·古尔德', '天文学家', '文化', ['global', 'western_europe'], 0.12, 51.50, '英国皇家天文学家，黑洞与引力研究权威。', { since: 1990, nationality: '英国' }),
  person('per-g-135', '钟南山', '呼吸病学专家', '社会', ['global', 'china'], 113.27, 23.13, '中国工程院院士，新冠疫情期间公共卫生权威。', { since: 2003, birthYear: 1936, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/钟南山' }),

  // ── 全球安全与军事人物 ──
  person('per-g-136', '劳埃德·奥斯汀', '美国前国防部长', '军事', ['global', 'north_america'], -77.04, 38.90, '美国首位非裔国防部长，协调乌克兰与印太安全。', { since: 2021, birthYear: 1953, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/劳埃德·奥斯汀' }),
  person('per-g-137', '马克·米利', '美国前参联会主席', '军事', ['global', 'north_america'], -77.04, 38.90, '美国第20任参谋长联席会议主席，退役上将。', { since: 2019, birthYear: 1958, nationality: '美国' }),
  person('per-g-138', '查尔斯·布朗', '美国参联会主席', '军事', ['global', 'north_america'], -77.04, 38.90, '美国第21任参联会主席，首位非裔空军参谋长。', { since: 2023, nationality: '美国' }),
  person('per-g-139', '瓦列里·格拉西莫夫', '俄军总参谋长', '军事', ['global', 'eastern_europe'], 37.62, 55.75, '俄罗斯武装力量总参谋长，「格拉西莫夫主义」提出者。', { since: 2012, birthYear: 1955, nationality: '俄罗斯', wikipedia: 'https://zh.wikipedia.org/wiki/瓦列里·格拉西莫夫' }),
  person('per-g-140', '谢尔盖·绍伊古', '俄罗斯前国防部长', '军事', ['global', 'eastern_europe'], 37.62, 55.75, '俄罗斯前国防部长，主导军事改革与对乌行动。', { since: 2012, birthYear: 1955, nationality: '俄罗斯', wikipedia: 'https://zh.wikipedia.org/wiki/谢尔盖·绍伊古' }),
  person('per-g-141', '安德烈·别洛乌索夫', '俄罗斯国防部长', '军事', ['global', 'eastern_europe'], 37.62, 55.75, '经济学家出身的俄罗斯新任国防部长。', { since: 2024, birthYear: 1959, nationality: '俄罗斯', wikipedia: 'https://zh.wikipedia.org/wiki/安德烈·别洛乌索夫' }),
  person('per-g-142', '约翰·海滕', '北约军事委员会主席', '军事', ['global', 'western_europe'], 4.35, 50.85, '荷兰海军上将，北约最高军事顾问。', { since: 2024, nationality: '荷兰' }),

  // ── 气候与环保领袖 ──
  person('per-g-143', '威廉·瑞肯', '气候学家', '社会', ['global', 'north_america'], -122.27, 37.87, 'NASA 前气候科学家，「气候警钟」提出者。', { since: 1980, nationality: '美国' }),
  person('per-g-144', '约翰·克里', '美国前气候特使', '政治', ['global', 'north_america'], -77.04, 38.90, '前美国国务卿，拜登政府气候特使。', { since: 2021, birthYear: 1943, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/约翰·克里' }),
  person('per-g-145', '瓦努·希帕', '气候活动家', '社会', ['global'], -149.50, -17.70, '太平洋岛国气候活动家，推动损失与损害基金。', { since: 2015, nationality: '斐济' }),
  person('per-g-146', '亨德里克·斯特凡', '海洋生物学家', '社会', ['global', 'western_europe'], 4.90, 52.37, '深海生态系统研究者，推动公海保护条约。', { since: 2010, nationality: '荷兰' }),

  // ── 宗教领袖 ──
  person('per-g-147', '方济各', '罗马教皇', '文化', ['global', 'latin_america'], 12.45, 41.90, '首位拉丁美洲裔教皇，倡导环境与社会公正。', { since: 2013, birthYear: 1936, nationality: '阿根廷', wikipedia: 'https://zh.wikipedia.org/wiki/方济各_(教宗)' }),
  person('per-g-148', '艾哈迈德·塔耶布', '爱资哈尔大伊玛目', '文化', ['global', 'middleeast'], 31.26, 30.04, '逊尼派最高权威，推动宗教对话与和平。', { since: 2010, nationality: '埃及' }),
  person('per-g-149', '贾斯汀·韦尔比', '坎特伯雷大主教', '文化', ['global', 'western_europe'], 1.01, 51.28, '英国国教精神领袖，推动全球和解。', { since: 2013, nationality: '英国' }),
  person('per-g-150', '达赖喇嘛', '藏传佛教精神领袖', '文化', ['global', 'asia_pacific'], 76.28, 32.23, '第十四世达赖喇嘛，诺贝尔和平奖得主。', { since: 1950, birthYear: 1935, nationality: '中国西藏', wikipedia: 'https://zh.wikipedia.org/wiki/第十四世达赖喇嘛' }),
  person('per-g-151', '阿亚图拉·西斯塔尼', '什叶派大阿亚图拉', '文化', ['global', 'middleeast'], 44.02, 32.62, '伊拉克纳杰夫什叶派最高宗教权威。', { since: 1990, birthYear: 1930, nationality: '伊拉克' }),
  person('per-g-152', '大卫·劳', '世界信义宗联合会主席', '文化', ['global', 'western_europe'], 9.99, 53.55, '德国神学家，推动基督教内部对话。', { since: 2023, nationality: '德国' }),

  // ── 全球媒体与舆论人物 ──
  person('per-g-153', '鲁伯特·默多克', '新闻集团创始人', '文化', ['global', 'western_europe', 'asia_pacific'], 151.21, -33.87, '传媒大亨，新闻集团与福克斯新闻创始人。', { since: 1950, birthYear: 1931, nationality: '澳大利亚/美国', wikipedia: 'https://zh.wikipedia.org/wiki/鲁伯特·默多克' }),
  person('per-g-154', '马克·汤普森', '纽约时报 CEO', '文化', ['global', 'north_america', 'western_europe'], -73.99, 40.72, '前 BBC 总裁，纽约时报公司 CEO。', { since: 2020, nationality: '英国' }),
  person('per-g-155', '费利克斯·奥伯恩', 'CNN 前 CEO', '文化', ['global', 'north_america'], -84.39, 33.75, '前 CNN 董事长，推动全球新闻数字化转型。', { since: 2023, nationality: '美国' }),
  person('per-g-156', '约翰·斯坦', '路透社总编辑', '文化', ['global', 'western_europe'], -0.13, 51.50, '路透社总编辑，协调全球新闻采编。', { since: 2023, nationality: '英国' }),
  person('per-g-157', '旺达·帕特洛', 'Politico CEO', '文化', ['global', 'north_america'], -77.04, 38.90, 'Politico 与 Axel Springer 新闻集团 CEO。', { since: 2021, nationality: '美国' }),

  // ── 体育与流行文化 ──
  person('per-g-158', '里奥·梅西', '足球运动员', '文化', ['global', 'latin_america'], -58.38, -34.60, '阿根廷足球巨星，8 次金球奖得主。', { since: 2004, birthYear: 1987, nationality: '阿根廷', wikipedia: 'https://zh.wikipedia.org/wiki/利昂内尔·梅西' }),
  person('per-g-159', '克里斯蒂亚诺·罗纳尔多', '足球运动员', '文化', ['global', 'western_europe'], -9.14, 38.72, '葡萄牙足球巨星，5 次金球奖得主。', { since: 2002, birthYear: 1985, nationality: '葡萄牙', wikipedia: 'https://zh.wikipedia.org/wiki/克里斯蒂亚诺·罗纳尔多' }),
  person('per-g-160', '勒布朗·詹姆斯', '篮球运动员', '文化', ['global', 'north_america'], -118.24, 34.05, 'NBA 历史总得分王，4 次 MVP 得主。', { since: 2003, birthYear: 1984, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/勒布朗·詹姆斯' }),
  person('per-g-161', '谷爱凌', '自由式滑雪运动员', '文化', ['global', 'china', 'north_america'], -122.42, 37.78, '自由式滑雪奥运冠军，中美文化桥梁。', { since: 2019, birthYear: 2003, nationality: '中国', wikipedia: 'https://zh.wikipedia.org/wiki/谷爱凌' }),

  // ── 全球央行与金融机构 ──
  person('per-g-162', '安德鲁·贝利', '英格兰银行行长', '经济', ['global', 'western_europe'], -0.13, 51.50, '英国央行行长，协调脱欧后金融稳定。', { since: 2020, birthYear: 1959, nationality: '英国', wikipedia: 'https://zh.wikipedia.org/wiki/安德鲁·贝利' }),
  person('per-g-163', '植田和男', '日本银行行长', '经济', ['global', 'asia_pacific'], 139.69, 35.69, '日本银行行长，推动货币政策正常化。', { since: 2023, birthYear: 1951, nationality: '日本', wikipedia: 'https://zh.wikipedia.org/wiki/植田和男' }),
  person('per-g-164', '李昌镛', '亚洲开发银行行长', '经济', ['global', 'asia_pacific'], 120.98, 14.60, '韩国经济学家，亚行行长，推动亚太发展融资。', { since: 2022, nationality: '韩国' }),
  person('per-g-165', '阿古斯丁·卡斯滕斯', '国际清算银行总经理', '经济', ['global', 'latin_america'], 7.59, 47.55, '前墨西哥央行行长，国际清算银行总经理。', { since: 2017, birthYear: 1958, nationality: '墨西哥', wikipedia: 'https://zh.wikipedia.org/wiki/阿古斯丁·卡斯滕斯' }),
  person('per-g-166', '诺希尔·卡达比亚', '国际货币基金组织前总裁', '经济', ['global', 'western_europe'], 2.35, 48.86, '前法国财政部长，IMF 前总裁。', { since: 2011, nationality: '法国' }),

  // ── 国际法与人权 ──
  person('per-g-23', '特奥多罗·欧班尼', '国际法院院长', '政治', ['global'], 4.35, 50.85, '国际司法权威，审理国际争端与战争罪案件。', { since: 2024, nationality: '美国' }),
  person('per-g-167', '纳瓦尼·谢尔盖', '国际刑事法院院长', '政治', ['global', 'western_europe'], 4.30, 52.07, '波兰法官，国际刑事法院院长。', { since: 2024, nationality: '波兰' }),
  person('per-g-168', '卡里马·坎农', '联合国人权事务高级专员', '政治', ['global'], -73.97, 40.75, '奥地利外交官，联合国人权高专。', { since: 2022, nationality: '奥地利' }),
  person('per-g-169', '艾琳·汗', '联合国言论自由特别报告员', '社会', ['global'], -73.97, 40.75, '孟加拉裔英国律师，推动全球言论自由。', { since: 2020, nationality: '英国' }),
  person('per-g-170', '何塞·迪亚兹', '国际法院副院长', '政治', ['global'], -3.70, 40.42, '西班牙法官，国际法院副院长。', { since: 2024, nationality: '西班牙' }),

  // ── 新兴科技与加密货币人物 ──
  person('per-g-171', '维塔利克·布特林', '以太坊创始人', '经济', ['global', 'eastern_europe', 'north_america'], -79.38, 43.65, '俄裔加拿大程序员，以太坊区块链创始人。', { since: 2013, birthYear: 1994, nationality: '加拿大', wikipedia: 'https://zh.wikipedia.org/wiki/维塔利克·布特林' }),
  person('per-g-172', '布莱恩·阿姆斯特朗', 'Coinbase CEO', '经济', ['global', 'north_america'], -122.42, 37.78, 'Coinbase 创始人，美国最大加密交易所掌门。', { since: 2012, birthYear: 1983, nationality: '美国' }),
  person('per-g-173', '赵长鹏', '币安创始人', '经济', ['global', 'asia_pacific'], 114.06, 22.55, '币安创始人，曾为华人首富，后认罪和解。', { since: 2017, birthYear: 1977, nationality: '加拿大/阿联酋', wikipedia: 'https://zh.wikipedia.org/wiki/赵长鹏' }),
  person('per-g-174', '迈克尔·塞勒', '微策略创始人', '经济', ['global', 'north_america'], -77.04, 38.90, '微策略创始人，比特币激进倡导者。', { since: 1989, birthYear: 1965, nationality: '美国' }),
  person('per-g-175', '凯瑟琳·伍德', 'ARK Invest 创始人', '经济', ['global', 'north_america'], -74.01, 40.71, 'ARK Invest 创始人，「木头姐」，颠覆性创新投资。', { since: 2014, birthYear: 1955, nationality: '美国' }),

  // ── 航天与太空探索 ──
  person('per-g-176', '比尔·尼尔森', 'NASA 局长', '政治', ['global', 'north_america'], -77.04, 38.90, '前佛州参议员，NASA 局长，主导阿耳忒弥斯登月。', { since: 2021, birthYear: 1942, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/比尔·尼尔森' }),
  person('per-g-177', '约瑟夫·阿施巴赫', '欧空局局长', '政治', ['global', 'western_europe'], 2.35, 48.86, '奥地利航天专家，欧空局局长。', { since: 2021, nationality: '奥地利' }),
  person('per-g-178', '尹正秀', '韩国航空宇宙研究院院长', '政治', ['global', 'asia_pacific'], 127.31, 36.40, '领导韩国月球与卫星项目。', { since: 2023, nationality: '韩国' }),
  person('per-g-179', '彭妥·苏迪安托', '印尼航天局局长', '政治', ['global', 'asia_pacific'], 106.85, -6.20, '领导印尼卫星与航天发展。', { since: 2024, nationality: '印度尼西亚' }),

  // ── 全球智库与研究 ──
  person('per-g-180', '理查德·哈斯', '外交关系委员会前主席', '政治', ['global', 'north_america'], -73.97, 40.76, '美国外交政策权威，CFR 前主席。', { since: 2003, nationality: '美国' }),
  person('per-g-181', '凯文·拉德', '亚洲协会政策研究院院长', '政治', ['global', 'asia_pacific'], 151.21, -33.87, '前澳大利亚总理，亚洲协会主席。', { since: 2014, nationality: '澳大利亚' }),
  person('per-g-182', '约翰·米尔斯海默', '国际关系学者', '文化', ['global', 'north_america'], -87.65, 41.88, '芝加哥大学教授，进攻性现实主义理论代表。', { since: 1990, birthYear: 1947, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/约翰·米尔斯海默' }),
  person('per-g-183', '约瑟夫·奈', '国际关系学者', '文化', ['global', 'north_america'], -71.12, 42.38, '「软实力」概念提出者，哈佛大学教授。', { since: 1990, birthYear: 1937, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/约瑟夫·奈' }),
  person('per-g-184', '亨利·基辛格', '前美国国务卿', '政治', ['global', 'north_america', 'western_europe'], -73.97, 40.76, '前美国国务卿，地缘战略思想家，2023年逝世。', { since: 1969, birthYear: 1923, deathYear: 2023, status: 'deceased', nationality: '美国/德国', wikipedia: 'https://zh.wikipedia.org/wiki/亨利·基辛格' }),
  person('per-g-185', '兹比格涅夫·布热津斯基', '前美国国家安全顾问', '政治', ['global', 'north_america', 'eastern_europe'], -77.04, 38.90, '《大棋局》作者，地缘战略大师，2017年逝世。', { since: 1977, birthYear: 1928, deathYear: 2017, status: 'deceased', nationality: '美国/波兰' }),

  // ── 诺贝尔奖与公共知识分子 ──
  person('per-g-186', '纳尔逊·曼德拉', '前南非总统', '政治', ['global'], 28.04, -26.20, '反种族隔离斗士，诺贝尔和平奖得主，2013年逝世。', { since: 1994, birthYear: 1918, deathYear: 2013, status: 'deceased', nationality: '南非', wikipedia: 'https://zh.wikipedia.org/wiki/纳尔逊·曼德拉' }),
  person('per-g-187', '穆罕默德·尤努斯', '孟加拉临时政府首席顾问', '政治', ['global', 'asia_pacific'], 90.41, 23.81, '微型金融先驱，诺贝尔和平奖得主，孟加拉临时政府领导人。', { since: 2024, birthYear: 1940, nationality: '孟加拉国', wikipedia: 'https://zh.wikipedia.org/wiki/穆罕默德·尤努斯' }),
  person('per-g-188', '丹尼尔·卡内曼', '心理学家', '文化', ['global', 'north_america', 'middleeast'], -74.66, 40.35, '行为经济学先驱，《思考快与慢》作者，2024年逝世。', { since: 1990, birthYear: 1934, deathYear: 2024, status: 'deceased', nationality: '以色列/美国', wikipedia: 'https://zh.wikipedia.org/wiki/丹尼尔·卡内曼' }),
  person('per-g-189', '阿马蒂亚·森', '经济学家', '文化', ['global', 'asia_pacific', 'western_europe'], -0.13, 51.50, '福利经济学大师，诺贝尔经济学奖得主。', { since: 1998, birthYear: 1933, nationality: '印度/英国', wikipedia: 'https://zh.wikipedia.org/wiki/阿马蒂亚·森' }),
  person('per-g-190', '保罗·克鲁格曼', '经济学家', '文化', ['global', 'north_america'], -74.01, 40.71, '纽约时报专栏作家，诺贝尔经济学奖得主。', { since: 2000, birthYear: 1953, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/保罗·克鲁格曼' }),
  person('per-g-191', '约瑟夫·斯蒂格利茨', '经济学家', '文化', ['global', 'north_america'], -74.01, 40.71, '诺贝尔经济学奖得主，不平等与全球化批评者。', { since: 2001, birthYear: 1943, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/约瑟夫·斯蒂格利茨' }),
  person('per-g-192', '内德·卢德', '经济学家', '文化', ['global', 'north_america'], -74.01, 40.71, '诺贝尔经济学奖得主，市场设计理论。', { since: 2012, nationality: '美国' }),
  person('per-g-193', '理查德·泰勒', '经济学家', '文化', ['global', 'north_america'], -87.65, 41.88, '行为经济学之父，诺贝尔经济学奖得主，《助推》。', { since: 2017, birthYear: 1945, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/理查德·泰勒' }),

  // ── 全球能源与大宗商品 ──
  person('per-g-194', '阿明·纳赛尔', '沙特阿美 CEO', '经济', ['global', 'middleeast'], 50.10, 26.31, '全球最大石油公司沙特阿美 CEO。', { since: 2015, nationality: '沙特阿拉伯' }),
  person('per-g-195', '帕特里克·普亚纳', '道达尔能源 CEO', '经济', ['global', 'western_europe'], 2.35, 48.86, '法国道达尔能源 CEO，平衡传统油气与新能源。', { since: 2014, nationality: '法国' }),
  person('per-g-196', '瓦埃勒·萨万', '壳牌 CEO', '经济', ['global', 'western_europe'], -0.13, 51.50, '壳牌 CEO，推动 LNG 与低碳转型。', { since: 2023, nationality: '加拿大/黎巴嫩' }),
  person('per-g-197', '安德斯·奥佩尔', ' Equinor CEO', '经济', ['global', 'western_europe'], 10.75, 59.91, '挪威国家石油公司 CEO，海上风电与碳捕集。', { since: 2020, nationality: '挪威' }),
  person('per-g-198', '亚历山大·久科夫', '俄罗斯天然气工业股份公司 CEO', '经济', ['global', 'eastern_europe'], 30.31, 59.94, '俄气 CEO，欧洲天然气供应核心人物。', { since: 2018, nationality: '俄罗斯' }),

  // ── 制药与生物科技 ──
  person('per-g-199', '艾伯特·博尔拉', '辉瑞 CEO', '经济', ['global', 'north_america'], -74.01, 40.71, '辉瑞 CEO，主导新冠疫苗与口服药。', { since: 2019, nationality: '希腊/美国' }),
  person('per-g-200', '斯特凡·班塞尔', 'Moderna CEO', '经济', ['global', 'north_america', 'western_europe'], -71.08, 42.36, 'Moderna CEO，mRNA 技术商业化先驱。', { since: 2011, birthYear: 1972, nationality: '法国', wikipedia: 'https://zh.wikipedia.org/wiki/斯特凡·班塞尔' }),
  person('per-g-201', '戴夫·里克斯', '礼来 CEO', '经济', ['global', 'north_america'], -86.16, 39.77, '礼来 CEO，GLP-1 减肥药浪潮推动者。', { since: 2017, nationality: '美国' }),
  person('per-g-202', '瓦斯·纳拉西姆汉', '诺华 CEO', '经济', ['global', 'western_europe'], 7.59, 47.55, '诺华 CEO，印度裔，推动创新药物管线。', { since: 2018, nationality: '瑞士' }),

  // ── 汽车与制造业 ──
  person('per-g-203', '玛丽·巴拉', '通用汽车 CEO', '经济', ['global', 'north_america'], -83.05, 42.33, '通用汽车 CEO，推动电动化转型。', { since: 2014, birthYear: 1961, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/玛丽·巴拉' }),
  person('per-g-204', '康林松', '梅赛德斯-奔驰 CEO', '经济', ['global', 'western_europe'], 9.18, 48.78, '梅赛德斯-奔驰 CEO，瑞典裔。', { since: 2019, nationality: '瑞典/德国' }),
  person('per-g-205', '奥利弗·布鲁姆', '保时捷/大众 CEO', '经济', ['global', 'western_europe'], 9.18, 48.78, '大众与保时捷双料 CEO。', { since: 2022, nationality: '德国' }),
  person('per-g-206', '卡洛斯·塔瓦雷斯', 'Stellantis CEO', '经济', ['global', 'western_europe'], 6.14, 46.20, 'Stellantis（标致/克莱斯勒）CEO，葡萄牙裔。', { since: 2021, nationality: '葡萄牙' }),

  // ── 数字货币监管与金融科技 ──
  person('per-g-207', '加里·根斯勒', '美国证券交易委员会主席', '经济', ['global', 'north_america'], -77.04, 38.90, '前 MIT 教授，SEC 主席，加密货币监管核心。', { since: 2021, birthYear: 1957, nationality: '美国' }),
  person('per-g-208', '珍妮特·耶伦', '美国财政部长', '经济', ['global', 'north_america'], -77.04, 38.90, '前美联储主席，美国首位女性财政部长。', { since: 2021, birthYear: 1946, nationality: '美国', wikipedia: 'https://zh.wikipedia.org/wiki/珍妮特·耶伦' }),
  person('per-g-209', '克里斯蒂娜·拉加德', '欧洲央行行长', '经济', ['global', 'western_europe'], 2.35, 48.86, '前 IMF 总裁，现任 ECB 行长。', { since: 2019, birthYear: 1956, nationality: '法国' }),
  person('per-g-210', '安德鲁·霍尔丹', '英国央行前行长', '经济', ['global', 'western_europe'], -0.13, 51.50, '前英格兰银行首席经济学家，金融稳定权威。', { since: 2021, nationality: '英国' }),
];
