import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 第二轮增密 · 中国周边态势（2026-06-10 至 06-16） */
const T16 = '2026-06-16T10:00:00Z';
const T15 = '2026-06-15T14:00:00Z';
const T14 = '2026-06-14T08:00:00Z';
const T13 = '2026-06-13T16:00:00Z';
const T12 = '2026-06-12T06:00:00Z';
const T11 = '2026-06-11T12:00:00Z';
const T10 = '2026-06-10T18:00:00Z';

export const CHINA_DENSIFY_EVENTS: EventDetail[] = [
  { id: 'r2-scs-johnson-south', title: '南沙琼礁 · 海警常态化巡航', source: '南海态势监测', timestamp: T16, location: [114.2, 8.6], impact_level: 'high', category: 'military', description: '海警编队对南沙北部岛礁实施例行维权巡航（种子/示例）' },
  { id: 'r2-scs-union-banks', title: '南沙群岛 · 联合礁渔业执法', source: '南海态势监测', timestamp: T15, location: [114.5, 9.8], impact_level: 'medium', category: 'maritime', description: '对非法捕捞船只实施登临检查（种子/示例）' },
  { id: 'r2-scs-luconia', title: '南沙路孔尼亚暗沙 · 油气勘探争议', source: '南海态势监测', timestamp: T14, location: [112.0, 5.0], impact_level: 'high', category: 'hotspots', description: '马来西亚声索区与中国九段线主张重叠（种子/示例）' },
  { id: 'r2-scs-reed-bank', title: '礼乐滩 · 中菲油气对峙', source: '南海态势监测', timestamp: T16, location: [116.8, 11.0], impact_level: 'critical', category: 'conflicts', description: '菲律宾勘探船与中国海警近距离对峙（种子/示例）' },
  { id: 'r2-scs-spratly-patrol', title: '南沙海域 · 多国军舰过境', source: '南海态势监测', timestamp: T13, location: [115.0, 7.5], impact_level: 'high', category: 'military', description: '美澳日联合编队穿越南沙邻近海域（种子/示例）' },
  { id: 'r2-scs-hainan-ex', title: '海南以南 · 海上联合演训', source: '南海态势监测', timestamp: T15, location: [110.5, 17.0], impact_level: 'high', category: 'military', description: '海军与海警联合反潜与岛礁夺控科目（种子/示例）' },
  { id: 'r2-scs-fishing-ban', title: '南海伏季休渔 · 执法强化', source: '南海态势监测', timestamp: T12, location: [113.0, 14.0], impact_level: 'medium', category: 'maritime', description: '休渔期对涉外渔船加强监管（种子/示例）' },
  { id: 'r2-scs-cuarteron', title: '华阳礁 · 灯塔与导航服务', source: '南海态势监测', timestamp: T11, location: [112.85, 8.9], impact_level: 'medium', category: 'waterways', description: '南沙灯塔为过往船只提供导航助航（种子/示例）' },
  { id: 'r2-scs-gaven', title: '南薰礁 · 生态监测站', source: '南海态势监测', timestamp: T10, location: [114.22, 10.08], impact_level: 'low', category: 'natural', description: '珊瑚礁生态与海洋环境持续观测（种子/示例）' },
  { id: 'r2-scs-irving', title: '弹丸礁附近 · 马方巡逻', source: '南海态势监测', timestamp: T14, location: [113.9, 7.4], impact_level: 'medium', category: 'hotspots', description: '马来西亚海警在占据岛礁周边巡逻（种子/示例）' },
  { id: 'r2-tw-strait-patrol', title: '台湾海峡 · 海警执法巡查', source: '台海态势监测', timestamp: T16, location: [119.5, 24.5], impact_level: 'high', category: 'military', description: '海警舰艇在海峡中线以西常态化执法（种子/示例）' },
  { id: 'r2-tw-kinmen-waters', title: '金门水域 · 渔船登临检查', source: '台海态势监测', timestamp: T15, location: [118.4, 24.45], impact_level: 'high', category: 'maritime', description: '对涉嫌违规作业渔船实施登临（种子/示例）' },
  { id: 'r2-tw-matsu', title: '马祖列岛 · 海空警戒', source: '台海态势监测', timestamp: T14, location: [119.95, 26.15], impact_level: 'medium', category: 'military', description: '台军提升马祖方向海空警戒等级（种子/示例）' },
  { id: 'r2-tw-penghu', title: '澎湖列岛 · 导弹阵地戒备', source: '台海态势监测', timestamp: T13, location: [119.58, 23.57], impact_level: 'high', category: 'bases', description: '天弓导弹阵地进入战备值班（种子/示例）' },
  { id: 'r2-tw-hualien', title: '花莲 · 战机紧急起飞', source: '台海态势监测', timestamp: T16, location: [121.62, 24.03], impact_level: 'high', category: 'aviation', description: 'F-16 编队应对海峡方向空情（种子/示例）' },
  { id: 'r2-tw-taoyuan', title: '桃园 · 民航绕飞管制', source: '台海态势监测', timestamp: T12, location: [121.23, 25.08], impact_level: 'medium', category: 'aviation', description: '海峡演训期间部分航线临时调整（种子/示例）' },
  { id: 'r2-tw-tainan', title: '台南 · 岸舰导弹演习', source: '台海态势监测', timestamp: T11, location: [120.2, 22.99], impact_level: 'high', category: 'military', description: '雄风系列反舰导弹实弹射击（种子/示例）' },
  { id: 'r2-tw-election', title: '台北 · 两岸政策辩论', source: '台海态势监测', timestamp: T10, location: [121.52, 25.05], impact_level: 'medium', category: 'conflicts', description: '立法院审议两岸经贸与防务预算（种子/示例）' },
  { id: 'r2-ic-okinawa', title: '冲绳 · 美军基地集结', source: '第一岛链监测', timestamp: T16, location: [127.68, 26.21], impact_level: 'high', category: 'bases', description: '嘉手纳基地战机出动频率上升（种子/示例）' },
  { id: 'r2-ic-bashi', title: '巴士海峡 · 潜艇过境', source: '第一岛链监测', timestamp: T15, location: [121.0, 21.0], impact_level: 'critical', category: 'military', description: '外军核动力潜艇穿越巴士海峡（种子/示例）' },
  { id: 'r2-ic-miyako', title: '宫古海峡 · 中俄联合巡航', source: '第一岛链监测', timestamp: T14, location: [125.5, 25.5], impact_level: 'high', category: 'military', description: '中俄海军编队穿越宫古海峡进入太平洋（种子/示例）' },
  { id: 'r2-ic-luzon', title: '吕宋海峡 · 美军航母编队', source: '第一岛链监测', timestamp: T13, location: [121.5, 19.0], impact_level: 'critical', category: 'maritime', description: '航母打击群在菲律宾海演训（种子/示例）' },
  { id: 'r2-ic-guam', title: '关岛 · 战略轰炸机部署', source: '第一岛链监测', timestamp: T16, location: [144.8, 13.45], impact_level: 'high', category: 'aviation', description: 'B-52 轰炸机轮换部署安德森基地（种子/示例）' },
  { id: 'r2-ic-philippines', title: '巴拉望 · 前沿基地扩建', source: '第一岛链监测', timestamp: T12, location: [117.85, 9.75], impact_level: 'medium', category: 'bases', description: '美军 EDCA 基地基础设施升级（种子/示例）' },
  { id: 'r2-jp-senkaku', title: '钓鱼岛 · 海警维权巡航', source: '中日态势监测', timestamp: T16, location: [123.47, 25.75], impact_level: 'critical', category: 'hotspots', description: '中国海警舰艇在钓鱼岛领海巡航（种子/示例）' },
  { id: 'r2-jp-okinawa-patrol', title: '冲绳海域 · 日海自巡逻', source: '中日态势监测', timestamp: T15, location: [127.0, 26.5], impact_level: 'high', category: 'military', description: '海上自卫队护卫舰加强西南诸岛巡逻（种子/示例）' },
  { id: 'r2-jp-yonaguni', title: '与那国岛 · 雷达监视', source: '中日态势监测', timestamp: T14, location: [122.99, 24.47], impact_level: 'medium', category: 'military', description: '陆上自卫队与那国岛雷达站持续监视（种子/示例）' },
  { id: 'r2-jp-ishigaki', title: '石垣岛 · 导弹部署', source: '中日态势监测', timestamp: T13, location: [124.16, 24.34], impact_level: 'high', category: 'bases', description: '陆上导弹部队西南转移部署（种子/示例）' },
  { id: 'r2-jp-east-china-sea', title: '东海 · 油气平台争议', source: '中日态势监测', timestamp: T16, location: [125.0, 29.5], impact_level: 'high', category: 'conflicts', description: '中日中间线附近油气开发分歧（种子/示例）' },
  { id: 'r2-jp-aegis', title: '舞鹤 · 宙斯盾舰出动', source: '中日态势监测', timestamp: T11, location: [135.38, 35.47], impact_level: 'medium', category: 'maritime', description: '导弹驱逐舰赴东海方向警戒（种子/示例）' },
  { id: 'r2-kp-dmz', title: '板门店 · 朝韩对峙', source: '半岛态势监测', timestamp: T16, location: [126.68, 37.95], impact_level: 'high', category: 'hotspots', description: '非军事区双方军人近距离对峙（种子/示例）' },
  { id: 'r2-kp-missile', title: '平安北道 · 弹道导弹试射', source: '半岛态势监测', timestamp: T15, location: [125.5, 40.0], impact_level: 'critical', category: 'military', description: '朝鲜发射中程弹道导弹落入日本海（种子/示例）' },
  { id: 'r2-kp-nuclear', title: '宁边 · 核设施活动', source: '半岛态势监测', timestamp: T14, location: [125.75, 39.8], impact_level: 'critical', category: 'nuclear', description: '卫星影像显示核设施车辆活动增加（种子/示例）' },
  { id: 'r2-kr-thaad', title: '星州 · 萨德雷达戒备', source: '半岛态势监测', timestamp: T13, location: [127.88, 35.25], impact_level: 'high', category: 'bases', description: '驻韩萨德系统进入高度戒备（种子/示例）' },
  { id: 'r2-kr-usfk', title: '乌山基地 · 战机紧急起飞', source: '半岛态势监测', timestamp: T16, location: [127.03, 37.09], impact_level: 'high', category: 'aviation', description: 'F-16 应对半岛导弹发射（种子/示例）' },
  { id: 'r2-kr-nll', title: '北方界线 · 炮击警告', source: '半岛态势监测', timestamp: T12, location: [125.5, 38.0], impact_level: 'critical', category: 'conflicts', description: '朝方在西海方向鸣炮警告韩方舰艇（种子/示例）' },
  { id: 'r2-dia-senkaku', title: '钓鱼岛列岛 · 主权主张', source: '岛礁争端监测', timestamp: T16, location: [123.5, 25.7], impact_level: 'critical', category: 'contested', description: '中日钓鱼岛主权争议持续（种子/示例）' },
  { id: 'r2-dia-paracel', title: '西沙群岛 · 越南抗议', source: '岛礁争端监测', timestamp: T15, location: [111.5, 16.5], impact_level: 'high', category: 'diplomatic', description: '越南就西沙旅游开放提出外交抗议（种子/示例）' },
  { id: 'r2-dia-scarborough', title: '黄岩岛 · 菲方巡逻', source: '岛礁争端监测', timestamp: T14, location: [117.8, 15.1], impact_level: 'critical', category: 'hotspots', description: '菲律宾海警在黄岩岛潟湖外围巡逻（种子/示例）' },
  { id: 'r2-dia-spratly-vn', title: '南沙南威岛 · 越方扩建', source: '岛礁争端监测', timestamp: T13, location: [111.92, 8.65], impact_level: 'high', category: 'conflicts', description: '越南在南沙占据岛礁持续填海（种子/示例）' },
  { id: 'r2-dia-dokdo', title: '独岛/竹岛 · 日韩争议', source: '岛礁争端监测', timestamp: T12, location: [131.87, 37.24], impact_level: 'medium', category: 'contested', description: '日韩围绕独岛主权争论再起（种子/示例）' },
  { id: 'r2-dia-kuril', title: '北方四岛 · 日俄争议', source: '岛礁争端监测', timestamp: T11, location: [145.75, 44.02], impact_level: 'medium', category: 'conflicts', description: '日俄和平条约谈判停滞（种子/示例）' },
  { id: 'r2-cn-zhoushan', title: '舟山群岛 · 海军演训', source: '中国周边监测', timestamp: T16, location: [122.1, 30.0], impact_level: 'high', category: 'military', description: '东海舰队舰艇编队实战化演训（种子/示例）' },
  { id: 'r2-cn-qingdao', title: '青岛 · 航母编队出港', source: '中国周边监测', timestamp: T15, location: [120.38, 36.07], impact_level: 'high', category: 'maritime', description: '山东舰编队赴西太平洋训练（种子/示例）' },
  { id: 'r2-cn-xisha', title: '西沙永兴岛 · 民航包机', source: '中国周边监测', timestamp: T14, location: [112.34, 16.83], impact_level: 'medium', category: 'aviation', description: '三沙市军民合用机场定期航班（种子/示例）' },
  { id: 'r2-cn-hk', title: '香港 · 国安执法行动', source: '中国周边监测', timestamp: T13, location: [114.17, 22.32], impact_level: 'medium', category: 'sanctions', description: '国安处依法调查危害国家安全案件（种子/示例）' },
  { id: 'r2-cn-macau', title: '澳门 · 口岸通关监测', source: '中国周边监测', timestamp: T12, location: [113.54, 22.2], impact_level: 'low', category: 'economic', description: '横琴口岸客流与经贸往来监测（种子/示例）' },
  { id: 'r2-cn-border-india', title: '中印边境 · 巡逻对峙', source: '中国周边监测', timestamp: T16, location: [78.5, 33.5], impact_level: 'high', category: 'conflicts', description: '实控线附近双方巡逻队近距离对峙（种子/示例）' },
  { id: 'r2-cn-border-myanmar', title: '中缅边境 · 难民安置', source: '中国周边监测', timestamp: T11, location: [98.5, 24.0], impact_level: 'medium', category: 'hotspots', description: '缅北冲突外溢边境人道压力（种子/示例）' },
  { id: 'r2-cn-russia-border', title: '中俄边境 · 联合巡逻', source: '中国周边监测', timestamp: T10, location: [130.5, 45.5], impact_level: 'medium', category: 'military', description: '两国边防军联合边境巡逻（种子/示例）' },
  { id: 'r2-cn-typhoon', title: '南海 · 台风路径预警', source: '气象监测', timestamp: T16, location: [115.0, 18.0], impact_level: 'high', category: 'weather', description: '热带气旋逼近华南沿海（种子/示例）' },
  { id: 'r2-cn-earthquake', title: '台湾东部 · 地震监测', source: '自然灾害监测', timestamp: T15, location: [121.6, 23.8], impact_level: 'medium', category: 'natural', description: '5.2 级地震，花莲震感明显（种子/示例）' },
];

export const CHINA_DENSIFY_INCIDENTS: Incident[] = [
  { id: 'r2-inc-scs-water', title: '南沙海域 · 水炮对峙', date: T16, type: 'military', faction: 'cn', location: { lng: 114.8, lat: 9.2 }, description: '中国海警船对菲方补给船实施水炮驱离（种子/示例）', source: '南海态势监测' },
  { id: 'r2-inc-scs-radar', title: '永暑礁 · 雷达开机', date: T15, type: 'military', faction: 'cn', location: { lng: 112.97, lat: 9.55 }, description: '南沙岛礁雷达系统进入战备值班（种子/示例）', source: '南海态势监测' },
  { id: 'r2-inc-scs-fish', title: '西沙海域 · 非法捕捞查处', date: T14, type: 'political', faction: 'cn', location: { lng: 111.8, lat: 16.2 }, description: '海警查获外籍渔船非法作业（种子/示例）', source: '南海态势监测' },
  { id: 'r2-inc-tw-strait', title: '海峡中线 · 军机过线', date: T16, type: 'military', faction: 'tw', location: { lng: 119.8, lat: 24.2 }, description: '解放军军机越过海峡中线（种子/示例）', source: '台海态势监测' },
  { id: 'r2-inc-tw-drone', title: '金门上空 · 无人机侵扰', date: T15, type: 'military', faction: 'cn', location: { lng: 118.42, lat: 24.43 }, description: '不明无人机飞越金门禁制水域（种子/示例）', source: '台海态势监测' },
  { id: 'r2-inc-tw-missile', title: '台东 · 导弹试射', date: T13, type: 'military', faction: 'tw', location: { lng: 121.15, lat: 22.75 }, description: '台军雄风导弹实弹射击（种子/示例）', source: '台海态势监测' },
  { id: 'r2-inc-ic-transit', title: '宫古海峡 · 舰艇编队过境', date: T16, type: 'military', faction: 'cn', location: { lng: 125.3, lat: 25.8 }, description: '中国海军编队穿越第一岛链（种子/示例）', source: '第一岛链监测' },
  { id: 'r2-inc-ic-sub', title: '巴士海峡 · 潜艇上浮', date: T14, type: 'military', faction: 'us', location: { lng: 121.2, lat: 21.5 }, description: '美军核潜艇例行上浮通过（种子/示例）', source: '第一岛链监测' },
  { id: 'r2-inc-jp-senkaku', title: '钓鱼岛 · 日舰接近', date: T16, type: 'military', faction: 'jp', location: { lng: 123.5, lat: 25.74 }, description: '日本海上保安厅舰艇接近钓鱼岛（种子/示例）', source: '中日态势监测' },
  { id: 'r2-inc-jp-eca', title: '东海 · 海警对峙', date: T15, type: 'military', faction: 'cn', location: { lng: 124.5, lat: 30.0 }, description: '中日海警在争议海域对峙（种子/示例）', source: '中日态势监测' },
  { id: 'r2-inc-kp-launch', title: '朝鲜 · 导弹发射', date: T16, type: 'military', faction: 'kp', location: { lng: 125.8, lat: 39.5 }, description: '朝鲜发射弹道导弹（种子/示例）', source: '半岛态势监测' },
  { id: 'r2-inc-kr-alert', title: '首尔 · 防空警报', date: T15, type: 'military', faction: 'kr', location: { lng: 126.98, lat: 37.57 }, description: '导弹发射后全国防空警报（种子/示例）', source: '半岛态势监测' },
  { id: 'r2-inc-dia-protest', title: '马尼拉 · 反华示威', date: T14, type: 'political', faction: 'ph', location: { lng: 120.98, lat: 14.6 }, description: '菲律宾民间组织抗议南海行动（种子/示例）', source: '岛礁争端监测' },
  { id: 'r2-inc-dia-vn', title: '河内 · 外交照会', date: T13, type: 'diplomatic', faction: 'vn', location: { lng: 105.85, lat: 21.03 }, description: '越南就南海岛礁提出抗议（种子/示例）', source: '岛礁争端监测' },
  { id: 'r2-inc-cn-sanction', title: '北京 · 对台制裁', date: T12, type: 'political', faction: 'cn', location: { lng: 116.4, lat: 39.9 }, description: '商务部公布对台贸易限制措施（种子/示例）', source: '中国周边监测' },
  { id: 'r2-inc-cn-exercise', title: '台海 · 联合封锁演习', date: T16, type: 'military', faction: 'cn', location: { lng: 120.0, lat: 24.0 }, description: '东部战区组织环台岛战备警巡（种子/示例）', source: '台海态势监测' },
  { id: 'r2-inc-scs-aus', title: '南海 · 澳军机抵近', date: T11, type: 'military', faction: 'us', location: { lng: 113.5, lat: 12.0 }, description: '澳军 P-8A 侦察机抵近南海（种子/示例）', source: '南海态势监测' },
  { id: 'r2-inc-tw-cyber', title: '台湾 · 网络攻击', date: T10, type: 'political', faction: 'contested', location: { lng: 121.5, lat: 25.05 }, description: '政府机构遭受分布式拒绝服务攻击（种子/示例）', source: '台海态势监测' },
  { id: 'r2-inc-ic-phil', title: '苏禄海 · 菲美联演', date: T12, type: 'military', faction: 'ph', location: { lng: 120.5, lat: 8.0 }, description: '菲美海上联合演习（种子/示例）', source: '第一岛链监测' },
  { id: 'r2-inc-kp-tunnel', title: '三八线 · 地道发现', date: T11, type: 'military', faction: 'kp', location: { lng: 126.68, lat: 37.95 }, description: '韩军发现朝方非军事区地道（种子/示例）', source: '半岛态势监测' },
];

export const CHINA_DENSIFY_FACILITIES: Facility[] = [
  { id: 'r2-fac-cuarteron', name: '华阳礁（南沙）', position: { lat: 8.9, lng: 112.85 }, faction: 'cn', type: 'naval', notes: '南沙南部战略支点（种子/示例）' },
  { id: 'r2-fac-gaven', name: '南薰礁（南沙）', position: { lat: 10.08, lng: 114.22 }, faction: 'cn', type: 'naval', notes: '南沙东北部岛礁（种子/示例）' },
  { id: 'r2-fac-hughes', name: '东门礁（南沙）', position: { lat: 9.55, lng: 114.3 }, faction: 'cn', type: 'naval', notes: '南沙人工岛礁（种子/示例）' },
  { id: 'r2-fac-johnson', name: '琼礁（南沙）', position: { lat: 9.8, lng: 114.5 }, faction: 'cn', type: 'naval', notes: '南沙岛礁建设点（种子/示例）' },
  { id: 'r2-fac-itu-aba', name: '太平岛（台占）', position: { lat: 10.38, lng: 114.37 }, faction: 'tw', type: 'airfield', notes: '南沙最大自然岛，台军驻守（种子/示例）' },
  { id: 'r2-fac-thitu', name: '中业岛（菲占）', position: { lat: 11.05, lng: 114.28 }, faction: 'ph', type: 'naval', notes: '菲律宾南沙最大占据岛（种子/示例）' },
  { id: 'r2-fac-swallow', name: '南子岛（越占）', position: { lat: 11.2, lng: 114.33 }, faction: 'vn', type: 'naval', notes: '越南南沙北部据点（种子/示例）' },
  { id: 'r2-fac-reef-antonio', name: '费信岛（菲占）', position: { lat: 10.05, lng: 114.23 }, faction: 'ph', type: 'naval', notes: '菲律宾南沙前沿基地（种子/示例）' },
  { id: 'r2-fac-kinmen', name: '金门守备区', position: { lat: 24.43, lng: 118.32 }, faction: 'tw', type: 'base', forces: ['陆军'], notes: '台军前沿守备（种子/示例）' },
  { id: 'r2-fac-matsu', name: '马祖守备区', position: { lat: 26.16, lng: 119.93 }, faction: 'tw', type: 'base', notes: '台军马祖防卫指挥部（种子/示例）' },
  { id: 'r2-fac-penghu', name: '澎湖防卫指挥部', position: { lat: 23.57, lng: 119.58 }, faction: 'tw', type: 'base', forces: ['陆军', '海军'], notes: '台海中线战略枢纽（种子/示例）' },
  { id: 'r2-fac-hsinchu-af', name: '新竹空军基地', position: { lat: 24.82, lng: 120.94 }, faction: 'tw', type: 'airfield', forces: ['幻影-2000'], notes: '台军西部防空主力（种子/示例）' },
  { id: 'r2-fac-taichung', name: '台中清泉岗基地', position: { lat: 24.26, lng: 120.62 }, faction: 'tw', type: 'airfield', notes: '台军中部航空基地（种子/示例）' },
  { id: 'r2-fac-kadena', name: '嘉手纳空军基地', position: { lat: 26.35, lng: 127.77 }, faction: 'us', type: 'airfield', forces: ['F-15', 'F-22'], notes: '美军太平洋最大空军基地（种子/示例）' },
  { id: 'r2-fac-yokosuka', name: '横须贺海军基地', position: { lat: 35.29, lng: 139.67 }, faction: 'us', type: 'naval', forces: ['第七舰队'], notes: '美军西太平洋母港（种子/示例）' },
  { id: 'r2-fac-sasebo', name: '佐世保海军基地', position: { lat: 33.16, lng: 129.72 }, faction: 'us', type: 'naval', notes: '美军两栖舰艇前沿基地（种子/示例）' },
  { id: 'r2-fac-okinawa', name: '冲绳陆战队基地', position: { lat: 26.5, lng: 127.85 }, faction: 'us', type: 'base', troopEstimate: '约2万', notes: '驻冲绳美军主要营地（种子/示例）' },
  { id: 'r2-fac-ishigaki', name: '石垣岛自卫队营地', position: { lat: 24.34, lng: 124.16 }, faction: 'jp', type: 'base', notes: '日本西南诸岛防卫前沿（种子/示例）' },
  { id: 'r2-fac-yonaguni', name: '与那国岛雷达站', position: { lat: 24.47, lng: 122.99 }, faction: 'jp', type: 'base', notes: '监视台湾海峡与钓鱼岛（种子/示例）' },
  { id: 'r2-fac-miyako', name: '宫古岛自卫队基地', position: { lat: 24.8, lng: 125.28 }, faction: 'jp', type: 'base', notes: '日本西南诸岛导弹部署点（种子/示例）' },
  { id: 'r2-fac-pyongtaek', name: '平泽汉弗莱斯军营', position: { lat: 36.97, lng: 127.02 }, faction: 'us', type: 'base', troopEstimate: '约3.5万', notes: '驻韩美军最大基地（种子/示例）' },
  { id: 'r2-fac-osan', name: '乌山空军基地', position: { lat: 37.09, lng: 127.03 }, faction: 'us', type: 'airfield', notes: '驻韩美军第七航空队（种子/示例）' },
  { id: 'r2-fac-kunsan', name: '群山空军基地', position: { lat: 35.9, lng: 126.62 }, faction: 'us', type: 'airfield', notes: '驻韩美军战斗机基地（种子/示例）' },
  { id: 'r2-fac-yongbyon', name: '宁边核设施', position: { lat: 39.8, lng: 125.75 }, faction: 'kp', type: 'nuclear', nuclearKind: 'enrichment', notes: '朝鲜主要核设施（种子/示例）' },
  { id: 'r2-fac-punggye', name: '丰溪里核试验场', position: { lat: 41.28, lng: 129.08 }, faction: 'kp', type: 'nuclear', nuclearKind: 'test_site', notes: '朝鲜核试验场（种子/示例）' },
  { id: 'r2-fac-subi', name: '渚碧礁（南沙）', position: { lat: 10.92, lng: 114.07 }, faction: 'cn', type: 'naval', forces: ['海警', '海军'], notes: '南沙北部大型人工岛（种子/示例）' },
  { id: 'r2-fac-reef-union', name: '赤瓜礁（南沙）', position: { lat: 9.9, lng: 114.5 }, faction: 'cn', type: 'naval', notes: '1988年赤瓜礁海战后中方控制（种子/示例）' },
  { id: 'r2-fac-duncan', name: ' Duncan 礁（菲声索）', position: { lat: 9.1, lng: 115.8 }, faction: 'ph', type: 'naval', notes: '菲律宾声索南沙岛礁（种子/示例）' },
  { id: 'r2-fac-lansdowne', name: '信义礁（菲占）', position: { lat: 9.9, lng: 115.5 }, faction: 'ph', type: 'naval', notes: '菲律宾实际控制岛礁（种子/示例）' },
  { id: 'r2-fac-zhoushan', name: '舟山海军基地', position: { lat: 30.0, lng: 122.1 }, faction: 'cn', type: 'naval', forces: ['东海舰队'], notes: '东海方向核心军港（种子/示例）' },
  { id: 'r2-fac-dalian', name: '大连海军基地', position: { lat: 38.9, lng: 121.6 }, faction: 'cn', type: 'naval', forces: ['北海舰队'], notes: '航母与潜艇母港（种子/示例）' },
  { id: 'r2-fac-qingdao', name: '青岛海军基地', position: { lat: 36.07, lng: 120.38 }, faction: 'cn', type: 'naval', forces: ['北海舰队', '航母编队'], notes: '辽宁舰母港（种子/示例）' },
  { id: 'r2-fac-yulin', name: '榆林海军基地', position: { lat: 18.25, lng: 109.51 }, faction: 'cn', type: 'naval', forces: ['南海舰队', '潜艇'], notes: '战略核潜艇基地（种子/示例）' },
  { id: 'r2-fac-guam', name: '安德森空军基地', position: { lat: 13.58, lng: 144.93 }, faction: 'us', type: 'airfield', forces: ['B-52', 'B-1B'], notes: '西太平洋战略轰炸机基地（种子/示例）' },
  { id: 'r2-fac-clark', name: '克拉克空军基地', position: { lat: 15.18, lng: 120.56 }, faction: 'us', type: 'airfield', notes: '美军菲律宾前沿基地（种子/示例）' },
  { id: 'r2-fac-subic', name: '苏比克湾', position: { lat: 14.8, lng: 120.28 }, faction: 'ph', type: 'naval', notes: '菲律宾主要军港（种子/示例）' },
  { id: 'r2-fac-antelope', name: '羚羊礁（中占）', position: { lat: 16.45, lng: 111.72 }, faction: 'cn', type: 'naval', notes: '西沙群岛岛礁（种子/示例）' },
  { id: 'r2-fac-tree', name: '永兴岛机场', position: { lat: 16.83, lng: 112.34 }, faction: 'cn', type: 'airfield', forces: ['歼-11'], notes: '西沙主要机场（种子/示例）' },
  { id: 'r2-fac-diaoyu', name: '钓鱼岛巡航基地（示意）', position: { lat: 25.75, lng: 123.47 }, faction: 'cn', type: 'naval', notes: '海警维权巡航出发点（种子/示例）' },
  { id: 'r2-fac-seongju', name: '星州萨德阵地', position: { lat: 35.25, lng: 127.88 }, faction: 'kr', type: 'missile', notes: '驻韩萨德反导系统（种子/示例）' },
];
