import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/**
 * 岛礁争端与势力分布 — 南海/东海争议点与各方控制态势
 */
export const CHINA_DISPUTE_EVENTS: EventDetail[] = [
  {
    id: 'cn-disp-spratly-cn',
    title: '南沙群岛 · 中方实际控制岛礁群',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T10:00:00Z',
    location: [114.0, 9.5],
    impact_level: 'critical',
    category: 'hotspots',
    description: '永暑礁、美济礁、渚碧礁等 7 岛礁由中方建设管控',
  },
  {
    id: 'cn-disp-paracel',
    title: '西沙群岛 · 中方完全控制',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T09:00:00Z',
    location: [112.0, 16.5],
    impact_level: 'high',
    category: 'hotspots',
    description: '1974年海战后中方实际控制，越南仍主张主权',
  },
  {
    id: 'cn-disp-scarborough',
    title: '黄岩岛 · 中菲争议核心区',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T11:00:00Z',
    location: [117.75, 15.13],
    impact_level: 'critical',
    category: 'conflicts',
    description: '2012年对峙后中方实际控制，菲方坚持主权主张',
  },
  {
    id: 'cn-disp-senkaku',
    title: '钓鱼岛 · 中日争议',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T08:00:00Z',
    location: [123.47, 25.75],
    impact_level: 'critical',
    category: 'conflicts',
    description: '中日双方均主张主权，中国海警常态化巡航',
  },
  {
    id: 'cn-disp-iturup',
    title: '北方四岛（南千岛群岛）· 日俄争议',
    source: 'seed/争端监测',
    timestamp: '2026-06-15T14:00:00Z',
    location: [147.0, 45.0],
    impact_level: 'medium',
    category: 'hotspots',
    description: '二战后日俄未签约领土争议，俄方实际控制',
  },
  {
    id: 'cn-disp-johnson-reef',
    title: '赤瓜礁 · 中方控制（1988）',
    source: 'seed/争端监测',
    timestamp: '2026-06-14T12:00:00Z',
    location: [114.28, 9.92],
    impact_level: 'high',
    category: 'military',
    description: '赤瓜礁海战后方实际控制，建有高脚屋与灯塔',
  },
  {
    id: 'cn-disp-thitu',
    title: '中业岛 · 菲律宾占领',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T07:00:00Z',
    location: [114.29, 11.05],
    impact_level: 'high',
    category: 'hotspots',
    description: '菲方南沙最大据点，近年跑道扩建与军事化',
  },
  {
    id: 'cn-disp-spratly-vn',
    title: '南威岛 · 越南占领',
    source: 'seed/争端监测',
    timestamp: '2026-06-15T16:00:00Z',
    location: [111.92, 8.64],
    impact_level: 'high',
    category: 'hotspots',
    description: '越南南沙最大岛礁，建有跑道与雷达',
  },
  {
    id: 'cn-disp-spratly-my',
    title: '弹丸礁（燕子礁）· 马来西亚',
    source: 'seed/争端监测',
    timestamp: '2026-06-14T10:00:00Z',
    location: [113.85, 7.37],
    impact_level: 'medium',
    category: 'hotspots',
    description: '马来西亚南沙唯一据点，建有度假村与简易跑道',
  },
  {
    id: 'cn-disp-ecs-platform',
    title: '东海平台 · 中日油气争议',
    source: 'seed/争端监测',
    timestamp: '2026-06-16T12:00:00Z',
    location: [125.0, 29.5],
    impact_level: 'high',
    category: 'economic',
    description: '中日对东海「中间线」划界与油气开发权分歧',
  },
];

export const CHINA_DISPUTE_INCIDENTS: Incident[] = [
  {
    id: 'cn-disp-inc-1',
    title: '菲方在黄岩岛附近扣押中国渔民',
    date: '2026-06-15T10:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 15.0, lng: 117.8 },
    description: '菲律宾海警在黄岩岛附近扣押中国渔船，中方提出交涉',
    source: 'xinhua',
  },
  {
    id: 'cn-disp-inc-2',
    title: '越南在南沙填海造岛',
    date: '2026-06-14T14:00:00Z',
    type: 'military',
    faction: 'vn',
    location: { lat: 8.64, lng: 111.92 },
    description: '卫星图像显示越方在南威岛等据点扩建设施',
    source: 'reuters',
  },
  {
    id: 'cn-disp-inc-3',
    title: '中国发布南海诸岛标准地名',
    date: '2026-06-13T08:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 16.83, lng: 112.33 },
    description: '自然资源部公布南海 302 个标准地名，强调主权',
    source: 'xinhua',
  },
  {
    id: 'cn-disp-inc-4',
    title: '马来西亚抗议中国海警进入南沙海域',
    date: '2026-06-16T09:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 7.37, lng: 113.85 },
    description: '马方称中国海警船进入其主张海域，中方回应依法巡航',
    source: 'reuters',
  },
  {
    id: 'cn-disp-inc-5',
    title: '国际仲裁裁决七周年 · 中方重申立场',
    date: '2026-06-12T12:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 9.5, lng: 114.0 },
    description: '外交部重申南海仲裁裁决非法无效，不接受不承认',
    source: 'xinhua',
  },
];

export const CHINA_DISPUTE_FACILITIES: Facility[] = [
  {
    id: 'cn-disp-fac-mischief',
    name: '美济礁（中方）',
    position: { lat: 9.92, lng: 115.52 },
    faction: 'cn',
    type: 'naval',
    notes: '南沙最大人工岛，中方实际控制与建设',
  },
  {
    id: 'cn-disp-fac-fiery',
    name: '永暑礁（中方）',
    position: { lat: 9.55, lng: 112.97 },
    faction: 'cn',
    type: 'base',
    notes: '南沙行政与军事中心',
  },
  {
    id: 'cn-disp-fac-scarborough',
    name: '黄岩岛（中方管控）',
    position: { lat: 15.13, lng: 117.75 },
    faction: 'cn',
    type: 'naval',
    notes: '2012年后中方海警常态化管控',
  },
  {
    id: 'cn-disp-fac-thitu',
    name: '中业岛（菲律宾）',
    position: { lat: 11.05, lng: 114.29 },
    faction: 'us',
    type: 'airfield',
    notes: '菲方占领，近年跑道延长',
  },
  {
    id: 'cn-disp-fac-spratly-vn',
    name: '南威岛（越南）',
    position: { lat: 8.64, lng: 111.92 },
    faction: 'vn',
    type: 'airfield',
    notes: '越方南沙最大据点',
  },
  {
    id: 'cn-disp-fac-spratly-my',
    name: '弹丸礁（马来西亚）',
    position: { lat: 7.37, lng: 113.85 },
    faction: 'my',
    type: 'naval',
    notes: '马方南沙唯一据点',
  },
  {
    id: 'cn-disp-fac-spratly-tw',
    name: '太平岛（台湾）',
    position: { lat: 10.38, lng: 114.36 },
    faction: 'tw',
    type: 'airfield',
    notes: '台方南沙最大岛礁，建有跑道',
  },
  {
    id: 'cn-disp-fac-johnson',
    name: '赤瓜礁（中方）',
    position: { lat: 9.92, lng: 114.28 },
    faction: 'cn',
    type: 'naval',
    notes: '1988年海战后中方控制',
  },
  {
    id: 'cn-disp-fac-gaven',
    name: '南薰礁（中方）',
    position: { lat: 10.12, lng: 114.52 },
    faction: 'cn',
    type: 'naval',
    notes: '南沙中方建设岛礁之一',
  },
  {
    id: 'cn-disp-fac-hughes',
    name: '东门礁（中方）',
    position: { lat: 9.55, lng: 114.42 },
    faction: 'cn',
    type: 'naval',
    notes: '南沙高脚屋升级为人工岛',
  },
  {
    id: 'cn-disp-fac-diaoyu',
    name: '钓鱼岛（中日争议）',
    position: { lat: 25.75, lng: 123.47 },
    faction: 'cn',
    type: 'naval',
    notes: '日方行政管辖，中方海警巡航',
  },
  {
    id: 'cn-disp-fac-reef-9',
    name: '仁爱礁（菲坐滩军舰）',
    position: { lat: 9.73, lng: 115.85 },
    faction: 'us',
    type: 'naval',
    notes: '1999年菲方故意坐滩，中方要求拖走',
  },
  {
    id: 'cn-disp-fac-landon',
    name: '兰屿（台湾）· 监视南沙',
    position: { lat: 22.03, lng: 121.55 },
    faction: 'tw',
    type: 'base',
    notes: '台军南部前哨，监视巴士海峡与南沙',
  },
  {
    id: 'cn-disp-fac-palawan',
    name: '巴拉望岛（菲）· 南海前沿',
    position: { lat: 9.5, lng: 118.0 },
    faction: 'us',
    type: 'base',
    notes: '菲律宾距南沙最近大型岛屿，美军 EDCA 基地',
  },
  {
    id: 'cn-disp-fac-woody',
    name: '永兴岛（中方·西沙）',
    position: { lat: 16.83, lng: 112.33 },
    faction: 'cn',
    type: 'airfield',
    notes: '西沙最大岛，三沙市政府驻地',
  },
];
