import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 第一岛链 · 战略节点与海峡 */
export const ISLAND_CHAIN_EVENTS: EventDetail[] = [
  {
    id: 'chain-miyako',
    title: '宫古海峡 · 第一岛链关键水道',
    source: '西太平洋态势',
    timestamp: '2026-06-16T06:00:00Z',
    location: [125.5, 25.0],
    impact_level: 'critical',
    category: 'waterways',
    description: '中国海军进出太平洋最主要通道之一，美日监视重点',
  },
  {
    id: 'chain-bashi',
    title: '巴士海峡 · 台海以南战略水道',
    source: '西太平洋态势',
    timestamp: '2026-06-16T05:30:00Z',
    location: [121.0, 21.0],
    impact_level: 'critical',
    category: 'waterways',
    description: '连接南海与太平洋，潜艇与水面舰艇常用通道',
  },
  {
    id: 'chain-okinawa',
    title: '冲绳 · 第一岛链枢纽',
    source: '西太平洋态势',
    timestamp: '2026-06-15T14:00:00Z',
    location: [127.68, 26.21],
    impact_level: 'high',
    category: 'bases',
    description: '美军太平洋司令部前沿，嘉手纳空军基地所在地',
  },
  {
    id: 'chain-guam',
    title: '关岛 · 第二岛链支点',
    source: '西太平洋态势',
    timestamp: '2026-06-15T12:00:00Z',
    location: [144.79, 13.44],
    impact_level: 'critical',
    category: 'bases',
    description: '美国西太平洋战略核心，轰炸机与核潜艇部署',
  },
  {
    id: 'chain-taiwan-strait',
    title: '台湾海峡 · 第一岛链中段',
    source: '西太平洋态势',
    timestamp: '2026-06-16T08:00:00Z',
    location: [119.5, 24.5],
    impact_level: 'critical',
    category: 'hotspots',
    description: '全球最繁忙航道之一，两岸军事对峙前沿',
  },
  {
    id: 'chain-luzon',
    title: '吕宋海峡 · 菲律宾北侧水道',
    source: '西太平洋态势',
    timestamp: '2026-06-14T10:00:00Z',
    location: [121.5, 20.0],
    impact_level: 'high',
    category: 'waterways',
    description: '巴士海峡以北，连接南海与太平洋的另一通道',
  },
  {
    id: 'chain-tsushima',
    title: '对马海峡 · 日本海出入口',
    source: '西太平洋态势',
    timestamp: '2026-06-13T08:00:00Z',
    location: [129.5, 34.5],
    impact_level: 'medium',
    category: 'waterways',
    description: '日本海通往东海与太平洋的关键海峡',
  },
  {
    id: 'chain-korea-strait',
    title: '朝鲜海峡 · 日韩之间水道',
    source: '西太平洋态势',
    timestamp: '2026-06-12T12:00:00Z',
    location: [129.0, 34.5],
    impact_level: 'medium',
    category: 'waterways',
    description: '连接日本海与东中国海，战略要道',
  },
];

export const ISLAND_CHAIN_INCIDENTS: Incident[] = [
  {
    id: 'chain-inc-1',
    title: '宫古海峡 · 中国航母编队穿越',
    date: '2026-06-15T18:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 25.0, lng: 125.5 },
    description: '辽宁舰航母编队经宫古海峡进入西太平洋，日本自卫队派出舰艇监视',
    source: 'defense',
  },
  {
    id: 'chain-inc-2',
    title: '巴士海峡 · 美军潜艇过境',
    date: '2026-06-14T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 21.0, lng: 121.0 },
    description: '美军核潜艇经巴士海峡进入南海，中方派出反潜力量跟踪',
    source: 'usni',
  },
  {
    id: 'chain-inc-3',
    title: '冲绳周边 · 中俄联合巡航',
    date: '2026-06-13T10:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 26.5, lng: 128.0 },
    description: '中俄轰炸机联合战略巡航至日本海，美日战机升空拦截',
    source: 'reuters',
  },
  {
    id: 'chain-inc-4',
    title: '台湾以东 · 美军航母演习',
    date: '2026-06-16T07:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 23.0, lng: 123.0 },
    description: '里根号航母打击群在台湾以东海域举行演习',
    source: 'usni',
  },
  {
    id: 'chain-inc-5',
    title: '对马海峡 · 朝鲜商船可疑过境',
    date: '2026-06-12T16:00:00Z',
    type: 'political',
    faction: 'kp',
    location: { lat: 34.5, lng: 129.5 },
    description: '疑似朝鲜籍船只经对马海峡，日本海上保安厅跟踪监视',
    source: 'reuters',
  },
];

export const ISLAND_CHAIN_FACILITIES: Facility[] = [
  {
    id: 'chain-fac-kadena',
    name: '嘉手纳空军基地（冲绳）',
    position: { lat: 26.35, lng: 127.77 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军', '日本自卫队'],
    weapons: ['F-15', 'F-22', 'E-3预警机'],
    notes: '西太平洋最大美军空军基地',
  },
  {
    id: 'chain-fac-yokosuka',
    name: '横须贺海军基地',
    position: { lat: 35.29, lng: 139.67 },
    faction: 'us',
    type: 'naval',
    forces: ['美国第七舰队'],
    notes: '美国第七舰队司令部，航母母港',
  },
  {
    id: 'chain-fac-guam',
    name: '关岛安德森空军基地',
    position: { lat: 13.58, lng: 144.92 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军', '战略轰炸机'],
    weapons: ['B-52', 'B-1B', 'B-2'],
    notes: '美国战略轰炸机前沿部署基地',
  },
  {
    id: 'chain-fac-subic',
    name: '苏比克湾（菲方）',
    position: { lat: 14.8, lng: 120.3 },
    faction: 'ph',
    type: 'naval',
    notes: '菲律宾海军基地，美菲联合使用',
  },
  {
    id: 'chain-fac-clark',
    name: '克拉克空军基地（菲）',
    position: { lat: 15.19, lng: 120.56 },
    faction: 'us',
    type: 'airfield',
    notes: '美军轮换部署基地，增强第一岛链南翼',
  },
  {
    id: 'chain-fac-okinawa-marines',
    name: '冲绳陆战队基地',
    position: { lat: 26.21, lng: 127.68 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 1.8 万',
    notes: '美国海军陆战队西太平洋核心部署',
  },
  {
    id: 'chain-fac-jeju',
    name: '济州岛海军基地（韩）',
    position: { lat: 33.5, lng: 126.5 },
    faction: 'kr',
    type: 'naval',
    notes: '韩国南部战略海军基地，监视朝鲜海峡',
  },
  {
    id: 'chain-fac-sasebo',
    name: '佐世保海军基地（日）',
    position: { lat: 33.16, lng: 129.72 },
    faction: 'jp',
    type: 'naval',
    notes: '日本海上自卫队重要基地，两栖舰艇部署',
  },
  {
    id: 'chain-fac-misawa',
    name: '三泽空军基地（日）',
    position: { lat: 40.7, lng: 141.37 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军', '日本航空自卫队'],
    notes: 'F-16 与 F-35 部署，面向俄罗斯方向',
  },
  {
    id: 'chain-fac-darwin',
    name: '达尔文港（澳）',
    position: { lat: -12.46, lng: 130.84 },
    faction: 'au',
    type: 'naval',
    notes: '美军陆战队轮换部署，第一岛链南延支点',
  },
];
