import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 中日局势 · 东海与钓鱼岛 */
export const JAPAN_EVENTS: EventDetail[] = [
  {
    id: 'jp-senkaku',
    title: '钓鱼岛（尖阁诸岛）· 主权争议核心',
    source: '东海态势',
    timestamp: '2026-06-16T07:00:00Z',
    location: [123.47, 25.75],
    impact_level: 'critical',
    category: 'hotspots',
    description: '中日东海争议最敏感区域，双方海警常态化对峙',
  },
  {
    id: 'jp-okinawa',
    title: '冲绳 · 第一岛链南翼',
    source: '东海态势',
    timestamp: '2026-06-15T14:00:00Z',
    location: [127.68, 26.21],
    impact_level: 'high',
    category: 'bases',
    description: '美军与日本自卫队前沿部署，面向台海与东海',
  },
  {
    id: 'jp-east-china-sea',
    title: '东海大陆架 · 油气争端',
    source: '东海态势',
    timestamp: '2026-06-14T12:00:00Z',
    location: [125.0, 29.0],
    impact_level: 'high',
    category: 'economic',
    description: '中日韩三方大陆架划界争议，油气资源开发权分歧',
  },
  {
    id: 'jp-chunxiao',
    title: '春晓油气田 · 中日分歧区',
    source: '东海态势',
    timestamp: '2026-06-15T10:00:00Z',
    location: [125.85, 28.22],
    impact_level: 'high',
    category: 'economic',
    description: '位于中日主张重叠区，中国已开发，日本抗议',
  },
  {
    id: 'jp-yokosuka',
    title: '横须贺 · 第七舰队母港',
    source: '东海态势',
    timestamp: '2026-06-16T05:00:00Z',
    location: [139.67, 35.29],
    impact_level: 'high',
    category: 'bases',
    description: '美国第七舰队司令部，面向东海与台海',
  },
  {
    id: 'jp-sdf-southwest',
    title: '日本西南诸岛 · 防卫强化',
    source: '东海态势',
    timestamp: '2026-06-13T08:00:00Z',
    location: [128.0, 27.0],
    impact_level: 'medium',
    category: 'military',
    description: '日本在冲绳以南岛屿部署导弹与雷达，应对台海危机',
  },
  {
    id: 'jp-aegis',
    title: '日本海自宙斯盾舰部署',
    source: '东海态势',
    timestamp: '2026-06-12T12:00:00Z',
    location: [135.5, 34.5],
    impact_level: 'medium',
    category: 'military',
    description: '日本海上自卫队宙斯盾驱逐舰常态化东海巡逻',
  },
  {
    id: 'jp-tokyo',
    title: '东京 · 政治与指挥中枢',
    source: '东海态势',
    timestamp: '2026-06-16T06:00:00Z',
    location: [139.69, 35.68],
    impact_level: 'medium',
    category: 'hotspots',
    description: '日本政府与自卫队指挥中枢',
  },
];

export const JAPAN_INCIDENTS: Incident[] = [
  {
    id: 'jp-inc-1',
    title: '钓鱼岛海域 · 中日海警对峙',
    date: '2026-06-16T06:30:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 25.75, lng: 123.47 },
    description: '中国海警2301船与日本海上保安厅巡逻船在钓鱼岛附近对峙',
    source: 'reuters',
  },
  {
    id: 'jp-inc-2',
    title: '东海中部 · 中国海警船进入争议水域',
    date: '2026-06-15T14:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 29.0, lng: 125.0 },
    description: '中国海警船进入日本声称的「专属经济区」，日方提出抗议',
    source: 'ap',
  },
  {
    id: 'jp-inc-3',
    title: '春晓油气田 · 日方抗议中方钻探',
    date: '2026-06-14T10:00:00Z',
    type: 'diplomatic',
    faction: 'jp',
    location: { lat: 28.22, lng: 125.85 },
    description: '日本外务省抗议中国在春晓油气田继续钻探活动',
    source: 'reuters',
  },
  {
    id: 'jp-inc-4',
    title: '冲绳周边 · 中国军机抵近',
    date: '2026-06-16T05:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 26.5, lng: 127.5 },
    description: '中国军机经宫古海峡进入太平洋，日本自卫队战机紧急升空',
    source: 'defense',
  },
  {
    id: 'jp-inc-5',
    title: '东海 · 日本驱逐舰与中国护卫舰相遇',
    date: '2026-06-13T16:00:00Z',
    type: 'military',
    faction: 'jp',
    location: { lat: 30.0, lng: 126.0 },
    description: '双方军舰在东海相遇，通过无线电沟通后各自离开',
    source: 'defense',
  },
  {
    id: 'jp-inc-6',
    title: '钓鱼岛 · 中国海警常态化巡航',
    date: '2026-06-12T08:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 25.75, lng: 123.47 },
    description: '中国海警船编队进入钓鱼岛领海巡航，日方跟踪监视',
    source: 'xinhua',
  },
];

export const JAPAN_FACILITIES: Facility[] = [
  {
    id: 'jp-fac-kadena',
    name: '嘉手纳空军基地',
    position: { lat: 26.35, lng: 127.77 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军', '日本航空自卫队'],
    weapons: ['F-15', 'F-22'],
    notes: '西太平洋最大美军空军基地',
  },
  {
    id: 'jp-fac-yokosuka',
    name: '横须贺海军基地',
    position: { lat: 35.29, lng: 139.67 },
    faction: 'us',
    type: 'naval',
    forces: ['美国第七舰队'],
    notes: '航母母港，面向东海台海',
  },
  {
    id: 'jp-fac-sasebo',
    name: '佐世保海军基地',
    position: { lat: 33.16, lng: 129.72 },
    faction: 'jp',
    type: 'naval',
    forces: ['日本海上自卫队'],
    notes: '两栖舰艇与扫雷舰部署',
  },
  {
    id: 'jp-fac-ishigaki',
    name: '石垣岛自卫队部署',
    position: { lat: 24.34, lng: 124.16 },
    faction: 'jp',
    type: 'base',
    forces: ['陆上自卫队'],
    notes: '距钓鱼岛最近日本岛屿，导弹部署点',
  },
  {
    id: 'jp-fac-miyako',
    name: '宫古岛自卫队基地',
    position: { lat: 24.8, lng: 125.28 },
    faction: 'jp',
    type: 'base',
    notes: '宫古海峡扼守，监视中国海军出入太平洋',
  },
  {
    id: 'jp-fac-senkaku-jp',
    name: '钓鱼岛（日行政管辖）',
    position: { lat: 25.75, lng: 123.47 },
    faction: 'jp',
    type: 'base',
    notes: '日方声称行政管辖，中方不承认',
  },
  {
    id: 'jp-fac-chunxiao',
    name: '春晓油气田（中方运营）',
    position: { lat: 28.22, lng: 125.85 },
    faction: 'cn',
    type: 'base',
    notes: '位于争议区，中国已开发',
  },
  {
    id: 'jp-fac-naha',
    name: '那霸空军基地',
    position: { lat: 26.2, lng: 127.65 },
    faction: 'jp',
    type: 'airfield',
    forces: ['日本航空自卫队'],
    notes: '冲绳主要空军基地',
  },
];
