import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 朝鲜半岛 · 监测点 */
export const KOREA_EVENTS: EventDetail[] = [
  {
    id: 'kr-dmz',
    title: '三八线 · 非军事区',
    source: '半岛态势',
    timestamp: '2026-06-16T08:00:00Z',
    location: [127.0, 38.0],
    impact_level: 'critical',
    category: 'hotspots',
    description: '全球最紧张军事分界线之一，朝韩对峙前沿',
  },
  {
    id: 'kr-pyeongyang',
    title: '平壤 · 朝鲜政治中心',
    source: '半岛态势',
    timestamp: '2026-06-16T06:00:00Z',
    location: [125.76, 39.04],
    impact_level: 'critical',
    category: 'hotspots',
    description: '朝鲜劳动党与军方指挥中枢',
  },
  {
    id: 'kr-seoul',
    title: '首尔 · 韩国首都',
    source: '半岛态势',
    timestamp: '2026-06-16T07:00:00Z',
    location: [126.98, 37.57],
    impact_level: 'high',
    category: 'hotspots',
    description: '距三八线仅约 50 公里，战时首要打击目标',
  },
  {
    id: 'kr-wonsan',
    title: '元山 · 朝鲜导弹发射场',
    source: '半岛态势',
    timestamp: '2026-06-15T14:00:00Z',
    location: [127.43, 39.15],
    impact_level: 'critical',
    category: 'military',
    description: '朝鲜东部重要导弹试射场',
  },
  {
    id: 'kr-sinpo',
    title: '新浦 · 潜艇导弹基地',
    source: '半岛态势',
    timestamp: '2026-06-15T12:00:00Z',
    location: [128.17, 40.02],
    impact_level: 'critical',
    category: 'military',
    description: '朝鲜潜射弹道导弹研发与试验基地',
  },
  {
    id: 'kr-yongbyon',
    title: '宁边 · 核设施',
    source: '半岛态势',
    timestamp: '2026-06-14T10:00:00Z',
    location: [125.75, 39.79],
    impact_level: 'critical',
    category: 'nuclear',
    description: '朝鲜主要核设施与钚生产设施',
  },
  {
    id: 'kr-osan',
    title: '乌山空军基地（美军）',
    source: '半岛态势',
    timestamp: '2026-06-16T05:00:00Z',
    location: [127.03, 37.09],
    impact_level: 'high',
    category: 'bases',
    description: '美国驻韩空军第七航空队司令部',
  },
  {
    id: 'kr-camp-humphreys',
    title: '汉弗莱斯营（美军）',
    source: '半岛态势',
    timestamp: '2026-06-15T08:00:00Z',
    location: [127.06, 36.96],
    impact_level: 'high',
    category: 'bases',
    description: '美国海外最大军事基地，驻韩美军司令部',
  },
  {
    id: 'kr-kaesong',
    title: '开城工业园（停运）',
    source: '半岛态势',
    timestamp: '2026-06-13T12:00:00Z',
    location: [126.68, 37.97],
    impact_level: 'medium',
    category: 'economic',
    description: '朝韩经济合作象征，2016年停运',
  },
  {
    id: 'kr-jeju',
    title: '济州岛 · 韩国南部战略要地',
    source: '半岛态势',
    timestamp: '2026-06-12T10:00:00Z',
    location: [126.53, 33.5],
    impact_level: 'medium',
    category: 'bases',
    description: '韩国海军南方战略基地',
  },
];

export const KOREA_INCIDENTS: Incident[] = [
  {
    id: 'kr-inc-1',
    title: '朝鲜试射弹道导弹 · 落入日本海',
    date: '2026-06-16T06:00:00Z',
    type: 'military',
    faction: 'kp',
    location: { lat: 40.0, lng: 129.0 },
    description: '朝鲜从平安北道发射中程弹道导弹，落入日本海',
    source: 'reuters',
  },
  {
    id: 'kr-inc-2',
    title: '三八线附近 · 朝鲜士兵越界',
    date: '2026-06-15T14:00:00Z',
    type: 'military',
    faction: 'kp',
    location: { lat: 38.0, lng: 127.0 },
    description: '朝鲜士兵越过军事分界线，韩方鸣枪警告后退回',
    source: 'ap',
  },
  {
    id: 'kr-inc-3',
    title: '美韩联合军演 · 乙支自由护盾',
    date: '2026-06-14T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 37.5, lng: 127.0 },
    description: '美韩举行大规模联合军演，朝鲜谴责为「侵略预演」',
    source: 'reuters',
  },
  {
    id: 'kr-inc-4',
    title: '宁边核设施 · 卫星发现活动增加',
    date: '2026-06-13T12:00:00Z',
    type: 'military',
    faction: 'kp',
    location: { lat: 39.79, lng: 125.75 },
    description: '商业卫星显示宁边核设施车辆活动增加，疑为核原料加工',
    source: '38north',
  },
  {
    id: 'kr-inc-5',
    title: '朝鲜对韩广播 · 心理战升级',
    date: '2026-06-16T07:00:00Z',
    type: 'political',
    faction: 'kp',
    location: { lat: 38.0, lng: 126.5 },
    description: '朝鲜恢复对韩边境广播，韩国以广播回应',
    source: 'yonhap',
  },
  {
    id: 'kr-inc-6',
    title: '黄海 · 中韩海警对峙',
    date: '2026-06-15T10:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 36.0, lng: 124.0 },
    description: '中韩海警在黄海苏岩礁附近海域对峙，渔业纠纷',
    source: 'xinhua',
  },
  {
    id: 'kr-inc-7',
    title: '朝鲜发射巡航导弹 · 东海方向',
    date: '2026-06-12T16:00:00Z',
    type: 'military',
    faction: 'kp',
    location: { lat: 39.5, lng: 127.5 },
    description: '朝鲜从陆基发射场发射多枚巡航导弹',
    source: 'kcna',
  },
  {
    id: 'kr-inc-8',
    title: '驻韩美军萨德系统 · 雷达开机',
    date: '2026-06-16T05:30:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 36.4, lng: 127.37 },
    description: '驻韩美军萨德反导系统雷达开机，监测朝鲜导弹活动',
    source: 'defense',
  },
];

export const KOREA_FACILITIES: Facility[] = [
  {
    id: 'kr-fac-yongbyon',
    name: '宁边核科学研究中心',
    position: { lat: 39.79, lng: 125.75 },
    faction: 'kp',
    type: 'nuclear',
    nuclearKind: 'research_reactor',
    status: '运行中',
    notes: '朝鲜主要钚生产设施',
  },
  {
    id: 'kr-fac-sinpo',
    name: '新浦造船厂（潜射导弹）',
    position: { lat: 40.02, lng: 128.17 },
    faction: 'kp',
    type: 'missile',
    notes: '朝鲜潜射弹道导弹研发基地',
  },
  {
    id: 'kr-fac-wonsan',
    name: '元山导弹发射场',
    position: { lat: 39.15, lng: 127.43 },
    faction: 'kp',
    type: 'missile',
    notes: '朝鲜东部主要导弹试射场',
  },
  {
    id: 'kr-fac-osan',
    name: '乌山空军基地',
    position: { lat: 37.09, lng: 127.03 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军第七航空队'],
    weapons: ['F-16', 'A-10'],
    notes: '驻韩美军主要空军基地',
  },
  {
    id: 'kr-fac-humphreys',
    name: '汉弗莱斯营',
    position: { lat: 36.96, lng: 127.06 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 3.6 万',
    notes: '美国海外最大军事基地',
  },
  {
    id: 'kr-fac-thaad',
    name: '萨德反导系统（星州）',
    position: { lat: 35.95, lng: 129.2 },
    faction: 'us',
    type: 'missile',
    weapons: ['萨德拦截弹'],
    notes: '部署于庆尚北道星州，引发中韩外交争议',
  },
  {
    id: 'kr-fac-pyeongtaek',
    name: '平泽海军基地',
    position: { lat: 36.99, lng: 126.83 },
    faction: 'kr',
    type: 'naval',
    forces: ['韩国海军'],
    notes: '韩国西部主要海军基地',
  },
  {
    id: 'kr-fac-dmz-south',
    name: '板门店（韩方）',
    position: { lat: 37.95, lng: 126.68 },
    faction: 'kr',
    type: 'base',
    notes: '朝韩军事分界线会谈场所',
  },
  {
    id: 'kr-fac-dandong',
    name: '丹东 · 中朝边境口岸',
    position: { lat: 40.13, lng: 124.39 },
    faction: 'cn',
    type: 'base',
    notes: '中国对朝贸易主要通道，边境监视',
  },
  {
    id: 'kr-fac-jeju-naval',
    name: '济州海军基地',
    position: { lat: 33.5, lng: 126.53 },
    faction: 'kr',
    type: 'naval',
    notes: '韩国南部战略海军基地',
  },
];
