import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 南海局势 · 事件监测点 */
export const SCS_EVENTS: EventDetail[] = [
  {
    id: 'scs-mischief-reef',
    title: '美济礁 · 南沙岛礁建设监测',
    source: '南海态势监测',
    timestamp: '2026-06-16T08:00:00Z',
    location: [115.52, 9.9],
    impact_level: 'high',
    category: 'military',
    description: '南沙群岛核心岛礁，具备机场、港口与雷达设施，南海方向战略支点',
  },
  {
    id: 'scs-fiery-cross',
    title: '永暑礁 · 南沙行政与补给中心',
    source: '南海态势监测',
    timestamp: '2026-06-16T07:30:00Z',
    location: [112.97, 9.55],
    impact_level: 'high',
    category: 'military',
    description: '南沙群岛最大人工岛，三公里跑道与深水港，区域管控枢纽',
  },
  {
    id: 'scs-subi-reef',
    title: '渚碧礁 · 渔业与海上执法基地',
    source: '南海态势监测',
    timestamp: '2026-06-15T14:20:00Z',
    location: [114.07, 10.92],
    impact_level: 'medium',
    category: 'military',
    description: '南沙北部重要岛礁，海警与海军前沿部署点',
  },
  {
    id: 'scs-woody-island',
    title: '永兴岛 · 西沙群岛行政中心',
    source: '南海态势监测',
    timestamp: '2026-06-16T06:00:00Z',
    location: [112.34, 16.83],
    impact_level: 'high',
    category: 'military',
    description: '三沙市政府驻地，西沙群岛军事与行政核心',
  },
  {
    id: 'scs-scarborough',
    title: '黄岩岛 · 中菲争议焦点',
    source: '南海态势监测',
    timestamp: '2026-06-16T10:15:00Z',
    location: [117.75, 15.13],
    impact_level: 'critical',
    category: 'hotspots',
    description: '中菲南海争议最敏感点位之一，海警常态化巡航与对峙',
  },
  {
    id: 'scs-spratly-it',
    title: '南沙群岛 · 多国占领岛礁态势',
    source: '南海态势监测',
    timestamp: '2026-06-15T16:00:00Z',
    location: [114.5, 8.5],
    impact_level: 'high',
    category: 'conflicts',
    description: '越南、菲律宾、马来西亚等国占据部分岛礁，与中国主张区域重叠',
  },
  {
    id: 'scs-paracel',
    title: '西沙群岛 · 海域管控区',
    source: '南海态势监测',
    timestamp: '2026-06-14T12:00:00Z',
    location: [111.5, 16.5],
    impact_level: 'high',
    category: 'military',
    description: '中国实际控制西沙群岛，越南仍主张主权',
  },
  {
    id: 'scs-nine-dash',
    title: '南海九段线 · 主张海域',
    source: '南海态势监测',
    timestamp: '2026-06-13T08:00:00Z',
    location: [113.0, 12.0],
    impact_level: 'medium',
    category: 'waterways',
    description: '中国历史性权利主张海域，与周边国家专属经济区部分重叠',
  },
  {
    id: 'scs-hainan-base',
    title: '三亚榆林 · 南海舰队母港',
    source: '南海态势监测',
    timestamp: '2026-06-16T05:00:00Z',
    location: [109.51, 18.25],
    impact_level: 'critical',
    category: 'bases',
    description: '南海舰队核心基地，航母编队与核潜艇部署',
  },
  {
    id: 'scs-reed-bank',
    title: '礼乐滩 · 油气勘探争议区',
    source: '南海态势监测',
    timestamp: '2026-06-15T11:30:00Z',
    location: [116.8, 11.0],
    impact_level: 'high',
    category: 'economic',
    description: '富含油气资源，中菲勘探权争议持续',
  },
];

/** 南海局势 · 冲突事件 */
export const SCS_INCIDENTS: Incident[] = [
  {
    id: 'scs-inc-1',
    title: '黄岩岛附近 · 中菲海警对峙升级',
    date: '2026-06-16T09:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 15.13, lng: 117.75 },
    description: '中国海警与菲律宾海岸警卫队在黄岩岛潟湖入口附近对峙，双方均宣称执法权',
    source: 'reuters',
  },
  {
    id: 'scs-inc-2',
    title: '南沙第二托马斯滩 · 菲律宾补给船遭拦截',
    date: '2026-06-15T14:30:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 9.75, lng: 115.85 },
    description: '中国海警对向坐滩军舰马德雷山号补给之菲方船只实施水炮驱离',
    source: 'ap',
  },
  {
    id: 'scs-inc-3',
    title: '美济礁周边 · 美军侦察机抵近',
    date: '2026-06-16T06:45:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 9.9, lng: 115.52 },
    description: 'P-8A 海神巡逻机抵近美济礁上空，中国战机升空伴飞',
    source: 'defense',
  },
  {
    id: 'scs-inc-4',
    title: '西沙海域 · 越南渔船被驱离',
    date: '2026-06-14T10:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 16.5, lng: 111.8 },
    description: '中国海警在西沙群岛附近驱离越方非法捕捞渔船',
    source: 'xinhua',
  },
  {
    id: 'scs-inc-5',
    title: '南海北部 · 美军航母打击群过境',
    date: '2026-06-13T18:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 14.0, lng: 115.0 },
    description: '罗斯福号航母打击群穿越南海，开展「航行自由」行动',
    source: 'usni',
  },
  {
    id: 'scs-inc-6',
    title: '礼乐滩 · 菲方勘探船遭中方抗议',
    date: '2026-06-15T08:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 11.0, lng: 116.8 },
    description: '中国外交部抗议菲律宾在礼乐滩单方面油气勘探活动',
    source: 'xinhua',
  },
  {
    id: 'scs-inc-7',
    title: '永暑礁 · 多国联合军演临近',
    date: '2026-06-12T12:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 9.55, lng: 112.97 },
    description: '美菲「肩并肩」军演在南沙以北海域举行，中国派出舰艇监视',
    source: 'reuters',
  },
  {
    id: 'scs-inc-8',
    title: '马六甲海峡入口 · 南海航运安全通报',
    date: '2026-06-16T11:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 2.5, lng: 104.0 },
    description: '中国海事局发布南海北部航行警告，提醒船舶注意军事演习区域',
    source: 'maritime',
  },
];

/** 南海局势 · 设施与岛礁 */
export const SCS_FACILITIES: Facility[] = [
  {
    id: 'scs-fac-mischief',
    name: '美济礁综合基地',
    position: { lat: 9.9, lng: 115.52 },
    faction: 'cn',
    type: 'naval',
    forces: ['海军', '海警', '空军'],
    weapons: ['歼-11', '红旗-9', '鹰击-12'],
    notes: '南沙最大人工岛，约 5.6 平方公里，具备完整军事与民事设施',
  },
  {
    id: 'scs-fac-fiery',
    name: '永暑礁综合基地',
    position: { lat: 9.55, lng: 112.97 },
    faction: 'cn',
    type: 'naval',
    forces: ['海军', '海警'],
    notes: '南沙行政与补给中心，三公里跑道',
  },
  {
    id: 'scs-fac-subi',
    name: '渚碧礁基地',
    position: { lat: 10.92, lng: 114.07 },
    faction: 'cn',
    type: 'naval',
    notes: '南沙北部前沿，渔业保护与管理',
  },
  {
    id: 'scs-fac-woody',
    name: '永兴岛（西沙）',
    position: { lat: 16.83, lng: 112.34 },
    faction: 'cn',
    type: 'airfield',
    forces: ['空军', '海警', '行政'],
    notes: '三沙市政府驻地，西沙核心岛礁',
  },
  {
    id: 'scs-fac-scarborough',
    name: '黄岩岛（控制区）',
    position: { lat: 15.13, lng: 117.75 },
    faction: 'cn',
    type: 'naval',
    notes: '中国实际控制，菲律宾主张主权',
  },
  {
    id: 'scs-fac-thitu',
    name: '中业岛（菲占）',
    position: { lat: 11.05, lng: 114.29 },
    faction: 'ph',
    type: 'airfield',
    notes: '菲律宾占据最大南沙岛礁，建有跑道',
  },
  {
    id: 'scs-fac-spratly-ph',
    name: '巴拉望岛（菲后方基地）',
    position: { lat: 9.8, lng: 118.7 },
    faction: 'ph',
    type: 'naval',
    notes: '菲律宾南海行动后方支援基地',
  },
  {
    id: 'scs-fac-vietnam',
    name: '南威岛（越占）',
    position: { lat: 8.65, lng: 111.92 },
    faction: 'vn',
    type: 'naval',
    notes: '越南占据南沙岛礁中最大者之一',
  },
  {
    id: 'scs-fac-malaysia',
    name: '弹丸礁（马占）',
    position: { lat: 7.37, lng: 113.85 },
    faction: 'my',
    type: 'naval',
    notes: '马来西亚占据，建有度假村与小型机场',
  },
  {
    id: 'scs-fac-sanya',
    name: '三亚榆林海军基地',
    position: { lat: 18.25, lng: 109.51 },
    faction: 'cn',
    type: 'naval',
    forces: ['南海舰队', '潜艇部队', '航母编队'],
    weapons: ['山东舰', '055型驱逐舰', '093核潜艇'],
    troopEstimate: '数万',
    notes: '南海方向核心军港',
  },
  {
    id: 'scs-fac-zhanjiang',
    name: '湛江海军基地',
    position: { lat: 21.2, lng: 110.4 },
    faction: 'cn',
    type: 'naval',
    forces: ['南海舰队'],
    notes: '南海舰队另一重要母港',
  },
  {
    id: 'scs-fac-reef-bank',
    name: '礼乐滩油气区',
    position: { lat: 11.0, lng: 116.8 },
    faction: 'contested',
    type: 'base',
    notes: '富含油气，中菲勘探权争议',
  },
];
