import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 台海局势 · 监测点 */
export const TAIWAN_EVENTS: EventDetail[] = [
  {
    id: 'tw-strait-mid',
    title: '台湾海峡中线 · 军事对峙前沿',
    source: '台海态势',
    timestamp: '2026-06-16T08:30:00Z',
    location: [119.5, 24.5],
    impact_level: 'critical',
    category: 'military',
    description: '两岸军机军舰常态化越过海峡中线，对峙态势持续',
  },
  {
    id: 'tw-kinmen',
    title: '金门岛 · 前线岛屿',
    source: '台海态势',
    timestamp: '2026-06-16T07:00:00Z',
    location: [118.32, 24.43],
    impact_level: 'high',
    category: 'hotspots',
    description: '距大陆最近台湾控制岛屿，两岸军事敏感区',
  },
  {
    id: 'tw-matsu',
    title: '马祖列岛 · 北翼前沿',
    source: '台海态势',
    timestamp: '2026-06-15T14:00:00Z',
    location: [119.93, 26.16],
    impact_level: 'high',
    category: 'hotspots',
    description: '台湾北部离岛，与福建平潭隔海相望',
  },
  {
    id: 'tw-penghu',
    title: '澎湖列岛 · 海峡枢纽',
    source: '台海态势',
    timestamp: '2026-06-15T12:00:00Z',
    location: [119.58, 23.57],
    impact_level: 'high',
    category: 'military',
    description: '控制台湾海峡中部航道，台军重要防御阵地',
  },
  {
    id: 'tw-taipei',
    title: '台北 · 政治中心',
    source: '台海态势',
    timestamp: '2026-06-16T06:00:00Z',
    location: [121.56, 25.03],
    impact_level: 'critical',
    category: 'hotspots',
    description: '台湾当局政治与军事指挥中枢',
  },
  {
    id: 'tw-kaohsiung',
    title: '高雄港 · 海军基地',
    source: '台海态势',
    timestamp: '2026-06-14T10:00:00Z',
    location: [120.28, 22.62],
    impact_level: 'high',
    category: 'bases',
    description: '台湾最大军港，海军舰队主要母港',
  },
  {
    id: 'tw-hualien',
    title: '花莲空军基地',
    source: '台海态势',
    timestamp: '2026-06-15T08:00:00Z',
    location: [121.62, 24.03],
    impact_level: 'high',
    category: 'bases',
    description: '台湾东部重要空军基地，战机洞库部署',
  },
  {
    id: 'tw-fujian-coast',
    title: '福建沿海 · 对台前沿',
    source: '台海态势',
    timestamp: '2026-06-16T05:00:00Z',
    location: [119.3, 26.08],
    impact_level: 'high',
    category: 'military',
    description: '东部战区对台作战前沿部署区',
  },
  {
    id: 'tw-dongsha',
    title: '东沙群岛（台控）',
    source: '台海态势',
    timestamp: '2026-06-13T12:00:00Z',
    location: [116.72, 20.7],
    impact_level: 'medium',
    category: 'hotspots',
    description: '台湾控制南海北部岛礁，战略位置重要',
  },
  {
    id: 'tw-pratas',
    title: '太平岛（台占南沙）',
    source: '台海态势',
    timestamp: '2026-06-12T10:00:00Z',
    location: [114.36, 10.38],
    impact_level: 'medium',
    category: 'hotspots',
    description: '台湾占据南沙最大自然岛，建有跑道',
  },
];

export const TAIWAN_INCIDENTS: Incident[] = [
  {
    id: 'tw-inc-1',
    title: '台海中线 · 解放军军机大规模过线',
    date: '2026-06-16T07:30:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 24.5, lng: 119.5 },
    description: '东部战区出动多架歼-16、轰-6K 越过海峡中线，台军战机紧急升空',
    source: 'defense',
  },
  {
    id: 'tw-inc-2',
    title: '金门海域 · 大陆海警常态化巡航',
    date: '2026-06-15T16:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 24.43, lng: 118.32 },
    description: '福建海警在金门附近海域开展执法巡航，台方声称「越界」',
    source: 'xinhua',
  },
  {
    id: 'tw-inc-3',
    title: '台湾以东 · 美军驱逐舰过航台海',
    date: '2026-06-14T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 24.0, lng: 121.0 },
    description: '美军驱逐舰穿越台湾海峡，中方谴责并派出舰艇跟踪监视',
    source: 'reuters',
  },
  {
    id: 'tw-inc-4',
    title: '澎湖海域 · 两岸军舰对峙',
    date: '2026-06-16T06:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 23.57, lng: 119.58 },
    description: '解放军海军舰艇在澎湖以西海域活动，台海军派出舰艇监视',
    source: 'defense',
  },
  {
    id: 'tw-inc-5',
    title: '马祖附近 · 无人机越界事件',
    date: '2026-06-15T10:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 26.16, lng: 119.93 },
    description: '大陆无人机飞越马祖上空，台军首次开枪警告',
    source: 'ap',
  },
  {
    id: 'tw-inc-6',
    title: '台海联合军演 · 东部战区围岛演习',
    date: '2026-06-13T08:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 24.0, lng: 120.0 },
    description: '解放军在台岛周边海空域开展联合战备警巡与围岛演习',
    source: 'xinhua',
  },
  {
    id: 'tw-inc-7',
    title: '美国对台军售 · 新一批武器交付',
    date: '2026-06-12T12:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 25.03, lng: 121.56 },
    description: '美国宣布新一批对台军售，包括导弹与雷达系统',
    source: 'reuters',
  },
  {
    id: 'tw-inc-8',
    title: '台湾海峡 · 民航绕飞通告',
    date: '2026-06-16T09:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 24.5, lng: 119.5 },
    description: '民航局发布台湾海峡北部临时禁航通告，影响部分国际航线',
    source: 'caac',
  },
];

export const TAIWAN_FACILITIES: Facility[] = [
  {
    id: 'tw-fac-kaohsiung',
    name: '高雄左营海军基地',
    position: { lat: 22.62, lng: 120.28 },
    faction: 'tw',
    type: 'naval',
    forces: ['台湾海军'],
    notes: '台湾最大军港，舰队司令部',
  },
  {
    id: 'tw-fac-hualien',
    name: '花莲空军基地',
    position: { lat: 24.03, lng: 121.62 },
    faction: 'tw',
    type: 'airfield',
    forces: ['台湾空军'],
    weapons: ['F-16V', 'IDF经国号'],
    notes: '东部战机洞库，躲避首轮打击',
  },
  {
    id: 'tw-fac-chingchuankang',
    name: '清泉岗空军基地',
    position: { lat: 24.26, lng: 120.62 },
    faction: 'tw',
    type: 'airfield',
    forces: ['台湾空军'],
    notes: '中部重要空军基地',
  },
  {
    id: 'tw-fac-kinmen',
    name: '金门守备部队',
    position: { lat: 24.43, lng: 118.32 },
    faction: 'tw',
    type: 'base',
    troopEstimate: '约 1 万',
    notes: '距大陆最近前线岛屿',
  },
  {
    id: 'tw-fac-penghu',
    name: '澎湖防卫指挥部',
    position: { lat: 23.57, lng: 119.58 },
    faction: 'tw',
    type: 'naval',
    notes: '控制海峡中部航道',
  },
  {
    id: 'tw-fac-fuzhou',
    name: '福州对台前沿',
    position: { lat: 26.08, lng: 119.3 },
    faction: 'cn',
    type: 'base',
    forces: ['东部战区'],
    notes: '大陆对台作战前沿部署',
  },
  {
    id: 'tw-fac-xiamen',
    name: '厦门对台前沿',
    position: { lat: 24.48, lng: 118.09 },
    faction: 'cn',
    type: 'base',
    forces: ['东部战区', '火箭军'],
    notes: '距金门最近大陆军事部署区',
  },
  {
    id: 'tw-fac-pingtan',
    name: '平潭综合实验区（军事）',
    position: { lat: 25.5, lng: 119.78 },
    faction: 'cn',
    type: 'naval',
    notes: '对台登陆作战前沿准备区',
  },
  {
    id: 'tw-fac-dongsha',
    name: '东沙岛（台军）',
    position: { lat: 20.7, lng: 116.72 },
    faction: 'tw',
    type: 'naval',
    notes: '台湾控制南海北部岛礁',
  },
];
