import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国国内政治与安全热点监测 / seed';

/** 国内政治与安全热点 · 事件监测点 */
export const US_DOMESTIC_EVENTS: EventDetail[] = [
  {
    id: 'us-dom-border-texas',
    title: '得州边境 · 移民与执法',
    source: SRC,
    timestamp: T,
    location: [-106.5, 31.75],
    impact_level: 'high',
    category: 'hotspots',
    description: '美墨边境移民潮与州联邦执法权争议',
  },
  {
    id: 'us-dom-border-arizona',
    title: '亚利桑那边境 · 墙与通道',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [-111.07, 31.33],
    impact_level: 'high',
    category: 'hotspots',
    description: '边境墙缺口与走私通道监测',
  },
  {
    id: 'us-dom-dc-capitol',
    title: '国会山 · 立法与安全',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [-77.01, 38.89],
    impact_level: 'high',
    category: 'hotspots',
    description: '国防授权、预算与选举相关立法',
  },
  {
    id: 'us-dom-election-swing',
    title: '摇摆州 · 2026 中期选举',
    source: SRC,
    timestamp: '2026-06-16T10:00:00Z',
    location: [-83.05, 42.33],
    impact_level: 'medium',
    category: 'hotspots',
    description: '密歇根等关键州选情与安全节点',
  },
  {
    id: 'us-dom-chicago',
    title: '芝加哥 · 枪支暴力热点',
    source: SRC,
    timestamp: '2026-06-14T22:00:00Z',
    location: [-87.63, 41.88],
    impact_level: 'medium',
    category: 'hotspots',
    description: '治安政策与社区安全争议',
  },
  {
    id: 'us-dom-minneapolis',
    title: '明尼阿波利斯 · 警民关系',
    source: SRC,
    timestamp: '2026-06-14T20:00:00Z',
    location: [-93.27, 44.98],
    impact_level: 'medium',
    category: 'protests',
    description: '执法改革与社会抗议（种子/示例）',
  },
  {
    id: 'us-dom-portland',
    title: '波特兰 · 社会运动',
    source: SRC,
    timestamp: '2026-06-13T18:00:00Z',
    location: [-122.68, 45.52],
    impact_level: 'medium',
    category: 'protests',
    description: '示威与联邦执法介入历史敏感区',
  },
  {
    id: 'us-dom-fentanyl',
    title: '芬太尼危机 · 跨境走私',
    source: SRC,
    timestamp: '2026-06-16T08:00:00Z',
    location: [-117.16, 32.72],
    impact_level: 'high',
    category: 'hotspots',
    description: '圣地亚哥口岸前体化学品与毒品走私',
  },
  {
    id: 'us-dom-election-georgia',
    title: '佐治亚 · 选举安全',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [-84.39, 33.75],
    impact_level: 'medium',
    category: 'hotspots',
    description: '投票系统与选举诚信争议',
  },
  {
    id: 'us-dom-pennsylvania',
    title: '宾夕法尼亚 · 摇摆州',
    source: SRC,
    timestamp: '2026-06-15T12:00:00Z',
    location: [-77.86, 40.27],
    impact_level: 'medium',
    category: 'hotspots',
    description: '关键选区与能源政策交汇',
  },
];

export const US_DOMESTIC_INCIDENTS: Incident[] = [
  {
    id: 'us-dom-inc-1',
    title: '得州边境 · 州兵与联邦对峙',
    date: '2026-06-16T06:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 31.75, lng: -106.5 },
    description: '州政府边境执法与联邦移民政策冲突',
    source: 'seed',
  },
  {
    id: 'us-dom-inc-2',
    title: '国会 · 国防授权法案辩论',
    date: '2026-06-15T20:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.89, lng: -77.01 },
    description: '2026 NDAA 预算与对华竞争条款',
    source: 'congress',
  },
  {
    id: 'us-dom-inc-3',
    title: '芝加哥 · 周末枪击事件',
    date: '2026-06-14T22:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 41.88, lng: -87.63 },
    description: '枪支暴力统计与社会政策辩论（种子/示例）',
    source: 'seed',
  },
  {
    id: 'us-dom-inc-4',
    title: '芬太尼 · 跨境缉获行动',
    date: '2026-06-16T04:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 32.72, lng: -117.16 },
    description: 'DEA 与海关在口岸查获前体化学品',
    source: 'dea',
  },
  {
    id: 'us-dom-inc-5',
    title: '密歇根 · 选举法诉讼',
    date: '2026-06-13T16:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 42.33, lng: -83.05 },
    description: '投票规则与选区划分司法挑战',
    source: 'seed',
  },
  {
    id: 'us-dom-inc-6',
    title: '波特兰 · 示威活动',
    date: '2026-06-12T20:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 45.52, lng: -122.68 },
    description: '社会运动与治安执法（种子/示例）',
    source: 'seed',
  },
];

export const US_DOMESTIC_FACILITIES: Facility[] = [
  {
    id: 'us-dom-fac-border-patrol',
    name: '海关与边境保护局（埃尔帕索）',
    position: { lat: 31.76, lng: -106.49 },
    faction: 'us',
    type: 'base',
    notes: '边境执法枢纽',
  },
  {
    id: 'us-dom-fac-fbi-hq',
    name: 'FBI 总部（胡佛大厦）',
    position: { lat: 38.9, lng: -77.05 },
    faction: 'us',
    type: 'base',
    notes: '国内安全执法',
  },
  {
    id: 'us-dom-fac-dhs',
    name: '国土安全部',
    position: { lat: 38.9, lng: -77.01 },
    faction: 'us',
    type: 'base',
    notes: '边境与网络安全政策',
  },
  {
    id: 'us-dom-fac-secret-service',
    name: '特勤局训练中心',
    position: { lat: 38.75, lng: -77.47 },
    faction: 'us',
    type: 'base',
    notes: '要员保护与选举安全',
  },
  {
    id: 'us-dom-fac-atf',
    name: 'ATF 国家培训中心',
    position: { lat: 38.9, lng: -77.0 },
    faction: 'us',
    type: 'base',
    notes: '枪支与爆炸物执法',
  },
  {
    id: 'us-dom-fac-election-cisa',
    name: 'CISA 选举安全中心',
    position: { lat: 38.9, lng: -77.04 },
    faction: 'us',
    type: 'base',
    notes: '关键基础设施与选举系统保护',
  },
  {
    id: 'us-dom-fac-san-diego-border',
    name: '圣伊西德罗口岸',
    position: { lat: 32.72, lng: -117.16 },
    faction: 'us',
    type: 'base',
    notes: '全球最繁忙陆地口岸之一',
  },
  {
    id: 'us-dom-fac-cbp-texas',
    name: '麦卡伦边境巡逻站',
    position: { lat: 26.2, lng: -98.23 },
    faction: 'us',
    type: 'base',
    notes: '里奥格兰德河谷执法',
  },
];
