import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国全球军事部署监测 / seed';

/** 全球军事部署 · 事件监测点 */
export const US_GARRISON_EVENTS: EventDetail[] = [
  {
    id: 'us-gar-guam-andersen',
    title: '关岛安德森空军基地',
    source: SRC,
    timestamp: T,
    location: [144.93, 13.58],
    impact_level: 'critical',
    category: 'bases',
    description: '西太平洋战略轰炸与加油机前沿，B-52/B-1 轮换部署',
  },
  {
    id: 'us-gar-guam-apra',
    title: '关岛阿普拉海军基地',
    source: SRC,
    timestamp: '2026-06-16T07:00:00Z',
    location: [144.65, 13.44],
    impact_level: 'critical',
    category: 'bases',
    description: '西太平洋潜艇与水面舰艇前沿补给港',
  },
  {
    id: 'us-gar-kadena',
    title: '冲绳嘉手纳空军基地',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [127.77, 26.35],
    impact_level: 'critical',
    category: 'bases',
    description: '第一岛链最大前沿空军基地，战斗机与加油机枢纽',
  },
  {
    id: 'us-gar-yokosuka',
    title: '横须贺海军基地',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [139.67, 35.29],
    impact_level: 'critical',
    category: 'bases',
    description: '美第七舰队母港，航母常驻',
  },
  {
    id: 'us-gar-sasebo',
    title: '佐世保海军基地',
    source: SRC,
    timestamp: '2026-06-15T12:00:00Z',
    location: [129.72, 33.16],
    impact_level: 'high',
    category: 'bases',
    description: '两栖舰艇与扫雷力量前沿港口',
  },
  {
    id: 'us-gar-okinawa-futenma',
    title: '普天间海军陆战队航空站',
    source: SRC,
    timestamp: '2026-06-14T16:00:00Z',
    location: [127.76, 26.27],
    impact_level: 'high',
    category: 'bases',
    description: '冲绳 MV-22 与战斗机部署，搬迁争议持续',
  },
  {
    id: 'us-gar-humphreys',
    title: '汉弗莱斯军营（平泽）',
    source: SRC,
    timestamp: '2026-06-16T05:00:00Z',
    location: [127.02, 36.97],
    impact_level: 'high',
    category: 'bases',
    description: '驻韩美军司令部，海外最大陆军基地',
  },
  {
    id: 'us-gar-ramstein',
    title: '拉姆施泰因空军基地',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [7.6, 49.44],
    impact_level: 'critical',
    category: 'bases',
    description: '美军欧洲空运与指挥枢纽，乌克兰援助转运中心',
  },
  {
    id: 'us-gar-diego-garcia',
    title: '迪戈加西亚战略基地',
    source: SRC,
    timestamp: '2026-06-16T04:00:00Z',
    location: [72.41, -7.31],
    impact_level: 'critical',
    category: 'bases',
    description: '印度洋战略前沿，轰炸机和海上巡逻机中转',
  },
  {
    id: 'us-gar-al-udeid',
    title: '乌代德空军基地',
    source: SRC,
    timestamp: '2026-06-15T10:00:00Z',
    location: [51.32, 25.12],
    impact_level: 'high',
    category: 'bases',
    description: '美中央司令部前沿空军枢纽（卡塔尔）',
  },
  {
    id: 'us-gar-bahrain',
    title: '巴林第五舰队总部',
    source: SRC,
    timestamp: '2026-06-14T14:00:00Z',
    location: [50.58, 26.23],
    impact_level: 'high',
    category: 'bases',
    description: '美海军中央司令部与第五舰队前沿',
  },
  {
    id: 'us-gar-rota',
    title: '罗塔海军基地',
    source: SRC,
    timestamp: '2026-06-13T12:00:00Z',
    location: [-6.35, 36.62],
    impact_level: 'medium',
    category: 'bases',
    description: '西班牙前沿驱逐舰母港，地中海—大西洋通道',
  },
  {
    id: 'us-gar-lemonnier',
    title: '莱蒙尼耶军营',
    source: SRC,
    timestamp: '2026-06-14T08:00:00Z',
    location: [43.15, 11.55],
    impact_level: 'high',
    category: 'bases',
    description: '美军非洲之角唯一常设基地（吉布提）',
  },
  {
    id: 'us-gar-guantanamo',
    title: '关塔那摩湾海军基地',
    source: SRC,
    timestamp: '2026-06-12T10:00:00Z',
    location: [-75.16, 19.9],
    impact_level: 'medium',
    category: 'bases',
    description: '加勒比海军基地与拘留设施',
  },
];

export const US_GARRISON_INCIDENTS: Incident[] = [
  {
    id: 'us-gar-inc-1',
    title: '关岛 · 敏捷作战部署演习',
    date: '2026-06-16T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 13.58, lng: 144.93 },
    description: '安德森基地 B-52 快速部署与分散作战演练',
    source: 'pacaf',
  },
  {
    id: 'us-gar-inc-2',
    title: '冲绳 · 嘉手纳战斗机轮换',
    date: '2026-06-15T16:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 26.35, lng: 127.77 },
    description: 'F-15/F-35 中队轮换部署与联合演训',
    source: 'pacaf',
  },
  {
    id: 'us-gar-inc-3',
    title: '横须贺 · 航母打击群出港',
    date: '2026-06-16T02:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 35.29, lng: 139.67 },
    description: '第七舰队 CSG 西太平洋巡逻',
    source: 'navy',
  },
  {
    id: 'us-gar-inc-4',
    title: '拉姆施泰因 · 跨大西洋空运',
    date: '2026-06-15T20:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 49.44, lng: 7.6 },
    description: 'C-17/C-130 欧洲前沿物资转运高峰',
    source: 'usafe',
  },
  {
    id: 'us-gar-inc-5',
    title: '迪戈加西亚 · 战略轰炸机前沿部署',
    date: '2026-06-14T12:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: -7.31, lng: 72.41 },
    description: 'B-52 印度洋前沿存在演训',
    source: 'afgsc',
  },
  {
    id: 'us-gar-inc-6',
    title: '驻韩美军 · 联合军演',
    date: '2026-06-13T06:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 36.97, lng: 127.02 },
    description: '半岛联合防御演训与力量展示',
    source: 'usfk',
  },
  {
    id: 'us-gar-inc-7',
    title: '乌代德 · 中东空中作战支援',
    date: '2026-06-12T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 25.12, lng: 51.32 },
    description: 'CENTCOM 前沿空中加油与侦察枢纽运转',
    source: 'centcom',
  },
  {
    id: 'us-gar-inc-8',
    title: '菲律宾 · EDCA 基地准入谈判',
    date: '2026-06-16T10:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 15.18, lng: 120.55 },
    description: '克拉克/巴拉望等 EDCA 基地设施升级磋商',
    source: 'state',
  },
];

export const US_GARRISON_FACILITIES: Facility[] = [
  {
    id: 'us-gar-fac-andersen',
    name: '安德森空军基地',
    position: { lat: 13.58, lng: 144.93 },
    faction: 'us',
    type: 'airfield',
    forces: ['太平洋空军', '战略轰炸机'],
    troopEstimate: '约 6,000',
    notes: '关岛战略前沿',
  },
  {
    id: 'us-gar-fac-apra',
    name: '阿普拉海军基地',
    position: { lat: 13.44, lng: 144.65 },
    faction: 'us',
    type: 'naval',
    forces: ['太平洋舰队潜艇'],
    notes: '关岛潜艇前沿',
  },
  {
    id: 'us-gar-fac-kadena',
    name: '嘉手纳空军基地',
    position: { lat: 26.35, lng: 127.77 },
    faction: 'us',
    type: 'airfield',
    forces: ['第18联队'],
    troopEstimate: '约 8,000',
    notes: '第一岛链空中枢纽',
  },
  {
    id: 'us-gar-fac-yokosuka',
    name: '横须贺海军基地',
    position: { lat: 35.29, lng: 139.67 },
    faction: 'us',
    type: 'naval',
    forces: ['第七舰队'],
    notes: '航母母港',
  },
  {
    id: 'us-gar-fac-sasebo',
    name: '佐世保海军基地',
    position: { lat: 33.16, lng: 129.72 },
    faction: 'us',
    type: 'naval',
    forces: ['两栖戒备群'],
  },
  {
    id: 'us-gar-fac-futenma',
    name: '普天间航空站',
    position: { lat: 26.27, lng: 127.76 },
    faction: 'us',
    type: 'airfield',
    forces: ['海军陆战队航空'],
  },
  {
    id: 'us-gar-fac-humphreys',
    name: '汉弗莱斯军营',
    position: { lat: 36.97, lng: 127.02 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 28,000',
    forces: ['驻韩美军'],
  },
  {
    id: 'us-gar-fac-ramstein',
    name: '拉姆施泰因空军基地',
    position: { lat: 49.44, lng: 7.6 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国驻欧空军'],
    notes: '欧洲空运枢纽',
  },
  {
    id: 'us-gar-fac-spangdahlem',
    name: '施潘达勒姆空军基地',
    position: { lat: 49.97, lng: 6.69 },
    faction: 'us',
    type: 'airfield',
    forces: ['战斗机联队'],
  },
  {
    id: 'us-gar-fac-diego',
    name: '迪戈加西亚基地',
    position: { lat: -7.31, lng: 72.41 },
    faction: 'us',
    type: 'airfield',
    forces: ['战略轰炸', '海上巡逻'],
    notes: '印度洋关键节点',
  },
  {
    id: 'us-gar-fac-aludeid',
    name: '乌代德空军基地',
    position: { lat: 25.12, lng: 51.32 },
    faction: 'us',
    type: 'airfield',
    forces: ['中央司令部空军'],
  },
  {
    id: 'us-gar-fac-bahrain',
    name: '第五舰队总部',
    position: { lat: 26.23, lng: 50.58 },
    faction: 'us',
    type: 'naval',
    forces: ['第五舰队'],
  },
  {
    id: 'us-gar-fac-rota',
    name: '罗塔海军基地',
    position: { lat: 36.62, lng: -6.35 },
    faction: 'us',
    type: 'naval',
    forces: ['驱逐舰前沿'],
  },
  {
    id: 'us-gar-fac-lemonnier',
    name: '莱蒙尼耶军营',
    position: { lat: 11.55, lng: 43.15 },
    faction: 'us',
    type: 'base',
    forces: ['非洲司令部'],
  },
  {
    id: 'us-gar-fac-vicenza',
    name: '维琴察军营',
    position: { lat: 45.55, lng: 11.55 },
    faction: 'us',
    type: 'base',
    forces: ['南欧陆军'],
  },
  {
    id: 'us-gar-fac-kuwait',
    name: '阿里萨卡姆军营',
    position: { lat: 29.35, lng: 47.92 },
    faction: 'us',
    type: 'base',
    forces: ['陆军前沿'],
  },
  {
    id: 'us-gar-fac-clark',
    name: '克拉克空军基地（EDCA）',
    position: { lat: 15.18, lng: 120.55 },
    faction: 'us',
    type: 'airfield',
    forces: ['轮换部署'],
    notes: '美菲加强防务合作协议',
  },
  {
    id: 'us-gar-fac-subic-bay',
    name: '苏比克湾前沿设施',
    position: { lat: 14.8, lng: 120.28 },
    faction: 'us',
    type: 'naval',
    notes: '菲律宾后勤与预置物资',
  },
  {
    id: 'us-gar-fac-guantanamo',
    name: '关塔那摩湾基地',
    position: { lat: 19.9, lng: -75.16 },
    faction: 'us',
    type: 'naval',
    forces: ['加勒比巡逻'],
  },
];
