import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国本土安全与关键基础设施监测 / seed';

/** 本土安全与关键基础设施 · 事件监测点 */
export const US_HOMELAND_EVENTS: EventDetail[] = [
  {
    id: 'us-hom-pentagon',
    title: '五角大楼 · 国防决策中枢',
    source: SRC,
    timestamp: T,
    location: [-77.06, 38.87],
    impact_level: 'critical',
    category: 'military',
    description: '美国国防部总部，全球军事部署指挥',
  },
  {
    id: 'us-hom-norad',
    title: 'NORAD · 夏延山综合体',
    source: SRC,
    timestamp: '2026-06-16T07:00:00Z',
    location: [-104.87, 38.99],
    impact_level: 'critical',
    category: 'nuclear',
    description: '北美防空司令部地下指挥中心，导弹预警核心',
  },
  {
    id: 'us-hom-peterson',
    title: '彼得森太空军基地',
    source: SRC,
    timestamp: '2026-06-15T16:00:00Z',
    location: [-104.7, 38.82],
    impact_level: 'critical',
    category: 'military',
    description: '美国太空军司令部与 NORAD 联合指挥中心',
  },
  {
    id: 'us-hom-fort-meade',
    title: '米德堡 · NSA/网络司令部',
    source: SRC,
    timestamp: '2026-06-16T09:00:00Z',
    location: [-76.74, 39.11],
    impact_level: 'critical',
    category: 'datacenters',
    description: '国家安全局与 USCYBERCOM 总部，网络战枢纽',
  },
  {
    id: 'us-hom-langley',
    title: '兰利 · 中央情报局总部',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [-76.15, 38.95],
    impact_level: 'high',
    category: 'military',
    description: '情报分析与海外行动协调中枢',
  },
  {
    id: 'us-hom-la-port',
    title: '洛杉矶/长滩港 · 亚太贸易门户',
    source: SRC,
    timestamp: '2026-06-15T12:00:00Z',
    location: [-118.25, 33.75],
    impact_level: 'critical',
    category: 'waterways',
    description: '美国最大集装箱港口，供应链关键节点',
  },
  {
    id: 'us-hom-ny-port',
    title: '纽约/新泽西港',
    source: SRC,
    timestamp: '2026-06-14T18:00:00Z',
    location: [-74.05, 40.67],
    impact_level: 'critical',
    category: 'waterways',
    description: '东海岸最大港口，金融与贸易交汇',
  },
  {
    id: 'us-hom-houston-port',
    title: '休斯顿港 · 能源出口枢纽',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [-95.02, 29.73],
    impact_level: 'critical',
    category: 'economic',
    description: '美国最大石化与 LNG 出口港口',
  },
  {
    id: 'us-hom-savannah-port',
    title: '萨凡纳港 · 东岸集装箱枢纽',
    source: SRC,
    timestamp: '2026-06-14T10:00:00Z',
    location: [-81.09, 32.08],
    impact_level: 'high',
    category: 'waterways',
    description: '东南沿海主要集装箱转运港',
  },
  {
    id: 'us-hom-permian-hub',
    title: '二叠纪盆地 · 页岩油气枢纽',
    source: SRC,
    timestamp: '2026-06-15T20:00:00Z',
    location: [-102.0, 31.5],
    impact_level: 'critical',
    category: 'economic',
    description: '美国油气产量核心，全球能源定价影响',
  },
  {
    id: 'us-hom-spr-bryan',
    title: '布莱恩芒德 SPR 储油库',
    source: SRC,
    timestamp: '2026-06-14T14:00:00Z',
    location: [-96.37, 30.08],
    impact_level: 'high',
    category: 'economic',
    description: '得州战略石油储备地下盐穴储存',
  },
  {
    id: 'us-hom-pjm-grid',
    title: 'PJM 电网 · 东海岸电力枢纽',
    source: SRC,
    timestamp: '2026-06-16T10:00:00Z',
    location: [-77.0, 39.5],
    impact_level: 'high',
    category: 'outages',
    description: '覆盖 13 州与 DC 的最大电网运营商',
  },
  {
    id: 'us-hom-ashburn-dc',
    title: '阿什本 · 全球数据中心之都',
    source: SRC,
    timestamp: '2026-06-16T11:00:00Z',
    location: [-77.49, 39.04],
    impact_level: 'critical',
    category: 'datacenters',
    description: '全球约 70% 互联网流量途经，云计算核心',
  },
  {
    id: 'us-hom-silicon-valley',
    title: '硅谷 · 科技与安全交汇',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [-122.08, 37.39],
    impact_level: 'high',
    category: 'datacenters',
    description: 'AI、芯片与网络安全产业核心',
  },
];

export const US_HOMELAND_INCIDENTS: Incident[] = [
  {
    id: 'us-hom-inc-1',
    title: 'NORAD · 北美防空演习',
    date: '2026-06-16T06:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 38.99, lng: -104.87 },
    description: '美加联合空天防御与导弹预警链路检验',
    source: 'norad',
  },
  {
    id: 'us-hom-inc-2',
    title: '关键基础设施网络威胁预警',
    date: '2026-06-15T22:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 39.11, lng: -76.74 },
    description: 'CISA 发布电网与水务系统漏洞通告',
    source: 'cisa',
  },
  {
    id: 'us-hom-inc-3',
    title: '墨西哥湾炼厂检修潮',
    date: '2026-06-14T16:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 29.73, lng: -95.02 },
    description: '飓风季前炼厂维护性减产，汽油库存下降',
    source: 'eia',
  },
  {
    id: 'us-hom-inc-4',
    title: '东海岸港口劳工谈判',
    date: '2026-06-13T14:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 40.67, lng: -74.05 },
    description: '码头工人合同谈判影响集装箱吞吐',
    source: 'seed',
  },
  {
    id: 'us-hom-inc-5',
    title: '德州电网夏季负荷预警',
    date: '2026-06-16T12:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 30.27, lng: -97.74 },
    description: 'ERCOT 发布极端高温用电高峰预警',
    source: 'ercot',
  },
  {
    id: 'us-hom-inc-6',
    title: 'SPR 释储评估听证',
    date: '2026-06-15T20:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9, lng: -77.04 },
    description: '能源部评估战略石油储备补充与释放策略',
    source: 'doe',
  },
];

export const US_HOMELAND_FACILITIES: Facility[] = [
  {
    id: 'us-hom-fac-pentagon',
    name: '五角大楼',
    position: { lat: 38.87, lng: -77.06 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 25,000',
    notes: '国防部总部',
  },
  {
    id: 'us-hom-fac-cheyenne',
    name: '夏延山 NORAD 中心',
    position: { lat: 38.99, lng: -104.87 },
    faction: 'us',
    type: 'base',
    notes: '地下导弹预警指挥',
  },
  {
    id: 'us-hom-fac-peterson',
    name: '彼得森太空军基地',
    position: { lat: 38.82, lng: -104.7 },
    faction: 'us',
    type: 'base',
    forces: ['太空军司令部', 'NORAD'],
  },
  {
    id: 'us-hom-fac-fort-meade',
    name: '米德堡联合基地',
    position: { lat: 39.11, lng: -76.74 },
    faction: 'us',
    type: 'base',
    forces: ['NSA', 'USCYBERCOM'],
    notes: '网络战与信号情报',
  },
  {
    id: 'us-hom-fac-langley',
    name: '兰利 CIA 总部',
    position: { lat: 38.95, lng: -76.15 },
    faction: 'us',
    type: 'base',
    notes: '情报中枢',
  },
  {
    id: 'us-hom-fac-norfolk',
    name: '诺福克海军基地',
    position: { lat: 36.95, lng: -76.3 },
    faction: 'us',
    type: 'naval',
    troopEstimate: '约 75,000',
    forces: ['大西洋舰队'],
    notes: '全球最大海军基地',
  },
  {
    id: 'us-hom-fac-san-diego',
    name: '圣迭戈海军基地',
    position: { lat: 32.68, lng: -117.12 },
    faction: 'us',
    type: 'naval',
    forces: ['太平洋舰队'],
  },
  {
    id: 'us-hom-fac-jblm',
    name: '刘易斯-麦科德联合基地',
    position: { lat: 47.11, lng: -122.58 },
    faction: 'us',
    type: 'base',
    forces: ['陆军', '空军'],
    notes: '西海岸主要力量投送枢纽',
  },
  {
    id: 'us-hom-fac-fort-bragg',
    name: '自由堡（布拉格堡）',
    position: { lat: 35.14, lng: -79.0 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 50,000',
    forces: ['特种作战司令部'],
  },
  {
    id: 'us-hom-fac-fort-hood',
    name: '卡瓦佐斯堡（胡德堡）',
    position: { lat: 31.13, lng: -97.78 },
    faction: 'us',
    type: 'base',
    forces: ['装甲部队'],
    troopEstimate: '约 36,000',
  },
  {
    id: 'us-hom-fac-camp-pendleton',
    name: '彭德尔顿营',
    position: { lat: 33.22, lng: -117.32 },
    faction: 'us',
    type: 'base',
    forces: ['海军陆战队'],
    notes: '西太部署训练出发地',
  },
  {
    id: 'us-hom-fac-ashburn',
    name: '阿什本数据中心集群',
    position: { lat: 39.04, lng: -77.49 },
    faction: 'us',
    type: 'base',
    notes: 'AWS/Azure/Google 核心节点',
  },
  {
    id: 'us-hom-fac-houston-refinery',
    name: '休斯顿炼化集群',
    position: { lat: 29.73, lng: -95.02 },
    faction: 'us',
    type: 'base',
    notes: '全美最大石化产能',
  },
  {
    id: 'us-hom-fac-spr',
    name: '战略石油储备（得州）',
    position: { lat: 30.08, lng: -96.37 },
    faction: 'us',
    type: 'base',
    notes: '地下盐穴储油约 3.58 亿桶',
  },
];
