import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国印太战略监测 / seed';

/** 印太战略 · 事件监测点 */
export const US_INDO_PACIFIC_EVENTS: EventDetail[] = [
  {
    id: 'us-ipp-first-chain',
    title: '第一岛链 · 前沿态势总览',
    source: SRC,
    timestamp: T,
    location: [127.0, 26.0],
    impact_level: 'critical',
    category: 'military',
    description: '日本列岛—琉球—台湾—菲律宾构成的美军前沿防御线',
  },
  {
    id: 'us-ipp-taiwan-straits',
    title: '台湾海峡 · 航行自由行动',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [119.5, 24.5],
    impact_level: 'critical',
    category: 'maritime',
    description: '美军舰机例行过航，《台湾关系法》安全承诺框架',
  },
  {
    id: 'us-ipp-aukus',
    title: 'AUKUS · 核潜艇与技术共享',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [151.2, -33.87],
    impact_level: 'high',
    category: 'military',
    description: '美英澳三边安全伙伴关系，澳核潜艇与高超音速合作',
  },
  {
    id: 'us-ipp-quad',
    title: '四方安全对话（QUAD）',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [139.75, 35.68],
    impact_level: 'high',
    category: 'diplomatic',
    description: '美日印澳海上安全与供应链韧性合作',
  },
  {
    id: 'us-ipp-edca-clark',
    title: '菲律宾克拉克 · EDCA 基地',
    source: SRC,
    timestamp: '2026-06-16T05:00:00Z',
    location: [120.55, 15.18],
    impact_level: 'high',
    category: 'bases',
    description: '美菲加强防务合作协议前沿设施',
  },
  {
    id: 'us-ipp-edca-palawan',
    title: '巴拉望 · 南海前沿 EDCA',
    source: SRC,
    timestamp: '2026-06-16T04:00:00Z',
    location: [118.7, 9.8],
    impact_level: 'high',
    category: 'bases',
    description: '临近南沙与礼乐滩，南海态势敏感前沿',
  },
  {
    id: 'us-ipp-tra',
    title: '《台湾关系法》 · 对台安全承诺',
    source: SRC,
    timestamp: '2026-06-16T10:00:00Z',
    location: [121.5, 25.05],
    impact_level: 'critical',
    category: 'hotspots',
    description: '美国对台军售与危机响应政策框架监测点',
  },
  {
    id: 'us-ipp-kadena',
    title: '嘉手纳 · 第一岛链空中枢纽',
    source: SRC,
    timestamp: '2026-06-15T12:00:00Z',
    location: [127.77, 26.35],
    impact_level: 'critical',
    category: 'bases',
    description: '冲绳最大空军基地，台海危机快速反应',
  },
  {
    id: 'us-ipp-yokosuka',
    title: '横须贺 · 第七舰队',
    source: SRC,
    timestamp: '2026-06-15T10:00:00Z',
    location: [139.67, 35.29],
    impact_level: 'critical',
    category: 'bases',
    description: '西太平洋航母与水面舰艇核心母港',
  },
  {
    id: 'us-ipp-guam',
    title: '关岛 · 第二岛链支点',
    source: SRC,
    timestamp: '2026-06-14T16:00:00Z',
    location: [144.79, 13.44],
    impact_level: 'critical',
    category: 'bases',
    description: '导弹防御、轰炸机和潜艇前沿部署',
  },
  {
    id: 'us-ipp-darwin',
    title: '达尔文 · 海军陆战队轮换',
    source: SRC,
    timestamp: '2026-06-14T12:00:00Z',
    location: [130.84, -12.46],
    impact_level: 'medium',
    category: 'bases',
    description: '澳北部美军陆战队轮换部署（2500人）',
  },
  {
    id: 'us-ipp-singapore',
    title: '新加坡 · 樟宜海军前沿',
    source: SRC,
    timestamp: '2026-06-13T14:00:00Z',
    location: [104.0, 1.33],
    impact_level: 'high',
    category: 'maritime',
    description: '濒海战斗舰与潜艇后勤补给，马六甲航道安全',
  },
  {
    id: 'us-ipp-scs-patrol',
    title: '南海 · 联合巡逻区',
    source: SRC,
    timestamp: '2026-06-16T08:00:00Z',
    location: [112.0, 15.0],
    impact_level: 'high',
    category: 'maritime',
    description: '美军舰机南海例行存在与盟友联合巡逻',
  },
  {
    id: 'us-ipp-iwakuni',
    title: '岩国海军陆战队航空站',
    source: SRC,
    timestamp: '2026-06-13T10:00:00Z',
    location: [132.22, 34.14],
    impact_level: 'high',
    category: 'bases',
    description: 'F-35B 与海军陆战队战斗机前沿',
  },
];

export const US_INDO_PACIFIC_INCIDENTS: Incident[] = [
  {
    id: 'us-ipp-inc-1',
    title: '台湾海峡 · 美军驱逐舰过航',
    date: '2026-06-16T04:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 24.5, lng: 119.5 },
    description: '阿利·伯克级驱逐舰例行航行自由行动',
    source: 'navy',
  },
  {
    id: 'us-ipp-inc-2',
    title: '冲绳 · 嘉手纳战斗机紧急出动',
    date: '2026-06-15T20:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 26.35, lng: 127.77 },
    description: '应对东海空域异常目标识别（种子/示例）',
    source: 'pacaf',
  },
  {
    id: 'us-ipp-inc-3',
    title: 'AUKUS · 核潜艇技术磋商',
    date: '2026-06-16T10:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: -33.87, lng: 151.2 },
    description: '澳大利亚核潜艇采购路线图进展评估',
    source: 'aukus',
  },
  {
    id: 'us-ipp-inc-4',
    title: '美菲 · 肩并肩联合军演',
    date: '2026-06-14T06:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 15.18, lng: 120.55 },
    description: '克拉克与巴拉望 EDCA 基地联合演训',
    source: 'usindopacom',
  },
  {
    id: 'us-ipp-inc-5',
    title: '对台军售 · 新一批装备交付',
    date: '2026-06-13T16:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 25.05, lng: 121.5 },
    description: '《台湾关系法》框架下防御性武器交付',
    source: 'state',
  },
  {
    id: 'us-ipp-inc-6',
    title: '关岛 · 导弹防御系统升级',
    date: '2026-06-12T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 13.58, lng: 144.93 },
    description: '关岛综合防空反导系统（GCI）部署推进',
    source: 'mda',
  },
  {
    id: 'us-ipp-inc-7',
    title: 'QUAD · 海上监视合作',
    date: '2026-06-16T02:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 5.0, lng: 110.0 },
    description: '四国海上态势感知与非法捕捞追踪',
    source: 'quad',
  },
  {
    id: 'us-ipp-inc-8',
    title: '南海 · 联合巡航',
    date: '2026-06-15T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 12.0, lng: 114.0 },
    description: '美军与菲律宾海军南海联合巡逻',
    source: 'navy',
  },
];

export const US_INDO_PACIFIC_FACILITIES: Facility[] = [
  {
    id: 'us-ipp-fac-kadena',
    name: '嘉手纳空军基地',
    position: { lat: 26.35, lng: 127.77 },
    faction: 'us',
    type: 'airfield',
    forces: ['第18联队'],
    notes: '第一岛链空中核心',
  },
  {
    id: 'us-ipp-fac-yokosuka',
    name: '横须贺海军基地',
    position: { lat: 35.29, lng: 139.67 },
    faction: 'us',
    type: 'naval',
    forces: ['第七舰队'],
  },
  {
    id: 'us-ipp-fac-clark',
    name: '克拉克 EDCA 基地',
    position: { lat: 15.18, lng: 120.55 },
    faction: 'us',
    type: 'airfield',
    notes: '美菲 EDCA',
  },
  {
    id: 'us-ipp-fac-palawan',
    name: '巴拉望 EDCA 设施',
    position: { lat: 9.8, lng: 118.7 },
    faction: 'us',
    type: 'base',
    notes: '南海前沿',
  },
  {
    id: 'us-ipp-fac-guam',
    name: '关岛联合基地',
    position: { lat: 13.44, lng: 144.79 },
    faction: 'us',
    type: 'airfield',
    forces: ['安德森', '阿普拉'],
    notes: '第二岛链支点',
  },
  {
    id: 'us-ipp-fac-iwakuni',
    name: '岩国航空站',
    position: { lat: 34.14, lng: 132.22 },
    faction: 'us',
    type: 'airfield',
    forces: ['海军陆战队航空'],
  },
  {
    id: 'us-ipp-fac-misawa',
    name: '三泽空军基地',
    position: { lat: 40.7, lng: 141.37 },
    faction: 'us',
    type: 'airfield',
    forces: ['F-16', '电子战'],
    notes: '日本北部前沿',
  },
  {
    id: 'us-ipp-fac-darwin',
    name: '达尔文轮换基地',
    position: { lat: -12.46, lng: 130.84 },
    faction: 'us',
    type: 'base',
    forces: ['海军陆战队'],
    troopEstimate: '约 2,500',
  },
  {
    id: 'us-ipp-fac-changi',
    name: '樟宜海军前沿',
    position: { lat: 1.33, lng: 104.0 },
    faction: 'us',
    type: 'naval',
    notes: '濒海战斗舰后勤',
  },
  {
    id: 'us-ipp-fac-pearl',
    name: '珍珠港海军基地',
    position: { lat: 21.35, lng: -157.95 },
    faction: 'us',
    type: 'naval',
    forces: ['太平洋舰队'],
    notes: '印太后勤枢纽',
  },
  {
    id: 'us-ipp-fac-san-diego',
    name: '圣迭戈海军基地',
    position: { lat: 32.68, lng: -117.12 },
    faction: 'us',
    type: 'naval',
    forces: ['太平洋舰队'],
    notes: '西太力量投送出发港',
  },
  {
    id: 'us-ipp-fac-camp-pendleton',
    name: '彭德尔顿营',
    position: { lat: 33.22, lng: -117.32 },
    faction: 'us',
    type: 'base',
    forces: ['海军陆战队'],
    notes: '西太部署训练',
  },
  {
    id: 'us-ipp-fac-australia-pine-gap',
    name: '松树谷联合设施',
    position: { lat: -23.8, lng: 133.74 },
    faction: 'us',
    type: 'base',
    notes: '美澳信号情报与导弹预警',
  },
  {
    id: 'us-ipp-fac-okinawa-camp',
    name: '冲绳陆战队营地',
    position: { lat: 26.5, lng: 127.85 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 18,000',
    forces: ['海军陆战队'],
  },
];
