import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国战略核力量监测';

/** 战略核力量 · 事件监测点 */
export const US_NUCLEAR_EVENTS: EventDetail[] = [
  {
    id: 'us-nuc-warren',
    title: 'F·E·沃伦基地 · 民兵 III 发射井群',
    source: SRC,
    timestamp: T,
    location: [-104.87, 41.14],
    impact_level: 'critical',
    category: 'nuclear',
    description: '怀俄明州，美国战略司令部陆基核威慑核心，约 150 枚民兵 III',
  },
  {
    id: 'us-nuc-malmstrom',
    title: '马姆斯特罗姆基地 · 发射井群',
    source: SRC,
    timestamp: '2026-06-15T12:00:00Z',
    location: [-111.18, 47.51],
    impact_level: 'critical',
    category: 'nuclear',
    description: '蒙大拿州，北美防空与战略导弹枢纽',
  },
  {
    id: 'us-nuc-minot',
    title: '迈诺特基地 · 陆基核与空基核',
    source: SRC,
    timestamp: '2026-06-15T10:00:00Z',
    location: [-101.35, 48.42],
    impact_level: 'critical',
    category: 'nuclear',
    description: '北达科他州，民兵 III 发射井与 B-52H 战略轰炸机共驻',
  },
  {
    id: 'us-nuc-kings-bay',
    title: '金斯湾 · 大西洋 SSBN 母港',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [-81.52, 30.8],
    impact_level: 'critical',
    category: 'nuclear',
    description: '佐治亚州，俄亥俄级战略核潜艇大西洋舰队母港',
  },
  {
    id: 'us-nuc-bangor',
    title: '班戈海军基地 · 太平洋 SSBN',
    source: SRC,
    timestamp: '2026-06-16T05:30:00Z',
    location: [-122.71, 47.73],
    impact_level: 'critical',
    category: 'nuclear',
    description: '华盛顿州，太平洋战略核潜艇与三叉戟 II D5 弹头',
  },
  {
    id: 'us-nuc-whiteman',
    title: '怀特曼基地 · B-2 战略轰炸',
    source: SRC,
    timestamp: '2026-06-14T14:00:00Z',
    location: [-93.55, 38.73],
    impact_level: 'critical',
    category: 'nuclear',
    description: '密苏里州，全球唯一 B-2 隐身战略轰炸机驻地',
  },
  {
    id: 'us-nuc-barksdale',
    title: '巴克斯代尔基地 · B-52 战略轰炸',
    source: SRC,
    timestamp: '2026-06-14T12:00:00Z',
    location: [-93.66, 32.5],
    impact_level: 'critical',
    category: 'nuclear',
    description: '路易斯安那州，全球打击司令部 B-52H 核心基地',
  },
  {
    id: 'us-nuc-dyess',
    title: '戴斯基地 · B-1B 常规/核常兼备',
    source: SRC,
    timestamp: '2026-06-13T16:00:00Z',
    location: [-99.85, 32.42],
    impact_level: 'high',
    category: 'nuclear',
    description: '得克萨斯州，全球打击司令部前沿轰炸机',
  },
  {
    id: 'us-nuc-ellsworth',
    title: '埃尔斯沃思基地 · B-1B 轰炸机',
    source: SRC,
    timestamp: '2026-06-13T14:00:00Z',
    location: [-103.1, 44.15],
    impact_level: 'high',
    category: 'nuclear',
    description: '南达科他州，全球打击司令部轰炸机联队',
  },
  {
    id: 'us-nuc-los-alamos',
    title: '洛斯阿拉莫斯国家实验室',
    source: SRC,
    timestamp: '2026-06-16T09:00:00Z',
    location: [-106.3, 35.88],
    impact_level: 'critical',
    category: 'nuclear',
    description: 'NNSA 核武器设计与科研核心，曼哈顿计划遗产',
  },
  {
    id: 'us-nuc-livermore',
    title: '劳伦斯利弗莫尔国家实验室',
    source: SRC,
    timestamp: '2026-06-16T08:30:00Z',
    location: [-121.7, 37.69],
    impact_level: 'critical',
    category: 'nuclear',
    description: 'NNSA 核武器模拟与惯性约束聚变研究',
  },
  {
    id: 'us-nuc-sandia',
    title: '桑迪亚国家实验室',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [-106.6, 35.05],
    impact_level: 'high',
    category: 'nuclear',
    description: '核弹头工程化与非核部件研发',
  },
  {
    id: 'us-nuc-pantex',
    title: '潘特克斯组装拆解厂',
    source: SRC,
    timestamp: '2026-06-15T16:00:00Z',
    location: [-101.94, 35.31],
    impact_level: 'critical',
    category: 'nuclear',
    description: '得克萨斯州，美国唯一核弹头总装与拆解设施',
  },
  {
    id: 'us-nuc-y12',
    title: 'Y-12 国家安全综合体',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [-84.25, 36.0],
    impact_level: 'critical',
    category: 'nuclear',
    description: '田纳西州，高浓缩铀储存与加工',
  },
  {
    id: 'us-nuc-hanford',
    title: '汉福德场址 · 钚生产遗产',
    source: SRC,
    timestamp: '2026-06-14T10:00:00Z',
    location: [-119.27, 46.57],
    impact_level: 'high',
    category: 'nuclear',
    description: '华盛顿州，冷战钚生产场址，环境修复进行中',
  },
];

export const US_NUCLEAR_INCIDENTS: Incident[] = [
  {
    id: 'us-nuc-inc-1',
    title: '战略司令部 · 民兵 III 戒备演习',
    date: '2026-06-16T07:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 41.14, lng: -104.87 },
    description: 'F·E·沃伦基地举行战备值班与通信链路检验',
    source: 'stratcom',
  },
  {
    id: 'us-nuc-inc-2',
    title: '俄亥俄级 SSBN 西太平洋巡逻',
    date: '2026-06-15T20:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 20.0, lng: 140.0 },
    description: '太平洋舰队战略核潜艇例行威慑巡逻（公开态势）',
    source: 'navy',
  },
  {
    id: 'us-nuc-inc-3',
    title: 'B-52 全球雷霆演习出动',
    date: '2026-06-14T18:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 32.5, lng: -93.66 },
    description: '巴克斯代尔 B-52H 跨洋战略巡航演训',
    source: 'afgsc',
  },
  {
    id: 'us-nuc-inc-4',
    title: 'NNSA · 弹头可靠性评估',
    date: '2026-06-16T10:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 35.88, lng: -106.3 },
    description: '洛斯阿拉莫斯实验室年度库存管理计划评审',
    source: 'nnsa',
  },
  {
    id: 'us-nuc-inc-5',
    title: '民兵 III 发射井现代化招标',
    date: '2026-06-13T12:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 47.51, lng: -111.18 },
    description: '哨兵 ICBM 替换计划与发射井基础设施升级',
    source: 'dod',
  },
  {
    id: 'us-nuc-inc-6',
    title: '三叉戟 II D5 试射（太平洋）',
    date: '2026-06-12T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 25.0, lng: -160.0 },
    description: '未武装弹头飞行试验，验证海基核威慑可靠性',
    source: 'navy',
  },
  {
    id: 'us-nuc-inc-7',
    title: 'B-21 突袭者低速率初始生产',
    date: '2026-06-16T11:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 34.9, lng: -117.88 },
    description: '爱德华兹基地试飞与棕榈谷生产线进度监测',
    source: 'afgsc',
  },
  {
    id: 'us-nuc-inc-8',
    title: '核安全管理局预算听证',
    date: '2026-06-15T22:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9, lng: -77.04 },
    description: '国会审议 NNSA 现代化与场址环境修复拨款',
    source: 'congress',
  },
];

export const US_NUCLEAR_FACILITIES: Facility[] = [
  {
    id: 'us-nuc-fac-warren',
    name: 'F·E·沃伦 · 民兵 III 井群',
    position: { lat: 41.14, lng: -104.87 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM'],
    notes: '怀俄明州战略导弹联队',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-malmstrom',
    name: '马姆斯特罗姆 · 发射井群',
    position: { lat: 47.51, lng: -111.18 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-minot-silo',
    name: '迈诺特 · 发射井群',
    position: { lat: 48.42, lng: -101.35 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-kings-bay',
    name: '金斯湾 SSBN 基地',
    position: { lat: 30.8, lng: -81.52 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['俄亥俄级 SSBN', '三叉戟 II D5'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-bangor',
    name: '班戈 SSBN 基地',
    position: { lat: 47.73, lng: -122.71 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['俄亥俄级 SSBN'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-whiteman',
    name: '怀特曼 · B-2 基地',
    position: { lat: 38.73, lng: -93.55 },
    faction: 'us',
    type: 'airfield',
    nuclearKind: 'icbm_base',
    status: '战备',
    weapons: ['B-2A 幽灵'],
    forces: ['全球打击司令部'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-barksdale',
    name: '巴克斯代尔 · B-52 基地',
    position: { lat: 32.5, lng: -93.66 },
    faction: 'us',
    type: 'airfield',
    nuclearKind: 'icbm_base',
    status: '战备',
    weapons: ['B-52H'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-dyess',
    name: '戴斯 · B-1B 基地',
    position: { lat: 32.42, lng: -99.85 },
    faction: 'us',
    type: 'airfield',
    nuclearKind: 'icbm_base',
    status: '战备',
    weapons: ['B-1B'],
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-los-alamos',
    name: '洛斯阿拉莫斯实验室',
    position: { lat: 35.88, lng: -106.3 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'research_reactor',
    status: '运行中',
    notes: 'NNSA 核武器设计',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-livermore',
    name: '利弗莫尔实验室',
    position: { lat: 37.69, lng: -121.7 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'research_reactor',
    status: '运行中',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-pantex',
    name: '潘特克斯组装厂',
    position: { lat: 35.31, lng: -101.94 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'warhead_storage',
    status: '运行中',
    notes: '唯一核弹头总装设施',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-y12',
    name: 'Y-12 铀加工综合体',
    position: { lat: 36.0, lng: -84.25 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'enrichment',
    status: '运行中',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-savannah',
    name: '萨凡纳河场址',
    position: { lat: 33.35, lng: -81.73 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'reprocessing',
    status: '运行中',
    notes: '氚与钚组分生产',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-nellis',
    name: '内利斯基地 · 核作战训练',
    position: { lat: 36.24, lng: -115.03 },
    faction: 'us',
    type: 'airfield',
    nuclearKind: 'icbm_base',
    status: '训练',
    notes: '红旗演习与核作战科目',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-offutt',
    name: '奥夫特基地 · 战略司令部',
    position: { lat: 41.12, lng: -95.91 },
    faction: 'us',
    type: 'base',
    status: '战备',
    notes: 'USSTRATCOM 总部',
    updatedAt: T,
  },
  {
    id: 'us-nuc-fac-norfolk-subs',
    name: '诺福克 · 攻击核潜艇',
    position: { lat: 36.95, lng: -76.3 },
    faction: 'us',
    type: 'naval',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['弗吉尼亚级 SSN'],
    notes: '大西洋攻击核潜艇枢纽',
    updatedAt: T,
  },
];
