import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国大西洋/北约枢纽监测 / seed';

/** 大西洋/北约枢纽 · 事件监测点 */
export const US_NATO_EVENTS: EventDetail[] = [
  {
    id: 'us-nato-shape',
    title: '北约盟军最高司令部（SHAPE）',
    source: SRC,
    timestamp: T,
    location: [4.0, 50.5],
    impact_level: 'critical',
    category: 'military',
    description: '比利时蒙斯，北约军事行动指挥中枢',
  },
  {
    id: 'us-nato-stuttgart',
    title: '斯图加特 · 美国欧洲司令部',
    source: SRC,
    timestamp: '2026-06-16T07:00:00Z',
    location: [9.18, 48.78],
    impact_level: 'critical',
    category: 'military',
    description: 'EUCOM/AFRICOM 总部，欧洲与非洲军事行动指挥',
  },
  {
    id: 'us-nato-ramstein',
    title: '拉姆施泰因 · 欧洲空运枢纽',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [7.6, 49.44],
    impact_level: 'critical',
    category: 'bases',
    description: '美军欧洲最大空军基地，跨大西洋力量投送',
  },
  {
    id: 'us-nato-aviano',
    title: '阿维亚诺空军基地',
    source: SRC,
    timestamp: '2026-06-15T16:00:00Z',
    location: [12.6, 46.03],
    impact_level: 'high',
    category: 'bases',
    description: '意大利北部，地中海与东欧作战前沿',
  },
  {
    id: 'us-nato-lakenheath',
    title: '莱肯希思空军基地',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [0.56, 52.41],
    impact_level: 'high',
    category: 'bases',
    description: '英国，F-35A 与 F-15E 前沿部署',
  },
  {
    id: 'us-nato-rota',
    title: '罗塔海军基地',
    source: SRC,
    timestamp: '2026-06-14T12:00:00Z',
    location: [-6.35, 36.62],
    impact_level: 'high',
    category: 'bases',
    description: '西班牙，地中海驱逐舰前沿母港',
  },
  {
    id: 'us-nato-poland',
    title: '波兰 · 前沿驻军',
    source: SRC,
    timestamp: '2026-06-16T05:00:00Z',
    location: [21.0, 52.2],
    impact_level: 'high',
    category: 'bases',
    description: '北约东翼前沿旅轮驻，威慑俄罗斯',
  },
  {
    id: 'us-nato-romania',
    title: '罗马尼亚 · 黑海前沿',
    source: SRC,
    timestamp: '2026-06-15T10:00:00Z',
    location: [28.6, 44.57],
    impact_level: 'high',
    category: 'bases',
    description: '黑海沿岸空军与导弹防御部署',
  },
  {
    id: 'us-nato-iceland',
    title: '冰岛 · 北大西洋巡逻',
    source: SRC,
    timestamp: '2026-06-14T08:00:00Z',
    location: [-22.6, 63.98],
    impact_level: 'medium',
    category: 'bases',
    description: '凯夫拉维克前沿设施，GIUK 缺口监视',
  },
  {
    id: 'us-nato-naples',
    title: '那不勒斯 · 美海军欧洲司令部',
    source: SRC,
    timestamp: '2026-06-13T14:00:00Z',
    location: [14.25, 40.83],
    impact_level: 'high',
    category: 'military',
    description: '第六舰队与北约南翼海上力量指挥',
  },
];

export const US_NATO_INCIDENTS: Incident[] = [
  {
    id: 'us-nato-inc-1',
    title: '北约 · 东欧前沿部署强化',
    date: '2026-06-16T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 52.2, lng: 21.0 },
    description: '波兰前沿旅装备预置与轮驻兵力增加',
    source: 'nato',
  },
  {
    id: 'us-nato-inc-2',
    title: '拉姆施泰因 · 乌克兰援助协调',
    date: '2026-06-15T18:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 49.44, lng: 7.6 },
    description: '乌克兰防务联络组会议与物资转运',
    source: 'euccom',
  },
  {
    id: 'us-nato-inc-3',
    title: '波罗的海 · 联合海上演习',
    date: '2026-06-14T10:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 57.0, lng: 20.0 },
    description: '北约波罗的海行动（BALTOPS）演训',
    source: 'navy',
  },
  {
    id: 'us-nato-inc-4',
    title: 'F-35 前沿部署轮换',
    date: '2026-06-13T12:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 52.41, lng: 0.56 },
    description: '莱肯希思 F-35A 中队东欧前沿部署',
    source: 'usafe',
  },
  {
    id: 'us-nato-inc-5',
    title: '北约峰会 · 防务开支目标',
    date: '2026-06-16T12:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 50.5, lng: 4.0 },
    description: '成员国 2% GDP 防务开支目标评估',
    source: 'nato',
  },
  {
    id: 'us-nato-inc-6',
    title: '黑海 · 联合巡逻',
    date: '2026-06-12T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 44.0, lng: 30.0 },
    description: '美军与罗马尼亚海军黑海存在',
    source: 'navy',
  },
];

export const US_NATO_FACILITIES: Facility[] = [
  {
    id: 'us-nato-fac-ramstein',
    name: '拉姆施泰因空军基地',
    position: { lat: 49.44, lng: 7.6 },
    faction: 'nato',
    type: 'airfield',
    forces: ['美国驻欧空军'],
    notes: '欧洲空运枢纽',
  },
  {
    id: 'us-nato-fac-stuttgart',
    name: '斯图加特联合基地',
    position: { lat: 48.78, lng: 9.18 },
    faction: 'us',
    type: 'base',
    forces: ['EUCOM', 'AFRICOM'],
  },
  {
    id: 'us-nato-fac-aviano',
    name: '阿维亚诺空军基地',
    position: { lat: 46.03, lng: 12.6 },
    faction: 'nato',
    type: 'airfield',
    forces: ['第31战斗机联队'],
  },
  {
    id: 'us-nato-fac-lakenheath',
    name: '莱肯希思空军基地',
    position: { lat: 52.41, lng: 0.56 },
    faction: 'nato',
    type: 'airfield',
    forces: ['F-35A', 'F-15E'],
  },
  {
    id: 'us-nato-fac-mildenhall',
    name: '米尔登霍尔空军基地',
    position: { lat: 52.37, lng: 0.49 },
    faction: 'nato',
    type: 'airfield',
    forces: ['特种作战', '加油机'],
  },
  {
    id: 'us-nato-fac-rota',
    name: '罗塔海军基地',
    position: { lat: 36.62, lng: -6.35 },
    faction: 'nato',
    type: 'naval',
    forces: ['驱逐舰前沿'],
  },
  {
    id: 'us-nato-fac-naples',
    name: '那不勒斯海军支援中心',
    position: { lat: 40.83, lng: 14.25 },
    faction: 'us',
    type: 'naval',
    forces: ['第六舰队'],
  },
  {
    id: 'us-nato-fac-poland-poznan',
    name: '波兹南前沿基地',
    position: { lat: 52.4, lng: 16.9 },
    faction: 'nato',
    type: 'base',
    forces: ['陆军前沿'],
    notes: '北约东翼',
  },
  {
    id: 'us-nato-fac-poland-zagan',
    name: '扎甘前沿驻军',
    position: { lat: 51.62, lng: 15.32 },
    faction: 'nato',
    type: 'base',
    troopEstimate: '约 4,000',
    forces: ['装甲旅战斗队'],
  },
  {
    id: 'us-nato-fac-romania',
    name: '罗马尼亚空军基地',
    position: { lat: 44.57, lng: 28.6 },
    faction: 'nato',
    type: 'airfield',
    forces: ['战斗机前沿'],
  },
  {
    id: 'us-nato-fac-keflavik',
    name: '凯夫拉维克前沿设施',
    position: { lat: 63.98, lng: -22.6 },
    faction: 'nato',
    type: 'airfield',
    notes: '北大西洋巡逻',
  },
  {
    id: 'us-nato-fac-vicenza',
    name: '维琴察军营',
    position: { lat: 45.55, lng: 11.55 },
    faction: 'nato',
    type: 'base',
    forces: ['南欧陆军'],
  },
];
