import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const T = '2026-06-16T08:00:00Z';
const SRC = '美国战略资源与供应链监测 / seed';

/** 战略资源与供应链 · 事件监测点 */
export const US_SUPPLY_CHAIN_EVENTS: EventDetail[] = [
  {
    id: 'us-sup-tsmc-az',
    title: '台积电亚利桑那 · 晶圆厂',
    source: SRC,
    timestamp: T,
    location: [-111.93, 33.31],
    impact_level: 'critical',
    category: 'semiconductors',
    description: 'CHIPS 法案旗舰项目，先进制程回流美国',
  },
  {
    id: 'us-sup-intel-ohio',
    title: '英特尔俄亥俄 · 超级晶圆厂',
    source: SRC,
    timestamp: '2026-06-16T07:00:00Z',
    location: [-82.99, 40.12],
    impact_level: 'critical',
    category: 'semiconductors',
    description: '英特尔 200 亿美元投资，美国本土先进制程',
  },
  {
    id: 'us-sup-intel-az',
    title: '英特尔钱德勒 · Ocotillo 园区',
    source: SRC,
    timestamp: '2026-06-15T16:00:00Z',
    location: [-111.88, 33.28],
    impact_level: 'high',
    category: 'semiconductors',
    description: '英特尔最大制造基地，先进封装与研发',
  },
  {
    id: 'us-sup-samsung-tx',
    title: '三星泰勒 · 得州晶圆厂',
    source: SRC,
    timestamp: '2026-06-15T14:00:00Z',
    location: [-96.95, 30.57],
    impact_level: 'high',
    category: 'semiconductors',
    description: '三星 170 亿美元投资，4nm 及以下制程',
  },
  {
    id: 'us-sup-micron-id',
    title: '美光爱达荷 · 存储芯片',
    source: SRC,
    timestamp: '2026-06-14T12:00:00Z',
    location: [-116.21, 43.62],
    impact_level: 'high',
    category: 'semiconductors',
    description: '美光总部与 DRAM/NAND 制造',
  },
  {
    id: 'us-sup-rare-earth',
    title: '芒廷帕斯 · 稀土矿山',
    source: SRC,
    timestamp: '2026-06-16T06:00:00Z',
    location: [-115.53, 35.47],
    impact_level: 'critical',
    category: 'minerals',
    description: '美国唯一在产稀土矿，对华依赖缓解关键',
  },
  {
    id: 'us-sup-lng-cameron',
    title: '卡梅伦 LNG · 出口终端',
    source: SRC,
    timestamp: '2026-06-15T18:00:00Z',
    location: [-93.35, 29.78],
    impact_level: 'high',
    category: 'economic',
    description: '路易斯安那州，全球最大 LNG 出口设施之一',
  },
  {
    id: 'us-sup-lng-sabine',
    title: '萨宾帕斯 LNG · 出口枢纽',
    source: SRC,
    timestamp: '2026-06-15T16:00:00Z',
    location: [-93.87, 29.73],
    impact_level: 'high',
    category: 'economic',
    description: '切尼尔能源旗舰出口终端，欧洲能源安全',
  },
  {
    id: 'us-sup-lng-freeport',
    title: '自由港 LNG · 得州出口',
    source: SRC,
    timestamp: '2026-06-14T14:00:00Z',
    location: [-95.3, 28.95],
    impact_level: 'high',
    category: 'economic',
    description: '墨西哥湾 LNG 出口，亚太与欧洲分流',
  },
  {
    id: 'us-sup-lng-cove',
    title: '科珀斯克里斯蒂 LNG',
    source: SRC,
    timestamp: '2026-06-13T12:00:00Z',
    location: [-97.35, 27.8],
    impact_level: 'medium',
    category: 'economic',
    description: '得州南部 LNG 出口扩建',
  },
  {
    id: 'us-sup-chips-act',
    title: 'CHIPS 法案 · 补贴发放监测',
    source: SRC,
    timestamp: '2026-06-16T10:00:00Z',
    location: [-77.04, 38.9],
    impact_level: 'high',
    category: 'economic',
    description: '商务部半导体制造补贴与护栏条款执行',
  },
  {
    id: 'us-sup-critical-minerals',
    title: '关键矿产战略储备评估',
    source: SRC,
    timestamp: '2026-06-15T20:00:00Z',
    location: [-77.04, 38.9],
    impact_level: 'high',
    category: 'minerals',
    description: '锂、钴、镍、石墨供应链多元化',
  },
];

export const US_SUPPLY_CHAIN_INCIDENTS: Incident[] = [
  {
    id: 'us-sup-inc-1',
    title: '台积电亚利桑那 · 投产进度评估',
    date: '2026-06-16T08:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 33.31, lng: -111.93 },
    description: '4nm 产线试产与良率监测',
    source: 'commerce',
  },
  {
    id: 'us-sup-inc-2',
    title: '稀土进口多元化协议',
    date: '2026-06-15T14:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 35.47, lng: -115.53 },
    description: '与澳大利亚、加拿大稀土加工合作',
    source: 'doe',
  },
  {
    id: 'us-sup-inc-3',
    title: 'LNG 出口创纪录',
    date: '2026-06-14T18:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 29.78, lng: -93.35 },
    description: '墨西哥湾 LNG 出口量创历史新高',
    source: 'eia',
  },
  {
    id: 'us-sup-inc-4',
    title: '芯片出口管制清单更新',
    date: '2026-06-13T16:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9, lng: -77.04 },
    description: 'AI 芯片与半导体制造设备管制收紧',
    source: 'bis',
  },
  {
    id: 'us-sup-inc-5',
    title: '英特尔俄亥俄 · 建设里程碑',
    date: '2026-06-12T12:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 40.12, lng: -82.99 },
    description: '晶圆厂主体结构封顶，2026 设备搬入',
    source: 'intel',
  },
];

export const US_SUPPLY_CHAIN_FACILITIES: Facility[] = [
  {
    id: 'us-sup-fac-tsmc-az',
    name: '台积电亚利桑那晶圆厂',
    position: { lat: 33.31, lng: -111.93 },
    faction: 'us',
    type: 'base',
    notes: '4nm/3nm 先进制程',
  },
  {
    id: 'us-sup-fac-intel-ohio',
    name: '英特尔俄亥俄晶圆厂',
    position: { lat: 40.12, lng: -82.99 },
    faction: 'us',
    type: 'base',
    notes: 'Intel 18A 制程',
  },
  {
    id: 'us-sup-fac-intel-chandler',
    name: '英特尔钱德勒园区',
    position: { lat: 33.28, lng: -111.88 },
    faction: 'us',
    type: 'base',
    notes: '最大制造基地',
  },
  {
    id: 'us-sup-fac-samsung-taylor',
    name: '三星泰勒晶圆厂',
    position: { lat: 30.57, lng: -96.95 },
    faction: 'us',
    type: 'base',
    notes: '4nm 制程',
  },
  {
    id: 'us-sup-fac-micron',
    name: '美光博伊西总部',
    position: { lat: 43.62, lng: -116.21 },
    faction: 'us',
    type: 'base',
    notes: 'DRAM/NAND',
  },
  {
    id: 'us-sup-fac-mountain-pass',
    name: '芒廷帕斯稀土矿',
    position: { lat: 35.47, lng: -115.53 },
    faction: 'us',
    type: 'base',
    notes: '美国唯一在产稀土矿',
  },
  {
    id: 'us-sup-fac-lng-cameron',
    name: '卡梅伦 LNG 终端',
    position: { lat: 29.78, lng: -93.35 },
    faction: 'us',
    type: 'base',
    notes: '年产能约 1500 万吨',
  },
  {
    id: 'us-sup-fac-lng-sabine',
    name: '萨宾帕斯 LNG',
    position: { lat: 29.73, lng: -93.87 },
    faction: 'us',
    type: 'base',
    notes: '切尼尔旗舰终端',
  },
  {
    id: 'us-sup-fac-lng-freeport',
    name: '自由港 LNG',
    position: { lat: 28.95, lng: -95.3 },
    faction: 'us',
    type: 'base',
  },
  {
    id: 'us-sup-fac-globalfoundries',
    name: '格芯纽约晶圆厂',
    position: { lat: 42.9, lng: -73.75 },
    faction: 'us',
    type: 'base',
    notes: '成熟制程与国防芯片',
  },
];
