/**
 * 美国地表层信息 · 政治/经济/交通/自然灾害/科技走廊
 * 前缀 us-surf- · 时间戳 2026-06-10 至 06-16
 */
import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

const SRC = '美国地表层态势监测 / seed';
const T16 = '2026-06-16T10:00:00Z';
const T15 = '2026-06-15T14:00:00Z';
const T14 = '2026-06-14T08:00:00Z';
const T13 = '2026-06-13T16:00:00Z';
const T12 = '2026-06-12T06:00:00Z';
const T11 = '2026-06-11T12:00:00Z';
const T10 = '2026-06-10T18:00:00Z';

const STATE_CAPITALS: { abbr: string; name: string; lng: number; lat: number }[] = [
  { abbr: 'al', name: '蒙哥马利', lng: -86.3, lat: 32.37 },
  { abbr: 'ak', name: '朱诺', lng: -134.42, lat: 58.3 },
  { abbr: 'az', name: '凤凰城', lng: -112.07, lat: 33.45 },
  { abbr: 'ar', name: '小石城', lng: -92.29, lat: 34.75 },
  { abbr: 'ca', name: '萨克拉门托', lng: -121.49, lat: 38.58 },
  { abbr: 'co', name: '丹佛', lng: -104.99, lat: 39.74 },
  { abbr: 'ct', name: '哈特福德', lng: -72.68, lat: 41.76 },
  { abbr: 'de', name: '多佛', lng: -75.52, lat: 39.16 },
  { abbr: 'fl', name: '塔拉哈西', lng: -84.28, lat: 30.44 },
  { abbr: 'ga', name: '亚特兰大', lng: -84.39, lat: 33.75 },
  { abbr: 'hi', name: '火奴鲁鲁', lng: -157.86, lat: 21.31 },
  { abbr: 'id', name: '博伊西', lng: -116.2, lat: 43.62 },
  { abbr: 'il', name: '斯普林菲尔德', lng: -89.65, lat: 39.8 },
  { abbr: 'in', name: '印第安纳波利斯', lng: -86.16, lat: 39.77 },
  { abbr: 'ia', name: '得梅因', lng: -93.61, lat: 41.59 },
  { abbr: 'ks', name: '托皮卡', lng: -95.68, lat: 39.05 },
  { abbr: 'ky', name: '法兰克福', lng: -84.87, lat: 38.2 },
  { abbr: 'la', name: '巴吞鲁日', lng: -91.19, lat: 30.46 },
  { abbr: 'me', name: '奥古斯塔', lng: -69.78, lat: 44.31 },
  { abbr: 'md', name: '安纳波利斯', lng: -76.49, lat: 38.98 },
  { abbr: 'ma', name: '波士顿', lng: -71.06, lat: 42.36 },
  { abbr: 'mi', name: '兰辛', lng: -84.56, lat: 42.73 },
  { abbr: 'mn', name: '圣保罗', lng: -93.1, lat: 44.95 },
  { abbr: 'ms', name: '杰克逊', lng: -90.18, lat: 32.3 },
  { abbr: 'mo', name: '杰斐逊城', lng: -92.17, lat: 38.58 },
  { abbr: 'mt', name: '海伦娜', lng: -112.04, lat: 46.59 },
  { abbr: 'ne', name: '林肯', lng: -96.68, lat: 40.81 },
  { abbr: 'nv', name: '卡森城', lng: -119.77, lat: 39.16 },
  { abbr: 'nh', name: '康科德', lng: -71.54, lat: 43.21 },
  { abbr: 'nj', name: '特伦顿', lng: -74.77, lat: 40.22 },
  { abbr: 'nm', name: '圣菲', lng: -105.94, lat: 35.69 },
  { abbr: 'ny', name: '奥尔巴尼', lng: -73.76, lat: 42.65 },
  { abbr: 'nc', name: '罗利', lng: -78.64, lat: 35.78 },
  { abbr: 'nd', name: '俾斯麦', lng: -100.78, lat: 46.81 },
  { abbr: 'oh', name: '哥伦布', lng: -82.99, lat: 39.96 },
  { abbr: 'ok', name: '俄克拉荷马城', lng: -97.52, lat: 35.47 },
  { abbr: 'or', name: '塞勒姆', lng: -123.03, lat: 44.94 },
  { abbr: 'pa', name: '哈里斯堡', lng: -76.88, lat: 40.27 },
  { abbr: 'ri', name: '普罗维登斯', lng: -71.41, lat: 41.82 },
  { abbr: 'sc', name: '哥伦比亚', lng: -81.03, lat: 34.0 },
  { abbr: 'sd', name: '皮尔', lng: -100.35, lat: 44.37 },
  { abbr: 'tn', name: '纳什维尔', lng: -86.78, lat: 36.17 },
  { abbr: 'tx', name: '奥斯汀', lng: -97.74, lat: 30.27 },
  { abbr: 'ut', name: '盐湖城', lng: -111.89, lat: 40.76 },
  { abbr: 'vt', name: '蒙彼利埃', lng: -72.58, lat: 44.26 },
  { abbr: 'va', name: '里士满', lng: -77.44, lat: 37.54 },
  { abbr: 'wa', name: '奥林匹亚', lng: -122.9, lat: 47.04 },
  { abbr: 'wv', name: '查尔斯顿', lng: -81.63, lat: 38.35 },
  { abbr: 'wi', name: '麦迪逊', lng: -89.38, lat: 43.07 },
  { abbr: 'wy', name: '夏延', lng: -104.82, lat: 41.14 },
];

const CAPITAL_TIMESTAMPS = [T10, T11, T12, T13, T14, T15, T16];

/** 联邦中枢与州府政治节点 */
export const US_SURFACE_FEDERAL_EVENTS: EventDetail[] = [
  {
    id: 'us-surf-dc-white-house',
    title: '华盛顿 · 白宫行政中枢',
    source: SRC,
    timestamp: T16,
    location: [-77.04, 38.9],
    impact_level: 'critical',
    category: 'hotspots',
    description: '总统行政令、国家安全决策与外交议程发布节点',
  },
  {
    id: 'us-surf-dc-capitol',
    title: '华盛顿 · 国会山立法',
    source: SRC,
    timestamp: T15,
    location: [-77.01, 38.89],
    impact_level: 'critical',
    category: 'hotspots',
    description: '众议院与参议院审议国防授权、预算与贸易法案',
  },
  {
    id: 'us-surf-dc-scotus',
    title: '华盛顿 · 最高法院',
    source: SRC,
    timestamp: T14,
    location: [-77.0, 38.89],
    impact_level: 'high',
    category: 'hotspots',
    description: '重大宪法与监管判例裁决窗口（种子/示例）',
  },
  {
    id: 'us-surf-dc-treasury',
    title: '华盛顿 · 财政部',
    source: SRC,
    timestamp: T16,
    location: [-77.03, 38.9],
    impact_level: 'high',
    category: 'economic',
    description: '国债发行、制裁执行与金融稳定政策',
  },
  {
    id: 'us-surf-dc-state',
    title: '华盛顿 · 国务院',
    source: SRC,
    timestamp: T15,
    location: [-77.05, 38.98],
    impact_level: 'high',
    category: 'hotspots',
    description: '外交政策声明与双边关系协调',
  },
  {
    id: 'us-surf-dc-fed',
    title: '华盛顿 · 美联储总部',
    source: SRC,
    timestamp: T12,
    location: [-77.04, 38.89],
    impact_level: 'critical',
    category: 'economic',
    description: '利率决议与全球流动性预期风向标',
  },
  {
    id: 'us-surf-dc-doj',
    title: '华盛顿 · 司法部',
    source: SRC,
    timestamp: T13,
    location: [-77.03, 38.89],
    impact_level: 'high',
    category: 'hotspots',
    description: '反垄断、选举诚信与国家安全诉讼',
  },
  {
    id: 'us-surf-dc-fbi',
    title: '华盛顿 · 联邦调查局总部',
    source: SRC,
    timestamp: T16,
    location: [-77.05, 38.9],
    impact_level: 'high',
    category: 'hotspots',
    description: '国内反恐与网络犯罪调查枢纽',
  },
  {
    id: 'us-surf-dc-cia',
    title: '兰利 · 中央情报局总部',
    source: SRC,
    timestamp: T11,
    location: [-77.15, 38.95],
    impact_level: 'high',
    category: 'military',
    description: '海外情报评估与秘密行动协调（公开节点）',
  },
  {
    id: 'us-surf-dc-nasa',
    title: '华盛顿 · 美国国家航空航天局',
    source: SRC,
    timestamp: T10,
    location: [-77.02, 38.88],
    impact_level: 'medium',
    category: 'economic',
    description: '商业航天与深空探测预算审议',
  },
  {
    id: 'us-surf-dc-epa',
    title: '华盛顿 · 环保署',
    source: SRC,
    timestamp: T14,
    location: [-77.03, 38.84],
    impact_level: 'medium',
    category: 'climate',
    description: '排放规则与气候政策执行监测',
  },
  {
    id: 'us-surf-dc-noaa',
    title: '银泉 · 国家海洋大气局',
    source: SRC,
    timestamp: T16,
    location: [-77.0, 38.99],
    impact_level: 'medium',
    category: 'weather',
    description: '全国飓风、野火与海洋气象预警中枢',
  },
];

export const US_SURFACE_CAPITAL_EVENTS: EventDetail[] = STATE_CAPITALS.map((s, i) => ({
  id: `us-surf-cap-${s.abbr}`,
  title: `${s.name} · 州府政治节点`,
  source: SRC,
  timestamp: CAPITAL_TIMESTAMPS[i % CAPITAL_TIMESTAMPS.length],
  location: [s.lng, s.lat] as [number, number],
  impact_level: 'medium' as const,
  category: 'hotspots',
  description: `${s.name}州议会与州长行政决策监测（种子/示例）`,
}));

/** 经济地标与金融中心 */
export const US_SURFACE_ECONOMIC_EVENTS: EventDetail[] = [
  {
    id: 'us-surf-econ-wall-st',
    title: '纽约 · 华尔街金融区',
    source: SRC,
    timestamp: T16,
    location: [-74.01, 40.71],
    impact_level: 'critical',
    category: 'economic',
    description: '纽交所、纳斯达克与全球风险偏好风向标',
  },
  {
    id: 'us-surf-econ-silicon-valley',
    title: '硅谷 · 全球科技资本',
    source: SRC,
    timestamp: T15,
    location: [-122.14, 37.44],
    impact_level: 'critical',
    category: 'econ_hubs',
    description: '风投、独角兽 IPO 与半导体设计生态',
  },
  {
    id: 'us-surf-econ-sand-hill',
    title: '门洛帕克 · 沙丘路风投',
    source: SRC,
    timestamp: T14,
    location: [-122.19, 37.42],
    impact_level: 'high',
    category: 'econ_hubs',
    description: '全球风险投资决策密度最高走廊',
  },
  {
    id: 'us-surf-econ-chicago-cme',
    title: '芝加哥 · 商品交易所',
    source: SRC,
    timestamp: T16,
    location: [-87.64, 41.88],
    impact_level: 'critical',
    category: 'economic',
    description: 'CME 农产品、能源与金融衍生品定价中心',
  },
  {
    id: 'us-surf-econ-houston-energy',
    title: '休斯顿 · 全球能源之都',
    source: SRC,
    timestamp: T15,
    location: [-95.37, 29.76],
    impact_level: 'critical',
    category: 'economic',
    description: '油气巨头总部、炼化与 LNG 出口枢纽',
  },
  {
    id: 'us-surf-econ-detroit-auto',
    title: '底特律 · 汽车工业',
    source: SRC,
    timestamp: T13,
    location: [-83.05, 42.33],
    impact_level: 'high',
    category: 'economic',
    description: '三大车企与电动车转型供应链',
  },
  {
    id: 'us-surf-econ-miami-intl',
    title: '迈阿密 · 拉美金融门户',
    source: SRC,
    timestamp: T12,
    location: [-80.19, 25.76],
    impact_level: 'high',
    category: 'econ_hubs',
    description: '跨境资本、邮轮旅游与飓风保险市场',
  },
  {
    id: 'us-surf-econ-research-triangle',
    title: '研究三角园 · 生物科技',
    source: SRC,
    timestamp: T11,
    location: [-78.64, 35.91],
    impact_level: 'high',
    category: 'econ_hubs',
    description: '杜克、北卡与药企研发集群',
  },
  {
    id: 'us-surf-econ-pittsburgh',
    title: '匹兹堡 · 钢铁与机器人',
    source: SRC,
    timestamp: T10,
    location: [-79.99, 40.44],
    impact_level: 'medium',
    category: 'economic',
    description: '先进制造与自动驾驶研发转型',
  },
  {
    id: 'us-surf-econ-seattle-amazon',
    title: '西雅图 · 云计算与电商',
    source: SRC,
    timestamp: T16,
    location: [-122.33, 47.61],
    impact_level: 'high',
    category: 'econ_hubs',
    description: 'AWS 与科技巨头总部经济辐射',
  },
  {
    id: 'us-surf-econ-dallas-fort-worth',
    title: '达拉斯-沃斯堡 · 物流金融',
    source: SRC,
    timestamp: T14,
    location: [-96.8, 32.78],
    impact_level: 'high',
    category: 'economic',
    description: '航空枢纽、能源交易与数据中心扩张',
  },
  {
    id: 'us-surf-econ-las-vegas',
    title: '拉斯维加斯 · 会展旅游',
    source: SRC,
    timestamp: T13,
    location: [-115.14, 36.17],
    impact_level: 'medium',
    category: 'economic',
    description: 'CES 等大型会展与博彩经济',
  },
];

/** 自然灾害与地质风险区 */
export const US_SURFACE_HAZARD_EVENTS: EventDetail[] = [
  {
    id: 'us-surf-haz-san-andreas',
    title: '加州 · 圣安德烈亚斯断层',
    source: 'USGS / seed',
    timestamp: T16,
    location: [-118.24, 34.05],
    impact_level: 'high',
    category: 'natural',
    description: '南加州地震活动与建筑抗震监测',
  },
  {
    id: 'us-surf-haz-new-madrid',
    title: '密苏里 · 新马德里地震带',
    source: 'USGS / seed',
    timestamp: T14,
    location: [-89.4, 36.0],
    impact_level: 'medium',
    category: 'natural',
    description: '中西部罕见强震历史带微震监测',
  },
  {
    id: 'us-surf-haz-cascadia',
    title: '太平洋西北 · 卡斯卡迪亚俯冲带',
    source: 'USGS / seed',
    timestamp: T15,
    location: [-124.0, 47.5],
    impact_level: 'critical',
    category: 'natural',
    description: '巨型地震与海啸复合风险区',
  },
  {
    id: 'us-surf-haz-gulf-hurricane',
    title: '墨西哥湾 · 飓风走廊',
    source: 'NHC / seed',
    timestamp: T16,
    location: [-90.0, 28.0],
    impact_level: 'high',
    category: 'weather',
    description: '油气平台、炼厂与沿海城市飓风路径',
  },
  {
    id: 'us-surf-haz-florida-keys',
    title: '佛罗里达礁岛群 · 风暴潮',
    source: 'NHC / seed',
    timestamp: T15,
    location: [-81.0, 24.5],
    impact_level: 'high',
    category: 'weather',
    description: '海平面上升与飓风风暴潮叠加风险',
  },
  {
    id: 'us-surf-haz-ca-wildfire-n',
    title: '北加州 · 野火季',
    source: 'NIFC / seed',
    timestamp: T16,
    location: [-122.0, 39.0],
    impact_level: 'high',
    category: 'climate',
    description: '森林火灾蔓延与电网断电风险',
  },
  {
    id: 'us-surf-haz-co-wildfire',
    title: '科罗拉多 · 山火监测',
    source: 'NIFC / seed',
    timestamp: T13,
    location: [-105.0, 39.5],
    impact_level: 'medium',
    category: 'climate',
    description: '落基山脉干旱与山火频发区',
  },
  {
    id: 'us-surf-haz-tornado-alley',
    title: '俄克拉荷马 · 龙卷风走廊',
    source: 'NWS / seed',
    timestamp: T14,
    location: [-97.0, 35.5],
    impact_level: 'high',
    category: 'weather',
    description: '春季强对流与龙卷风预警密集区',
  },
  {
    id: 'us-surf-haz-yellowstone',
    title: '黄石 · 地热火山系统',
    source: 'USGS / seed',
    timestamp: T12,
    location: [-110.67, 44.43],
    impact_level: 'medium',
    category: 'natural',
    description: '超级火山地热活动与微震监测',
  },
  {
    id: 'us-surf-haz-hawaii-volcano',
    title: '夏威夷 · 基拉韦厄火山',
    source: 'USGS / seed',
    timestamp: T11,
    location: [-155.3, 19.4],
    impact_level: 'medium',
    category: 'natural',
    description: '熔岩流与火山气体排放监测',
  },
  {
    id: 'us-surf-haz-atlantic-nc',
    title: '北卡罗来纳外海 · 大西洋飓风',
    source: 'NHC / seed',
    timestamp: T16,
    location: [-76.0, 34.5],
    impact_level: 'high',
    category: 'weather',
    description: '外岸群岛与军事基地飓风威胁',
  },
  {
    id: 'us-surf-haz-pnw-wildfire',
    title: '俄勒冈 · 太平洋西北野火',
    source: 'NIFC / seed',
    timestamp: T10,
    location: [-121.5, 44.0],
    impact_level: 'high',
    category: 'climate',
    description: '森林烟雾跨境影响空气质量',
  },
  {
    id: 'us-surf-haz-socal-drought',
    title: '南加州 · 干旱与火灾',
    source: 'NWS / seed',
    timestamp: T15,
    location: [-117.5, 34.0],
    impact_level: 'high',
    category: 'climate',
    description: '连续干旱加剧灌木丛火灾风险',
  },
];

/** 科技走廊与创新集群 */
export const US_SURFACE_TECH_EVENTS: EventDetail[] = [
  {
    id: 'us-surf-tech-route128',
    title: '波士顿 · 128 公路科技带',
    source: SRC,
    timestamp: T16,
    location: [-71.2, 42.4],
    impact_level: 'high',
    category: 'semiconductors',
    description: '生物医药、机器人和国防科技集群',
  },
  {
    id: 'us-surf-tech-dulles',
    title: '北弗吉尼亚 · 杜勒斯科技走廊',
    source: SRC,
    timestamp: T15,
    location: [-77.45, 38.95],
    impact_level: 'high',
    category: 'datacenters',
    description: '云计算数据中心与网络安全企业密集区',
  },
  {
    id: 'us-surf-tech-denver',
    title: '丹佛 · 科技中心',
    source: SRC,
    timestamp: T14,
    location: [-104.87, 39.62],
    impact_level: 'medium',
    category: 'econ_hubs',
    description: '航空航天与清洁能源初创生态',
  },
  {
    id: 'us-surf-tech-phoenix-chip',
    title: '凤凰城 · 半导体制造带',
    source: SRC,
    timestamp: T16,
    location: [-111.9, 33.45],
    impact_level: 'high',
    category: 'semiconductors',
    description: '台积电、英特尔晶圆厂与供应链本地化',
  },
  {
    id: 'us-surf-tech-austin',
    title: '奥斯汀 · 芯片与设计',
    source: SRC,
    timestamp: T13,
    location: [-97.74, 30.27],
    impact_level: 'high',
    category: 'semiconductors',
    description: '三星、特斯拉与初创企业共存生态',
  },
  {
    id: 'us-surf-tech-atlanta-fintech',
    title: '亚特兰大 · 金融科技',
    source: SRC,
    timestamp: T12,
    location: [-84.39, 33.75],
    impact_level: 'medium',
    category: 'econ_hubs',
    description: '支付处理与物流科技总部集群',
  },
  {
    id: 'us-surf-tech-slc',
    title: '盐湖城 · 硅坡',
    source: SRC,
    timestamp: T11,
    location: [-111.89, 40.76],
    impact_level: 'medium',
    category: 'econ_hubs',
    description: '企业软件与户外科技创业带',
  },
  {
    id: 'us-surf-tech-raleigh',
    title: '罗利-达勒姆 · 研究三角',
    source: SRC,
    timestamp: T10,
    location: [-78.64, 35.91],
    impact_level: 'high',
    category: 'semiconductors',
    description: 'IBM、思科与芯片设计人才池',
  },
];

export const US_SURFACE_EVENTS: EventDetail[] = [
  ...US_SURFACE_FEDERAL_EVENTS,
  ...US_SURFACE_CAPITAL_EVENTS,
  ...US_SURFACE_ECONOMIC_EVENTS,
  ...US_SURFACE_HAZARD_EVENTS,
  ...US_SURFACE_TECH_EVENTS,
];

/** 2026 年 6 月表层态势事件 */
export const US_SURFACE_INCIDENTS: Incident[] = [
  {
    id: 'us-surf-inc-fed-rate',
    title: '美联储 · 6 月利率决议',
    date: T12,
    type: 'political',
    faction: 'us',
    location: { lng: -77.04, lat: 38.89 },
    description: '联邦基金利率维持不变，点阵图偏鹰（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-scotus-ruling',
    title: '最高法院 · 监管裁决',
    date: T14,
    type: 'political',
    faction: 'us',
    location: { lng: -77.0, lat: 38.89 },
    description: '行政机构权力边界判例引发市场波动（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-gulf-storm',
    title: '墨西哥湾 · 热带风暴预警',
    date: T16,
    type: 'political',
    faction: 'us',
    location: { lng: -90.0, lat: 28.0 },
    description: 'NHC 发布飓风观察，油气平台撤离（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-ca-evac',
    title: '北加州 · 野火疏散令',
    date: T15,
    type: 'political',
    faction: 'us',
    location: { lng: -122.0, lat: 39.0 },
    description: '数千居民撤离，输电线路威胁（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-port-strike',
    title: '洛杉矶港 · 劳资谈判',
    date: T13,
    type: 'political',
    faction: 'us',
    location: { lng: -118.27, lat: 33.74 },
    description: '码头工人合同谈判影响跨太平洋货运（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-ord-delays',
    title: '芝加哥奥黑尔 · 航班大面积延误',
    date: T16,
    type: 'political',
    faction: 'us',
    location: { lng: -87.9, lat: 41.98 },
    description: '雷暴与空管人手短缺叠加（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-rail-derail',
    title: '俄亥俄 · 货运列车脱轨',
    date: T11,
    type: 'political',
    faction: 'us',
    location: { lng: -80.85, lat: 40.9 },
    description: '化学品车厢脱轨，EPA 现场监测（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-tx-grid',
    title: '得州 · 夏季用电高峰',
    date: T14,
    type: 'political',
    faction: 'us',
    location: { lng: -97.74, lat: 30.27 },
    description: 'ERCOT 发布节电呼吁，电价飙升（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-sv-layoffs',
    title: '硅谷 · 科技裁员潮',
    date: T10,
    type: 'political',
    faction: 'us',
    location: { lng: -122.14, lat: 37.44 },
    description: '多家独角兽宣布裁员与重组（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-midterm-ga',
    title: '佐治亚 · 中期选举造势',
    date: T15,
    type: 'political',
    faction: 'us',
    location: { lng: -84.39, lat: 33.75 },
    description: '关键摇摆州竞选集会与安全部署（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-ai-reg-ca',
    title: '加州 · AI 监管法案',
    date: T16,
    type: 'political',
    faction: 'us',
    location: { lng: -121.49, lat: 38.58 },
    description: '州议会审议大模型安全与透明度立法（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-cascadia-drill',
    title: '太平洋西北 · 地震演习',
    date: T12,
    type: 'military',
    faction: 'us',
    location: { lng: -124.0, lat: 47.5 },
    description: '全州「ShakeOut」海啸疏散演练（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-ny-flooding',
    title: '纽约 · 暴雨内涝',
    date: T13,
    type: 'political',
    faction: 'us',
    location: { lng: -74.01, lat: 40.71 },
    description: '地铁进水与地下商业区关闭（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-chip-act',
    title: '亚利桑那 · 晶圆厂投产',
    date: T16,
    type: 'diplomatic',
    faction: 'us',
    location: { lng: -111.9, lat: 33.45 },
    description: 'CHIPS 法案资助工厂试产里程碑（种子/示例）',
    source: SRC,
  },
  {
    id: 'us-surf-inc-miami-insurance',
    title: '迈阿密 · 飓风保险危机',
    date: T11,
    type: 'political',
    faction: 'us',
    location: { lng: -80.19, lat: 25.76 },
    description: '保险公司撤出高风险沿海保单（种子/示例）',
    source: SRC,
  },
];

/** 机场、港口、铁路枢纽 */
export const US_SURFACE_FACILITIES: Facility[] = [
  // ── 主要机场 ──
  {
    id: 'us-surf-fac-jfk',
    name: '肯尼迪国际机场',
    position: { lat: 40.64, lng: -73.78 },
    faction: 'us',
    type: 'airfield',
    notes: '美东国际门户，客运量全美前列（种子/示例）',
    updatedAt: T16,
  },
  {
    id: 'us-surf-fac-lax',
    name: '洛杉矶国际机场',
    position: { lat: 33.94, lng: -118.41 },
    faction: 'us',
    type: 'airfield',
    notes: '跨太平洋货运与客运枢纽（种子/示例）',
    updatedAt: T15,
  },
  {
    id: 'us-surf-fac-ord',
    name: '芝加哥奥黑尔国际机场',
    position: { lat: 41.98, lng: -87.9 },
    faction: 'us',
    type: 'airfield',
    notes: '全美转机量最大机场之一（种子/示例）',
    updatedAt: T16,
  },
  {
    id: 'us-surf-fac-atl',
    name: '哈兹菲尔德-杰克逊亚特兰大机场',
    position: { lat: 33.64, lng: -84.43 },
    faction: 'us',
    type: 'airfield',
    notes: '全球客运量最高机场（种子/示例）',
    updatedAt: T14,
  },
  {
    id: 'us-surf-fac-dfw',
    name: '达拉斯-沃斯堡国际机场',
    position: { lat: 32.9, lng: -97.04 },
    faction: 'us',
    type: 'airfield',
    notes: '美国航空枢纽，货运增长快（种子/示例）',
    updatedAt: T13,
  },
  {
    id: 'us-surf-fac-sfo',
    name: '旧金山国际机场',
    position: { lat: 37.62, lng: -122.38 },
    faction: 'us',
    type: 'airfield',
    notes: '硅谷商务与亚太航线门户（种子/示例）',
    updatedAt: T15,
  },
  {
    id: 'us-surf-fac-mia',
    name: '迈阿密国际机场',
    position: { lat: 25.8, lng: -80.29 },
    faction: 'us',
    type: 'airfield',
    notes: '拉美航线与冷链货运枢纽（种子/示例）',
    updatedAt: T12,
  },
  {
    id: 'us-surf-fac-sea',
    name: '西雅图-塔科马国际机场',
    position: { lat: 47.45, lng: -122.31 },
    faction: 'us',
    type: 'airfield',
    notes: '波音与亚马逊物流辐射（种子/示例）',
    updatedAt: T11,
  },
  {
    id: 'us-surf-fac-den',
    name: '丹佛国际机场',
    position: { lat: 39.86, lng: -104.67 },
    faction: 'us',
    type: 'airfield',
    notes: '中部高原转机与宽体机枢纽（种子/示例）',
    updatedAt: T10,
  },
  {
    id: 'us-surf-fac-iah',
    name: '乔治·布什洲际机场',
    position: { lat: 29.98, lng: -95.34 },
    faction: 'us',
    type: 'airfield',
    notes: '休斯顿能源业商务航空（种子/示例）',
    updatedAt: T14,
  },
  {
    id: 'us-surf-fac-ewr',
    name: '纽瓦克自由国际机场',
    position: { lat: 40.69, lng: -74.17 },
    faction: 'us',
    type: 'airfield',
    notes: '纽约都会区货运与联航枢纽（种子/示例）',
    updatedAt: T13,
  },
  {
    id: 'us-surf-fac-bos',
    name: '波士顿洛根国际机场',
    position: { lat: 42.36, lng: -71.01 },
    faction: 'us',
    type: 'airfield',
    notes: '新英格兰与欧洲航线门户（种子/示例）',
    updatedAt: T12,
  },
  // ── 主要港口 ──
  {
    id: 'us-surf-fac-la-port',
    name: '洛杉矶/长滩港',
    position: { lat: 33.74, lng: -118.27 },
    faction: 'us',
    type: 'naval',
    notes: '全美最大集装箱港口综合体（种子/示例）',
    updatedAt: T16,
  },
  {
    id: 'us-surf-fac-ny-nj-port',
    name: '纽约/新泽西港',
    position: { lat: 40.67, lng: -74.04 },
    faction: 'us',
    type: 'naval',
    notes: '美东最大集装箱与滚装码头（种子/示例）',
    updatedAt: T15,
  },
  {
    id: 'us-surf-fac-houston-port',
    name: '休斯顿港',
    position: { lat: 29.73, lng: -95.27 },
    faction: 'us',
    type: 'naval',
    notes: '能源与石化出口第一大港（种子/示例）',
    updatedAt: T14,
  },
  {
    id: 'us-surf-fac-savannah-port',
    name: '萨凡纳港',
    position: { lat: 32.08, lng: -81.09 },
    faction: 'us',
    type: 'naval',
    notes: '东南沿海集装箱增长最快港口（种子/示例）',
    updatedAt: T13,
  },
  {
    id: 'us-surf-fac-charleston-port',
    name: '查尔斯顿港',
    position: { lat: 32.79, lng: -79.93 },
    faction: 'us',
    type: 'naval',
    notes: '汽车出口与深水航道扩建（种子/示例）',
    updatedAt: T12,
  },
  {
    id: 'us-surf-fac-seattle-port',
    name: '西雅图港',
    position: { lat: 47.6, lng: -122.34 },
    faction: 'us',
    type: 'naval',
    notes: '阿拉斯加航线与亚太集装箱（种子/示例）',
    updatedAt: T11,
  },
  {
    id: 'us-surf-fac-oakland-port',
    name: '奥克兰港',
    position: { lat: 37.8, lng: -122.3 },
    faction: 'us',
    type: 'naval',
    notes: '北加州农产品与集装箱出口（种子/示例）',
    updatedAt: T10,
  },
  {
    id: 'us-surf-fac-nola-port',
    name: '新奥尔良港',
    position: { lat: 29.95, lng: -90.06 },
    faction: 'us',
    type: 'naval',
    notes: '密西西比河出海与粮食出口枢纽（种子/示例）',
    updatedAt: T14,
  },
  {
    id: 'us-surf-fac-baltimore-port',
    name: '巴尔的摩港',
    position: { lat: 39.27, lng: -76.58 },
    faction: 'us',
    type: 'naval',
    notes: '汽车滚装与煤炭出口（种子/示例）',
    updatedAt: T13,
  },
  {
    id: 'us-surf-fac-norfolk-port',
    name: '诺福克港',
    position: { lat: 36.85, lng: -76.29 },
    faction: 'us',
    type: 'naval',
    notes: '煤炭出口与海军基地毗邻（种子/示例）',
    updatedAt: T12,
  },
  // ── 铁路枢纽 ──
  {
    id: 'us-surf-fac-chicago-union',
    name: '芝加哥联合车站',
    position: { lat: 41.88, lng: -87.64 },
    faction: 'us',
    type: 'base',
    notes: '全美铁路货运编组中心（种子/示例）',
    updatedAt: T16,
  },
  {
    id: 'us-surf-fac-kansas-city-rail',
    name: '堪萨斯城铁路枢纽',
    position: { lat: 39.1, lng: -94.58 },
    faction: 'us',
    type: 'base',
    notes: '北美铁路十字路口（种子/示例）',
    updatedAt: T15,
  },
  {
    id: 'us-surf-fac-memphis-rail',
    name: '孟菲斯铁路枢纽',
    position: { lat: 35.15, lng: -90.05 },
    faction: 'us',
    type: 'base',
    notes: 'FedEx 超级枢纽与货运铁路交汇（种子/示例）',
    updatedAt: T14,
  },
  {
    id: 'us-surf-fac-atlanta-rail',
    name: '亚特兰大铁路枢纽',
    position: { lat: 33.75, lng: -84.39 },
    faction: 'us',
    type: 'base',
    notes: '东南货运铁路网络核心（种子/示例）',
    updatedAt: T13,
  },
  {
    id: 'us-surf-fac-dallas-rail',
    name: '达拉斯铁路编组站',
    position: { lat: 32.78, lng: -96.8 },
    faction: 'us',
    type: 'base',
    notes: '南部物流与联运中心（种子/示例）',
    updatedAt: T12,
  },
  {
    id: 'us-surf-fac-la-union',
    name: '洛杉矶联合车站',
    position: { lat: 34.06, lng: -118.24 },
    faction: 'us',
    type: 'base',
    notes: '西海岸客运与货运铁路节点（种子/示例）',
    updatedAt: T11,
  },
  {
    id: 'us-surf-fac-nyc-penn',
    name: '纽约宾州车站',
    position: { lat: 40.75, lng: -73.99 },
    faction: 'us',
    type: 'base',
    notes: '美东客运铁路最繁忙车站（种子/示例）',
    updatedAt: T10,
  },
  {
    id: 'us-surf-fac-philly-30th',
    name: '费城 30 街车站',
    position: { lat: 39.96, lng: -75.18 },
    faction: 'us',
    type: 'base',
    notes: '东北走廊铁路枢纽（种子/示例）',
    updatedAt: T14,
  },
];
