/**
 * 东北亚地缘博弈 · 地图种子数据
 * 关键基地、DMZ、导弹与舰队区域 — 公开近似坐标，整理日 2026-06-17
 */

import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 东北亚战略监测点 */
export const NORTHEAST_ASIA_EVENTS: EventDetail[] = [
  {
    id: 'nea-dmz',
    title: '三八线 · 非军事区（DMZ）',
    source: '东北亚态势',
    timestamp: '2026-06-17T08:00:00Z',
    location: [127.0, 38.0],
    impact_level: 'critical',
    category: 'hotspots',
    description: '朝韩军事分界线，全球最紧张边界之一',
  },
  {
    id: 'nea-yokota',
    title: '横田空军基地（驻日美军）',
    source: '东北亚态势',
    timestamp: '2026-06-17T06:00:00Z',
    location: [139.35, 35.75],
    impact_level: 'high',
    category: 'bases',
    description: '驻日美军与第五航空队司令部',
  },
  {
    id: 'nea-kadena',
    title: '嘉手纳空军基地（驻日美军）',
    source: '东北亚态势',
    timestamp: '2026-06-17T05:30:00Z',
    location: [127.77, 26.35],
    impact_level: 'critical',
    category: 'bases',
    description: '西太平洋最大空军基地，冲绳前沿空中力量',
  },
  {
    id: 'nea-yokosuka',
    title: '横须贺海军基地（第七舰队）',
    source: '东北亚态势',
    timestamp: '2026-06-17T05:00:00Z',
    location: [139.67, 35.29],
    impact_level: 'critical',
    category: 'bases',
    description: '美国第七舰队司令部与航母母港',
  },
  {
    id: 'nea-osan',
    title: '乌山空军基地（驻韩美军）',
    source: '东北亚态势',
    timestamp: '2026-06-17T04:30:00Z',
    location: [127.03, 37.09],
    impact_level: 'high',
    category: 'bases',
    description: '驻韩美军第七航空队前沿基地',
  },
  {
    id: 'nea-humphreys',
    title: '汉弗莱斯营（驻韩美军司令部）',
    source: '东北亚态势',
    timestamp: '2026-06-17T04:00:00Z',
    location: [127.06, 36.96],
    impact_level: 'critical',
    category: 'bases',
    description: '美国海外最大军事基地，驻韩美军司令部',
  },
  {
    id: 'nea-yongbyon',
    title: '宁边 · 朝鲜核设施',
    source: '东北亚态势',
    timestamp: '2026-06-16T10:00:00Z',
    location: [125.75, 39.79],
    impact_level: 'critical',
    category: 'nuclear',
    description: '朝鲜主要钚生产与核研发设施',
  },
  {
    id: 'nea-sinpo',
    title: '新浦 · 潜射导弹基地',
    source: '东北亚态势',
    timestamp: '2026-06-16T08:00:00Z',
    location: [128.17, 40.02],
    impact_level: 'critical',
    category: 'military',
    description: '朝鲜 SLBM 研发与试验基地',
  },
  {
    id: 'nea-kuril',
    title: '北方四岛 · 日俄领土争端',
    source: '东北亚态势',
    timestamp: '2026-06-15T12:00:00Z',
    location: [147.0, 45.5],
    impact_level: 'high',
    category: 'hotspots',
    description: '日称北方领土、俄称南千岛群岛，和平条约未签',
  },
  {
    id: 'nea-vladivostok',
    title: '符拉迪沃斯托克 · 俄太平洋舰队',
    source: '东北亚态势',
    timestamp: '2026-06-15T06:00:00Z',
    location: [131.89, 43.12],
    impact_level: 'high',
    category: 'military',
    description: '俄罗斯太平洋舰队司令部与远东战略支点',
  },
  {
    id: 'nea-thaad',
    title: '萨德系统（星州）',
    source: '东北亚态势',
    timestamp: '2026-06-16T05:00:00Z',
    location: [129.2, 35.95],
    impact_level: 'high',
    category: 'military',
    description: '驻韩美军反导系统，引发中韩外交争议',
  },
  {
    id: 'nea-panmunjom',
    title: '板门店 · 朝韩会谈场所',
    source: '东北亚态势',
    timestamp: '2026-06-14T08:00:00Z',
    location: [126.68, 37.95],
    impact_level: 'high',
    category: 'hotspots',
    description: 'DMZ 内唯一正式会谈与军事热线节点',
  },
];

export const NORTHEAST_ASIA_INCIDENTS: Incident[] = [
  {
    id: 'nea-inc-1',
    title: '朝鲜试射弹道导弹 · 落入日本海',
    date: '2026-06-17T06:00:00Z',
    type: 'military',
    faction: 'kp',
    location: { lat: 40.0, lng: 129.0 },
    description: '朝鲜从平安北道发射中程弹道导弹，落入日本海专属经济区',
    source: 'reuters',
  },
  {
    id: 'nea-inc-2',
    title: '美韩联合军演 · 乙支自由护盾',
    date: '2026-06-16T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 37.5, lng: 127.0 },
    description: '美韩举行大规模联合军演，朝鲜谴责为「侵略预演」',
    source: 'reuters',
  },
  {
    id: 'nea-inc-3',
    title: '俄太平洋舰队 · 日本海演习',
    date: '2026-06-15T10:00:00Z',
    type: 'military',
    faction: 'ru',
    location: { lat: 42.0, lng: 132.0 },
    description: '俄舰艇编队在日本海举行实弹演习，日本自卫队监视跟踪',
    source: 'defense',
  },
  {
    id: 'nea-inc-4',
    title: '钓鱼岛海域 · 中日海警对峙',
    date: '2026-06-16T06:30:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 25.75, lng: 123.47 },
    description: '中国海警与日本海上保安厅在钓鱼岛附近海域对峙',
    source: 'reuters',
  },
  {
    id: 'nea-inc-5',
    title: '驻日美军 F-35 · 冲绳紧急升空',
    date: '2026-06-16T05:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 26.5, lng: 127.5 },
    description: '嘉手纳基地 F-35 紧急升空应对周边空域异常活动',
    source: 'defense',
  },
  {
    id: 'nea-inc-6',
    title: '北方四岛 · 俄加强导弹部署',
    date: '2026-06-14T12:00:00Z',
    type: 'military',
    faction: 'ru',
    location: { lat: 44.5, lng: 146.5 },
    description: '卫星图像显示择捉岛新增 coastal 防御导弹阵地',
    source: '38north',
  },
];

export const NORTHEAST_ASIA_FACILITIES: Facility[] = [
  {
    id: 'nea-fac-yokota',
    name: '横田空军基地',
    position: { lat: 35.75, lng: 139.35 },
    faction: 'us',
    type: 'airfield',
    forces: ['驻日美军', '第五航空队'],
    notes: '驻日美军司令部，区域空运与指挥枢纽',
  },
  {
    id: 'nea-fac-kadena',
    name: '嘉手纳空军基地',
    position: { lat: 26.35, lng: 127.77 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军', '日本航空自卫队'],
    weapons: ['F-15', 'F-22', 'F-35'],
    notes: '西太平洋最大空军基地',
  },
  {
    id: 'nea-fac-yokosuka',
    name: '横须贺海军基地',
    position: { lat: 35.29, lng: 139.67 },
    faction: 'us',
    type: 'naval',
    forces: ['美国第七舰队'],
    notes: '航母母港，面向东海与台海',
  },
  {
    id: 'nea-fac-osan',
    name: '乌山空军基地',
    position: { lat: 37.09, lng: 127.03 },
    faction: 'us',
    type: 'airfield',
    forces: ['美国空军第七航空队'],
    weapons: ['F-16'],
    notes: '驻韩美军主要空军基地',
  },
  {
    id: 'nea-fac-humphreys',
    name: '汉弗莱斯营',
    position: { lat: 36.96, lng: 127.06 },
    faction: 'us',
    type: 'base',
    troopEstimate: '约 3.6 万',
    notes: '驻韩美军司令部，美国海外最大基地',
  },
  {
    id: 'nea-fac-yongbyon',
    name: '宁边核科学研究中心',
    position: { lat: 39.79, lng: 125.75 },
    faction: 'kp',
    type: 'nuclear',
    nuclearKind: 'research_reactor',
    status: '运行中',
    notes: '朝鲜主要钚生产设施',
  },
  {
    id: 'nea-fac-sinpo',
    name: '新浦造船厂（SLBM）',
    position: { lat: 40.02, lng: 128.17 },
    faction: 'kp',
    type: 'missile',
    notes: '朝鲜潜射弹道导弹研发基地',
  },
  {
    id: 'nea-fac-wonsan',
    name: '元山导弹发射场',
    position: { lat: 39.15, lng: 127.43 },
    faction: 'kp',
    type: 'missile',
    notes: '朝鲜东部主要导弹试射场',
  },
  {
    id: 'nea-fac-thaad',
    name: '萨德反导系统（星州）',
    position: { lat: 35.95, lng: 129.2 },
    faction: 'us',
    type: 'missile',
    weapons: ['萨德拦截弹'],
    notes: '2017 年部署，引发中韩外交争议',
  },
  {
    id: 'nea-fac-vladivostok',
    name: '符拉迪沃斯托克海军基地',
    position: { lat: 43.12, lng: 131.89 },
    faction: 'ru',
    type: 'naval',
    forces: ['俄罗斯太平洋舰队'],
    notes: '俄远东最大海军基地',
  },
  {
    id: 'nea-fac-kuril',
    name: '择捉岛军事部署',
    position: { lat: 44.7, lng: 147.35 },
    faction: 'ru',
    type: 'base',
    notes: '日俄北方领土争端核心岛屿',
  },
  {
    id: 'nea-fac-panmunjom',
    name: '板门店（DMZ）',
    position: { lat: 37.95, lng: 126.68 },
    faction: 'kr',
    type: 'base',
    notes: '朝韩军事分界线会谈场所',
  },
];

/** 东北亚地图聚焦边界 [[minLng, minLat], [maxLng, maxLat]] */
export const NORTHEAST_ASIA_BOUNDS: [[number, number], [number, number]] = [
  [118, 33],
  [150, 46],
];
