import type { EventDetail } from '@/types/geo';
import type { Incident, Facility } from '@/types/middleeast';

/** 第二轮增密 · 全球公开态势整理（2026-06-10 至 06-16） */
const T16 = '2026-06-16T10:00:00Z';
const T15 = '2026-06-15T14:00:00Z';
const T14 = '2026-06-14T08:00:00Z';
const T13 = '2026-06-13T16:00:00Z';
const T12 = '2026-06-12T06:00:00Z';
const T11 = '2026-06-11T12:00:00Z';
const T10 = '2026-06-10T18:00:00Z';

export const GLOBAL_DENSIFY_EVENTS: EventDetail[] = [
  { id: 'r2g-red-sea', title: '红海 · 商船袭击余波', source: '公开态势整理', timestamp: T16, location: [43.0, 14.5], impact_level: 'critical', category: 'maritime', description: '胡塞武装袭击后航运保险费率持续高企' },
  { id: 'r2g-suez', title: '苏伊士运河 · 通行监测', source: '公开态势整理', timestamp: T15, location: [32.35, 30.45], impact_level: 'high', category: 'waterways', description: '全球约12%贸易量途经运河' },
  { id: 'r2g-panama', title: '巴拿马运河 · 干旱限航', source: '公开态势整理', timestamp: T14, location: [-79.92, 9.08], impact_level: 'high', category: 'waterways', description: '加通湖水位偏低限制每日过闸量' },
  { id: 'r2g-hormuz', title: '霍尔木兹海峡 · 油轮通行', source: '公开态势整理', timestamp: T16, location: [56.5, 26.5], impact_level: 'critical', category: 'waterways', description: '全球约20%石油贸易途经' },
  { id: 'r2g-bab', title: '曼德海峡 · 护航编队', source: '公开态势整理', timestamp: T13, location: [43.3, 12.6], impact_level: 'high', category: 'military', description: '多国海军护航商船穿越红海入口' },
  { id: 'r2g-ukraine-front', title: '乌克兰东部 · 前线态势', source: '公开态势整理', timestamp: T16, location: [37.5, 48.5], impact_level: 'critical', category: 'conflicts', description: '顿巴斯方向交火持续' },
  { id: 'r2g-gaza', title: '加沙地带 · 人道危机', source: '公开态势整理', timestamp: T15, location: [34.47, 31.5], impact_level: 'critical', category: 'hotspots', description: '人道援助通道与停火谈判' },
  { id: 'r2g-sudan', title: '苏丹 · 内战持续', source: '公开态势整理', timestamp: T14, location: [32.5, 15.5], impact_level: 'critical', category: 'conflicts', description: '喀土穆周边战事与人道撤离' },
  { id: 'r2g-sahel', title: '萨赫勒 · 恐怖主义威胁', source: '公开态势整理', timestamp: T13, location: [2.0, 14.0], impact_level: 'high', category: 'conflicts', description: '马里-尼日尔-布基纳法索安全形势恶化' },
  { id: 'r2g-venezuela', title: '委内瑞拉 · 边境争端', source: '公开态势整理', timestamp: T12, location: [-61.0, 7.0], impact_level: 'high', category: 'conflicts', description: '埃塞奎博地区主权争议' },
  { id: 'r2g-haiti', title: '海地 · 帮派暴力', source: '公开态势整理', timestamp: T11, location: [-72.33, 18.54], impact_level: 'high', category: 'hotspots', description: '太子港治安崩溃，联合国讨论维和' },
  { id: 'r2g-myanmar', title: '缅甸 · 内战扩大', source: '公开态势整理', timestamp: T16, location: [96.0, 19.0], impact_level: 'critical', category: 'conflicts', description: '民族武装与军政府战事蔓延' },
  { id: 'r2g-ethiopia', title: '埃塞俄比亚 · 提格雷局势', source: '公开态势整理', timestamp: T10, location: [39.0, 14.0], impact_level: 'high', category: 'conflicts', description: '和平协议后地方武装摩擦' },
  { id: 'r2g-nato-baltic', title: '波罗的海 · 北约演习', source: '公开态势整理', timestamp: T15, location: [24.0, 57.0], impact_level: 'high', category: 'military', description: '北约波罗的海防卫演习' },
  { id: 'r2g-arctic', title: '北极 · 航道开通', source: '公开态势整理', timestamp: T14, location: [60.0, 75.0], impact_level: 'medium', category: 'waterways', description: '北极东北航道冰情缓解' },
  { id: 'r2g-north-korea', title: '朝鲜半岛 · 导弹发射', source: '公开态势整理', timestamp: T16, location: [125.5, 40.0], impact_level: 'critical', category: 'military', description: '朝鲜弹道导弹试射' },
  { id: 'r2g-india-pak', title: '克什米尔 · 边境交火', source: '公开态势整理', timestamp: T13, location: [74.5, 34.0], impact_level: 'high', category: 'conflicts', description: '实控线附近零星炮击' },
  { id: 'r2g-taiwan', title: '台湾海峡 · 军事演训', source: '公开态势整理', timestamp: T16, location: [120.0, 24.0], impact_level: 'critical', category: 'military', description: '环台岛战备警巡' },
  { id: 'r2g-south-china-sea', title: '南海 · 岛礁对峙', source: '公开态势整理', timestamp: T15, location: [114.0, 10.0], impact_level: 'high', category: 'hotspots', description: '多国岛礁占领与对峙' },
  { id: 'r2g-opec', title: '欧佩克 · 减产延期', source: '公开态势整理', timestamp: T14, location: [54.0, 24.0], impact_level: 'high', category: 'economic', description: '产油国延长自愿减产' },
  { id: 'r2g-fed', title: '美联储 · 利率决议', source: '公开态势整理', timestamp: T12, location: [-77.04, 38.9], impact_level: 'high', category: 'economic', description: '全球金融市场关注利率路径' },
  { id: 'r2g-eu-sanctions', title: '欧盟 · 新一轮制裁', source: '公开态势整理', timestamp: T11, location: [4.35, 50.85], impact_level: 'medium', category: 'sanctions', description: '对俄能源与金融制裁延期' },
  { id: 'r2g-chip', title: '全球芯片 · 供应链扰动', source: '公开态势整理', timestamp: T16, location: [121.0, 24.8], impact_level: 'high', category: 'economic', description: '先进制程产能紧张' },
  { id: 'r2g-cyber', title: '全球 · 勒索软件攻击', source: '公开态势整理', timestamp: T13, location: [-0.12, 51.5], impact_level: 'medium', category: 'outages', description: '医疗系统遭受网络攻击' },
  { id: 'r2g-power-grid', title: '欧洲 · 电网压力', source: '公开态势整理', timestamp: T12, location: [13.4, 52.5], impact_level: 'medium', category: 'outages', description: '可再生能源波动致供电紧张' },
  { id: 'r2g-aviation-eu', title: '欧洲空域 · 罢工潮', source: '公开态势整理', timestamp: T15, location: [2.35, 48.86], impact_level: 'medium', category: 'aviation', description: '空管与地勤罢工致航班取消' },
  { id: 'r2g-aviation-asia', title: '东亚 · 航班恢复', source: '公开态势整理', timestamp: T14, location: [139.77, 35.68], impact_level: 'low', category: 'aviation', description: '国际航线客流恢复至疫前八成' },
  { id: 'r2g-cable-cut', title: '红海海底电缆 · 受损修复', source: '公开态势整理', timestamp: T16, location: [42.0, 15.0], impact_level: 'high', category: 'cables', description: '多条国际光缆中断后抢修' },
  { id: 'r2g-iran-nuclear', title: '伊朗 · 核计划进展', source: '公开态势整理', timestamp: T15, location: [51.42, 35.69], impact_level: 'critical', category: 'nuclear', description: '浓缩铀丰度接近武器级门槛' },
  { id: 'r2g-france-nuclear', title: '法国 · 核电站检修', source: '公开态势整理', timestamp: T13, location: [4.8, 44.5], impact_level: 'medium', category: 'nuclear', description: '多台核电机组计划外停机' },
  { id: 'r2g-heat-india', title: '印度 · 极端热浪', source: '公开态势整理', timestamp: T16, location: [78.96, 20.59], impact_level: 'critical', category: 'weather', description: '多地气温突破45°C' },
  { id: 'r2g-flood-brazil', title: '巴西南部 · 洪涝灾害', source: '公开态势整理', timestamp: T14, location: [-51.23, -30.03], impact_level: 'critical', category: 'natural', description: '强降雨致大规模洪灾' },
  { id: 'r2g-quake-japan', title: '日本 · 地震预警', source: '公开态势整理', timestamp: T12, location: [142.36, 38.27], impact_level: 'high', category: 'natural', description: '东部海域5.8级地震' },
  { id: 'r2g-wildfire-canada', title: '加拿大 · 野火季', source: '公开态势整理', timestamp: T11, location: [-120.0, 54.0], impact_level: 'high', category: 'climate', description: '西部林火蔓延' },
  { id: 'r2g-drought-mexico', title: '墨西哥城 · 干旱', source: '公开态势整理', timestamp: T10, location: [-99.13, 19.43], impact_level: 'high', category: 'climate', description: '水库蓄水量创新低' },
  { id: 'r2g-protest-fr', title: '法国 · 全国性罢工', source: '公开态势整理', timestamp: T16, location: [2.35, 48.86], impact_level: 'medium', category: 'protests', description: '养老金与劳工改革抗议' },
  { id: 'r2g-launch-spacex', title: '佛罗里达 · 商业发射', source: '公开态势整理', timestamp: T15, location: [-80.6, 28.5], impact_level: 'low', category: 'launch_sites', description: '星链卫星批量发射' },
  { id: 'r2g-launch-china', title: '文昌 · 载人航天任务', source: '公开态势整理', timestamp: T14, location: [110.95, 19.61], impact_level: 'medium', category: 'launch_sites', description: '空间站补给飞船发射' },
  { id: 'r2g-semiconductor-tw', title: '台湾 · 晶圆厂产能', source: '公开态势整理', timestamp: T16, location: [120.97, 24.78], impact_level: 'critical', category: 'semiconductors', description: '先进制程产能满载' },
  { id: 'r2g-garrison-djibouti', title: '吉布提 · 多国基地', source: '公开态势整理', timestamp: T13, location: [43.1, 11.6], impact_level: 'high', category: 'garrisons', description: '中美法日等多国军事存在' },
  { id: 'r2g-mining-congo', title: '刚果（金）· 钴矿', source: '公开态势整理', timestamp: T12, location: [27.48, -11.66], impact_level: 'critical', category: 'minerals', description: '电动车电池关键原料' },
  { id: 'r2g-dc-virginia', title: '弗吉尼亚 · 数据中心', source: '公开态势整理', timestamp: T11, location: [-77.49, 39.04], impact_level: 'high', category: 'datacenters', description: 'AI训练算力集群' },
  { id: 'r2g-pipeline-nord', title: '北欧 · 天然气管道', source: '公开态势整理', timestamp: T10, location: [12.0, 55.0], impact_level: 'high', category: 'pipelines', description: '波罗的海管道运营监测' },
  { id: 'r2g-hub-nyc', title: '纽约 · 金融市场', source: '公开态势整理', timestamp: T16, location: [-74.01, 40.71], impact_level: 'critical', category: 'econ_hubs', description: '全球金融中心波动' },
  { id: 'r2g-deepsea-pacific', title: '太平洋 · 深海采矿', source: '公开态势整理', timestamp: T14, location: [-160.0, 0.0], impact_level: 'medium', category: 'deep_sea_mining', description: '国际海底管理局许可争议' },
  { id: 'r2g-tectonic-ring', title: '环太平洋 · 地震带', source: '公开态势整理', timestamp: T13, location: [-155.0, 19.0], impact_level: 'medium', category: 'tectonics', description: '板块边界活动监测' },
];

export const GLOBAL_DENSIFY_INCIDENTS: Incident[] = [
  { id: 'r2g-inc-redsea-1', title: '红海 · 商船遭袭', date: T16, type: 'military', faction: 'houthis', location: { lng: 42.5, lat: 14.8 }, description: '胡塞武装无人机袭击货轮', source: '公开态势整理' },
  { id: 'r2g-inc-ukraine-1', title: '哈尔科夫 · 俄军推进', date: T15, type: 'military', faction: 'ru', location: { lng: 36.25, lat: 49.99 }, description: '俄军向哈尔科夫州边境推进', source: '公开态势整理' },
  { id: 'r2g-inc-gaza-1', title: '加沙 · 人道援助', date: T16, type: 'political', faction: 'il', location: { lng: 34.47, lat: 31.5 }, description: '援助车队进入加沙', source: '公开态势整理' },
  { id: 'r2g-inc-sudan-1', title: '喀土穆 · 空袭', date: T14, type: 'military', faction: 'rsf', location: { lng: 32.53, lat: 15.55 }, description: '快速支援部队空袭政府军阵地', source: '公开态势整理' },
  { id: 'r2g-inc-sahel-1', title: '马里 · 恐怖袭击', date: T13, type: 'military', faction: 'jnim', location: { lng: -4.0, lat: 16.0 }, description: '极端组织袭击军事哨所', source: '公开态势整理' },
  { id: 'r2g-inc-venezuela-1', title: '埃塞奎博 · 军事集结', date: T12, type: 'military', faction: 've', location: { lng: -61.0, lat: 7.0 }, description: '委内瑞拉边境军事部署', source: '公开态势整理' },
  { id: 'r2g-inc-myanmar-1', title: '掸邦 · 武装冲突', date: T16, type: 'military', faction: 'kia', location: { lng: 98.0, lat: 23.0 }, description: '克钦独立军与政府军交火', source: '公开态势整理' },
  { id: 'r2g-inc-india-1', title: '克什米尔 · 炮击', date: T15, type: 'military', faction: 'in', location: { lng: 74.5, lat: 34.0 }, description: '印巴边境零星交火', source: '公开态势整理' },
  { id: 'r2g-inc-nato-1', title: '波罗的海 · 俄舰接近', date: T14, type: 'military', faction: 'ru', location: { lng: 20.0, lat: 58.0 }, description: '俄军舰进入波罗的海演习区', source: '公开态势整理' },
  { id: 'r2g-inc-iran-1', title: '伊朗 · 浓缩铀报告', date: T16, type: 'political', faction: 'ir', location: { lng: 51.42, lat: 35.69 }, description: 'IAEA报告铀浓缩进展', source: '公开态势整理' },
  { id: 'r2g-inc-cyber-1', title: '全球 · 勒索攻击', date: T13, type: 'political', faction: 'contested', location: { lng: -0.12, lat: 51.5 }, description: '医疗机构系统遭勒索软件', source: '公开态势整理' },
  { id: 'r2g-inc-sanction-1', title: '华盛顿 · 新制裁名单', date: T12, type: 'political', faction: 'us', location: { lng: -77.04, lat: 38.9 }, description: '财政部公布新一轮制裁', source: '公开态势整理' },
  { id: 'r2g-inc-cable-1', title: '红海 · 光缆中断', date: T16, type: 'political', faction: 'contested', location: { lng: 42.0, lat: 15.0 }, description: '多条国际海底光缆受损', source: '公开态势整理' },
  { id: 'r2g-inc-protest-1', title: '巴黎 · 示威游行', date: T15, type: 'political', faction: 'fr', location: { lng: 2.35, lat: 48.86 }, description: '全国性罢工示威', source: '公开态势整理' },
  { id: 'r2g-inc-launch-1', title: '朝鲜 · 导弹试射', date: T16, type: 'military', faction: 'kp', location: { lng: 125.8, lat: 39.5 }, description: '弹道导弹落入日本海', source: '公开态势整理' },
  { id: 'r2g-inc-taiwan-1', title: '台海 · 军机过线', date: T16, type: 'military', faction: 'cn', location: { lng: 119.8, lat: 24.2 }, description: '解放军军机越过海峡中线', source: '公开态势整理' },
  { id: 'r2g-inc-scs-1', title: '南沙 · 水炮对峙', date: T15, type: 'military', faction: 'cn', location: { lng: 114.8, lat: 9.2 }, description: '海警对菲方船只水炮驱离', source: '公开态势整理' },
  { id: 'r2g-inc-opec-1', title: '维也纳 · 减产决定', date: T14, type: 'diplomatic', faction: 'opec', location: { lng: 16.37, lat: 48.21 }, description: '欧佩克+延长减产协议', source: '公开态势整理' },
  { id: 'r2g-inc-haiti-1', title: '太子港 · 帮派冲突', date: T11, type: 'military', faction: 'gangs', location: { lng: -72.33, lat: 18.54 }, description: '帮派争夺港口控制权', source: '公开态势整理' },
  { id: 'r2g-inc-ethiopia-1', title: '提格雷 · 武装摩擦', date: T10, type: 'military', faction: 'tplf', location: { lng: 39.0, lat: 14.0 }, description: '地方武装与联邦政府摩擦', source: '公开态势整理' },
  { id: 'r2g-inc-arctic-1', title: '北极 · 俄军事演习', date: T13, type: 'military', faction: 'ru', location: { lng: 50.0, lat: 72.0 }, description: '北方舰队北极演习', source: '公开态势整理' },
  { id: 'r2g-inc-yemen-1', title: '也门 · 胡塞袭击', date: T16, type: 'military', faction: 'houthis', location: { lng: 44.2, lat: 15.35 }, description: '胡塞武装袭击红海商船', source: '公开态势整理' },
  { id: 'r2g-inc-syria-1', title: '叙利亚 · 空袭', date: T12, type: 'military', faction: 'il', location: { lng: 36.3, lat: 33.5 }, description: '以色列空袭叙利亚境内目标', source: '公开态势整理' },
  { id: 'r2g-inc-lebanon-1', title: '黎巴嫩 · 边境交火', date: T14, type: 'military', faction: 'hezbollah', location: { lng: 35.5, lat: 33.2 }, description: '真主党与以军边境交火', source: '公开态势整理' },
  { id: 'r2g-inc-colombia-1', title: '哥伦比亚 · 游击队', date: T11, type: 'military', faction: 'eln', location: { lng: -74.0, lat: 4.6 }, description: '民族解放军袭击军事目标', source: '公开态势整理' },
];

export const GLOBAL_DENSIFY_FACILITIES: Facility[] = [
  { id: 'r2g-fac-djibouti-cn', name: '吉布提保障基地', position: { lat: 11.59, lng: 43.07 }, faction: 'cn', type: 'naval', notes: '中国首个海外保障基地' },
  { id: 'r2g-fac-djibouti-us', name: '勒莫尼耶军营', position: { lat: 11.55, lng: 43.15 }, faction: 'us', type: 'base', troopEstimate: '约4000', notes: '美军非洲司令部前沿' },
  { id: 'r2g-fac-guam', name: '关岛安德森基地', position: { lat: 13.58, lng: 144.93 }, faction: 'us', type: 'airfield', forces: ['B-52'], notes: '西太平洋战略轰炸机基地' },
  { id: 'r2g-fac-diego', name: '迪戈加西亚基地', position: { lat: -7.3, lng: 72.4 }, faction: 'us', type: 'naval', notes: '印度洋战略支点' },
  { id: 'r2g-fac-bahrain', name: '第五舰队总部', position: { lat: 26.23, lng: 50.58 }, faction: 'us', type: 'naval', notes: '美国海军中央司令部' },
  { id: 'r2g-fac-aludeid', name: '乌代德空军基地', position: { lat: 25.12, lng: 51.32 }, faction: 'us', type: 'airfield', notes: '中东最大美军基地' },
  { id: 'r2g-fac-ramstein', name: '拉姆施泰因基地', position: { lat: 49.44, lng: 7.6 }, faction: 'us', type: 'airfield', notes: '美军欧洲司令部枢纽' },
  { id: 'r2g-fac-incirlik', name: '因吉尔利克基地', position: { lat: 37.0, lng: 35.43 }, faction: 'us', type: 'airfield', notes: '土耳其境内美军基地' },
  { id: 'r2g-fac-sevastopol', name: '塞瓦斯托波尔', position: { lat: 44.62, lng: 33.53 }, faction: 'ru', type: 'naval', forces: ['黑海舰队'], notes: '俄黑海舰队母港' },
  { id: 'r2g-fac-kaliningrad', name: '加里宁格勒', position: { lat: 54.7, lng: 20.5 }, faction: 'ru', type: 'base', notes: '波罗的海飞地军事集群' },
  { id: 'r2g-fac-tartus', name: '塔尔图斯海军基地', position: { lat: 34.9, lng: 35.87 }, faction: 'ru', type: 'naval', notes: '俄地中海补给点' },
  { id: 'r2g-fac-hmeimim', name: '赫梅明空军基地', position: { lat: 35.41, lng: 35.95 }, faction: 'ru', type: 'airfield', notes: '俄叙利亚空中枢纽' },
  { id: 'r2g-fac-natanz', name: '纳坦兹核设施', position: { lat: 33.72, lng: 51.73 }, faction: 'ir', type: 'nuclear', nuclearKind: 'enrichment', notes: '伊朗主要铀浓缩设施' },
  { id: 'r2g-fac-fordow', name: '福尔多核设施', position: { lat: 34.88, lng: 51.58 }, faction: 'ir', type: 'nuclear', nuclearKind: 'enrichment', notes: '地下铀浓缩设施' },
  { id: 'r2g-fac-dimona', name: '迪莫纳核设施', position: { lat: 31.0, lng: 35.15 }, faction: 'il', type: 'nuclear', nuclearKind: 'power_plant', notes: '以色列核设施' },
  { id: 'r2g-fac-pakistan-k', name: '卡胡塔核设施', position: { lat: 33.6, lng: 73.4 }, faction: 'pk', type: 'nuclear', nuclearKind: 'enrichment', notes: '巴基斯坦核计划核心' },
  { id: 'r2g-fac-yokosuka', name: '横须贺海军基地', position: { lat: 35.29, lng: 139.67 }, faction: 'us', type: 'naval', forces: ['第七舰队'], notes: '美军西太平洋母港' },
  { id: 'r2g-fac-kadena', name: '嘉手纳空军基地', position: { lat: 26.35, lng: 127.77 }, faction: 'us', type: 'airfield', notes: '冲绳最大空军基地' },
  { id: 'r2g-fac-subic', name: '苏比克湾', position: { lat: 14.8, lng: 120.28 }, faction: 'ph', type: 'naval', notes: '菲律宾主要军港' },
  { id: 'r2g-fac-darwin', name: '达尔文港', position: { lat: -12.46, lng: 130.84 }, faction: 'au', type: 'naval', notes: '美军轮换部署港' },
  { id: 'r2g-fac-pine-gap', name: '松树谷联合设施', position: { lat: -23.8, lng: 133.74 }, faction: 'us', type: 'base', notes: '美澳信号情报设施' },
  { id: 'r2g-fac-lakenheath', name: '莱肯希思基地', position: { lat: 52.41, lng: 0.56 }, faction: 'us', type: 'airfield', forces: ['F-35'], notes: '美军欧洲战斗机基地' },
  { id: 'r2g-fac-rota', name: '罗塔海军基地', position: { lat: 36.62, lng: -6.35 }, faction: 'us', type: 'naval', notes: '地中海驱逐舰前沿港' },
  { id: 'r2g-fac-guantanamo', name: '关塔那摩湾', position: { lat: 19.9, lng: -75.16 }, faction: 'us', type: 'naval', notes: '加勒比海军基地' },
  { id: 'r2g-fac-norfolk', name: '诺福克海军基地', position: { lat: 36.95, lng: -76.33 }, faction: 'us', type: 'naval', forces: ['大西洋舰队'], notes: '全球最大海军基地' },
  { id: 'r2g-fac-pearl', name: '珍珠港', position: { lat: 21.35, lng: -157.97 }, faction: 'us', type: 'naval', notes: '太平洋舰队司令部' },
  { id: 'r2g-fac-san-diego', name: '圣迭戈海军基地', position: { lat: 32.68, lng: -117.12 }, faction: 'us', type: 'naval', notes: '太平洋舰队主要母港' },
  { id: 'r2g-fac-camp-humphreys', name: '汉弗莱斯军营', position: { lat: 36.97, lng: 127.02 }, faction: 'us', type: 'base', troopEstimate: '约3.5万', notes: '驻韩美军最大基地' },
  { id: 'r2g-fac-akrotiri', name: '阿克罗蒂里基地', position: { lat: 34.59, lng: 32.96 }, faction: 'uk', type: 'airfield', notes: '英军东地中海基地' },
  { id: 'r2g-fac-fr-djibouti', name: '法军吉布提基地', position: { lat: 11.6, lng: 43.16 }, faction: 'fr', type: 'base', notes: '法国海外最大驻军' },
  { id: 'r2g-fac-cn-ream', name: '柬埔寨云壤基地', position: { lat: 10.62, lng: 103.52 }, faction: 'cn', type: 'naval', notes: '中柬海军合作设施' },
  { id: 'r2g-fac-zaporizhzhia', name: '扎波罗热核电站', position: { lat: 47.51, lng: 34.58 }, faction: 'ru', type: 'nuclear', nuclearKind: 'power_plant', status: '争议控制', notes: '欧洲最大核电站' },
  { id: 'r2g-fac-chernobyl', name: '切尔诺贝利禁区', position: { lat: 51.39, lng: 30.1 }, faction: 'ua', type: 'nuclear', nuclearKind: 'contamination', notes: '1986事故遗址' },
  { id: 'r2g-fac-fukushima', name: '福岛第一核电站', position: { lat: 37.42, lng: 141.03 }, faction: 'jp', type: 'nuclear', nuclearKind: 'contamination', notes: '2011事故后处理中' },
  { id: 'r2g-fac-kashiwazaki', name: '柏崎刈羽核电站', position: { lat: 37.43, lng: 138.6 }, faction: 'jp', type: 'nuclear', nuclearKind: 'power_plant', notes: '全球最大核电站之一' },
];
