import type { EventDetail } from '@/types/geo';

/**
 * 全球视角 · 种子事件数据（用于在未接入实时 GeoJSON 流时填充地图内容）
 *
 * ⚠ 占位/示例：用于打通「事件 → GeoJSON/地图图层 → SidePanel」链路。
 */
export const GLOBAL_SEED_EVENTS: EventDetail[] = [
  {
    id: 'cn-singapore-waterway',
    title: '新加坡港 · 航道监测点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-16T09:30:00Z',
    location: [103.82, 1.35],
    impact_level: 'high',
    category: 'waterways',
    description: '航运通行与通航风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-hk-economic',
    title: '香港—珠江口 · 贸易与通道韧性监测',
    source: 'seed/示例（港口与贸易）',
    timestamp: '2026-06-16T10:10:00Z',
    location: [114.17, 22.32],
    impact_level: 'high',
    category: 'economic',
    description: '港口装卸与通航韧性占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-sandstorm-weather',
    title: '华北—华西走廊 · 沙尘与能见度预警',
    source: 'seed/示例（气象监测）',
    timestamp: '2026-06-16T07:40:00Z',
    location: [115.86, 36.10],
    impact_level: 'medium',
    category: 'weather',
    description: '极端天气对物流/航运影响占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-japan-earthquake',
    title: '日本东部 · 地震与余震预警',
    source: 'seed/示例（自然灾害）',
    timestamp: '2026-06-15T06:10:00Z',
    location: [142.36, 38.27],
    impact_level: 'high',
    category: 'natural',
    description: '地震活动与余震风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-malacca-waterway',
    title: '马六甲海峡 · 航道监测点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-14T20:20:00Z',
    location: [102.25, 2.3],
    impact_level: 'medium',
    category: 'waterways',
    description: '航道过境风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-shanghai-economic',
    title: '上海港 · 一带一路节点监测',
    source: 'seed/示例（港口与贸易）',
    timestamp: '2026-06-16T10:25:00Z',
    location: [121.47, 31.23],
    impact_level: 'high',
    category: 'economic',
    description: '关键港口与经贸活跃度占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-dubai-economic',
    title: '迪拜港 · 航运与贸易通道韧性监测',
    source: 'seed/示例（港口与贸易）',
    timestamp: '2026-06-16T13:05:00Z',
    location: [55.27, 25.20],
    impact_level: 'high',
    category: 'economic',
    description: '关键港口装卸节奏与通航风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-hormuz-hotspot',
    title: '霍尔木兹海峡 · 航道风险热点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-15T18:15:00Z',
    location: [56.3, 26.6],
    impact_level: 'high',
    category: 'hotspots',
    description: '航道风险上行与通行约束叠加占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-malacca-waterway-2',
    title: '马六甲海峡 · 航道监测点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-16T08:55:00Z',
    location: [102.25, 2.3],
    impact_level: 'medium',
    category: 'waterways',
    description: '航道过境风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-suez-waterway',
    title: '苏伊士运河 · 通行与风险预警点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-15T22:10:00Z',
    location: [32.35, 30.00],
    impact_level: 'medium',
    category: 'waterways',
    description: '运河通行不确定性与调度风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-redsea-hotspot',
    title: '红海航道 · 风险热点与绕行预警',
    source: 'seed/示例（海事监测）',
    timestamp: '2026-06-15T09:20:00Z',
    location: [43.2, 15.0],
    impact_level: 'medium',
    category: 'hotspots',
    description: '海上通行风险上升与绕行成本变化占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-taiwan-waterway',
    title: '台海周边 · 航运与通行韧性监测',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-16T12:40:00Z',
    location: [121.60, 25.05],
    impact_level: 'high',
    category: 'waterways',
    description: '航线调整与通行约束占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-taiwan-hotspot',
    title: '台海周边 · 安全热点',
    source: 'seed/示例（安全监测）',
    timestamp: '2026-06-16T11:45:00Z',
    location: [122.00, 24.90],
    impact_level: 'high',
    category: 'hotspots',
    description: '安全风险热点占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-typhoon-weather',
    title: '西北太平洋 · 热带气旋路径预警',
    source: 'seed/示例（气象监测）',
    timestamp: '2026-06-16T05:30:00Z',
    location: [127.0, 23.0],
    impact_level: 'medium',
    category: 'weather',
    description: '气旋路径与风浪影响占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-earthquake-weather',
    title: '日本东部 · 地震与余震风险联动预警',
    source: 'seed/示例（自然灾害）',
    timestamp: '2026-06-15T06:40:00Z',
    location: [141.6, 37.7],
    impact_level: 'high',
    category: 'natural',
    description: '地震活动与余震风险联动占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-sandstorm-weather-2',
    title: '华北内陆 · 沙尘暴能见度预警点',
    source: 'seed/示例（气象监测）',
    timestamp: '2026-06-16T06:20:00Z',
    location: [111.7, 36.9],
    impact_level: 'medium',
    category: 'weather',
    description: '沙尘影响对交通/通行的联动预警占位点（阶段3 接真实数据）',
  },
  {
    id: 'cn-gwadar-economic',
    title: '瓜达尔港 · 中巴经济走廊节点监测',
    source: 'seed/示例（一带一路）',
    timestamp: '2026-06-16T11:00:00Z',
    location: [62.33, 25.12],
    impact_level: 'high',
    category: 'economic',
    description: '走廊陆海联运与能源通道关键节点',
  },
  {
    id: 'cn-djibouti-bases',
    title: '吉布提保障基地 · 亚丁湾护航支撑',
    source: 'seed/示例（海外保障）',
    timestamp: '2026-06-15T14:30:00Z',
    location: [43.15, 11.58],
    impact_level: 'medium',
    category: 'bases',
    description: '海外首个保障基地，红海—亚丁湾航线安全支撑',
  },
  {
    id: 'cn-panama-waterway',
    title: '巴拿马运河 · 全球航运咽喉监测',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-16T08:00:00Z',
    location: [-79.92, 9.08],
    impact_level: 'high',
    category: 'waterways',
    description: '全球贸易量约 5% 经此通行，干旱与通行配额影响运价',
  },
  {
    id: 'cn-cape-waterway',
    title: '好望角 · 绕行航线监测点',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-15T20:00:00Z',
    location: [18.47, -34.36],
    impact_level: 'medium',
    category: 'waterways',
    description: '红海风险上升后 VLCC 绕行增加，航程与成本抬升',
  },
  {
    id: 'cn-arctic-waterway',
    title: '北极东北航道 · 季节性通航监测',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-14T12:00:00Z',
    location: [140.0, 72.0],
    impact_level: 'low',
    category: 'waterways',
    description: '冰期缩短背景下北方海路货运试点与风险监测',
  },
  {
    id: 'cn-rail-europe-economic',
    title: '杜伊斯堡 · 中欧班列枢纽',
    source: 'seed/示例（贸易通道）',
    timestamp: '2026-06-16T09:15:00Z',
    location: [6.76, 51.43],
    impact_level: 'medium',
    category: 'economic',
    description: '亚欧陆路贸易主枢纽，班列频次与通关效率监测',
  },
  {
    id: 'cn-lithium-economic',
    title: '锂三角 · 关键矿产供应链监测',
    source: 'seed/示例（资源贸易）',
    timestamp: '2026-06-15T16:00:00Z',
    location: [-67.0, -23.0],
    impact_level: 'medium',
    category: 'economic',
    description: '新能源电池原料产地，中资企业投资与出口政策敏感',
  },
  {
    id: 'cn-africa-hotspot',
    title: '萨赫勒地区 · 安全与资源风险热点',
    source: 'seed/示例（安全监测）',
    timestamp: '2026-06-14T10:00:00Z',
    location: [2.0, 14.0],
    impact_level: 'medium',
    category: 'hotspots',
    description: '反恐与矿业投资交织，中资企业安保需求上升',
  },
  {
    id: 'cn-flood-natural',
    title: '孟加拉湾 · 季风洪涝预警',
    source: 'seed/示例（自然灾害）',
    timestamp: '2026-06-16T04:00:00Z',
    location: [90.4, 23.8],
    impact_level: 'medium',
    category: 'natural',
    description: '季风季节洪涝对供应链与港口装卸的影响监测',
  },
  {
    id: 'cn-sanctions-economic',
    title: '全球制裁合规 · 能源贸易监测点',
    source: 'seed/示例（经贸合规）',
    timestamp: '2026-06-15T11:30:00Z',
    location: [51.4, 35.7],
    impact_level: 'high',
    category: 'sanctions',
    description: '次级制裁与能源进口多元化政策交汇敏感区',
  },
  {
    id: 'cn-nuclear-hotspot',
    title: '朝鲜半岛 · 核导态势监测',
    source: 'seed/示例（战略安全）',
    timestamp: '2026-06-16T13:00:00Z',
    location: [125.75, 39.02],
    impact_level: 'critical',
    category: 'nuclear',
    description: '半岛无核化谈判与导弹试射周期监测',
  },
  {
    id: 'cn-perth-iron',
    title: '珀斯 · 铁矿石出口与航运监测',
    source: 'seed/示例（资源贸易）',
    timestamp: '2026-06-16T11:10:00Z',
    location: [115.86, -31.95],
    impact_level: 'high',
    category: 'economic',
    description: '中国炼厂主要铁矿石来源，运价与港口装卸节奏敏感',
  },
  {
    id: 'cn-rotterdam-waterway',
    title: '鹿特丹—莱茵河 · 亚欧贸易通道',
    source: 'seed/示例（航运监测）',
    timestamp: '2026-06-15T15:30:00Z',
    location: [4.48, 51.92],
    impact_level: 'medium',
    category: 'waterways',
    description: '中欧班列终点与集装箱转运枢纽',
  },
  {
    id: 'cn-mozambique-lng',
    title: '莫桑比克 · LNG 项目与东非通道',
    source: 'seed/示例（能源）',
    timestamp: '2026-06-14T18:00:00Z',
    location: [40.7, -14.5],
    impact_level: 'medium',
    category: 'economic',
    description: '东非天然气出口与中国长期采购合同监测',
  },
  {
    id: 'cn-russia-pipeline',
    title: '西伯利亚 · 中俄能源管道监测',
    source: 'seed/示例（能源通道）',
    timestamp: '2026-06-16T09:50:00Z',
    location: [104.3, 52.3],
    impact_level: 'high',
    category: 'economic',
    description: '东线天然气管道输量与过境协调',
  },
  {
    id: 'cn-istanbul-waterway',
    title: '土耳其海峡 · 黑海粮食与能源通道',
    source: 'IMO / seed',
    timestamp: '2026-06-15T12:00:00Z',
    location: [29.0, 41.0],
    impact_level: 'high',
    category: 'waterways',
    description: '博斯普鲁斯海峡通行与粮食走廊延伸',
  },
  {
    id: 'cn-kenya-rail',
    title: '蒙内铁路 · 东非陆海联运节点',
    source: 'seed/示例（一带一路）',
    timestamp: '2026-06-14T14:30:00Z',
    location: [36.82, -1.29],
    impact_level: 'medium',
    category: 'economic',
    description: '内罗毕—蒙巴萨通道，东非贸易与物流骨干',
  },
  {
    id: 'cn-eu-outage',
    title: '欧洲电网 · 跨境电力互联监测',
    source: 'ENTSO-E / seed',
    timestamp: '2026-06-16T07:00:00Z',
    location: [6.13, 49.61],
    impact_level: 'medium',
    category: 'outages',
    description: '极端天气下跨境输电容量与工业限电风险',
  },
  {
    id: 'cn-indonesia-nickel',
    title: '印尼苏拉威西 · 镍冶炼产能监测',
    source: 'seed/示例（产业链）',
    timestamp: '2026-06-16T12:20:00Z',
    location: [121.0, -2.5],
    impact_level: 'high',
    category: 'economic',
    description: '新能源电池原料本地化政策与出口限制',
  },
  {
    id: 'cn-antarctica-weather',
    title: '南极科考 · 极端环境预警参考',
    source: 'seed/示例（气象）',
    timestamp: '2026-06-13T08:00:00Z',
    location: [58.0, -62.0],
    impact_level: 'low',
    category: 'weather',
    description: '极地科考站气象与航运窗口监测',
  },
  {
    id: 'cn-djibouti-bases-2',
    title: '吉布提 · 多国基地集聚区监测',
    source: 'seed/示例（基地）',
    timestamp: '2026-06-16T14:45:00Z',
    location: [43.15, 11.58],
    impact_level: 'medium',
    category: 'bases',
    description: '中美法日等多国保障与军事存在交汇',
  },
  {
    id: 'cn-eu-sanctions',
    title: '布鲁塞尔 · 对俄次级制裁外溢监测',
    source: 'EEAS / seed',
    timestamp: '2026-06-15T13:00:00Z',
    location: [4.35, 50.85],
    impact_level: 'medium',
    category: 'sanctions',
    description: '中欧贸易合规与军民两用物项审查',
  },
  {
    id: 'cn-pakistan-nuclear',
    title: '南亚 · 核态势与扩散风险监测',
    source: 'IAEA / seed',
    timestamp: '2026-06-14T11:00:00Z',
    location: [73.05, 33.72],
    impact_level: 'high',
    category: 'nuclear',
    description: '印巴核威慑平衡与地区安全',
  },
  {
    id: 'cn-germany-outage',
    title: '德国工业带 · 能源价格与限电风险',
    source: 'seed/示例（基础设施）',
    timestamp: '2026-06-16T08:15:00Z',
    location: [9.99, 53.55],
    impact_level: 'medium',
    category: 'outages',
    description: '气价波动对化工与汽车产业链影响',
  },
  {
    id: 'cn-caspian-economic',
    title: '里海 · 能源过境与管道枢纽',
    source: 'seed/示例（能源通道）',
    timestamp: '2026-06-15T10:30:00Z',
    location: [51.0, 44.0],
    impact_level: 'medium',
    category: 'economic',
    description: '中亚油气南向运输替代路线',
  },
  {
    id: 'cn-ethiopia-hotspot',
    title: '埃塞俄比亚 · 地区安全与投资项目',
    source: 'seed/示例（热点）',
    timestamp: '2026-06-13T14:00:00Z',
    location: [38.75, 9.03],
    impact_level: 'medium',
    category: 'hotspots',
    description: '北部冲突缓和与基建复工监测',
  },
  {
    id: 'cn-nigeria-economic',
    title: '拉各斯 · 西非贸易与能源枢纽',
    source: 'seed/示例（经济）',
    timestamp: '2026-06-16T10:40:00Z',
    location: [3.38, 6.45],
    impact_level: 'medium',
    category: 'economic',
    description: '原油出口与制造业供应链节点',
  },
  {
    id: 'cn-greenland-natural',
    title: '格陵兰 · 冰盖融化与海平面监测',
    source: 'NASA / seed',
    timestamp: '2026-06-12T12:00:00Z',
    location: [-42.0, 72.0],
    impact_level: 'low',
    category: 'natural',
    description: '气候变化长期指标参考点',
  },
  {
    id: 'cn-jun-bri-summit',
    title: '一带一路高峰论坛 · 基建合作监测',
    source: 'seed/示例（经济）',
    timestamp: '2026-06-15T08:00:00Z',
    location: [116.4, 39.9],
    impact_level: 'high',
    category: 'economic',
    description: '互联互通项目与债务可持续性议题（种子/示例）',
  },
  {
    id: 'cn-jun-semiconductor',
    title: '长三角 · 芯片产业链景气监测',
    source: 'seed/示例（产业链）',
    timestamp: '2026-06-14T12:00:00Z',
    location: [121.5, 31.2],
    impact_level: 'critical',
    category: 'economic',
    description: '先进制程产能与出口管制影响（种子/示例）',
  },
  {
    id: 'cn-jun-south-china-sea',
    title: '南海 · 岛礁建设与发展监测',
    source: 'seed/示例（热点）',
    timestamp: '2026-06-13T16:00:00Z',
    location: [112.5, 9.5],
    impact_level: 'high',
    category: 'hotspots',
    description: '岛礁设施与航行自由议题（种子/示例）',
  },
  {
    id: 'cn-jun-eu-trade',
    title: '中欧贸易 · 电动车反补贴调查',
    source: 'seed/示例（制裁）',
    timestamp: '2026-06-14T10:00:00Z',
    location: [4.35, 50.85],
    impact_level: 'high',
    category: 'sanctions',
    description: '欧盟对华电动车关税博弈（种子/示例）',
  },
  {
    id: 'cn-jun-floods',
    title: '华南 · 梅雨强降雨预警',
    source: 'seed/示例（自然灾害）',
    timestamp: '2026-06-15T06:00:00Z',
    location: [113.26, 23.13],
    impact_level: 'high',
    category: 'natural',
    description: '珠江流域城市内涝风险上升（种子/示例）',
  },
  {
    id: 'cn-jun-arctic',
    title: '北极航道 · 季节性通航监测',
    source: 'seed/示例（航运）',
    timestamp: '2026-06-12T10:00:00Z',
    location: [120.0, 72.0],
    impact_level: 'medium',
    category: 'waterways',
    description: '北方海航道商业航运试验（种子/示例）',
  },
  {
    id: 'cn-jun-africa-mining',
    title: '刚果（金）· 钴矿供应链监测',
    source: 'seed/示例（资源）',
    timestamp: '2026-06-13T14:00:00Z',
    location: [27.48, -11.66],
    impact_level: 'high',
    category: 'economic',
    description: '电池产业链关键矿产采购（种子/示例）',
  },
  {
    id: 'cn-jun-middle-east-energy',
    title: '波斯湾 · 能源进口多元化',
    source: 'seed/示例（能源）',
    timestamp: '2026-06-15T10:00:00Z',
    location: [50.0, 26.0],
    impact_level: 'critical',
    category: 'economic',
    description: '中东局势下油气进口安全监测（种子/示例）',
  },
  {
    id: 'cn-jun-typhoon',
    title: '西北太平洋 · 台风路径预警',
    source: 'seed/示例（气象）',
    timestamp: '2026-06-14T00:00:00Z',
    location: [130.0, 20.0],
    impact_level: 'medium',
    category: 'weather',
    description: '台风季航运与港口作业风险（种子/示例）',
  },
  {
    id: 'cn-jun-central-asia',
    title: '中亚 · 天然气管道输送监测',
    source: 'seed/示例（能源通道）',
    timestamp: '2026-06-12T08:00:00Z',
    location: [66.0, 41.0],
    impact_level: 'medium',
    category: 'waterways',
    description: '中俄中亚能源走廊运营态势（种子/示例）',
  },
  {
    id: 'cn-jun-latin-trade',
    title: '拉美 · 大豆与锂进口监测',
    source: 'seed/示例（贸易）',
    timestamp: '2026-06-13T20:00:00Z',
    location: [-58.0, -34.6],
    impact_level: 'medium',
    category: 'economic',
    description: '粮食安全与新能源产业链进口（种子/示例）',
  },
];

