/**
 * 全球航天发射日志 — 2025–2026 种子任务记录
 *
 * ⚠ 公开报道与机构通告汇总，用于态势演示；非实时发射数据库。
 * 整理日：2026-06-16
 */

import type { LayerId } from '@/types/geo';

export type LaunchStatus = 'success' | 'failure' | 'partial' | 'scheduled' | 'scrubbed';

export interface LaunchLogEntry {
  id: string;
  title: string;
  provider: string;
  siteId?: string;
  location: { lng: number; lat: number };
  launchTime: string;
  status: LaunchStatus;
  orbit?: string;
  payload?: string;
  note?: string;
  layerId: LayerId;
}

/** 全球发射任务日志（按 launchTime 升序维护，展示时倒序） */
export const GLOBAL_LAUNCH_LOG: LaunchLogEntry[] = [
  // ── 2025 Q1 ───────────────────────────────────────────────────
  {
    id: 'll-2025-01-spacex-sl9',
    title: 'SpaceX Falcon 9 · Starlink Group 7-10',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-01-08T03:27:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '23 颗 Starlink 卫星',
    note: '卡纳维拉尔角 SLC-40',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-01-cnsa-cz5',
    title: 'CNSA 长征五号 · 通信技术试验卫星',
    provider: 'CNSA',
    siteId: 'launch-cn-wenchang',
    location: { lng: 110.95, lat: 19.61 },
    launchTime: '2025-01-17T09:00:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: '通信技术试验十四号',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-02-ula-vulcan',
    title: 'ULA Vulcan Centaur · USSF-106',
    provider: 'ULA',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-02-21T18:45:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: '美国太空军机密载荷',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-03-isro-gslv',
    title: 'ISRO GSLV Mk III · NISAR',
    provider: 'ISRO',
    siteId: 'launch-in-sriharikota',
    location: { lng: 80.23, lat: 13.72 },
    launchTime: '2025-03-12T04:30:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: 'NASA-ISRO 合成孔径雷达卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-03-roscosmos-soyuz',
    title: 'Roscosmos Soyuz 2.1a · Progress MS-29',
    provider: 'Roscosmos',
    siteId: 'launch-ru-baikonur',
    location: { lng: 63.34, lat: 45.96 },
    launchTime: '2025-03-28T11:20:00Z',
    status: 'success',
    orbit: 'LEO/ISS',
    payload: '国际空间站货运飞船',
    layerId: 'launch_log',
  },
  // ── 2025 Q2 ───────────────────────────────────────────────────
  {
    id: 'll-2025-04-esa-ariane',
    title: 'ESA Ariane 6 · CSO-3',
    provider: 'ESA',
    siteId: 'launch-eu-kourou',
    location: { lng: -52.77, lat: 5.24 },
    launchTime: '2025-04-15T21:00:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '法国光学侦察卫星 CSO-3',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-04-spacex-fh',
    title: 'SpaceX Falcon Heavy · GOES-U',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-04-29T22:12:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: 'GOES-U 气象卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-05-jaxa-h3',
    title: 'JAXA H3 · ALOS-4',
    provider: 'JAXA',
    siteId: 'launch-jp-tanegashima',
    location: { lng: 130.97, lat: 30.4 },
    launchTime: '2025-05-18T01:22:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '先进陆地观测卫星 ALOS-4',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-05-rocketlab',
    title: 'Rocket Lab Electron · Kineis K-01~05',
    provider: 'Rocket Lab',
    siteId: 'launch-nz-mahia',
    location: { lng: 177.87, lat: -39.26 },
    launchTime: '2025-05-25T21:30:00Z',
    status: 'partial',
    orbit: 'LEO',
    payload: '5 颗物联网卫星（1 颗未入轨）',
    note: '部分载荷未达目标轨道',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-06-cnsa-shenzhou',
    title: 'CNSA 长征二号F · 神舟十九号',
    provider: 'CNSA',
    siteId: 'launch-cn-jiuquan',
    location: { lng: 100.29, lat: 40.96 },
    launchTime: '2025-06-30T04:00:00Z',
    status: 'success',
    orbit: 'LEO/ISS',
    payload: '载人飞船 · 3 名航天员',
    layerId: 'launch_log',
  },
  // ── 2025 Q3 ───────────────────────────────────────────────────
  {
    id: 'll-2025-07-spacex-polaris',
    title: 'SpaceX Falcon 9 · Polaris Dawn',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-07-14T08:23:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '商业载人龙飞船 · 舱外活动任务',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-08-cnsa-changzheng',
    title: 'CNSA 长征三号乙 · 中星系列',
    provider: 'CASC',
    siteId: 'launch-cn-xichang',
    location: { lng: 102.03, lat: 28.25 },
    launchTime: '2025-08-06T12:15:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: '中星通信卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-08-blue-origin',
    title: 'Blue Origin New Glenn · ESCAPADE',
    provider: 'Blue Origin',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-08-22T10:00:00Z',
    status: 'failure',
    orbit: '地火转移',
    payload: 'NASA 火星探测双星 ESCAPADE',
    note: '上面级异常，载荷未脱离',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-09-spacex-starship',
    title: 'SpaceX Starship · IFT-6',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-09-19T12:30:00Z',
    status: 'partial',
    orbit: '亚轨道',
    payload: '星舰全栈综合飞行试验',
    note: '助推器海上回收成功，飞船再入前失联',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-10-roscosmos-angara',
    title: 'Roscosmos Angara-A5 · 通信卫星',
    provider: 'Roscosmos',
    siteId: 'launch-ru-vostochny',
    location: { lng: 128.17, lat: 51.88 },
    launchTime: '2025-10-03T09:00:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: '俄罗斯新一代通信卫星',
    layerId: 'launch_log',
  },
  // ── 2025 Q4 ───────────────────────────────────────────────────
  {
    id: 'll-2025-11-nasa-artemis',
    title: 'NASA SLS · Artemis II',
    provider: 'NASA',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-11-15T06:00:00Z',
    status: 'success',
    orbit: '地月转移',
    payload: '猎户座飞船 · 载人绕月',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-11-isro-pslv',
    title: 'ISRO PSLV · Proba-3',
    provider: 'ISRO',
    siteId: 'launch-in-sriharikota',
    location: { lng: 80.23, lat: 13.72 },
    launchTime: '2025-11-28T04:45:00Z',
    status: 'success',
    orbit: '高椭圆',
    payload: 'ESA 日冕观测编队',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-12-spacex-crew',
    title: 'SpaceX Falcon 9 · Crew-11',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2025-12-10T18:00:00Z',
    status: 'success',
    orbit: 'LEO/ISS',
    payload: 'NASA 商业载人轮换任务',
    layerId: 'launch_log',
  },
  {
    id: 'll-2025-12-cnsa-moon',
    title: 'CNSA 长征五号 · 嫦娥七号',
    provider: 'CNSA',
    siteId: 'launch-cn-wenchang',
    location: { lng: 110.95, lat: 19.61 },
    launchTime: '2025-12-22T08:30:00Z',
    status: 'success',
    orbit: '地月转移',
    payload: '月球南极探测轨道器+着陆器',
    layerId: 'launch_log',
  },
  // ── 2026 Q1 ───────────────────────────────────────────────────
  {
    id: 'll-2026-01-spacex-sl',
    title: 'SpaceX Falcon 9 · Starlink Group 12-8',
    provider: 'SpaceX',
    siteId: 'launch-us-vandenberg',
    location: { lng: -120.63, lat: 34.74 },
    launchTime: '2026-01-14T02:15:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '22 颗 Starlink 卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-01-ariane',
    title: 'Arianespace Vega-C · THEOS-2',
    provider: 'Arianespace',
    siteId: 'launch-eu-kourou',
    location: { lng: -52.77, lat: 5.24 },
    launchTime: '2026-01-28T19:00:00Z',
    status: 'scrubbed',
    orbit: 'SSO',
    payload: '泰国地球观测卫星',
    note: '高空风切变，推迟至下一窗口',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-02-jaxa-h2a',
    title: 'JAXA H-IIA · 情报收集卫星',
    provider: 'JAXA',
    siteId: 'launch-jp-tanegashima',
    location: { lng: 130.97, lat: 30.4 },
    launchTime: '2026-02-08T05:30:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '日本光学侦察卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-02-kari',
    title: 'KARI 世界号 · KOMPSAT-7',
    provider: 'KARI',
    siteId: 'launch-kr-naro',
    location: { lng: 127.54, lat: 34.43 },
    launchTime: '2026-02-19T07:00:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '韩国多用途卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-03-ula-atlas',
    title: 'ULA Atlas V · STP-3',
    provider: 'ULA',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2026-03-05T22:40:00Z',
    status: 'success',
    orbit: 'GTO',
    payload: '美国太空军技术验证',
    layerId: 'launch_log',
  },
  // ── 2026 Q2（近期） ─────────────────────────────────────────────
  {
    id: 'll-2026-04-cnsa-tiangong',
    title: 'CNSA 长征七号 · 天舟九号',
    provider: 'CASC',
    siteId: 'launch-cn-wenchang',
    location: { lng: 110.95, lat: 19.61 },
    launchTime: '2026-04-12T09:17:00Z',
    status: 'success',
    orbit: 'LEO/天宫',
    payload: '空间站货运补给',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-04-spacex-nrol',
    title: 'SpaceX Falcon 9 · NROL-126',
    provider: 'SpaceX',
    siteId: 'launch-us-vandenberg',
    location: { lng: -120.63, lat: 34.74 },
    launchTime: '2026-04-22T14:00:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '美国国家侦察局机密载荷',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-05-roscosmos',
    title: 'Roscosmos Soyuz 2.1b · 格洛纳斯-M',
    provider: 'Roscosmos',
    siteId: 'launch-ru-plesetsk',
    location: { lng: 40.58, lat: 62.93 },
    launchTime: '2026-05-03T10:45:00Z',
    status: 'success',
    orbit: 'MEO',
    payload: 'GLONASS 导航卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-05-rocketlab-2',
    title: 'Rocket Lab Electron · TROPICS-2',
    provider: 'Rocket Lab',
    siteId: 'launch-nz-mahia',
    location: { lng: 177.87, lat: -39.26 },
    launchTime: '2026-05-11T23:00:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: 'NASA 热带气旋观测星座',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-05-cnsa-beidou',
    title: 'CNSA 长征三号乙 · 北斗导航',
    provider: 'CASC',
    siteId: 'launch-cn-xichang',
    location: { lng: 102.03, lat: 28.25 },
    launchTime: '2026-05-20T13:30:00Z',
    status: 'success',
    orbit: 'MEO',
    payload: '北斗三号备份星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-05-spacex-scrub',
    title: 'SpaceX Falcon 9 · Starlink Group 6-62',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2026-05-28T08:00:00Z',
    status: 'scrubbed',
    orbit: 'LEO',
    payload: 'Starlink V2 Mini 批次',
    note: '地面系统检查，T-0 前中止',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-spacex-sl6',
    title: 'SpaceX Falcon 9 · Starlink Group 6-45',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2026-06-02T06:12:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '24 颗 Starlink 卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-esa-juice',
    title: 'ESA Ariane 6 · Sentinel-1C',
    provider: 'ESA',
    siteId: 'launch-eu-kourou',
    location: { lng: -52.77, lat: 5.24 },
    launchTime: '2026-06-05T21:30:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '哥白尼雷达对地观测',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-isro-gaganyaan',
    title: 'ISRO LVM3 · Gaganyaan-1 无人试验',
    provider: 'ISRO',
    siteId: 'launch-in-sriharikota',
    location: { lng: 80.23, lat: 13.72 },
    launchTime: '2026-06-08T04:00:00Z',
    status: 'success',
    orbit: '亚轨道',
    payload: '印度载人航天无人验证飞行',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-cnsa-jiuquan',
    title: 'CNSA 快舟一号甲 · 商业遥感',
    provider: 'CASC',
    siteId: 'launch-cn-jiuquan',
    location: { lng: 100.29, lat: 40.96 },
    launchTime: '2026-06-10T11:00:00Z',
    status: 'success',
    orbit: 'SSO',
    payload: '吉林一号宽幅卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-jaxa-fail',
    title: 'JAXA Epsilon S · RAISE-4',
    provider: 'JAXA',
    siteId: 'launch-jp-uchinoura',
    location: { lng: 131.08, lat: 31.25 },
    launchTime: '2026-06-11T08:20:00Z',
    status: 'failure',
    orbit: 'LEO',
    payload: '小型技术试验卫星',
    note: '第二级点火异常',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-spacex-vandy',
    title: 'SpaceX Falcon 9 · NRO L-153',
    provider: 'SpaceX',
    siteId: 'launch-us-vandenberg',
    location: { lng: -120.63, lat: 34.74 },
    launchTime: '2026-06-13T15:45:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '美国国家侦察局载荷',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-cnsa-wenchang',
    title: 'CNSA 长征八号 · 卫星互联网试验',
    provider: 'CASC',
    siteId: 'launch-cn-wenchang',
    location: { lng: 110.95, lat: 19.61 },
    launchTime: '2026-06-14T10:30:00Z',
    status: 'success',
    orbit: 'LEO',
    payload: '低轨互联网试验星组网',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-roscosmos-soyuz2',
    title: 'Roscosmos Soyuz MS-28 · 载人轮换',
    provider: 'Roscosmos',
    siteId: 'launch-ru-baikonur',
    location: { lng: 63.34, lat: 45.96 },
    launchTime: '2026-06-15T14:20:00Z',
    status: 'success',
    orbit: 'LEO/ISS',
    payload: '联盟号载人飞船 · 3 名航天员',
    layerId: 'launch_log',
  },
  // ── 计划中 ─────────────────────────────────────────────────────
  {
    id: 'll-2026-06-spacex-sched',
    title: 'SpaceX Falcon 9 · Starlink Group 6-46',
    provider: 'SpaceX',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2026-06-17T22:00:00Z',
    status: 'scheduled',
    orbit: 'LEO',
    payload: 'Starlink V2 Mini 批次',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-ula-sched',
    title: 'ULA Vulcan · Amazon Kuiper',
    provider: 'ULA',
    siteId: 'launch-us-ksc',
    location: { lng: -80.6, lat: 28.57 },
    launchTime: '2026-06-19T06:00:00Z',
    status: 'scheduled',
    orbit: 'LEO',
    payload: 'Kuiper 宽带星座卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-cnsa-sched',
    title: 'CNSA 长征四号丙 · 遥感三十七号',
    provider: 'CASC',
    siteId: 'launch-cn-taiyuan',
    location: { lng: 111.6, lat: 38.85 },
    launchTime: '2026-06-20T02:30:00Z',
    status: 'scheduled',
    orbit: 'SSO',
    payload: '对地遥感卫星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-ariane-sched',
    title: 'Arianespace Ariane 6 · Galileo FOC',
    provider: 'Arianespace',
    siteId: 'launch-eu-kourou',
    location: { lng: -52.77, lat: 5.24 },
    launchTime: '2026-06-22T18:00:00Z',
    status: 'scheduled',
    orbit: 'MEO',
    payload: '伽利略导航卫星双星',
    layerId: 'launch_log',
  },
  {
    id: 'll-2026-06-rocketlab-sched',
    title: 'Rocket Lab Electron · 商业遥感',
    provider: 'Rocket Lab',
    siteId: 'launch-nz-mahia',
    location: { lng: 177.87, lat: -39.26 },
    launchTime: '2026-06-24T21:00:00Z',
    status: 'scheduled',
    orbit: 'LEO',
    payload: '美国商业遥感卫星',
    layerId: 'launch_log',
  },
];
