/**
 * 全球航天发射场档案 — 轨道发射中心与海上发射平台
 *
 * ⚠ 公开资料示意坐标，非精确军事坐标；用于态势图层演示。
 * 来源：各国航天机构公开资料、维基百科与开源情报汇总。
 * 整理日：2026-06-16
 */

import type { ImpactLevel } from '@/types/geo';
import { DENSIFY_LAUNCH_SITES } from './global.layers-densify-r2';

export type LaunchSiteStatus = 'active' | 'retired' | 'planned';
export type LaunchSiteSubKind = 'orbital' | 'civilian' | 'military';

export interface LaunchSitePoint {
  id: string;
  name: string;
  lng: number;
  lat: number;
  operator: string;
  status: LaunchSiteStatus;
  note: string;
  impact: ImpactLevel;
  subKind?: LaunchSiteSubKind;
}

/** 全球主要航天发射场（由 /api/geodata 按区域边界过滤后上屏） */
export const GLOBAL_LAUNCH_SITES: LaunchSitePoint[] = [
  // ── 中国 ──────────────────────────────────────────────────────
  {
    id: 'launch-cn-jiuquan',
    name: '酒泉卫星发射中心',
    lng: 100.29,
    lat: 40.96,
    operator: '中国',
    status: 'active',
    subKind: 'military',
    note: '中国最早、规模最大的航天发射基地，载人航天与深空探测主力',
    impact: 'critical',
  },
  {
    id: 'launch-cn-xichang',
    name: '西昌卫星发射中心',
    lng: 102.03,
    lat: 28.25,
    operator: '中国',
    status: 'active',
    subKind: 'military',
    note: '地球同步轨道卫星主力发射场',
    impact: 'high',
  },
  {
    id: 'launch-cn-taiyuan',
    name: '太原卫星发射中心',
    lng: 111.6,
    lat: 38.85,
    operator: '中国',
    status: 'active',
    subKind: 'military',
    note: '太阳同步轨道与极地轨道卫星发射',
    impact: 'high',
  },
  {
    id: 'launch-cn-wenchang',
    name: '文昌航天发射场',
    lng: 110.95,
    lat: 19.61,
    operator: '中国',
    status: 'active',
    subKind: 'orbital',
    note: '新一代运载火箭（长征五号/七号）主发射场，近赤道优势',
    impact: 'critical',
  },
  {
    id: 'launch-cn-sea',
    name: '海上发射平台（黄海）',
    lng: 121.0,
    lat: 35.2,
    operator: '中国',
    status: 'active',
    subKind: 'orbital',
    note: '长征十一号海上发射任务区域（公开报道海域）',
    impact: 'medium',
  },
  // ── 美国 ──────────────────────────────────────────────────────
  {
    id: 'launch-us-ksc',
    name: '肯尼迪航天中心 / 卡纳维拉尔角',
    lng: -80.6,
    lat: 28.57,
    operator: '美国 NASA/SpaceX',
    status: 'active',
    subKind: 'orbital',
    note: '美国载人航天与商业发射核心枢纽',
    impact: 'critical',
  },
  {
    id: 'launch-us-vandenberg',
    name: '范登堡太空军基地',
    lng: -120.63,
    lat: 34.74,
    operator: '美国',
    status: 'active',
    subKind: 'military',
    note: '极地轨道与导弹预警卫星发射，西海岸战略发射场',
    impact: 'high',
  },
  {
    id: 'launch-us-wallops',
    name: '瓦勒普斯飞行设施',
    lng: -75.48,
    lat: 37.94,
    operator: '美国 NASA',
    status: 'active',
    subKind: 'civilian',
    note: '小型运载火箭与亚轨道科学任务',
    impact: 'medium',
  },
  // ── 俄罗斯 ────────────────────────────────────────────────────
  {
    id: 'launch-ru-baikonur',
    name: '拜科努尔航天发射场',
    lng: 63.34,
    lat: 45.96,
    operator: '俄罗斯/哈萨克斯坦',
    status: 'active',
    subKind: 'orbital',
    note: '联盟号载人飞船与多国商业发射，历史最悠久发射场之一',
    impact: 'critical',
  },
  {
    id: 'launch-ru-plesetsk',
    name: '普列谢茨克航天发射场',
    lng: 40.58,
    lat: 62.93,
    operator: '俄罗斯',
    status: 'active',
    subKind: 'military',
    note: '北极圈附近，军用与导航卫星主力基地',
    impact: 'high',
  },
  {
    id: 'launch-ru-vostochny',
    name: '东方航天发射场',
    lng: 128.17,
    lat: 51.88,
    operator: '俄罗斯',
    status: 'active',
    subKind: 'orbital',
    note: '远东新建发射场，减轻对拜科努尔依赖',
    impact: 'high',
  },
  // ── 欧洲 ──────────────────────────────────────────────────────
  {
    id: 'launch-eu-kourou',
    name: '圭亚那航天中心（库鲁）',
    lng: -52.77,
    lat: 5.24,
    operator: 'ESA/法国',
    status: 'active',
    subKind: 'orbital',
    note: '阿丽亚娜系列与联盟号商业发射，近赤道高载荷优势',
    impact: 'critical',
  },
  {
    id: 'launch-eu-esrange',
    name: '埃斯兰奇航天中心',
    lng: 21.1,
    lat: 67.89,
    operator: '瑞典/ESA',
    status: 'active',
    subKind: 'civilian',
    note: '亚轨道与小型卫星发射，欧洲北部试验场',
    impact: 'medium',
  },
  // ── 印度 ──────────────────────────────────────────────────────
  {
    id: 'launch-in-sriharikota',
    name: '萨迪什·达万航天中心',
    lng: 80.23,
    lat: 13.72,
    operator: '印度 ISRO',
    status: 'active',
    subKind: 'orbital',
    note: '印度航天主力发射场，月探与火星任务起点',
    impact: 'high',
  },
  // ── 日本 ──────────────────────────────────────────────────────
  {
    id: 'launch-jp-tanegashima',
    name: '种子岛宇宙中心',
    lng: 130.97,
    lat: 30.4,
    operator: '日本 JAXA',
    status: 'active',
    subKind: 'orbital',
    note: 'H-IIA/H3 等大型运载火箭主发射场',
    impact: 'high',
  },
  {
    id: 'launch-jp-uchinoura',
    name: '内之浦宇宙空间观测所',
    lng: 131.08,
    lat: 31.25,
    operator: '日本 JAXA',
    status: 'active',
    subKind: 'civilian',
    note: '固体火箭与小型卫星发射',
    impact: 'medium',
  },
  // ── 韩国 ──────────────────────────────────────────────────────
  {
    id: 'launch-kr-naro',
    name: '罗老宇航中心',
    lng: 127.54,
    lat: 34.43,
    operator: '韩国',
    status: 'active',
    subKind: 'orbital',
    note: '韩国自主运载火箭（世界号）发射场',
    impact: 'medium',
  },
  // ── 新西兰 ────────────────────────────────────────────────────
  {
    id: 'launch-nz-mahia',
    name: '马希亚半岛（Rocket Lab）',
    lng: 177.87,
    lat: -39.26,
    operator: '新西兰/Rocket Lab',
    status: 'active',
    subKind: 'civilian',
    note: '电子号小型商业运载火箭高频发射场',
    impact: 'medium',
  },
  // ── 伊朗 ──────────────────────────────────────────────────────
  {
    id: 'launch-ir-semnan',
    name: '塞姆南航天中心',
    lng: 53.92,
    lat: 35.24,
    operator: '伊朗',
    status: 'active',
    subKind: 'military',
    note: '伊朗卫星与运载火箭试验发射（公开报道）',
    impact: 'medium',
  },
  // ── 其他 ──────────────────────────────────────────────────────
  {
    id: 'launch-il-palmachim',
    name: '帕尔马希姆空军基地',
    lng: 34.69,
    lat: 31.89,
    operator: '以色列',
    status: 'active',
    subKind: 'military',
    note: '以色列沙维特运载火箭发射场',
    impact: 'medium',
  },
  {
    id: 'launch-br-alcantara',
    name: '阿尔坎塔拉发射中心',
    lng: -44.37,
    lat: -2.37,
    operator: '巴西',
    status: 'active',
    subKind: 'orbital',
    note: '近赤道发射优势，与多国合作计划',
    impact: 'low',
  },
  {
    id: 'launch-kp-sohae',
    name: '西海卫星发射场',
    lng: 124.67,
    lat: 39.66,
    operator: '朝鲜',
    status: 'active',
    subKind: 'military',
    note: '朝鲜卫星与运载火箭试验场（公开报道）',
    impact: 'high',
  },
  {
    id: 'launch-au-arnhem',
    name: '阿纳姆航天中心',
    lng: 136.82,
    lat: -12.37,
    operator: '澳大利亚/NASA',
    status: 'active',
    subKind: 'civilian',
    note: '商业亚轨道发射与 NASA 合作试验场',
    impact: 'low',
  },
  {
    id: 'launch-cn-haiyang',
    name: '海阳东方航天港',
    lng: 121.16,
    lat: 36.78,
    operator: '中国',
    status: 'active',
    subKind: 'orbital',
    note: '海上固体火箭发射平台（种子/示例）',
    impact: 'medium',
  },
  {
    id: 'launch-uk-saxavord',
    name: '萨克萨沃德航天港',
    lng: -1.33,
    lat: 60.83,
    operator: '英国',
    status: 'planned',
    subKind: 'orbital',
    note: '英国本土垂直发射场规划（种子/示例）',
    impact: 'low',
  },
  {
    id: 'launch-de-bavaria',
    name: '巴伐利亚航天港',
    lng: 11.5,
    lat: 48.3,
    operator: '德国/Isar Aerospace',
    status: 'planned',
    subKind: 'orbital',
    note: '欧洲商业小型火箭发射场（种子/示例）',
    impact: 'low',
  },
  {
    id: 'launch-it-malindi',
    name: '圣马科发射平台',
    lng: 40.19,
    lat: -2.94,
    operator: '意大利/肯尼亚',
    status: 'active',
    subKind: 'orbital',
    note: '海上发射平台，赤道优势（种子/示例）',
    impact: 'low',
  },
  {
    id: 'launch-au-whalers-way',
    name: '捕鲸人路航天港',
    lng: 136.5,
    lat: -12.2,
    operator: '澳大利亚',
    status: 'planned',
    subKind: 'orbital',
    note: '北澳商业发射场规划（种子/示例）',
    impact: 'low',
  },
  ...DENSIFY_LAUNCH_SITES,
];
