import type { Incident } from '@/types/middleeast';

/**
 * 全球视角 · 种子冲突事件数据（用于时间轴/侧边栏/地图图层打通）
 *
 * ⚠ 占位/示例：非实时情报；用于演示 timeRange 与图层筛选效果。
 */
export const GLOBAL_SEED_INCIDENTS: Incident[] = [
  {
    id: 'cn-inc-1',
    title: '东亚航线通行风险上升 · 政治/外交通报',
    date: '2026-06-16T12:15:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 35.68, lng: 139.76 }, // 东京
    description:
      '多方通报显示，东亚外海航线风险溢出上升，部分航司调整安全航道与停靠港计划；市场对运价与船期波动的担忧加剧。',
    source: 'xinhua',
  },
  {
    id: 'cn-inc-2',
    title: '港口装卸节奏波动 · 外交与通行协商消息',
    date: '2026-06-16T09:40:00Z',
    type: 'diplomatic',
    faction: 'iran',
    location: { lat: 22.32, lng: 114.17 }, // 香港
    description:
      '港口与贸易相关方发布协商进展，强调在不影响关键货运的前提下提升通关效率；短期拥堵对供应链的影响逐步显现。',
    source: 'reuters',
  },
  {
    id: 'cn-inc-3',
    title: '海上态势升级 · 关注军事层面的区域安全',
    date: '2026-06-15T18:05:00Z',
    type: 'political',
    faction: 'israel',
    location: { lat: 12.0, lng: 122.8 }, // 中菲海域近海（偏陆架）
    description:
      '多国发布风险提示与海上监测信息，强调区域安全的阶段性变化；相关海事机构呼吁船舶维持警戒。',
    source: 'ap',
  },
  {
    id: 'cn-inc-4',
    title: '极端天气引发的通行协调 · 外交回应',
    date: '2026-06-16T07:55:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 36.10, lng: 115.86 }, // 华北走廊近陆
    description:
      '气象部门与交通协调方发布风险等级更新，要求关键路段与港航企业做好极端天气下的调度与安保。',
    source: 'bbc',
  },
  {
    id: 'cn-inc-5',
    title: '能源与航运价格波动预期上修 · 政治信号',
    date: '2026-06-14T16:20:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 24.7, lng: 46.7 },
    description:
      '能源市场对航运风险溢价的定价上修，部分合约与期货反映更高的短期成本预期。',
    source: 'reuters',
  },
  {
    id: 'cn-inc-6',
    title: '中欧班列通行效率协调 · 外交通报',
    date: '2026-06-16T08:30:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 51.43, lng: 6.76 },
    description: '多国铁路运营商协调口岸通关与运力调配，缩短亚欧陆运周期。',
    source: 'xinhua',
  },
  {
    id: 'cn-inc-7',
    title: '北极航道试航窗口延长 · 航运信号',
    date: '2026-06-15T10:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 72.0, lng: 140.0 },
    description: '北方海路冰期缩短背景下，能源与集装箱试航频次增加。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-8',
    title: '非洲矿产投资安保升级 · 安全通报',
    date: '2026-06-13T14:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: -4.0, lng: 15.0 },
    description: '中资矿业项目加强驻地安保与撤离预案演练。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-9',
    title: '铁矿石发货延迟 · 供应链通报',
    date: '2026-06-16T11:30:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: -31.95, lng: 115.86 },
    description: '西澳港口天气影响装船节奏，短期到港量下调。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-10',
    title: '中欧班列口岸拥堵缓解 · 物流通报',
    date: '2026-06-15T16:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 43.6, lng: 87.6 },
    description: '阿拉山口—霍尔果斯口岸通关效率提升，班列等待时间缩短。',
    source: 'xinhua',
  },
  {
    id: 'cn-inc-11',
    title: '南海渔业执法巡航 · 海上态势',
    date: '2026-06-14T08:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 12.0, lng: 114.0 },
    description: '海警编队开展例行巡航与护渔行动。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-12',
    title: 'LNG 现货采购招标 · 能源信号',
    date: '2026-06-16T15:45:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 31.23, lng: 121.47 },
    description: '多家能源企业发布夏季用气补充采购计划。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-13',
    title: '里海过境协调 · 能源外运通报',
    date: '2026-06-15T11:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 44.0, lng: 51.0 },
    description: '中亚国家就油气管道输送配额举行磋商。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-14',
    title: '西非港口拥堵 · 物流延误',
    date: '2026-06-14T16:30:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 6.45, lng: 3.38 },
    description: '拉各斯港集装箱堆场饱和，船期延误。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-15',
    title: '格陵兰航道试航 · 极地合作信号',
    date: '2026-06-13T10:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 72.0, lng: -42.0 },
    description: '科考船队完成北极航道联合观测任务。',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-jun-1',
    title: '中欧班列西向发运量创新高',
    date: '2026-06-15T08:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 43.82, lng: 87.62 },
    description: '乌鲁木齐集结中心日均发运增长',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-jun-2',
    title: 'RCEP 区域内贸易协定深化',
    date: '2026-06-14T12:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: 1.28, lng: 103.85 },
    description: '东盟—中国自贸区升级谈判进展',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-jun-3',
    title: '中东局势推升进口油气成本',
    date: '2026-06-15T10:00:00Z',
    type: 'political',
    faction: 'cn',
    location: { lat: 26.0, lng: 50.0 },
    description: '炼厂加工利润承压，储备补库加快',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-jun-4',
    title: '金砖扩员后首次经贸部长会议',
    date: '2026-06-13T14:00:00Z',
    type: 'diplomatic',
    faction: 'cn',
    location: { lat: -15.8, lng: -47.9 },
    description: '本币结算与供应链合作议题',
    source: '公开态势整理',
  },
  {
    id: 'cn-inc-jun-5',
    title: '南海渔业执法巡航通报',
    date: '2026-06-12T10:00:00Z',
    type: 'military',
    faction: 'cn',
    location: { lat: 12.0, lng: 114.0 },
    description: '海警舰艇编队例行执法',
    source: '公开态势整理',
  },
];

