/**
 * 第十轮增密 · 地表主题图层 A（2026-06-24）
 *
 * protests / climate / econ_hubs / minerals / datacenters / nuclear_reactors
 * 坐标为公开资料示意位置，非精确/实时数据。整理日：2026-06-24。
 */

import type { ThematicPoint } from './global.thematic';

const T = '2026-06-24T10:00:00Z';
const T2 = '2026-06-23T08:00:00Z';
const T3 = '2026-06-22T16:00:00Z';

export const DENSIFY_PROTESTS_R10: ThematicPoint[] = [
  { id: 'r10-pro-001', name: '北京 · 紧缩政策抗议', layerId: 'protests', lng: 116.31, lat: 39.86, note: '北京爆发紧缩政策相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-002', name: '上海 · 住房危机抗议', layerId: 'protests', lng: 121.41, lat: 31.21, note: '上海爆发住房危机相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-003', name: '东京 · 劳工权益抗议', layerId: 'protests', lng: 139.66, lat: 35.69, note: '东京爆发劳工权益相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-004', name: '首尔 · 选举争议抗议', layerId: 'protests', lng: 126.98, lat: 37.59, note: '首尔爆发选举争议相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-005', name: '新加坡 · 环保诉求抗议', layerId: 'protests', lng: 103.88, lat: 1.32, note: '新加坡爆发环保诉求相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-006', name: '孟买 · 土地征收抗议', layerId: 'protests', lng: 72.93, lat: 19.04, note: '孟买爆发土地征收相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-007', name: '迪拜 · 燃油涨价抗议', layerId: 'protests', lng: 55.36, lat: 25.18, note: '迪拜爆发燃油涨价相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-008', name: '伊斯坦布尔 · 司法改革抗议', layerId: 'protests', lng: 28.92, lat: 41.08, note: '伊斯坦布尔爆发司法改革相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-009', name: '伦敦 · 教育预算抗议', layerId: 'protests', lng: -0.18, lat: 51.52, note: '伦敦爆发教育预算相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-010', name: '巴黎 · 移民政策抗议', layerId: 'protests', lng: 2.32, lat: 48.90, note: '巴黎爆发移民政策相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-011', name: '柏林 · 腐败调查抗议', layerId: 'protests', lng: 13.40, lat: 52.48, note: '柏林爆发腐败调查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-012', name: '莫斯科 · 最低工资抗议', layerId: 'protests', lng: 37.65, lat: 55.73, note: '莫斯科爆发最低工资相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-013', name: '纽约 · 养老金改革抗议', layerId: 'protests', lng: -73.95, lat: 40.71, note: '纽约爆发养老金改革相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-014', name: '华盛顿 · 医疗私有化抗议', layerId: 'protests', lng: -76.95, lat: 38.92, note: '华盛顿爆发医疗私有化相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-015', name: '洛杉矶 · 学生贷款抗议', layerId: 'protests', lng: -118.33, lat: 34.09, note: '洛杉矶爆发学生贷款相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-016', name: '休斯顿 · 警察暴力抗议', layerId: 'protests', lng: -95.42, lat: 29.72, note: '休斯顿爆发警察暴力相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-017', name: '圣保罗 · 性别平等抗议', layerId: 'protests', lng: -46.66, lat: -23.57, note: '圣保罗爆发性别平等相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-018', name: '布宜诺斯艾利斯 · 原住民权利抗议', layerId: 'protests', lng: -58.38, lat: -34.60, note: '布宜诺斯艾利斯爆发原住民权利相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-019', name: '开罗 · 网络审查抗议', layerId: 'protests', lng: 31.27, lat: 30.06, note: '开罗爆发网络审查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-020', name: '拉各斯 · 关税冲击抗议', layerId: 'protests', lng: 3.44, lat: 6.56, note: '拉各斯爆发关税冲击相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-021', name: '内罗毕 · 紧缩政策抗议', layerId: 'protests', lng: 36.91, lat: -1.33, note: '内罗毕爆发紧缩政策相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-022', name: '约翰内斯堡 · 住房危机抗议', layerId: 'protests', lng: 27.96, lat: -26.22, note: '约翰内斯堡爆发住房危机相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-023', name: '悉尼 · 劳工权益抗议', layerId: 'protests', lng: 151.15, lat: -33.87, note: '悉尼爆发劳工权益相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-024', name: '雅加达 · 选举争议抗议', layerId: 'protests', lng: 106.82, lat: -6.19, note: '雅加达爆发选举争议相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-025', name: '曼谷 · 环保诉求抗议', layerId: 'protests', lng: 100.50, lat: 13.79, note: '曼谷爆发环保诉求相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-026', name: '河内 · 土地征收抗议', layerId: 'protests', lng: 105.88, lat: 20.99, note: '河内爆发土地征收相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-027', name: '马尼拉 · 燃油涨价抗议', layerId: 'protests', lng: 121.04, lat: 14.53, note: '马尼拉爆发燃油涨价相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-028', name: '台北 · 司法改革抗议', layerId: 'protests', lng: 121.65, lat: 25.04, note: '台北爆发司法改革相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-029', name: '香港 · 教育预算抗议', layerId: 'protests', lng: 114.07, lat: 22.30, note: '香港爆发教育预算相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-030', name: '利雅得 · 移民政策抗议', layerId: 'protests', lng: 46.66, lat: 24.75, note: '利雅得爆发移民政策相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-031', name: '德黑兰 · 腐败调查抗议', layerId: 'protests', lng: 51.39, lat: 35.65, note: '德黑兰爆发腐败调查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-032', name: '巴格达 · 最低工资抗议', layerId: 'protests', lng: 44.37, lat: 33.29, note: '巴格达爆发最低工资相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-033', name: '基辅 · 养老金改革抗议', layerId: 'protests', lng: 30.55, lat: 50.45, note: '基辅爆发养老金改革相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-034', name: '华沙 · 医疗私有化抗议', layerId: 'protests', lng: 21.07, lat: 52.25, note: '华沙爆发医疗私有化相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-035', name: '罗马 · 学生贷款抗议', layerId: 'protests', lng: 12.59, lat: 41.94, note: '罗马爆发学生贷款相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-036', name: '马德里 · 警察暴力抗议', layerId: 'protests', lng: -3.79, lat: 40.36, note: '马德里爆发警察暴力相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-037', name: '阿姆斯特丹 · 性别平等抗议', layerId: 'protests', lng: 4.84, lat: 52.35, note: '阿姆斯特丹爆发性别平等相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-038', name: '苏黎世 · 原住民权利抗议', layerId: 'protests', lng: 8.51, lat: 47.37, note: '苏黎世爆发原住民权利相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-039', name: '斯德哥尔摩 · 网络审查抗议', layerId: 'protests', lng: 18.07, lat: 59.35, note: '斯德哥尔摩爆发网络审查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-040', name: '赫尔辛基 · 关税冲击抗议', layerId: 'protests', lng: 24.97, lat: 60.21, note: '赫尔辛基爆发关税冲击相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-041', name: '多伦多 · 紧缩政策抗议', layerId: 'protests', lng: -79.32, lat: 43.61, note: '多伦多爆发紧缩政策相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-042', name: '温哥华 · 住房危机抗议', layerId: 'protests', lng: -123.03, lat: 49.26, note: '温哥华爆发住房危机相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-043', name: '墨西哥城 · 劳工权益抗议', layerId: 'protests', lng: -99.22, lat: 19.43, note: '墨西哥城爆发劳工权益相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-044', name: '利马 · 选举争议抗议', layerId: 'protests', lng: -77.10, lat: -12.03, note: '利马爆发选举争议相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-045', name: '波哥大 · 环保诉求抗议', layerId: 'protests', lng: -74.10, lat: 4.75, note: '波哥大爆发环保诉求相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-046', name: '圣地亚哥 · 土地征收抗议', layerId: 'protests', lng: -70.65, lat: -33.49, note: '圣地亚哥爆发土地征收相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-047', name: '卡拉奇 · 燃油涨价抗议', layerId: 'protests', lng: 67.04, lat: 24.84, note: '卡拉奇爆发燃油涨价相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-048', name: '达卡 · 司法改革抗议', layerId: 'protests', lng: 90.47, lat: 23.81, note: '达卡爆发司法改革相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-049', name: '科伦坡 · 教育预算抗议', layerId: 'protests', lng: 79.95, lat: 6.95, note: '科伦坡爆发教育预算相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-050', name: '仰光 · 移民政策抗议', layerId: 'protests', lng: 96.06, lat: 16.91, note: '仰光爆发移民政策相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-051', name: '金边 · 腐败调查抗议', layerId: 'protests', lng: 104.86, lat: 11.52, note: '金边爆发腐败调查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-052', name: '万象 · 最低工资抗议', layerId: 'protests', lng: 102.60, lat: 17.96, note: '万象爆发最低工资相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-053', name: '阿拉木图 · 养老金改革抗议', layerId: 'protests', lng: 76.95, lat: 43.24, note: '阿拉木图爆发养老金改革相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-054', name: '塔什干 · 医疗私有化抗议', layerId: 'protests', lng: 69.27, lat: 41.32, note: '塔什干爆发医疗私有化相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-055', name: '巴库 · 学生贷款抗议', layerId: 'protests', lng: 49.93, lat: 40.45, note: '巴库爆发学生贷款相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-056', name: '第比利斯 · 警察暴力抗议', layerId: 'protests', lng: 44.88, lat: 41.68, note: '第比利斯爆发警察暴力相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-057', name: '基辅 · 性别平等抗议', layerId: 'protests', lng: 30.43, lat: 50.43, note: '基辅爆发性别平等相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-058', name: '明斯克 · 原住民权利抗议', layerId: 'protests', lng: 27.51, lat: 53.90, note: '明斯克爆发原住民权利相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-059', name: '贝尔格莱德 · 网络审查抗议', layerId: 'protests', lng: 20.43, lat: 44.84, note: '贝尔格莱德爆发网络审查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-060', name: '布达佩斯 · 关税冲击抗议', layerId: 'protests', lng: 19.04, lat: 47.54, note: '布达佩斯爆发关税冲击相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-061', name: '布拉格 · 紧缩政策抗议', layerId: 'protests', lng: 14.45, lat: 50.04, note: '布拉格爆发紧缩政策相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-062', name: '维也纳 · 住房危机抗议', layerId: 'protests', lng: 16.43, lat: 48.19, note: '维也纳爆发住房危机相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-063', name: '雅典 · 劳工权益抗议', layerId: 'protests', lng: 23.82, lat: 37.98, note: '雅典爆发劳工权益相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-064', name: '开普敦 · 选举争议抗议', layerId: 'protests', lng: 18.33, lat: -33.90, note: '开普敦爆发选举争议相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-065', name: '卡萨布兰卡 · 环保诉求抗议', layerId: 'protests', lng: -7.68, lat: 33.63, note: '卡萨布兰卡爆发环保诉求相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-066', name: '突尼斯 · 土地征收抗议', layerId: 'protests', lng: 10.15, lat: 36.76, note: '突尼斯爆发土地征收相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-067', name: '喀土穆 · 燃油涨价抗议', layerId: 'protests', lng: 32.50, lat: 15.58, note: '喀土穆爆发燃油涨价相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-068', name: '亚的斯亚贝巴 · 司法改革抗议', layerId: 'protests', lng: 38.77, lat: 9.03, note: '亚的斯亚贝巴爆发司法改革相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
  { id: 'r10-pro-069', name: '金沙萨 · 教育预算抗议', layerId: 'protests', lng: 15.37, lat: -4.30, note: '金沙萨爆发教育预算相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3 },
  { id: 'r10-pro-070', name: '拉各斯 · 移民政策抗议', layerId: 'protests', lng: 3.47, lat: 6.56, note: '拉各斯爆发移民政策相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T },
  { id: 'r10-pro-071', name: '达累斯萨拉姆 · 腐败调查抗议', layerId: 'protests', lng: 39.19, lat: -6.83, note: '达累斯萨拉姆爆发腐败调查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2 },
  { id: 'r10-pro-072', name: '卢萨卡 · 最低工资抗议', layerId: 'protests', lng: 28.23, lat: -15.44, note: '卢萨卡爆发最低工资相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3 },
  { id: 'r10-pro-073', name: '惠灵顿 · 养老金改革抗议', layerId: 'protests', lng: 174.75, lat: -41.29, note: '惠灵顿爆发养老金改革相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T },
  { id: 'r10-pro-074', name: '奥克兰 · 医疗私有化抗议', layerId: 'protests', lng: 174.76, lat: -36.83, note: '奥克兰爆发医疗私有化相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2 },
  { id: 'r10-pro-075', name: '雷克雅未克 · 学生贷款抗议', layerId: 'protests', lng: -21.91, lat: 64.19, note: '雷克雅未克爆发学生贷款相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3 },
  { id: 'r10-pro-076', name: '多哈 · 警察暴力抗议', layerId: 'protests', lng: 51.59, lat: 25.25, note: '多哈爆发警察暴力相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T },
  { id: 'r10-pro-077', name: '麦纳麦 · 性别平等抗议', layerId: 'protests', lng: 50.67, lat: 26.21, note: '麦纳麦爆发性别平等相关示威（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2 },
  { id: 'r10-pro-078', name: '科威特城 · 原住民权利抗议', layerId: 'protests', lng: 47.89, lat: 29.38, note: '科威特城爆发原住民权利相关示威（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3 },
  { id: 'r10-pro-079', name: '马斯喀特 · 网络审查抗议', layerId: 'protests', lng: 58.53, lat: 23.61, note: '马斯喀特爆发网络审查相关示威（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T },
  { id: 'r10-pro-080', name: '安曼 · 关税冲击抗议', layerId: 'protests', lng: 35.90, lat: 31.99, note: '安曼爆发关税冲击相关示威（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2 },
];

export const DENSIFY_CLIMATE_R10: ThematicPoint[] = [
  { id: 'r10-cli-001', name: '北京 · 暴雨洪涝', layerId: 'climate', lng: 116.31, lat: 39.86, note: '北京遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'flood' },
  { id: 'r10-cli-002', name: '上海 · 持续干旱', layerId: 'climate', lng: 121.41, lat: 31.21, note: '上海遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'drought' },
  { id: 'r10-cli-003', name: '东京 · 破纪录高温', layerId: 'climate', lng: 139.66, lat: 35.69, note: '东京遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'heatwave' },
  { id: 'r10-cli-004', name: '首尔 · 野火蔓延', layerId: 'climate', lng: 126.98, lat: 37.59, note: '首尔遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'wildfire' },
  { id: 'r10-cli-005', name: '新加坡 · 强台风逼近', layerId: 'climate', lng: 103.88, lat: 1.32, note: '新加坡遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'storm' },
  { id: 'r10-cli-006', name: '孟买 · 跨境烟霾', layerId: 'climate', lng: 72.93, lat: 19.04, note: '孟买遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'haze' },
  { id: 'r10-cli-007', name: '迪拜 · 冰川消融', layerId: 'climate', lng: 55.36, lat: 25.18, note: '迪拜遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'ice' },
  { id: 'r10-cli-008', name: '伊斯坦布尔 · 极端降雪', layerId: 'climate', lng: 28.92, lat: 41.08, note: '伊斯坦布尔遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'flood' },
  { id: 'r10-cli-009', name: '伦敦 · 海水倒灌', layerId: 'climate', lng: -0.18, lat: 51.52, note: '伦敦遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'drought' },
  { id: 'r10-cli-010', name: '巴黎 · 沙尘暴', layerId: 'climate', lng: 2.32, lat: 48.90, note: '巴黎遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'heatwave' },
  { id: 'r10-cli-011', name: '柏林 · 暴雨洪涝', layerId: 'climate', lng: 13.40, lat: 52.48, note: '柏林遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'wildfire' },
  { id: 'r10-cli-012', name: '莫斯科 · 持续干旱', layerId: 'climate', lng: 37.65, lat: 55.73, note: '莫斯科遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'storm' },
  { id: 'r10-cli-013', name: '纽约 · 破纪录高温', layerId: 'climate', lng: -73.95, lat: 40.71, note: '纽约遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'haze' },
  { id: 'r10-cli-014', name: '华盛顿 · 野火蔓延', layerId: 'climate', lng: -76.95, lat: 38.92, note: '华盛顿遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'ice' },
  { id: 'r10-cli-015', name: '洛杉矶 · 强台风逼近', layerId: 'climate', lng: -118.33, lat: 34.09, note: '洛杉矶遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'flood' },
  { id: 'r10-cli-016', name: '休斯顿 · 跨境烟霾', layerId: 'climate', lng: -95.42, lat: 29.72, note: '休斯顿遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'drought' },
  { id: 'r10-cli-017', name: '圣保罗 · 冰川消融', layerId: 'climate', lng: -46.66, lat: -23.57, note: '圣保罗遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'heatwave' },
  { id: 'r10-cli-018', name: '布宜诺斯艾利斯 · 极端降雪', layerId: 'climate', lng: -58.38, lat: -34.60, note: '布宜诺斯艾利斯遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'wildfire' },
  { id: 'r10-cli-019', name: '开罗 · 海水倒灌', layerId: 'climate', lng: 31.27, lat: 30.06, note: '开罗遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'storm' },
  { id: 'r10-cli-020', name: '拉各斯 · 沙尘暴', layerId: 'climate', lng: 3.44, lat: 6.56, note: '拉各斯遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'haze' },
  { id: 'r10-cli-021', name: '内罗毕 · 暴雨洪涝', layerId: 'climate', lng: 36.91, lat: -1.33, note: '内罗毕遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'ice' },
  { id: 'r10-cli-022', name: '约翰内斯堡 · 持续干旱', layerId: 'climate', lng: 27.96, lat: -26.22, note: '约翰内斯堡遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'flood' },
  { id: 'r10-cli-023', name: '悉尼 · 破纪录高温', layerId: 'climate', lng: 151.15, lat: -33.87, note: '悉尼遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'drought' },
  { id: 'r10-cli-024', name: '雅加达 · 野火蔓延', layerId: 'climate', lng: 106.82, lat: -6.19, note: '雅加达遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'heatwave' },
  { id: 'r10-cli-025', name: '曼谷 · 强台风逼近', layerId: 'climate', lng: 100.50, lat: 13.79, note: '曼谷遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'wildfire' },
  { id: 'r10-cli-026', name: '河内 · 跨境烟霾', layerId: 'climate', lng: 105.88, lat: 20.99, note: '河内遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'storm' },
  { id: 'r10-cli-027', name: '马尼拉 · 冰川消融', layerId: 'climate', lng: 121.04, lat: 14.53, note: '马尼拉遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'haze' },
  { id: 'r10-cli-028', name: '台北 · 极端降雪', layerId: 'climate', lng: 121.65, lat: 25.04, note: '台北遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'ice' },
  { id: 'r10-cli-029', name: '香港 · 海水倒灌', layerId: 'climate', lng: 114.07, lat: 22.30, note: '香港遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'flood' },
  { id: 'r10-cli-030', name: '利雅得 · 沙尘暴', layerId: 'climate', lng: 46.66, lat: 24.75, note: '利雅得遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'drought' },
  { id: 'r10-cli-031', name: '德黑兰 · 暴雨洪涝', layerId: 'climate', lng: 51.39, lat: 35.65, note: '德黑兰遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'heatwave' },
  { id: 'r10-cli-032', name: '巴格达 · 持续干旱', layerId: 'climate', lng: 44.37, lat: 33.29, note: '巴格达遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'wildfire' },
  { id: 'r10-cli-033', name: '基辅 · 破纪录高温', layerId: 'climate', lng: 30.55, lat: 50.45, note: '基辅遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'storm' },
  { id: 'r10-cli-034', name: '华沙 · 野火蔓延', layerId: 'climate', lng: 21.07, lat: 52.25, note: '华沙遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'haze' },
  { id: 'r10-cli-035', name: '罗马 · 强台风逼近', layerId: 'climate', lng: 12.59, lat: 41.94, note: '罗马遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'ice' },
  { id: 'r10-cli-036', name: '马德里 · 跨境烟霾', layerId: 'climate', lng: -3.79, lat: 40.36, note: '马德里遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'flood' },
  { id: 'r10-cli-037', name: '阿姆斯特丹 · 冰川消融', layerId: 'climate', lng: 4.84, lat: 52.35, note: '阿姆斯特丹遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'drought' },
  { id: 'r10-cli-038', name: '苏黎世 · 极端降雪', layerId: 'climate', lng: 8.51, lat: 47.37, note: '苏黎世遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'heatwave' },
  { id: 'r10-cli-039', name: '斯德哥尔摩 · 海水倒灌', layerId: 'climate', lng: 18.07, lat: 59.35, note: '斯德哥尔摩遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'wildfire' },
  { id: 'r10-cli-040', name: '赫尔辛基 · 沙尘暴', layerId: 'climate', lng: 24.97, lat: 60.21, note: '赫尔辛基遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'storm' },
  { id: 'r10-cli-041', name: '多伦多 · 暴雨洪涝', layerId: 'climate', lng: -79.32, lat: 43.61, note: '多伦多遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'haze' },
  { id: 'r10-cli-042', name: '温哥华 · 持续干旱', layerId: 'climate', lng: -123.03, lat: 49.26, note: '温哥华遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'ice' },
  { id: 'r10-cli-043', name: '墨西哥城 · 破纪录高温', layerId: 'climate', lng: -99.22, lat: 19.43, note: '墨西哥城遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'flood' },
  { id: 'r10-cli-044', name: '利马 · 野火蔓延', layerId: 'climate', lng: -77.10, lat: -12.03, note: '利马遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'drought' },
  { id: 'r10-cli-045', name: '波哥大 · 强台风逼近', layerId: 'climate', lng: -74.10, lat: 4.75, note: '波哥大遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'heatwave' },
  { id: 'r10-cli-046', name: '圣地亚哥 · 跨境烟霾', layerId: 'climate', lng: -70.65, lat: -33.49, note: '圣地亚哥遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'wildfire' },
  { id: 'r10-cli-047', name: '卡拉奇 · 冰川消融', layerId: 'climate', lng: 67.04, lat: 24.84, note: '卡拉奇遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'storm' },
  { id: 'r10-cli-048', name: '达卡 · 极端降雪', layerId: 'climate', lng: 90.47, lat: 23.81, note: '达卡遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'haze' },
  { id: 'r10-cli-049', name: '科伦坡 · 海水倒灌', layerId: 'climate', lng: 79.95, lat: 6.95, note: '科伦坡遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'ice' },
  { id: 'r10-cli-050', name: '仰光 · 沙尘暴', layerId: 'climate', lng: 96.06, lat: 16.91, note: '仰光遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'flood' },
  { id: 'r10-cli-051', name: '金边 · 暴雨洪涝', layerId: 'climate', lng: 104.86, lat: 11.52, note: '金边遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'drought' },
  { id: 'r10-cli-052', name: '万象 · 持续干旱', layerId: 'climate', lng: 102.60, lat: 17.96, note: '万象遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'heatwave' },
  { id: 'r10-cli-053', name: '阿拉木图 · 破纪录高温', layerId: 'climate', lng: 76.95, lat: 43.24, note: '阿拉木图遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'wildfire' },
  { id: 'r10-cli-054', name: '塔什干 · 野火蔓延', layerId: 'climate', lng: 69.27, lat: 41.32, note: '塔什干遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'storm' },
  { id: 'r10-cli-055', name: '巴库 · 强台风逼近', layerId: 'climate', lng: 49.93, lat: 40.45, note: '巴库遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'haze' },
  { id: 'r10-cli-056', name: '第比利斯 · 跨境烟霾', layerId: 'climate', lng: 44.88, lat: 41.68, note: '第比利斯遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'ice' },
  { id: 'r10-cli-057', name: '基辅 · 冰川消融', layerId: 'climate', lng: 30.43, lat: 50.43, note: '基辅遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'flood' },
  { id: 'r10-cli-058', name: '明斯克 · 极端降雪', layerId: 'climate', lng: 27.51, lat: 53.90, note: '明斯克遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'drought' },
  { id: 'r10-cli-059', name: '贝尔格莱德 · 海水倒灌', layerId: 'climate', lng: 20.43, lat: 44.84, note: '贝尔格莱德遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'heatwave' },
  { id: 'r10-cli-060', name: '布达佩斯 · 沙尘暴', layerId: 'climate', lng: 19.04, lat: 47.54, note: '布达佩斯遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'wildfire' },
  { id: 'r10-cli-061', name: '布拉格 · 暴雨洪涝', layerId: 'climate', lng: 14.45, lat: 50.04, note: '布拉格遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'storm' },
  { id: 'r10-cli-062', name: '维也纳 · 持续干旱', layerId: 'climate', lng: 16.43, lat: 48.19, note: '维也纳遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'haze' },
  { id: 'r10-cli-063', name: '雅典 · 破纪录高温', layerId: 'climate', lng: 23.82, lat: 37.98, note: '雅典遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'ice' },
  { id: 'r10-cli-064', name: '开普敦 · 野火蔓延', layerId: 'climate', lng: 18.33, lat: -33.90, note: '开普敦遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'flood' },
  { id: 'r10-cli-065', name: '卡萨布兰卡 · 强台风逼近', layerId: 'climate', lng: -7.68, lat: 33.63, note: '卡萨布兰卡遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'drought' },
  { id: 'r10-cli-066', name: '突尼斯 · 跨境烟霾', layerId: 'climate', lng: 10.15, lat: 36.76, note: '突尼斯遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'heatwave' },
  { id: 'r10-cli-067', name: '喀土穆 · 冰川消融', layerId: 'climate', lng: 32.50, lat: 15.58, note: '喀土穆遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'wildfire' },
  { id: 'r10-cli-068', name: '亚的斯亚贝巴 · 极端降雪', layerId: 'climate', lng: 38.77, lat: 9.03, note: '亚的斯亚贝巴遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'storm' },
  { id: 'r10-cli-069', name: '金沙萨 · 海水倒灌', layerId: 'climate', lng: 15.37, lat: -4.30, note: '金沙萨遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T3, subKind: 'haze' },
  { id: 'r10-cli-070', name: '拉各斯 · 沙尘暴', layerId: 'climate', lng: 3.47, lat: 6.56, note: '拉各斯遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T, subKind: 'ice' },
  { id: 'r10-cli-071', name: '达累斯萨拉姆 · 暴雨洪涝', layerId: 'climate', lng: 39.19, lat: -6.83, note: '达累斯萨拉姆遭遇暴雨洪涝（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T2, subKind: 'flood' },
  { id: 'r10-cli-072', name: '卢萨卡 · 持续干旱', layerId: 'climate', lng: 28.23, lat: -15.44, note: '卢萨卡遭遇持续干旱（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T3, subKind: 'drought' },
  { id: 'r10-cli-073', name: '惠灵顿 · 破纪录高温', layerId: 'climate', lng: 174.75, lat: -41.29, note: '惠灵顿遭遇破纪录高温（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T, subKind: 'heatwave' },
  { id: 'r10-cli-074', name: '奥克兰 · 野火蔓延', layerId: 'climate', lng: 174.76, lat: -36.83, note: '奥克兰遭遇野火蔓延（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T2, subKind: 'wildfire' },
  { id: 'r10-cli-075', name: '雷克雅未克 · 强台风逼近', layerId: 'climate', lng: -21.91, lat: 64.19, note: '雷克雅未克遭遇强台风逼近（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T3, subKind: 'storm' },
  { id: 'r10-cli-076', name: '多哈 · 跨境烟霾', layerId: 'climate', lng: 51.59, lat: 25.25, note: '多哈遭遇跨境烟霾（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T, subKind: 'haze' },
  { id: 'r10-cli-077', name: '麦纳麦 · 冰川消融', layerId: 'climate', lng: 50.67, lat: 26.21, note: '麦纳麦遭遇冰川消融（公开资料汇总，示意坐标）', impact: 'low', updatedAt: T2, subKind: 'ice' },
  { id: 'r10-cli-078', name: '科威特城 · 极端降雪', layerId: 'climate', lng: 47.89, lat: 29.38, note: '科威特城遭遇极端降雪（公开资料汇总，示意坐标）', impact: 'medium', updatedAt: T3, subKind: 'flood' },
  { id: 'r10-cli-079', name: '马斯喀特 · 海水倒灌', layerId: 'climate', lng: 58.53, lat: 23.61, note: '马斯喀特遭遇海水倒灌（公开资料汇总，示意坐标）', impact: 'high', updatedAt: T, subKind: 'drought' },
  { id: 'r10-cli-080', name: '安曼 · 沙尘暴', layerId: 'climate', lng: 35.90, lat: 31.99, note: '安曼遭遇沙尘暴（公开资料汇总，示意坐标）', impact: 'critical', updatedAt: T2, subKind: 'heatwave' },
];

export const DENSIFY_ECON_HUBS_R10: ThematicPoint[] = [
  { id: 'r10-hub-001', name: '北京 · 金融节点', layerId: 'econ_hubs', lng: 116.31, lat: 39.86, note: '区域金融枢纽（北京）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-002', name: '上海 · 金融节点', layerId: 'econ_hubs', lng: 121.41, lat: 31.21, note: '离岸中心（上海）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-003', name: '东京 · 金融节点', layerId: 'econ_hubs', lng: 139.66, lat: 35.69, note: '创投生态（东京）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-004', name: '首尔 · 金融节点', layerId: 'econ_hubs', lng: 126.98, lat: 37.59, note: '大宗商品交易（首尔）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-005', name: '新加坡 · 金融节点', layerId: 'econ_hubs', lng: 103.88, lat: 1.32, note: '主权财富基金（新加坡）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-006', name: '孟买 · 金融节点', layerId: 'econ_hubs', lng: 72.93, lat: 19.04, note: '自贸区政策（孟买）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-007', name: '迪拜 · 金融节点', layerId: 'econ_hubs', lng: 55.36, lat: 25.18, note: '跨境支付试点（迪拜）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-008', name: '伊斯坦布尔 · 金融节点', layerId: 'econ_hubs', lng: 28.92, lat: 41.08, note: '绿色债券发行（伊斯坦布尔）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-009', name: '伦敦 · 金融节点', layerId: 'econ_hubs', lng: -0.18, lat: 51.52, note: '数字资产监管沙盒（伦敦）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-010', name: '巴黎 · 金融节点', layerId: 'econ_hubs', lng: 2.32, lat: 48.90, note: '再保险中心（巴黎）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-011', name: '柏林 · 金融节点', layerId: 'econ_hubs', lng: 13.40, lat: 52.48, note: '区域金融枢纽（柏林）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-012', name: '莫斯科 · 金融节点', layerId: 'econ_hubs', lng: 37.65, lat: 55.73, note: '离岸中心（莫斯科）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-013', name: '纽约 · 金融节点', layerId: 'econ_hubs', lng: -73.95, lat: 40.71, note: '创投生态（纽约）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-014', name: '华盛顿 · 金融节点', layerId: 'econ_hubs', lng: -76.95, lat: 38.92, note: '大宗商品交易（华盛顿）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-015', name: '洛杉矶 · 金融节点', layerId: 'econ_hubs', lng: -118.33, lat: 34.09, note: '主权财富基金（洛杉矶）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-016', name: '休斯顿 · 金融节点', layerId: 'econ_hubs', lng: -95.42, lat: 29.72, note: '自贸区政策（休斯顿）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-017', name: '圣保罗 · 金融节点', layerId: 'econ_hubs', lng: -46.66, lat: -23.57, note: '跨境支付试点（圣保罗）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-018', name: '布宜诺斯艾利斯 · 金融节点', layerId: 'econ_hubs', lng: -58.38, lat: -34.60, note: '绿色债券发行（布宜诺斯艾利斯）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-019', name: '开罗 · 金融节点', layerId: 'econ_hubs', lng: 31.27, lat: 30.06, note: '数字资产监管沙盒（开罗）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-020', name: '拉各斯 · 金融节点', layerId: 'econ_hubs', lng: 3.44, lat: 6.56, note: '再保险中心（拉各斯）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-021', name: '内罗毕 · 金融节点', layerId: 'econ_hubs', lng: 36.91, lat: -1.33, note: '区域金融枢纽（内罗毕）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-022', name: '约翰内斯堡 · 金融节点', layerId: 'econ_hubs', lng: 27.96, lat: -26.22, note: '离岸中心（约翰内斯堡）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-023', name: '悉尼 · 金融节点', layerId: 'econ_hubs', lng: 151.15, lat: -33.87, note: '创投生态（悉尼）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-024', name: '雅加达 · 金融节点', layerId: 'econ_hubs', lng: 106.82, lat: -6.19, note: '大宗商品交易（雅加达）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-025', name: '曼谷 · 金融节点', layerId: 'econ_hubs', lng: 100.50, lat: 13.79, note: '主权财富基金（曼谷）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-026', name: '河内 · 金融节点', layerId: 'econ_hubs', lng: 105.88, lat: 20.99, note: '自贸区政策（河内）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-027', name: '马尼拉 · 金融节点', layerId: 'econ_hubs', lng: 121.04, lat: 14.53, note: '跨境支付试点（马尼拉）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-028', name: '台北 · 金融节点', layerId: 'econ_hubs', lng: 121.65, lat: 25.04, note: '绿色债券发行（台北）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-029', name: '香港 · 金融节点', layerId: 'econ_hubs', lng: 114.07, lat: 22.30, note: '数字资产监管沙盒（香港）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-030', name: '利雅得 · 金融节点', layerId: 'econ_hubs', lng: 46.66, lat: 24.75, note: '再保险中心（利雅得）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-031', name: '德黑兰 · 金融节点', layerId: 'econ_hubs', lng: 51.39, lat: 35.65, note: '区域金融枢纽（德黑兰）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-032', name: '巴格达 · 金融节点', layerId: 'econ_hubs', lng: 44.37, lat: 33.29, note: '离岸中心（巴格达）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-033', name: '基辅 · 金融节点', layerId: 'econ_hubs', lng: 30.55, lat: 50.45, note: '创投生态（基辅）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-034', name: '华沙 · 金融节点', layerId: 'econ_hubs', lng: 21.07, lat: 52.25, note: '大宗商品交易（华沙）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-035', name: '罗马 · 金融节点', layerId: 'econ_hubs', lng: 12.59, lat: 41.94, note: '主权财富基金（罗马）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-036', name: '马德里 · 金融节点', layerId: 'econ_hubs', lng: -3.79, lat: 40.36, note: '自贸区政策（马德里）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-037', name: '阿姆斯特丹 · 金融节点', layerId: 'econ_hubs', lng: 4.84, lat: 52.35, note: '跨境支付试点（阿姆斯特丹）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-038', name: '苏黎世 · 金融节点', layerId: 'econ_hubs', lng: 8.51, lat: 47.37, note: '绿色债券发行（苏黎世）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-039', name: '斯德哥尔摩 · 金融节点', layerId: 'econ_hubs', lng: 18.07, lat: 59.35, note: '数字资产监管沙盒（斯德哥尔摩）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-040', name: '赫尔辛基 · 金融节点', layerId: 'econ_hubs', lng: 24.97, lat: 60.21, note: '再保险中心（赫尔辛基）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-041', name: '多伦多 · 金融节点', layerId: 'econ_hubs', lng: -79.32, lat: 43.61, note: '区域金融枢纽（多伦多）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-042', name: '温哥华 · 金融节点', layerId: 'econ_hubs', lng: -123.03, lat: 49.26, note: '离岸中心（温哥华）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-043', name: '墨西哥城 · 金融节点', layerId: 'econ_hubs', lng: -99.22, lat: 19.43, note: '创投生态（墨西哥城）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-044', name: '利马 · 金融节点', layerId: 'econ_hubs', lng: -77.10, lat: -12.03, note: '大宗商品交易（利马）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-045', name: '波哥大 · 金融节点', layerId: 'econ_hubs', lng: -74.10, lat: 4.75, note: '主权财富基金（波哥大）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-046', name: '圣地亚哥 · 金融节点', layerId: 'econ_hubs', lng: -70.65, lat: -33.49, note: '自贸区政策（圣地亚哥）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-047', name: '卡拉奇 · 金融节点', layerId: 'econ_hubs', lng: 67.04, lat: 24.84, note: '跨境支付试点（卡拉奇）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-048', name: '达卡 · 金融节点', layerId: 'econ_hubs', lng: 90.47, lat: 23.81, note: '绿色债券发行（达卡）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-049', name: '科伦坡 · 金融节点', layerId: 'econ_hubs', lng: 79.95, lat: 6.95, note: '数字资产监管沙盒（科伦坡）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-050', name: '仰光 · 金融节点', layerId: 'econ_hubs', lng: 96.06, lat: 16.91, note: '再保险中心（仰光）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-051', name: '金边 · 金融节点', layerId: 'econ_hubs', lng: 104.86, lat: 11.52, note: '区域金融枢纽（金边）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-052', name: '万象 · 金融节点', layerId: 'econ_hubs', lng: 102.60, lat: 17.96, note: '离岸中心（万象）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-053', name: '阿拉木图 · 金融节点', layerId: 'econ_hubs', lng: 76.95, lat: 43.24, note: '创投生态（阿拉木图）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-054', name: '塔什干 · 金融节点', layerId: 'econ_hubs', lng: 69.27, lat: 41.32, note: '大宗商品交易（塔什干）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-055', name: '巴库 · 金融节点', layerId: 'econ_hubs', lng: 49.93, lat: 40.45, note: '主权财富基金（巴库）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-056', name: '第比利斯 · 金融节点', layerId: 'econ_hubs', lng: 44.88, lat: 41.68, note: '自贸区政策（第比利斯）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-057', name: '基辅 · 金融节点', layerId: 'econ_hubs', lng: 30.43, lat: 50.43, note: '跨境支付试点（基辅）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-058', name: '明斯克 · 金融节点', layerId: 'econ_hubs', lng: 27.51, lat: 53.90, note: '绿色债券发行（明斯克）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-059', name: '贝尔格莱德 · 金融节点', layerId: 'econ_hubs', lng: 20.43, lat: 44.84, note: '数字资产监管沙盒（贝尔格莱德）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-060', name: '布达佩斯 · 金融节点', layerId: 'econ_hubs', lng: 19.04, lat: 47.54, note: '再保险中心（布达佩斯）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-061', name: '布拉格 · 金融节点', layerId: 'econ_hubs', lng: 14.45, lat: 50.04, note: '区域金融枢纽（布拉格）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-062', name: '维也纳 · 金融节点', layerId: 'econ_hubs', lng: 16.43, lat: 48.19, note: '离岸中心（维也纳）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-063', name: '雅典 · 金融节点', layerId: 'econ_hubs', lng: 23.82, lat: 37.98, note: '创投生态（雅典）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-064', name: '开普敦 · 金融节点', layerId: 'econ_hubs', lng: 18.33, lat: -33.90, note: '大宗商品交易（开普敦）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-065', name: '卡萨布兰卡 · 金融节点', layerId: 'econ_hubs', lng: -7.68, lat: 33.63, note: '主权财富基金（卡萨布兰卡）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-066', name: '突尼斯 · 金融节点', layerId: 'econ_hubs', lng: 10.15, lat: 36.76, note: '自贸区政策（突尼斯）（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-hub-067', name: '喀土穆 · 金融节点', layerId: 'econ_hubs', lng: 32.50, lat: 15.58, note: '跨境支付试点（喀土穆）（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-hub-068', name: '亚的斯亚贝巴 · 金融节点', layerId: 'econ_hubs', lng: 38.77, lat: 9.03, note: '绿色债券发行（亚的斯亚贝巴）（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-hub-069', name: '金沙萨 · 金融节点', layerId: 'econ_hubs', lng: 15.37, lat: -4.30, note: '数字资产监管沙盒（金沙萨）（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-hub-070', name: '拉各斯 · 金融节点', layerId: 'econ_hubs', lng: 3.47, lat: 6.56, note: '再保险中心（拉各斯）（公开资料汇总，示意坐标）', impact: 'medium' },
];

export const DENSIFY_MINERALS_R10: ThematicPoint[] = [
  { id: 'r10-min-001', name: '北京 · lithium产区', layerId: 'minerals', lng: 116.31, lat: 39.86, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-002', name: '上海 · cobalt产区', layerId: 'minerals', lng: 121.41, lat: 31.21, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-003', name: '东京 · copper产区', layerId: 'minerals', lng: 139.66, lat: 35.69, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-004', name: '首尔 · nickel产区', layerId: 'minerals', lng: 126.98, lat: 37.59, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-005', name: '新加坡 · rare_earth产区', layerId: 'minerals', lng: 103.88, lat: 1.32, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-006', name: '孟买 · iron产区', layerId: 'minerals', lng: 72.93, lat: 19.04, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-007', name: '迪拜 · uranium产区', layerId: 'minerals', lng: 55.36, lat: 25.18, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-008', name: '伊斯坦布尔 · tin产区', layerId: 'minerals', lng: 28.92, lat: 41.08, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-009', name: '伦敦 · bauxite产区', layerId: 'minerals', lng: -0.18, lat: 51.52, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-010', name: '巴黎 · tantalum产区', layerId: 'minerals', lng: 2.32, lat: 48.90, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
  { id: 'r10-min-011', name: '柏林 · graphite产区', layerId: 'minerals', lng: 13.40, lat: 52.48, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'high', subKind: 'graphite' },
  { id: 'r10-min-012', name: '莫斯科 · manganese产区', layerId: 'minerals', lng: 37.65, lat: 55.73, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'manganese' },
  { id: 'r10-min-013', name: '纽约 · lithium产区', layerId: 'minerals', lng: -73.95, lat: 40.71, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-014', name: '华盛顿 · cobalt产区', layerId: 'minerals', lng: -76.95, lat: 38.92, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-015', name: '洛杉矶 · copper产区', layerId: 'minerals', lng: -118.33, lat: 34.09, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-016', name: '休斯顿 · nickel产区', layerId: 'minerals', lng: -95.42, lat: 29.72, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-017', name: '圣保罗 · rare_earth产区', layerId: 'minerals', lng: -46.66, lat: -23.57, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-018', name: '布宜诺斯艾利斯 · iron产区', layerId: 'minerals', lng: -58.38, lat: -34.60, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-019', name: '开罗 · uranium产区', layerId: 'minerals', lng: 31.27, lat: 30.06, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-020', name: '拉各斯 · tin产区', layerId: 'minerals', lng: 3.44, lat: 6.56, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-021', name: '内罗毕 · bauxite产区', layerId: 'minerals', lng: 36.91, lat: -1.33, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-022', name: '约翰内斯堡 · tantalum产区', layerId: 'minerals', lng: 27.96, lat: -26.22, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
  { id: 'r10-min-023', name: '悉尼 · graphite产区', layerId: 'minerals', lng: 151.15, lat: -33.87, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'high', subKind: 'graphite' },
  { id: 'r10-min-024', name: '雅加达 · manganese产区', layerId: 'minerals', lng: 106.82, lat: -6.19, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'manganese' },
  { id: 'r10-min-025', name: '曼谷 · lithium产区', layerId: 'minerals', lng: 100.50, lat: 13.79, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-026', name: '河内 · cobalt产区', layerId: 'minerals', lng: 105.88, lat: 20.99, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-027', name: '马尼拉 · copper产区', layerId: 'minerals', lng: 121.04, lat: 14.53, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-028', name: '台北 · nickel产区', layerId: 'minerals', lng: 121.65, lat: 25.04, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-029', name: '香港 · rare_earth产区', layerId: 'minerals', lng: 114.07, lat: 22.30, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-030', name: '利雅得 · iron产区', layerId: 'minerals', lng: 46.66, lat: 24.75, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-031', name: '德黑兰 · uranium产区', layerId: 'minerals', lng: 51.39, lat: 35.65, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-032', name: '巴格达 · tin产区', layerId: 'minerals', lng: 44.37, lat: 33.29, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-033', name: '基辅 · bauxite产区', layerId: 'minerals', lng: 30.55, lat: 50.45, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-034', name: '华沙 · tantalum产区', layerId: 'minerals', lng: 21.07, lat: 52.25, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
  { id: 'r10-min-035', name: '罗马 · graphite产区', layerId: 'minerals', lng: 12.59, lat: 41.94, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'high', subKind: 'graphite' },
  { id: 'r10-min-036', name: '马德里 · manganese产区', layerId: 'minerals', lng: -3.79, lat: 40.36, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'manganese' },
  { id: 'r10-min-037', name: '阿姆斯特丹 · lithium产区', layerId: 'minerals', lng: 4.84, lat: 52.35, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-038', name: '苏黎世 · cobalt产区', layerId: 'minerals', lng: 8.51, lat: 47.37, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-039', name: '斯德哥尔摩 · copper产区', layerId: 'minerals', lng: 18.07, lat: 59.35, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-040', name: '赫尔辛基 · nickel产区', layerId: 'minerals', lng: 24.97, lat: 60.21, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-041', name: '多伦多 · rare_earth产区', layerId: 'minerals', lng: -79.32, lat: 43.61, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-042', name: '温哥华 · iron产区', layerId: 'minerals', lng: -123.03, lat: 49.26, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-043', name: '墨西哥城 · uranium产区', layerId: 'minerals', lng: -99.22, lat: 19.43, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-044', name: '利马 · tin产区', layerId: 'minerals', lng: -77.10, lat: -12.03, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-045', name: '波哥大 · bauxite产区', layerId: 'minerals', lng: -74.10, lat: 4.75, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-046', name: '圣地亚哥 · tantalum产区', layerId: 'minerals', lng: -70.65, lat: -33.49, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
  { id: 'r10-min-047', name: '卡拉奇 · graphite产区', layerId: 'minerals', lng: 67.04, lat: 24.84, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'high', subKind: 'graphite' },
  { id: 'r10-min-048', name: '达卡 · manganese产区', layerId: 'minerals', lng: 90.47, lat: 23.81, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'manganese' },
  { id: 'r10-min-049', name: '科伦坡 · lithium产区', layerId: 'minerals', lng: 79.95, lat: 6.95, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-050', name: '仰光 · cobalt产区', layerId: 'minerals', lng: 96.06, lat: 16.91, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-051', name: '金边 · copper产区', layerId: 'minerals', lng: 104.86, lat: 11.52, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-052', name: '万象 · nickel产区', layerId: 'minerals', lng: 102.60, lat: 17.96, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-053', name: '阿拉木图 · rare_earth产区', layerId: 'minerals', lng: 76.95, lat: 43.24, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-054', name: '塔什干 · iron产区', layerId: 'minerals', lng: 69.27, lat: 41.32, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-055', name: '巴库 · uranium产区', layerId: 'minerals', lng: 49.93, lat: 40.45, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-056', name: '第比利斯 · tin产区', layerId: 'minerals', lng: 44.88, lat: 41.68, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-057', name: '基辅 · bauxite产区', layerId: 'minerals', lng: 30.43, lat: 50.43, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-058', name: '明斯克 · tantalum产区', layerId: 'minerals', lng: 27.51, lat: 53.90, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
  { id: 'r10-min-059', name: '贝尔格莱德 · graphite产区', layerId: 'minerals', lng: 20.43, lat: 44.84, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'graphite' },
  { id: 'r10-min-060', name: '布达佩斯 · manganese产区', layerId: 'minerals', lng: 19.04, lat: 47.54, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'manganese' },
  { id: 'r10-min-061', name: '布拉格 · lithium产区', layerId: 'minerals', lng: 14.45, lat: 50.04, note: '战略矿产开发加速（公开资料汇总，示意坐标）', impact: 'low', subKind: 'lithium' },
  { id: 'r10-min-062', name: '维也纳 · cobalt产区', layerId: 'minerals', lng: 16.43, lat: 48.19, note: '中资/美资投资争议（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'cobalt' },
  { id: 'r10-min-063', name: '雅典 · copper产区', layerId: 'minerals', lng: 23.82, lat: 37.98, note: '环保许可受阻（公开资料汇总，示意坐标）', impact: 'high', subKind: 'copper' },
  { id: 'r10-min-064', name: '开普敦 · nickel产区', layerId: 'minerals', lng: 18.33, lat: -33.90, note: '出口配额调整（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'nickel' },
  { id: 'r10-min-065', name: '卡萨布兰卡 · rare_earth产区', layerId: 'minerals', lng: -7.68, lat: 33.63, note: '冲突矿产监管（公开资料汇总，示意坐标）', impact: 'low', subKind: 'rare_earth' },
  { id: 'r10-min-066', name: '突尼斯 · iron产区', layerId: 'minerals', lng: 10.15, lat: 36.76, note: '精炼产能扩张（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'iron' },
  { id: 'r10-min-067', name: '喀土穆 · uranium产区', layerId: 'minerals', lng: 32.50, lat: 15.58, note: '勘探权拍卖（公开资料汇总，示意坐标）', impact: 'high', subKind: 'uranium' },
  { id: 'r10-min-068', name: '亚的斯亚贝巴 · tin产区', layerId: 'minerals', lng: 38.77, lat: 9.03, note: '社区抗议封锁（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'tin' },
  { id: 'r10-min-069', name: '金沙萨 · bauxite产区', layerId: 'minerals', lng: 15.37, lat: -4.30, note: '供应链重组节点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'bauxite' },
  { id: 'r10-min-070', name: '拉各斯 · tantalum产区', layerId: 'minerals', lng: 3.47, lat: 6.56, note: '库存战略储备（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'tantalum' },
];

export const DENSIFY_DATACENTERS_R10: ThematicPoint[] = [
  { id: 'r10-dc-001', name: '北京 · 算力节点', layerId: 'datacenters', lng: 116.31, lat: 39.86, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-002', name: '上海 · 算力节点', layerId: 'datacenters', lng: 121.41, lat: 31.21, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-003', name: '东京 · 算力节点', layerId: 'datacenters', lng: 139.66, lat: 35.69, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-004', name: '首尔 · 算力节点', layerId: 'datacenters', lng: 126.98, lat: 37.59, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-005', name: '新加坡 · 算力节点', layerId: 'datacenters', lng: 103.88, lat: 1.32, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-006', name: '孟买 · 算力节点', layerId: 'datacenters', lng: 72.93, lat: 19.04, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-007', name: '迪拜 · 算力节点', layerId: 'datacenters', lng: 55.36, lat: 25.18, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-008', name: '伊斯坦布尔 · 算力节点', layerId: 'datacenters', lng: 28.92, lat: 41.08, note: '超算中心（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-009', name: '伦敦 · 算力节点', layerId: 'datacenters', lng: -0.18, lat: 51.52, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-010', name: '巴黎 · 算力节点', layerId: 'datacenters', lng: 2.32, lat: 48.90, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-011', name: '柏林 · 算力节点', layerId: 'datacenters', lng: 13.40, lat: 52.48, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-012', name: '莫斯科 · 算力节点', layerId: 'datacenters', lng: 37.65, lat: 55.73, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-013', name: '纽约 · 算力节点', layerId: 'datacenters', lng: -73.95, lat: 40.71, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-014', name: '华盛顿 · 算力节点', layerId: 'datacenters', lng: -76.95, lat: 38.92, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-015', name: '洛杉矶 · 算力节点', layerId: 'datacenters', lng: -118.33, lat: 34.09, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-016', name: '休斯顿 · 算力节点', layerId: 'datacenters', lng: -95.42, lat: 29.72, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-017', name: '圣保罗 · 算力节点', layerId: 'datacenters', lng: -46.66, lat: -23.57, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-018', name: '布宜诺斯艾利斯 · 算力节点', layerId: 'datacenters', lng: -58.38, lat: -34.60, note: '超算中心（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-019', name: '开罗 · 算力节点', layerId: 'datacenters', lng: 31.27, lat: 30.06, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-020', name: '拉各斯 · 算力节点', layerId: 'datacenters', lng: 3.44, lat: 6.56, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-021', name: '内罗毕 · 算力节点', layerId: 'datacenters', lng: 36.91, lat: -1.33, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-022', name: '约翰内斯堡 · 算力节点', layerId: 'datacenters', lng: 27.96, lat: -26.22, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-023', name: '悉尼 · 算力节点', layerId: 'datacenters', lng: 151.15, lat: -33.87, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-024', name: '雅加达 · 算力节点', layerId: 'datacenters', lng: 106.82, lat: -6.19, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-025', name: '曼谷 · 算力节点', layerId: 'datacenters', lng: 100.50, lat: 13.79, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-026', name: '河内 · 算力节点', layerId: 'datacenters', lng: 105.88, lat: 20.99, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-027', name: '马尼拉 · 算力节点', layerId: 'datacenters', lng: 121.04, lat: 14.53, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-028', name: '台北 · 算力节点', layerId: 'datacenters', lng: 121.65, lat: 25.04, note: '超算中心（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-029', name: '香港 · 算力节点', layerId: 'datacenters', lng: 114.07, lat: 22.30, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-030', name: '利雅得 · 算力节点', layerId: 'datacenters', lng: 46.66, lat: 24.75, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-031', name: '德黑兰 · 算力节点', layerId: 'datacenters', lng: 51.39, lat: 35.65, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-032', name: '巴格达 · 算力节点', layerId: 'datacenters', lng: 44.37, lat: 33.29, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-033', name: '基辅 · 算力节点', layerId: 'datacenters', lng: 30.55, lat: 50.45, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-034', name: '华沙 · 算力节点', layerId: 'datacenters', lng: 21.07, lat: 52.25, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-035', name: '罗马 · 算力节点', layerId: 'datacenters', lng: 12.59, lat: 41.94, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-036', name: '马德里 · 算力节点', layerId: 'datacenters', lng: -3.79, lat: 40.36, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-037', name: '阿姆斯特丹 · 算力节点', layerId: 'datacenters', lng: 4.84, lat: 52.35, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-038', name: '苏黎世 · 算力节点', layerId: 'datacenters', lng: 8.51, lat: 47.37, note: '超算中心（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-039', name: '斯德哥尔摩 · 算力节点', layerId: 'datacenters', lng: 18.07, lat: 59.35, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-040', name: '赫尔辛基 · 算力节点', layerId: 'datacenters', lng: 24.97, lat: 60.21, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-041', name: '多伦多 · 算力节点', layerId: 'datacenters', lng: -79.32, lat: 43.61, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-042', name: '温哥华 · 算力节点', layerId: 'datacenters', lng: -123.03, lat: 49.26, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-043', name: '墨西哥城 · 算力节点', layerId: 'datacenters', lng: -99.22, lat: 19.43, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-044', name: '利马 · 算力节点', layerId: 'datacenters', lng: -77.10, lat: -12.03, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-045', name: '波哥大 · 算力节点', layerId: 'datacenters', lng: -74.10, lat: 4.75, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-046', name: '圣地亚哥 · 算力节点', layerId: 'datacenters', lng: -70.65, lat: -33.49, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-047', name: '卡拉奇 · 算力节点', layerId: 'datacenters', lng: 67.04, lat: 24.84, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-048', name: '达卡 · 算力节点', layerId: 'datacenters', lng: 90.47, lat: 23.81, note: '超算中心（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-049', name: '科伦坡 · 算力节点', layerId: 'datacenters', lng: 79.95, lat: 6.95, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-050', name: '仰光 · 算力节点', layerId: 'datacenters', lng: 96.06, lat: 16.91, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-051', name: '金边 · 算力节点', layerId: 'datacenters', lng: 104.86, lat: 11.52, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-052', name: '万象 · 算力节点', layerId: 'datacenters', lng: 102.60, lat: 17.96, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-053', name: '阿拉木图 · 算力节点', layerId: 'datacenters', lng: 76.95, lat: 43.24, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-054', name: '塔什干 · 算力节点', layerId: 'datacenters', lng: 69.27, lat: 41.32, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-055', name: '巴库 · 算力节点', layerId: 'datacenters', lng: 49.93, lat: 40.45, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-056', name: '第比利斯 · 算力节点', layerId: 'datacenters', lng: 44.88, lat: 41.68, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-057', name: '基辅 · 算力节点', layerId: 'datacenters', lng: 30.43, lat: 50.43, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-058', name: '明斯克 · 算力节点', layerId: 'datacenters', lng: 27.51, lat: 53.90, note: '超算中心（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-059', name: '贝尔格莱德 · 算力节点', layerId: 'datacenters', lng: 20.43, lat: 44.84, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-060', name: '布达佩斯 · 算力节点', layerId: 'datacenters', lng: 19.04, lat: 47.54, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-061', name: '布拉格 · 算力节点', layerId: 'datacenters', lng: 14.45, lat: 50.04, note: 'AI训练集群（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-062', name: '维也纳 · 算力节点', layerId: 'datacenters', lng: 16.43, lat: 48.19, note: '云主权合规节点（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-063', name: '雅典 · 算力节点', layerId: 'datacenters', lng: 23.82, lat: 37.98, note: '边缘推理中心（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-064', name: '开普敦 · 算力节点', layerId: 'datacenters', lng: 18.33, lat: -33.90, note: '灾备双活机房（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-065', name: '卡萨布兰卡 · 算力节点', layerId: 'datacenters', lng: -7.68, lat: 33.63, note: '液冷试点园区（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-066', name: '突尼斯 · 算力节点', layerId: 'datacenters', lng: 10.15, lat: 36.76, note: '绿电PPA签约（公开资料汇总，示意坐标）', impact: 'medium' },
  { id: 'r10-dc-067', name: '喀土穆 · 算力节点', layerId: 'datacenters', lng: 32.50, lat: 15.58, note: '跨境数据枢纽（公开资料汇总，示意坐标）', impact: 'high' },
  { id: 'r10-dc-068', name: '亚的斯亚贝巴 · 算力节点', layerId: 'datacenters', lng: 38.77, lat: 9.03, note: '超算中心（公开资料汇总，示意坐标）', impact: 'critical' },
  { id: 'r10-dc-069', name: '金沙萨 · 算力节点', layerId: 'datacenters', lng: 15.37, lat: -4.30, note: '量子计算试点（公开资料汇总，示意坐标）', impact: 'low' },
  { id: 'r10-dc-070', name: '拉各斯 · 算力节点', layerId: 'datacenters', lng: 3.47, lat: 6.56, note: '游戏/流媒体CDN（公开资料汇总，示意坐标）', impact: 'medium' },
];

export const DENSIFY_NUCLEAR_R10: ThematicPoint[] = [
  { id: 'r10-npp-001', name: '北京 · 核电项目', layerId: 'nuclear_reactors', lng: 116.31, lat: 39.86, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'mega' },
  { id: 'r10-npp-002', name: '上海 · 核电项目', layerId: 'nuclear_reactors', lng: 121.41, lat: 31.21, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'large' },
  { id: 'r10-npp-003', name: '东京 · 核电项目', layerId: 'nuclear_reactors', lng: 139.66, lat: 35.69, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'small' },
  { id: 'r10-npp-004', name: '首尔 · 核电项目', layerId: 'nuclear_reactors', lng: 126.98, lat: 37.59, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'mega' },
  { id: 'r10-npp-005', name: '新加坡 · 核电项目', layerId: 'nuclear_reactors', lng: 103.88, lat: 1.32, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'large' },
  { id: 'r10-npp-006', name: '孟买 · 核电项目', layerId: 'nuclear_reactors', lng: 72.93, lat: 19.04, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'small' },
  { id: 'r10-npp-007', name: '迪拜 · 核电项目', layerId: 'nuclear_reactors', lng: 55.36, lat: 25.18, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'mega' },
  { id: 'r10-npp-008', name: '伊斯坦布尔 · 核电项目', layerId: 'nuclear_reactors', lng: 28.92, lat: 41.08, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'large' },
  { id: 'r10-npp-009', name: '伦敦 · 核电项目', layerId: 'nuclear_reactors', lng: -0.18, lat: 51.52, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'small' },
  { id: 'r10-npp-010', name: '巴黎 · 核电项目', layerId: 'nuclear_reactors', lng: 2.32, lat: 48.90, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'mega' },
  { id: 'r10-npp-011', name: '柏林 · 核电项目', layerId: 'nuclear_reactors', lng: 13.40, lat: 52.48, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'large' },
  { id: 'r10-npp-012', name: '莫斯科 · 核电项目', layerId: 'nuclear_reactors', lng: 37.65, lat: 55.73, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'small' },
  { id: 'r10-npp-013', name: '纽约 · 核电项目', layerId: 'nuclear_reactors', lng: -73.95, lat: 40.71, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'mega' },
  { id: 'r10-npp-014', name: '华盛顿 · 核电项目', layerId: 'nuclear_reactors', lng: -76.95, lat: 38.92, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'large' },
  { id: 'r10-npp-015', name: '洛杉矶 · 核电项目', layerId: 'nuclear_reactors', lng: -118.33, lat: 34.09, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'small' },
  { id: 'r10-npp-016', name: '休斯顿 · 核电项目', layerId: 'nuclear_reactors', lng: -95.42, lat: 29.72, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'mega' },
  { id: 'r10-npp-017', name: '圣保罗 · 核电项目', layerId: 'nuclear_reactors', lng: -46.66, lat: -23.57, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'large' },
  { id: 'r10-npp-018', name: '布宜诺斯艾利斯 · 核电项目', layerId: 'nuclear_reactors', lng: -58.38, lat: -34.60, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'small' },
  { id: 'r10-npp-019', name: '开罗 · 核电项目', layerId: 'nuclear_reactors', lng: 31.27, lat: 30.06, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'mega' },
  { id: 'r10-npp-020', name: '拉各斯 · 核电项目', layerId: 'nuclear_reactors', lng: 3.44, lat: 6.56, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'large' },
  { id: 'r10-npp-021', name: '内罗毕 · 核电项目', layerId: 'nuclear_reactors', lng: 36.91, lat: -1.33, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'small' },
  { id: 'r10-npp-022', name: '约翰内斯堡 · 核电项目', layerId: 'nuclear_reactors', lng: 27.96, lat: -26.22, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'mega' },
  { id: 'r10-npp-023', name: '悉尼 · 核电项目', layerId: 'nuclear_reactors', lng: 151.15, lat: -33.87, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'large' },
  { id: 'r10-npp-024', name: '雅加达 · 核电项目', layerId: 'nuclear_reactors', lng: 106.82, lat: -6.19, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'small' },
  { id: 'r10-npp-025', name: '曼谷 · 核电项目', layerId: 'nuclear_reactors', lng: 100.50, lat: 13.79, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'mega' },
  { id: 'r10-npp-026', name: '河内 · 核电项目', layerId: 'nuclear_reactors', lng: 105.88, lat: 20.99, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'large' },
  { id: 'r10-npp-027', name: '马尼拉 · 核电项目', layerId: 'nuclear_reactors', lng: 121.04, lat: 14.53, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'high', subKind: 'small' },
  { id: 'r10-npp-028', name: '台北 · 核电项目', layerId: 'nuclear_reactors', lng: 121.65, lat: 25.04, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'critical', subKind: 'mega' },
  { id: 'r10-npp-029', name: '香港 · 核电项目', layerId: 'nuclear_reactors', lng: 114.07, lat: 22.30, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'low', subKind: 'large' },
  { id: 'r10-npp-030', name: '利雅得 · 核电项目', layerId: 'nuclear_reactors', lng: 46.66, lat: 24.75, note: '核电扩建/新建项目监测点（公开资料汇总，示意坐标）', impact: 'medium', subKind: 'small' },
];
