/**
 * 第十轮增密 · 产业链/供应链图层（2026-06-24）
 * aerospace_mfg / defense_mfg / semi_supply / chemicals
 */

import type { ThematicPoint } from './global.thematic';

export const DENSIFY_AEROSPACE_MFG_R10: ThematicPoint[] = [
  { id: 'r10-am-001', name: '多伦多 · 无人机总装', layerId: 'aerospace_mfg', lng: -79.38, lat: 43.65, note: '无人机总装节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-002', name: '温哥华 · MRO维修', layerId: 'aerospace_mfg', lng: -123.10, lat: 49.29, note: 'MRO维修节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-003', name: '墨西哥城 · 起落架系统', layerId: 'aerospace_mfg', lng: -99.09, lat: 19.45, note: '起落架系统节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-004', name: '利马 · 航电集成', layerId: 'aerospace_mfg', lng: -76.98, lat: -12.02, note: '航电集成节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-005', name: '波哥大 · 复合材料', layerId: 'aerospace_mfg', lng: -73.99, lat: 4.75, note: '复合材料节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-006', name: '圣地亚哥 · 发动机部件', layerId: 'aerospace_mfg', lng: -70.55, lat: -33.40, note: '发动机部件节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-007', name: '卡拉奇 · 无人机总装', layerId: 'aerospace_mfg', lng: 67.13, lat: 24.92, note: '无人机总装节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-008', name: '达卡 · MRO维修', layerId: 'aerospace_mfg', lng: 90.55, lat: 23.88, note: 'MRO维修节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-009', name: '科伦坡 · 起落架系统', layerId: 'aerospace_mfg', lng: 80.02, lat: 7.01, note: '起落架系统节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-010', name: '仰光 · 航电集成', layerId: 'aerospace_mfg', lng: 96.33, lat: 16.96, note: '航电集成节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-011', name: '金边 · 复合材料', layerId: 'aerospace_mfg', lng: 105.12, lat: 11.66, note: '复合材料节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-012', name: '万象 · 发动机部件', layerId: 'aerospace_mfg', lng: 102.85, lat: 18.09, note: '发动机部件节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-013', name: '阿拉木图 · 无人机总装', layerId: 'aerospace_mfg', lng: 77.19, lat: 43.36, note: '无人机总装节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-014', name: '塔什干 · MRO维修', layerId: 'aerospace_mfg', lng: 69.50, lat: 41.43, note: 'MRO维修节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-015', name: '巴库 · 起落架系统', layerId: 'aerospace_mfg', lng: 50.15, lat: 40.55, note: '起落架系统节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-016', name: '第比利斯 · 航电集成', layerId: 'aerospace_mfg', lng: 45.09, lat: 41.87, note: '航电集成节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-017', name: '基辅 · 复合材料', layerId: 'aerospace_mfg', lng: 30.84, lat: 50.61, note: '复合材料节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-018', name: '明斯克 · 发动机部件', layerId: 'aerospace_mfg', lng: 27.91, lat: 54.07, note: '发动机部件节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-019', name: '贝尔格莱德 · 无人机总装', layerId: 'aerospace_mfg', lng: 20.82, lat: 45.00, note: '无人机总装节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-020', name: '布达佩斯 · MRO维修', layerId: 'aerospace_mfg', lng: 19.42, lat: 47.69, note: 'MRO维修节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-021', name: '布拉格 · 起落架系统', layerId: 'aerospace_mfg', lng: 14.82, lat: 50.28, note: '起落架系统节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-022', name: '维也纳 · 航电集成', layerId: 'aerospace_mfg', lng: 16.79, lat: 48.42, note: '航电集成节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-023', name: '雅典 · 复合材料', layerId: 'aerospace_mfg', lng: 24.17, lat: 38.20, note: '复合材料节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-024', name: '开普敦 · 发动机部件', layerId: 'aerospace_mfg', lng: 18.88, lat: -33.69, note: '发动机部件节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-025', name: '卡萨布兰卡 · 无人机总装', layerId: 'aerospace_mfg', lng: -7.14, lat: 33.83, note: '无人机总装节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-026', name: '突尼斯 · MRO维修', layerId: 'aerospace_mfg', lng: 10.68, lat: 37.05, note: 'MRO维修节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
  { id: 'r10-am-027', name: '喀土穆 · 起落架系统', layerId: 'aerospace_mfg', lng: 33.02, lat: 15.86, note: '起落架系统节点（公开资料汇总）', impact: 'high', subKind: 'airframer' },
  { id: 'r10-am-028', name: '亚的斯亚贝巴 · 航电集成', layerId: 'aerospace_mfg', lng: 39.28, lat: 9.30, note: '航电集成节点（公开资料汇总）', impact: 'critical', subKind: 'supplier' },
  { id: 'r10-am-029', name: '金沙萨 · 复合材料', layerId: 'aerospace_mfg', lng: 15.87, lat: -4.04, note: '复合材料节点（公开资料汇总）', impact: 'low', subKind: 'airframer' },
  { id: 'r10-am-030', name: '拉各斯 · 发动机部件', layerId: 'aerospace_mfg', lng: 3.96, lat: 6.81, note: '发动机部件节点（公开资料汇总）', impact: 'medium', subKind: 'supplier' },
];

export const DENSIFY_DEFENSE_MFG_R10: ThematicPoint[] = [
  { id: 'r10-dm-001', name: '多伦多 · 导弹工厂', layerId: 'defense_mfg', lng: -79.38, lat: 43.65, note: '导弹工厂节点（公开资料汇总）', impact: 'low', subKind: 'missiles' },
  { id: 'r10-dm-002', name: '温哥华 · 坦克总装', layerId: 'defense_mfg', lng: -123.10, lat: 49.29, note: '坦克总装节点（公开资料汇总）', impact: 'medium', subKind: 'prime' },
  { id: 'r10-dm-003', name: '墨西哥城 · 雷达电子', layerId: 'defense_mfg', lng: -99.09, lat: 19.45, note: '雷达电子节点（公开资料汇总）', impact: 'high', subKind: 'shipyard' },
  { id: 'r10-dm-004', name: '利马 · 护卫舰建造', layerId: 'defense_mfg', lng: -76.98, lat: -12.02, note: '护卫舰建造节点（公开资料汇总）', impact: 'critical', subKind: 'missiles' },
  { id: 'r10-dm-005', name: '波哥大 · 弹药产线', layerId: 'defense_mfg', lng: -73.99, lat: 4.75, note: '弹药产线节点（公开资料汇总）', impact: 'low', subKind: 'prime' },
  { id: 'r10-dm-006', name: '圣地亚哥 · 防空系统', layerId: 'defense_mfg', lng: -70.55, lat: -33.40, note: '防空系统节点（公开资料汇总）', impact: 'medium', subKind: 'shipyard' },
  { id: 'r10-dm-007', name: '卡拉奇 · 导弹工厂', layerId: 'defense_mfg', lng: 67.13, lat: 24.92, note: '导弹工厂节点（公开资料汇总）', impact: 'high', subKind: 'missiles' },
  { id: 'r10-dm-008', name: '达卡 · 坦克总装', layerId: 'defense_mfg', lng: 90.55, lat: 23.88, note: '坦克总装节点（公开资料汇总）', impact: 'critical', subKind: 'prime' },
  { id: 'r10-dm-009', name: '科伦坡 · 雷达电子', layerId: 'defense_mfg', lng: 80.02, lat: 7.01, note: '雷达电子节点（公开资料汇总）', impact: 'low', subKind: 'shipyard' },
  { id: 'r10-dm-010', name: '仰光 · 护卫舰建造', layerId: 'defense_mfg', lng: 96.33, lat: 16.96, note: '护卫舰建造节点（公开资料汇总）', impact: 'medium', subKind: 'missiles' },
  { id: 'r10-dm-011', name: '金边 · 弹药产线', layerId: 'defense_mfg', lng: 105.12, lat: 11.66, note: '弹药产线节点（公开资料汇总）', impact: 'high', subKind: 'prime' },
  { id: 'r10-dm-012', name: '万象 · 防空系统', layerId: 'defense_mfg', lng: 102.85, lat: 18.09, note: '防空系统节点（公开资料汇总）', impact: 'critical', subKind: 'shipyard' },
  { id: 'r10-dm-013', name: '阿拉木图 · 导弹工厂', layerId: 'defense_mfg', lng: 77.19, lat: 43.36, note: '导弹工厂节点（公开资料汇总）', impact: 'low', subKind: 'missiles' },
  { id: 'r10-dm-014', name: '塔什干 · 坦克总装', layerId: 'defense_mfg', lng: 69.50, lat: 41.43, note: '坦克总装节点（公开资料汇总）', impact: 'medium', subKind: 'prime' },
  { id: 'r10-dm-015', name: '巴库 · 雷达电子', layerId: 'defense_mfg', lng: 50.15, lat: 40.55, note: '雷达电子节点（公开资料汇总）', impact: 'high', subKind: 'shipyard' },
  { id: 'r10-dm-016', name: '第比利斯 · 护卫舰建造', layerId: 'defense_mfg', lng: 45.09, lat: 41.87, note: '护卫舰建造节点（公开资料汇总）', impact: 'critical', subKind: 'missiles' },
  { id: 'r10-dm-017', name: '基辅 · 弹药产线', layerId: 'defense_mfg', lng: 30.84, lat: 50.61, note: '弹药产线节点（公开资料汇总）', impact: 'low', subKind: 'prime' },
  { id: 'r10-dm-018', name: '明斯克 · 防空系统', layerId: 'defense_mfg', lng: 27.91, lat: 54.07, note: '防空系统节点（公开资料汇总）', impact: 'medium', subKind: 'shipyard' },
  { id: 'r10-dm-019', name: '贝尔格莱德 · 导弹工厂', layerId: 'defense_mfg', lng: 20.82, lat: 45.00, note: '导弹工厂节点（公开资料汇总）', impact: 'high', subKind: 'missiles' },
  { id: 'r10-dm-020', name: '布达佩斯 · 坦克总装', layerId: 'defense_mfg', lng: 19.42, lat: 47.69, note: '坦克总装节点（公开资料汇总）', impact: 'critical', subKind: 'prime' },
  { id: 'r10-dm-021', name: '布拉格 · 雷达电子', layerId: 'defense_mfg', lng: 14.82, lat: 50.28, note: '雷达电子节点（公开资料汇总）', impact: 'low', subKind: 'shipyard' },
  { id: 'r10-dm-022', name: '维也纳 · 护卫舰建造', layerId: 'defense_mfg', lng: 16.79, lat: 48.42, note: '护卫舰建造节点（公开资料汇总）', impact: 'medium', subKind: 'missiles' },
  { id: 'r10-dm-023', name: '雅典 · 弹药产线', layerId: 'defense_mfg', lng: 24.17, lat: 38.20, note: '弹药产线节点（公开资料汇总）', impact: 'high', subKind: 'prime' },
  { id: 'r10-dm-024', name: '开普敦 · 防空系统', layerId: 'defense_mfg', lng: 18.88, lat: -33.69, note: '防空系统节点（公开资料汇总）', impact: 'critical', subKind: 'shipyard' },
  { id: 'r10-dm-025', name: '卡萨布兰卡 · 导弹工厂', layerId: 'defense_mfg', lng: -7.14, lat: 33.83, note: '导弹工厂节点（公开资料汇总）', impact: 'low', subKind: 'missiles' },
  { id: 'r10-dm-026', name: '突尼斯 · 坦克总装', layerId: 'defense_mfg', lng: 10.68, lat: 37.05, note: '坦克总装节点（公开资料汇总）', impact: 'medium', subKind: 'prime' },
  { id: 'r10-dm-027', name: '喀土穆 · 雷达电子', layerId: 'defense_mfg', lng: 33.02, lat: 15.86, note: '雷达电子节点（公开资料汇总）', impact: 'high', subKind: 'shipyard' },
  { id: 'r10-dm-028', name: '亚的斯亚贝巴 · 护卫舰建造', layerId: 'defense_mfg', lng: 39.28, lat: 9.30, note: '护卫舰建造节点（公开资料汇总）', impact: 'critical', subKind: 'missiles' },
  { id: 'r10-dm-029', name: '金沙萨 · 弹药产线', layerId: 'defense_mfg', lng: 15.87, lat: -4.04, note: '弹药产线节点（公开资料汇总）', impact: 'low', subKind: 'prime' },
  { id: 'r10-dm-030', name: '拉各斯 · 防空系统', layerId: 'defense_mfg', lng: 3.96, lat: 6.81, note: '防空系统节点（公开资料汇总）', impact: 'medium', subKind: 'shipyard' },
];

export const DENSIFY_SEMI_SUPPLY_R10: ThematicPoint[] = [
  { id: 'r10-ss-001', name: '多伦多 · 光刻配套', layerId: 'semi_supply', lng: -79.38, lat: 43.65, note: '光刻配套节点（公开资料汇总）', impact: 'low', subKind: 'materials' },
  { id: 'r10-ss-002', name: '温哥华 · 检测设备', layerId: 'semi_supply', lng: -123.10, lat: 49.29, note: '检测设备节点（公开资料汇总）', impact: 'medium', subKind: 'eda' },
  { id: 'r10-ss-003', name: '墨西哥城 · 掩模制造', layerId: 'semi_supply', lng: -99.09, lat: 19.45, note: '掩模制造节点（公开资料汇总）', impact: 'high', subKind: 'osat' },
  { id: 'r10-ss-004', name: '利马 · 特种气体', layerId: 'semi_supply', lng: -76.98, lat: -12.02, note: '特种气体节点（公开资料汇总）', impact: 'critical', subKind: 'materials' },
  { id: 'r10-ss-005', name: '波哥大 · 封装基板', layerId: 'semi_supply', lng: -73.99, lat: 4.75, note: '封装基板节点（公开资料汇总）', impact: 'low', subKind: 'eda' },
  { id: 'r10-ss-006', name: '圣地亚哥 · 国产设备', layerId: 'semi_supply', lng: -70.55, lat: -33.40, note: '国产设备节点（公开资料汇总）', impact: 'medium', subKind: 'osat' },
  { id: 'r10-ss-007', name: '卡拉奇 · 光刻配套', layerId: 'semi_supply', lng: 67.13, lat: 24.92, note: '光刻配套节点（公开资料汇总）', impact: 'high', subKind: 'materials' },
  { id: 'r10-ss-008', name: '达卡 · 检测设备', layerId: 'semi_supply', lng: 90.55, lat: 23.88, note: '检测设备节点（公开资料汇总）', impact: 'critical', subKind: 'eda' },
  { id: 'r10-ss-009', name: '科伦坡 · 掩模制造', layerId: 'semi_supply', lng: 80.02, lat: 7.01, note: '掩模制造节点（公开资料汇总）', impact: 'low', subKind: 'osat' },
  { id: 'r10-ss-010', name: '仰光 · 特种气体', layerId: 'semi_supply', lng: 96.33, lat: 16.96, note: '特种气体节点（公开资料汇总）', impact: 'medium', subKind: 'materials' },
  { id: 'r10-ss-011', name: '金边 · 封装基板', layerId: 'semi_supply', lng: 105.12, lat: 11.66, note: '封装基板节点（公开资料汇总）', impact: 'high', subKind: 'eda' },
  { id: 'r10-ss-012', name: '万象 · 国产设备', layerId: 'semi_supply', lng: 102.85, lat: 18.09, note: '国产设备节点（公开资料汇总）', impact: 'critical', subKind: 'osat' },
  { id: 'r10-ss-013', name: '阿拉木图 · 光刻配套', layerId: 'semi_supply', lng: 77.19, lat: 43.36, note: '光刻配套节点（公开资料汇总）', impact: 'low', subKind: 'materials' },
  { id: 'r10-ss-014', name: '塔什干 · 检测设备', layerId: 'semi_supply', lng: 69.50, lat: 41.43, note: '检测设备节点（公开资料汇总）', impact: 'medium', subKind: 'eda' },
  { id: 'r10-ss-015', name: '巴库 · 掩模制造', layerId: 'semi_supply', lng: 50.15, lat: 40.55, note: '掩模制造节点（公开资料汇总）', impact: 'high', subKind: 'osat' },
  { id: 'r10-ss-016', name: '第比利斯 · 特种气体', layerId: 'semi_supply', lng: 45.09, lat: 41.87, note: '特种气体节点（公开资料汇总）', impact: 'critical', subKind: 'materials' },
  { id: 'r10-ss-017', name: '基辅 · 封装基板', layerId: 'semi_supply', lng: 30.84, lat: 50.61, note: '封装基板节点（公开资料汇总）', impact: 'low', subKind: 'eda' },
  { id: 'r10-ss-018', name: '明斯克 · 国产设备', layerId: 'semi_supply', lng: 27.91, lat: 54.07, note: '国产设备节点（公开资料汇总）', impact: 'medium', subKind: 'osat' },
  { id: 'r10-ss-019', name: '贝尔格莱德 · 光刻配套', layerId: 'semi_supply', lng: 20.82, lat: 45.00, note: '光刻配套节点（公开资料汇总）', impact: 'high', subKind: 'materials' },
  { id: 'r10-ss-020', name: '布达佩斯 · 检测设备', layerId: 'semi_supply', lng: 19.42, lat: 47.69, note: '检测设备节点（公开资料汇总）', impact: 'critical', subKind: 'eda' },
  { id: 'r10-ss-021', name: '布拉格 · 掩模制造', layerId: 'semi_supply', lng: 14.82, lat: 50.28, note: '掩模制造节点（公开资料汇总）', impact: 'low', subKind: 'osat' },
  { id: 'r10-ss-022', name: '维也纳 · 特种气体', layerId: 'semi_supply', lng: 16.79, lat: 48.42, note: '特种气体节点（公开资料汇总）', impact: 'medium', subKind: 'materials' },
  { id: 'r10-ss-023', name: '雅典 · 封装基板', layerId: 'semi_supply', lng: 24.17, lat: 38.20, note: '封装基板节点（公开资料汇总）', impact: 'high', subKind: 'eda' },
  { id: 'r10-ss-024', name: '开普敦 · 国产设备', layerId: 'semi_supply', lng: 18.88, lat: -33.69, note: '国产设备节点（公开资料汇总）', impact: 'critical', subKind: 'osat' },
  { id: 'r10-ss-025', name: '卡萨布兰卡 · 光刻配套', layerId: 'semi_supply', lng: -7.14, lat: 33.83, note: '光刻配套节点（公开资料汇总）', impact: 'low', subKind: 'materials' },
  { id: 'r10-ss-026', name: '突尼斯 · 检测设备', layerId: 'semi_supply', lng: 10.68, lat: 37.05, note: '检测设备节点（公开资料汇总）', impact: 'medium', subKind: 'eda' },
  { id: 'r10-ss-027', name: '喀土穆 · 掩模制造', layerId: 'semi_supply', lng: 33.02, lat: 15.86, note: '掩模制造节点（公开资料汇总）', impact: 'high', subKind: 'osat' },
  { id: 'r10-ss-028', name: '亚的斯亚贝巴 · 特种气体', layerId: 'semi_supply', lng: 39.28, lat: 9.30, note: '特种气体节点（公开资料汇总）', impact: 'critical', subKind: 'materials' },
  { id: 'r10-ss-029', name: '金沙萨 · 封装基板', layerId: 'semi_supply', lng: 15.87, lat: -4.04, note: '封装基板节点（公开资料汇总）', impact: 'low', subKind: 'eda' },
  { id: 'r10-ss-030', name: '拉各斯 · 国产设备', layerId: 'semi_supply', lng: 3.96, lat: 6.81, note: '国产设备节点（公开资料汇总）', impact: 'medium', subKind: 'osat' },
];

export const DENSIFY_CHEMICALS_R10: ThematicPoint[] = [
  { id: 'r10-ch-001', name: '多伦多 · 氟化工', layerId: 'chemicals', lng: -79.38, lat: 43.65, note: '氟化工节点（公开资料汇总）', impact: 'low', subKind: 'specialty' },
  { id: 'r10-ch-002', name: '温哥华 · 钛白粉', layerId: 'chemicals', lng: -123.10, lat: 49.29, note: '钛白粉节点（公开资料汇总）', impact: 'medium', subKind: 'petrochem' },
  { id: 'r10-ch-003', name: '墨西哥城 · 碳纤维', layerId: 'chemicals', lng: -99.09, lat: 19.45, note: '碳纤维节点（公开资料汇总）', impact: 'high', subKind: 'battery' },
  { id: 'r10-ch-004', name: '利马 · 电解液', layerId: 'chemicals', lng: -76.98, lat: -12.02, note: '电解液节点（公开资料汇总）', impact: 'critical', subKind: 'specialty' },
  { id: 'r10-ch-005', name: '波哥大 · 工业气体', layerId: 'chemicals', lng: -73.99, lat: 4.75, note: '工业气体节点（公开资料汇总）', impact: 'low', subKind: 'petrochem' },
  { id: 'r10-ch-006', name: '圣地亚哥 · 聚合物', layerId: 'chemicals', lng: -70.55, lat: -33.40, note: '聚合物节点（公开资料汇总）', impact: 'medium', subKind: 'battery' },
  { id: 'r10-ch-007', name: '卡拉奇 · 氟化工', layerId: 'chemicals', lng: 67.13, lat: 24.92, note: '氟化工节点（公开资料汇总）', impact: 'high', subKind: 'specialty' },
  { id: 'r10-ch-008', name: '达卡 · 钛白粉', layerId: 'chemicals', lng: 90.55, lat: 23.88, note: '钛白粉节点（公开资料汇总）', impact: 'critical', subKind: 'petrochem' },
  { id: 'r10-ch-009', name: '科伦坡 · 碳纤维', layerId: 'chemicals', lng: 80.02, lat: 7.01, note: '碳纤维节点（公开资料汇总）', impact: 'low', subKind: 'battery' },
  { id: 'r10-ch-010', name: '仰光 · 电解液', layerId: 'chemicals', lng: 96.33, lat: 16.96, note: '电解液节点（公开资料汇总）', impact: 'medium', subKind: 'specialty' },
  { id: 'r10-ch-011', name: '金边 · 工业气体', layerId: 'chemicals', lng: 105.12, lat: 11.66, note: '工业气体节点（公开资料汇总）', impact: 'high', subKind: 'petrochem' },
  { id: 'r10-ch-012', name: '万象 · 聚合物', layerId: 'chemicals', lng: 102.85, lat: 18.09, note: '聚合物节点（公开资料汇总）', impact: 'critical', subKind: 'battery' },
  { id: 'r10-ch-013', name: '阿拉木图 · 氟化工', layerId: 'chemicals', lng: 77.19, lat: 43.36, note: '氟化工节点（公开资料汇总）', impact: 'low', subKind: 'specialty' },
  { id: 'r10-ch-014', name: '塔什干 · 钛白粉', layerId: 'chemicals', lng: 69.50, lat: 41.43, note: '钛白粉节点（公开资料汇总）', impact: 'medium', subKind: 'petrochem' },
  { id: 'r10-ch-015', name: '巴库 · 碳纤维', layerId: 'chemicals', lng: 50.15, lat: 40.55, note: '碳纤维节点（公开资料汇总）', impact: 'high', subKind: 'battery' },
  { id: 'r10-ch-016', name: '第比利斯 · 电解液', layerId: 'chemicals', lng: 45.09, lat: 41.87, note: '电解液节点（公开资料汇总）', impact: 'critical', subKind: 'specialty' },
  { id: 'r10-ch-017', name: '基辅 · 工业气体', layerId: 'chemicals', lng: 30.84, lat: 50.61, note: '工业气体节点（公开资料汇总）', impact: 'low', subKind: 'petrochem' },
  { id: 'r10-ch-018', name: '明斯克 · 聚合物', layerId: 'chemicals', lng: 27.91, lat: 54.07, note: '聚合物节点（公开资料汇总）', impact: 'medium', subKind: 'battery' },
  { id: 'r10-ch-019', name: '贝尔格莱德 · 氟化工', layerId: 'chemicals', lng: 20.82, lat: 45.00, note: '氟化工节点（公开资料汇总）', impact: 'high', subKind: 'specialty' },
  { id: 'r10-ch-020', name: '布达佩斯 · 钛白粉', layerId: 'chemicals', lng: 19.42, lat: 47.69, note: '钛白粉节点（公开资料汇总）', impact: 'critical', subKind: 'petrochem' },
  { id: 'r10-ch-021', name: '布拉格 · 碳纤维', layerId: 'chemicals', lng: 14.82, lat: 50.28, note: '碳纤维节点（公开资料汇总）', impact: 'low', subKind: 'battery' },
  { id: 'r10-ch-022', name: '维也纳 · 电解液', layerId: 'chemicals', lng: 16.79, lat: 48.42, note: '电解液节点（公开资料汇总）', impact: 'medium', subKind: 'specialty' },
  { id: 'r10-ch-023', name: '雅典 · 工业气体', layerId: 'chemicals', lng: 24.17, lat: 38.20, note: '工业气体节点（公开资料汇总）', impact: 'high', subKind: 'petrochem' },
  { id: 'r10-ch-024', name: '开普敦 · 聚合物', layerId: 'chemicals', lng: 18.88, lat: -33.69, note: '聚合物节点（公开资料汇总）', impact: 'critical', subKind: 'battery' },
  { id: 'r10-ch-025', name: '卡萨布兰卡 · 氟化工', layerId: 'chemicals', lng: -7.14, lat: 33.83, note: '氟化工节点（公开资料汇总）', impact: 'low', subKind: 'specialty' },
  { id: 'r10-ch-026', name: '突尼斯 · 钛白粉', layerId: 'chemicals', lng: 10.68, lat: 37.05, note: '钛白粉节点（公开资料汇总）', impact: 'medium', subKind: 'petrochem' },
  { id: 'r10-ch-027', name: '喀土穆 · 碳纤维', layerId: 'chemicals', lng: 33.02, lat: 15.86, note: '碳纤维节点（公开资料汇总）', impact: 'high', subKind: 'battery' },
  { id: 'r10-ch-028', name: '亚的斯亚贝巴 · 电解液', layerId: 'chemicals', lng: 39.28, lat: 9.30, note: '电解液节点（公开资料汇总）', impact: 'critical', subKind: 'specialty' },
  { id: 'r10-ch-029', name: '金沙萨 · 工业气体', layerId: 'chemicals', lng: 15.87, lat: -4.04, note: '工业气体节点（公开资料汇总）', impact: 'low', subKind: 'petrochem' },
  { id: 'r10-ch-030', name: '拉各斯 · 聚合物', layerId: 'chemicals', lng: 3.96, lat: 6.81, note: '聚合物节点（公开资料汇总）', impact: 'medium', subKind: 'battery' },
];

