import type {
  EnergyImpactRegion,
  EnergyDataPoint,
  OilProducerMapPoint,
} from '@/types/middleeast';

/**
 * 全球视角 · 能源经济种子数据（用于 economic 图层与侧边栏展示）
 *
 * ⚠ 占位/示例：非实时数据；用于演示地图内容与时间标注。
 */
export const globalEnergyImpactRegions: EnergyImpactRegion[] = [
  {
    id: 'cn-energy-asia',
    name: '亚洲（中国视角）',
    flag: '🇨🇳',
    dependency:
      '关键能源与航运风险通过海上通道影响亚洲供应链；当区域安全与天气条件叠加时，价格与通行节奏易出现波动。',
    impact:
      '能源与运价短期联动抬升；企业通过替代航线与库存策略降低不确定性。',
    source: 'seed/示例',
    updatedAt: '2026-06-14',
  },
];

export const globalEnergyDataPoints: EnergyDataPoint[] = [
  {
    id: 'cn-brent',
    name: '布伦特原油（示例）',
    unit: '美元/桶',
    value: 84.2,
    change: 8.5,
    changePercent: 11.2,
    description: '示例：航运风险溢价导致阶段性上行',
    updatedAt: '2026-06-16T18:00:00Z',
    source: 'seed/示例',
  },
  {
    id: 'cn-ttf',
    name: '欧洲 TTF（示例）',
    unit: '欧元/MWh',
    value: 38.5,
    change: 4.2,
    changePercent: 12.2,
    description: '示例：地缘与运输风险推高气价预期',
    updatedAt: '2026-06-16T17:00:00Z',
    source: 'seed/示例',
  },
  {
    id: 'cn-lng-japan',
    name: '日本 LNG 到岸（示例）',
    unit: '美元/百万英热',
    value: 15.1,
    change: 2.1,
    changePercent: 16.2,
    description: '亚洲天然气价格联动指标',
    updatedAt: '2026-06-16T16:00:00Z',
    source: 'seed/示例',
  },
  {
    id: 'cn-iron-ore',
    name: '铁矿石（普氏62%）',
    unit: '美元/吨',
    value: 118.5,
    change: 3.2,
    changePercent: 2.8,
    description: '炼厂原料成本与澳洲发货节奏',
    updatedAt: '2026-06-16T14:30:00Z',
    source: '普氏 / seed',
  },
  {
    id: 'cn-coal-thermal',
    name: '动力煤（秦皇岛港）',
    unit: '元/吨',
    value: 875,
    change: 12,
    changePercent: 1.4,
    description: '电厂库存与进口煤补充节奏',
    updatedAt: '2026-06-16T11:00:00Z',
    source: 'seed/示例',
  },
  {
    id: 'cn-container-freight',
    name: '集装箱运价（亚欧线）',
    unit: '美元/TEU',
    value: 2850,
    change: 320,
    changePercent: 12.6,
    description: '红海绕行推升亚欧航线成本',
    updatedAt: '2026-06-16T10:00:00Z',
    source: 'seed/示例',
  },
];

export const globalOilProducerMapPoints: OilProducerMapPoint[] = [
  {
    id: 'cn-oil-sa',
    name: '沙特阿拉伯（示例点）',
    lng: 46.7,
    lat: 24.7,
    production: '约 950 万桶/日（示例）',
    exportShare: '全球关键出口国',
    note: '航运风险情景下，市场对供给稳定性更敏感。',
    updatedAt: '2026-06-16T18:10:00Z',
  },
  {
    id: 'cn-oil-ir',
    name: '伊朗（示例点）',
    lng: 51.4,
    lat: 35.7,
    production: '约 320 万桶/日（示例）',
    exportShare: '制裁与海上通道影响显著',
    note: '区域安全变化会放大出口与运输成本波动。',
    updatedAt: '2026-06-16T16:40:00Z',
  },
  {
    id: 'cn-oil-om',
    name: '阿曼（示例点）',
    lng: 58.4,
    lat: 23.6,
    production: '约 100 万桶/日（示例）',
    exportShare: '可作为替代运输节点',
    note: '当主通道风险上升时，替代路线需求更集中。',
    updatedAt: '2026-06-15T19:30:00Z',
  },
  {
    id: 'cn-oil-ru',
    name: '俄罗斯（示例点）',
    lng: 37.6,
    lat: 55.75,
    production: '约 950 万桶/日（示例）',
    exportShare: '管道与远东出口',
    note: '制裁与折扣幅度影响亚洲买家结构。',
    updatedAt: '2026-06-16T15:00:00Z',
  },
  {
    id: 'cn-oil-br',
    name: '巴西（示例点）',
    lng: -47.88,
    lat: -15.79,
    production: '约 320 万桶/日（示例）',
    exportShare: '海上出口为主',
    note: '南美原油对华出口增长监测点。',
    updatedAt: '2026-06-16T14:00:00Z',
  },
  {
    id: 'cn-oil-ng',
    name: '尼日利亚（示例点）',
    lng: 3.4,
    lat: 6.45,
    production: '约 140 万桶/日（示例）',
    exportShare: '西非主要出口国',
    note: '产区安全与装船节奏波动。',
    updatedAt: '2026-06-15T20:00:00Z',
  },
  {
    id: 'cn-oil-ao',
    name: '安哥拉（示例点）',
    lng: 13.23,
    lat: -8.84,
    production: '约 110 万桶/日（示例）',
    exportShare: '对华出口重要来源',
    note: '海上油田与FPSO装船节奏。',
    updatedAt: '2026-06-16T11:30:00Z',
  },
  {
    id: 'cn-oil-kz',
    name: '哈萨克斯坦（示例点）',
    lng: 71.43,
    lat: 51.16,
    production: '约 160 万桶/日（示例）',
    exportShare: '管道输送为主',
    note: '里海油气东向供应监测。',
    updatedAt: '2026-06-15T16:00:00Z',
  },
  {
    id: 'cn-oil-iraq-jun',
    name: '伊拉克巴士拉（示例点）',
    lng: 47.78,
    lat: 30.5,
    production: '约 420 万桶/日（示例）',
    exportShare: '对华长期合同',
    note: '中东局势下出口节奏监测（种子/示例）',
    updatedAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 'cn-oil-uae-jun',
    name: '阿联酋阿布扎比（示例点）',
    lng: 54.37,
    lat: 24.45,
    production: '约 320 万桶/日（示例）',
    exportShare: '亚洲炼厂主力供应',
    note: '波斯湾风险溢价敏感（种子/示例）',
    updatedAt: '2026-06-14T12:00:00Z',
  },
  {
    id: 'cn-oil-russia-jun',
    name: '俄罗斯远东出口（示例点）',
    lng: 132.0,
    lat: 43.0,
    production: '管道+海运（示例）',
    exportShare: '对华折扣原油',
    note: '乌拉尔折扣与影子舰队运输（种子/示例）',
    updatedAt: '2026-06-13T08:00:00Z',
  },
];

