import type { Facility } from '@/types/middleeast';

/**
 * 全球关键节点与海外保障设施
 * ⚠ 占位/示例：用于 bases / economic 图层演示，非实时情报。
 */
export const GLOBAL_SEED_FACILITIES: Facility[] = [
  {
    id: 'cn-fac-djibouti',
    name: '吉布提保障基地',
    position: { lat: 11.58, lng: 43.15 },
    faction: 'cn',
    type: 'naval',
    forces: ['海军陆战队', '补给保障'],
    troopEstimate: '约 2,000',
    notes: '中国在海外首个保障基地，亚丁湾护航与非洲任务支撑点',
  },
  {
    id: 'cn-fac-gwadar',
    name: '瓜达尔港 · 中巴经济走廊节点',
    position: { lat: 25.12, lng: 62.33 },
    faction: 'cn',
    type: 'naval',
    forces: ['港口运营', '陆海联运'],
    notes: '一带一路关键出海口，能源与货物转运枢纽',
  },
  {
    id: 'cn-fac-kyaukpyu',
    name: '皎漂港 · 中缅通道',
    position: { lat: 19.43, lng: 93.55 },
    faction: 'cn',
    type: 'naval',
    notes: '印度洋替代航线节点，降低马六甲依赖',
  },
  {
    id: 'cn-fac-piraeus',
    name: '比雷埃夫斯港 · 中欧陆海快线',
    position: { lat: 37.94, lng: 23.64 },
    faction: 'cn',
    type: 'naval',
    notes: '地中海进入欧洲的桥头堡，中远海运运营',
  },
  {
    id: 'cn-fac-hamburg',
    name: '汉堡港 · 北欧贸易枢纽',
    position: { lat: 53.55, lng: 9.99 },
    faction: 'cn',
    type: 'naval',
    notes: '中欧班列终点之一，集装箱吞吐量欧洲前列',
  },
  {
    id: 'cn-fac-sri-lanka',
    name: '汉班托塔港 · 印度洋补给',
    position: { lat: 6.12, lng: 81.12 },
    faction: 'cn',
    type: 'naval',
    notes: '印度洋航线关键停靠与转运节点',
  },
  {
    id: 'cn-fac-ream',
    name: '云壤海军基地（柬埔寨）',
    position: { lat: 10.62, lng: 103.52 },
    faction: 'cn',
    type: 'naval',
    notes: '泰国湾战略位置，南海周边海上通道监测',
  },
  {
    id: 'cn-fac-sanya',
    name: '三亚 · 南海舰队基地',
    position: { lat: 18.25, lng: 109.51 },
    faction: 'cn',
    type: 'naval',
    forces: ['南海舰队', '潜艇', '航母编队'],
    troopEstimate: '数万',
    weapons: ['055型驱逐舰', '核潜艇', '山东舰'],
    notes: '南海方向核心军港与训练基地',
  },
  {
    id: 'cn-fac-qingdao',
    name: '青岛 · 北海舰队',
    position: { lat: 36.07, lng: 120.38 },
    faction: 'cn',
    type: 'naval',
    forces: ['北海舰队', '航母'],
    notes: '黄海与西太平洋方向主要出海口',
  },
  {
    id: 'cn-fac-ningbo',
    name: '宁波—舟山港 · 全球第一大港',
    position: { lat: 29.87, lng: 121.55 },
    faction: 'cn',
    type: 'base',
    notes: '年吞吐量全球领先，外贸集装箱主枢纽',
  },
  {
    id: 'cn-fac-mombasa',
    name: '蒙巴萨港 · 东非海运门户',
    position: { lat: -4.04, lng: 39.66 },
    faction: 'cn',
    type: 'naval',
    notes: '蒙内铁路终点，东非贸易与转运枢纽',
  },
  {
    id: 'cn-fac-piraeus-2',
    name: '比雷埃夫斯集装箱码头',
    position: { lat: 37.94, lng: 23.64 },
    faction: 'cn',
    type: 'base',
    notes: '地中海进入中欧陆海快线桥头堡',
  },
  {
    id: 'cn-fac-lianyungang',
    name: '连云港 · 亚欧陆海交汇',
    position: { lat: 34.6, lng: 119.22 },
    faction: 'cn',
    type: 'naval',
    notes: '中欧班列东向起点，中亚货物出海通道',
  },
  {
    id: 'cn-fac-kashgar',
    name: '喀什 · 中巴走廊陆路节点',
    position: { lat: 39.47, lng: 75.99 },
    faction: 'cn',
    type: 'base',
    notes: '通往红其拉甫口岸，连接瓜达尔方向',
  },
  {
    id: 'cn-fac-hamburg-2',
    name: '汉堡—威廉港 · 北欧集装箱枢纽',
    position: { lat: 53.55, lng: 9.99 },
    faction: 'cn',
    type: 'naval',
    notes: '中欧贸易主港，铁路支线辐射德波捷',
  },
  {
    id: 'cn-fac-tashkent',
    name: '塔什干 · 中亚物流枢纽',
    position: { lat: 41.3, lng: 69.24 },
    faction: 'cn',
    type: 'base',
    notes: '中欧班列西向节点，连接里海通道',
  },
  {
    id: 'cn-fac-colombo',
    name: '科伦坡港',
    position: { lat: 6.93, lng: 79.85 },
    faction: 'cn',
    type: 'naval',
    notes: '印度洋关键转运港，能源与集装箱中转',
  },
  {
    id: 'cn-fac-piraeus-3',
    name: '比雷埃夫斯集装箱码头 II',
    position: { lat: 37.94, lng: 23.62 },
    faction: 'cn',
    type: 'naval',
    notes: '地中海进入中东欧铁路联运',
  },
  {
    id: 'cn-fac-dalian',
    name: '大连港 · 东北亚能源枢纽',
    position: { lat: 38.91, lng: 121.6 },
    faction: 'cn',
    type: 'naval',
    notes: 'LNG 与原油进口主港',
  },
  {
    id: 'cn-fac-xiamen',
    name: '厦门港 · 海峡西岸门户',
    position: { lat: 24.48, lng: 118.08 },
    faction: 'cn',
    type: 'naval',
    notes: '对台贸易与集装箱转运',
  },
  {
    id: 'cn-fac-alexandria',
    name: '亚历山大港 · 地中海节点',
    position: { lat: 31.2, lng: 29.92 },
    faction: 'cn',
    type: 'naval',
    notes: '苏伊士运河西侧转运枢纽',
  },
  {
    id: 'cn-fac-valencia',
    name: '瓦伦西亚港 · 伊比利亚门户',
    position: { lat: 39.45, lng: -0.32 },
    faction: 'cn',
    type: 'naval',
    notes: '中欧班列南线海运衔接',
  },
  {
    id: 'cn-fac-darwin',
    name: '达尔文港 · 澳北资源出口',
    position: { lat: -12.46, lng: 130.84 },
    faction: 'cn',
    type: 'naval',
    notes: '铁矿石与 LNG 进口节点',
  },
];
