/**
 * 全球核设施档案 — 核电站、浓缩设施、导弹发射井、战略核潜艇基地、核试验场与污染区
 *
 * ⚠ 坐标为公开资料中的示意/中心点，非精确军事坐标；用于态势图层演示。
 * 来源：IAEA PRIS、公开开源情报（OSINT）、各国监管机构与学术文献汇总。
 * 检索整理日：2026-06-16
 */

import type { Facility } from '@/types/middleeast';

const T = '2026-06-15T12:00:00Z';

/** 全球核设施点位（由 /api/geodata 按区域边界过滤后合并上屏） */
export const GLOBAL_NUCLEAR_FACILITIES: Facility[] = [
  // ── 北美 · 美国 ──────────────────────────────────────────────
  {
    id: 'nuc-us-palo-verde',
    name: '帕洛弗迪核电站',
    position: { lat: 33.39, lng: -112.86 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '美国装机容量最大核电站（IAEA PRIS）',
    updatedAt: T,
  },
  {
    id: 'nuc-us-few-warren',
    name: 'F·E·沃伦空军基地 · 民兵 III 发射井群',
    position: { lat: 41.14, lng: -104.87 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM'],
    notes: '怀俄明州，美国战略司令部陆基核威慑',
    updatedAt: T,
  },
  {
    id: 'nuc-us-malmstrom',
    name: '马姆斯特罗姆空军基地 · 发射井群',
    position: { lat: 47.51, lng: -111.18 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM'],
    notes: '蒙大拿州，北美防空与战略导弹枢纽',
    updatedAt: T,
  },
  {
    id: 'nuc-us-minot',
    name: '迈诺特空军基地 · 发射井群',
    position: { lat: 48.42, lng: -101.35 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['民兵 III ICBM', 'B-52H'],
    notes: '北达科他州，空基与陆基核力量集结',
    updatedAt: T,
  },
  {
    id: 'nuc-us-kings-bay',
    name: '金斯湾潜艇基地',
    position: { lat: 30.8, lng: -81.52 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['俄亥俄级 SSBN', '三叉戟 II D5'],
    notes: '大西洋战略核潜艇母港',
    updatedAt: T,
  },
  {
    id: 'nuc-us-bangor',
    name: '班戈海军基地',
    position: { lat: 47.73, lng: -122.71 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['俄亥俄级 SSBN'],
    notes: '太平洋战略核潜艇母港',
    updatedAt: T,
  },
  {
    id: 'nuc-us-hanford',
    name: '汉福德区 · 核废料与污染监测',
    position: { lat: 46.56, lng: -119.52 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '修复中',
    notes: '曼哈顿计划钚生产遗址，美国最大核污染清理工程之一',
    updatedAt: T,
  },
  {
    id: 'nuc-us-nevada-test',
    name: '内华达国家安全区 · 核试验场',
    position: { lat: 37.12, lng: -116.05 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'test_site',
    status: '封存',
    notes: '历史核试验场，次临界试验与监测',
    updatedAt: T,
  },
  {
    id: 'nuc-us-pantex',
    name: '潘特克斯工厂 · 核弹头组装/拆解',
    position: { lat: 35.31, lng: -101.96 },
    faction: 'us',
    type: 'nuclear',
    nuclearKind: 'warhead_storage',
    status: '运行中',
    notes: '美国主要核弹头维护与储存设施',
    updatedAt: T,
  },

  // ── 欧洲 · 俄乌 / 俄罗斯 ─────────────────────────────────────
  {
    id: 'nuc-ru-kozelsk',
    name: '科热利斯克 · 亚尔斯发射井群',
    position: { lat: 54.04, lng: 35.78 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '战备',
    weapons: ['RS-24 亚尔斯 ICBM'],
    notes: '卡卢加州，俄陆基机动/井基战略力量',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-vladimir',
    name: '弗拉基米尔州 · 战略导弹师',
    position: { lat: 56.13, lng: 40.41 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'icbm_base',
    status: '战备',
    weapons: ['白杨-M / 亚尔斯'],
    notes: '俄战略火箭军重要基地群',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-severodvinsk',
    name: '北德文斯克 · 战略核潜艇建造与基地',
    position: { lat: 64.57, lng: 39.83 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '运行中',
    weapons: ['北风之神级 SSBN'],
    notes: '北方舰队核潜艇核心枢纽',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-kola',
    name: '科拉核电站',
    position: { lat: 67.47, lng: 32.48 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '北极圈内重要核电基地（IAEA PRIS）',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-mayak',
    name: '马亚克 · 核废料与污染区',
    position: { lat: 55.7, lng: 60.82 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '监测中',
    notes: '1957 克什特姆核事故，东乌拉尔放射性污染带',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-novaya-zemlya',
    name: '新地岛 · 核试验场',
    position: { lat: 73.0, lng: 54.0 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'test_site',
    status: '封存',
    notes: '苏联时期主要核试验场，沙皇炸弹试验地',
    updatedAt: T,
  },
  {
    id: 'nuc-ua-chernobyl',
    name: '切尔诺贝利隔离区',
    position: { lat: 51.39, lng: 30.1 },
    faction: 'ua',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '隔离',
    notes: '1986 事故遗址，欧洲最大核污染区（IAEA 监测）',
    updatedAt: T,
  },
  {
    id: 'nuc-ua-zaporizhzhia',
    name: '扎波罗热核电站',
    position: { lat: 47.51, lng: 34.58 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '争议控制',
    notes: '欧洲最大核电站，IAEA 驻场监测',
    updatedAt: T,
  },
  {
    id: 'nuc-fr-flamanville',
    name: '弗拉芒维尔核电站',
    position: { lat: 49.54, lng: -1.88 },
    faction: 'fr',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '法国 EPR 机组所在地',
    updatedAt: T,
  },
  {
    id: 'nuc-fr-ile-longue',
    name: 'Île Longue · 战略核潜艇基地',
    position: { lat: 48.3, lng: -4.5 },
    faction: 'fr',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['凯旋级 SSBN', 'M51 SLBM'],
    notes: '法国海基核威慑唯一基地',
    updatedAt: T,
  },
  {
    id: 'nuc-uk-trident',
    name: '法斯兰海军基地 · 三叉戟核潜艇',
    position: { lat: 56.07, lng: -4.82 },
    faction: 'uk',
    type: 'nuclear',
    nuclearKind: 'submarine_base',
    status: '战备',
    weapons: ['前卫级 SSBN'],
    notes: '英国海基核威慑母港',
    updatedAt: T,
  },

  // ── 中东（与区域 dataset 互补，同址由去重逻辑处理）────────────
  {
    id: 'nuc-il-dimona',
    name: '迪莫纳核设施',
    position: { lat: 31.0, lng: 35.15 },
    faction: 'israel',
    type: 'nuclear',
    nuclearKind: 'warhead_storage',
    status: '未公开承认',
    notes: '内盖夫沙漠，国际广泛关注的核能力中心',
    updatedAt: T,
  },
  {
    id: 'nuc-ir-natanz',
    name: '纳坦兹铀浓缩设施',
    position: { lat: 33.72, lng: 51.73 },
    faction: 'iran',
    type: 'nuclear',
    nuclearKind: 'enrichment',
    status: '运行/受损',
    notes: 'IAEA 核查重点，地下离心机大厅',
    updatedAt: T,
  },
  {
    id: 'nuc-ir-fordow',
    name: '福尔多地下浓缩设施',
    position: { lat: 34.88, lng: 50.99 },
    faction: 'iran',
    type: 'nuclear',
    nuclearKind: 'enrichment',
    status: '运行',
    notes: '山体掩体保护的关键浓缩设施',
    updatedAt: T,
  },
  {
    id: 'nuc-ir-bushehr',
    name: '布什尔核电站',
    position: { lat: 28.83, lng: 50.95 },
    faction: 'iran',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '伊朗唯一商用核电站（IAEA 保障监督）',
    updatedAt: T,
  },
  {
    id: 'nuc-pk-kahuta',
    name: '卡胡塔 · 浓缩设施',
    position: { lat: 33.59, lng: 73.35 },
    faction: 'pk',
    type: 'nuclear',
    nuclearKind: 'enrichment',
    status: '运行中',
    notes: '巴基斯坦铀浓缩与核武器计划核心',
    updatedAt: T,
  },

  // ── 东亚 ─────────────────────────────────────────────────────
  {
    id: 'nuc-cn-taishan',
    name: '台山核电站',
    position: { lat: 21.92, lng: 112.98 },
    faction: 'cn',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: 'EPR 技术机组，粤港澳大湾区供电',
    updatedAt: T,
  },
  {
    id: 'nuc-cn-dayawan',
    name: '大亚湾核电站',
    position: { lat: 22.6, lng: 114.54 },
    faction: 'cn',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '中国大陆首座大型商用核电站',
    updatedAt: T,
  },
  {
    id: 'nuc-cn-jilantai',
    name: '吉兰泰 · 导弹训练与发射井区',
    position: { lat: 39.75, lng: 105.45 },
    faction: 'cn',
    type: 'nuclear',
    nuclearKind: 'missile_silo',
    status: '监测中',
    notes: '开源卫星显示的大规模井基建设区（OSINT）',
    updatedAt: T,
  },
  {
    id: 'nuc-kp-yongbyon',
    name: '宁边核科学研究中心',
    position: { lat: 39.8, lng: 125.75 },
    faction: 'kp',
    type: 'nuclear',
    nuclearKind: 'enrichment',
    status: '运行中',
    notes: '朝鲜核计划核心设施，钚生产与浓缩',
    updatedAt: T,
  },
  {
    id: 'nuc-kp-punggye',
    name: '丰溪里核试验场',
    position: { lat: 41.28, lng: 129.08 },
    faction: 'kp',
    type: 'nuclear',
    nuclearKind: 'test_site',
    status: '封存/可恢复',
    notes: '朝鲜六次核试验场地',
    updatedAt: T,
  },
  {
    id: 'nuc-jp-fukushima',
    name: '福岛第一核电站 · 污染监测',
    position: { lat: 37.42, lng: 141.03 },
    faction: 'jp',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '退役/清理中',
    notes: '2011 事故后持续监测，ALPS 处理水排放争议',
    updatedAt: T,
  },
  {
    id: 'nuc-jp-kashiwazaki',
    name: '柏崎刈羽核电站',
    position: { lat: 37.43, lng: 138.6 },
    faction: 'jp',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '部分重启',
    notes: '世界装机容量最大核电站之一',
    updatedAt: T,
  },
  {
    id: 'nuc-in-kudankulam',
    name: '库丹库兰核电站',
    position: { lat: 8.17, lng: 77.71 },
    faction: 'in',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '印度南部大型核电基地',
    updatedAt: T,
  },
  {
    id: 'nuc-in-pokhran',
    name: '博克兰核试验场',
    position: { lat: 27.0, lng: 71.75 },
    faction: 'in',
    type: 'nuclear',
    nuclearKind: 'test_site',
    status: '封存',
    notes: '1998 年核试验场地',
    updatedAt: T,
  },

  // ── 其他 ─────────────────────────────────────────────────────
  {
    id: 'nuc-kz-semipalatinsk',
    name: '塞米巴拉金斯克 · 原核试验场污染区',
    position: { lat: 50.07, lng: 78.45 },
    faction: 'kz',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '监测中',
    notes: '苏联时期 456 次核试验，遗留大范围污染',
    updatedAt: T,
  },
  {
    id: 'nuc-au-maralinga',
    name: '马拉林加 · 核试验污染区',
    position: { lat: -30.17, lng: 131.65 },
    faction: 'au',
    type: 'nuclear',
    nuclearKind: 'contamination',
    status: '修复后监测',
    notes: '英国在澳核试验遗留污染（1950–60 年代）',
    updatedAt: T,
  },
  {
    id: 'nuc-cn-fangchenggang',
    name: '防城港核电站',
    position: { lat: 21.6, lng: 108.35 },
    faction: 'cn',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '西部沿海核电基地（种子/示例）',
    updatedAt: T,
  },
  {
    id: 'nuc-cn-yangjiang',
    name: '阳江核电站',
    position: { lat: 21.7, lng: 112.0 },
    faction: 'cn',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '华南核电集群（种子/示例）',
    updatedAt: T,
  },
  {
    id: 'nuc-pk-chashma',
    name: '恰希玛核电站',
    position: { lat: 32.39, lng: 71.46 },
    faction: 'pk',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '中巴核能合作项目（种子/示例）',
    updatedAt: T,
  },
  {
    id: 'nuc-ua-rivne',
    name: '里夫涅核电站',
    position: { lat: 51.33, lng: 25.89 },
    faction: 'ua',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '乌克兰西部核电，战时供电关键',
    updatedAt: T,
  },
  {
    id: 'nuc-ua-khmelnytskyi',
    name: '赫梅利尼茨基核电站',
    position: { lat: 50.3, lng: 26.65 },
    faction: 'ua',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '乌克兰西部核电基地',
    updatedAt: T,
  },
  {
    id: 'nuc-ru-beloyarsk',
    name: '别洛亚尔斯克核电站',
    position: { lat: 56.84, lng: 60.8 },
    faction: 'ru',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '快中子增殖堆试验基地',
    updatedAt: T,
  },
  {
    id: 'nuc-fr-cattenom',
    name: '卡特泰姆核电站',
    position: { lat: 49.42, lng: 6.22 },
    faction: 'fr',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '法国最大核电站之一',
    updatedAt: T,
  },
  {
    id: 'nuc-uk-sellafield',
    name: '塞拉菲尔德后处理厂',
    position: { lat: 54.42, lng: -3.5 },
    faction: 'uk',
    type: 'nuclear',
    nuclearKind: 'reprocessing',
    status: '运行中',
    notes: '英国核废料后处理与钚储存',
    updatedAt: T,
  },
  {
    id: 'nuc-kr-hanul',
    name: '韩蔚核电站',
    position: { lat: 37.09, lng: 129.38 },
    faction: 'kr',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '韩国东部核电集群',
    updatedAt: T,
  },
  {
    id: 'nuc-ro-cernavoda',
    name: '切尔纳沃达核电站',
    position: { lat: 44.32, lng: 28.05 },
    faction: 'ro',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '罗马尼亚唯一核电站，多瑙河沿岸',
    updatedAt: T,
  },
  {
    id: 'nuc-bg-kozloduy',
    name: '科兹洛杜伊核电站',
    position: { lat: 43.75, lng: 23.65 },
    faction: 'bg',
    type: 'nuclear',
    nuclearKind: 'power_plant',
    status: '运行中',
    notes: '保加利亚主要核电，巴尔干电力枢纽',
    updatedAt: T,
  },
];

/** 核设施子类中文标签 */
export const NUCLEAR_KIND_LABEL: Record<string, string> = {
  power_plant: '核电站',
  enrichment: '铀浓缩',
  reprocessing: '后处理',
  missile_silo: '导弹发射井',
  warhead_storage: '弹头储存',
  submarine_base: '战略核潜艇基地',
  icbm_base: '洲际导弹基地',
  test_site: '核试验场',
  contamination: '核污染区',
  research_reactor: '研究堆',
};
