// 中东冲突事件 — LIFEOS-005 阶段3 第五批
// 迁自 Iran conflictData.ts(incidents)，69 条，可上地图(按事件类型着色)。含公开来源链接。
import type { Incident } from '@/types/middleeast';

export const MIDEAST_INCIDENTS: Incident[] = [
  // ---------- Reuters 等网络来源（2026-06-16 前后，带原文链接）----------
  {
    id: 'evt-reuters-1',
    title: '共和党阻止叫停美空袭议案，美伊战事进入第六天',
    date: '2026-06-16T14:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9, lng: -77.0 },
    description: '美国国会共和党人阻止了旨在叫停对伊朗空袭的议案；美伊战争进入第六天，伊朗向以色列发射新一波导弹。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/asia-pacific/iran-launches-wave-missiles-israel-us-republicans-block-measure-halt-us-air-2026-06-16/',
  },
  {
    id: 'evt-reuters-2',
    title: '伊朗称在波斯湾击中美国油轮，美方未立即确认',
    date: '2026-06-16T12:30:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 26.5, lng: 56.5 },
    description: '伊朗伊斯兰革命卫队称在波斯湾击中一艘美国油轮并引发大火；美方未立即确认。若属实，将加剧霍尔木兹航运风险。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/middle-east/iran-says-it-hits-us-oil-tanker-gulf-no-immediate-confirmation-2026-06-16/',
  },
  {
    id: 'evt-reuters-3',
    title: '斯里兰卡称正努力保障第二艘伊朗船船员安全',
    date: '2026-06-16T11:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 6.93, lng: 79.85 },
    description: '美潜艇攻击伊朗舰艇后，伊朗船员在斯里兰卡医院救治。斯里兰卡表示正努力保障另一艘伊朗船只上人员的生命安全。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/asia-pacific/iranian-sailors-recovering-sri-lankan-hospital-after-us-submarine-attack-2026-06-16/',
  },
  {
    id: 'evt-reuters-4',
    title: '阿塞拜疆称两人遭伊朗无人机/导弹袭击受伤',
    date: '2026-06-16T10:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 40.41, lng: 49.87 },
    description: '阿塞拜疆称来自伊朗方向的导弹/无人机落在机场附近，造成两人受伤。冲突溢出效应波及高加索。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/asia-pacific/missiles-drones-coming-iran-fell-airport-azerbaijan-source-says-2026-06-16/',
  },
  {
    id: 'evt-reuters-5',
    title: '内塔尼亚胡与特朗普的战争联盟随伊朗危机扩大面临考验',
    date: '2026-06-15T18:00:00Z',
    type: 'political',
    faction: 'israel',
    location: { lat: 32.0853, lng: 34.7818 },
    description: '特朗普与内塔尼亚胡此前将「政权更迭」列为目标，特朗普后又将美方目标调整为摧毁伊朗导弹与海军、阻止拥核，战争目标分歧显现；民调显示仅约四分之一美国人支持美方空袭。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/middle-east/netanyahus-war-alliance-with-trump-faces-test-iran-crisis-widens-2026-06-15/',
  },
  {
    id: 'evt-reuters-6',
    title: '滞留海湾旅客冒险选路回家：「大家欢呼」',
    date: '2026-06-15T12:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 25.28, lng: 51.52 },
    description: '海湾多国领空关闭或受限后，大量旅客滞留；部分人改道陆路或经第三国返程，报道称机上乘客在起飞时「大家欢呼」。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/middle-east/everyone-cheered-stranded-gulf-travellers-gamble-their-route-home-2026-06-15/',
  },
  {
    id: 'evt-reuters-7',
    title: '以军发言人：已做好数周对伊行动准备，不太可能出动地面部队',
    date: '2026-06-14T16:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 32.0853, lng: 34.7818 },
    description: '以色列国防军发言人表示，以方已为持续数周的对伊朗军事行动做好准备，但不太可能部署地面部队。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/middle-east/israel-prepared-weeks-long-iran-campaign-unlikely-deploy-ground-forces-2026-06-14/',
  },
  {
    id: 'evt-reuters-8',
    title: '以美在伊朗领袖与核心圈会晤时发动打击，消息人士称',
    date: '2026-06-12T06:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.6892, lng: 51.389 },
    description: '以色列与美国在周六发动的打击，时机选在伊朗最高领袖与核心圈会晤之际。以方官员确认包括最高领袖在内多名高层在袭击中身亡。',
    source: 'reuters',
    link: 'https://www.reuters.com/world/middle-east/israel-us-launched-strikes-iranian-leader-met-with-inner-circle-sources-say-2026-06-12',
  },
  {
    id: 'evt-hard-7',
    title: '伊朗革命卫队称在波斯湾击中美国油轮并引发大火',
    date: '2026-06-16T12:45:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 26.5, lng: 56.5 },
    description: '伊朗伊斯兰革命卫队宣布在波斯湾使用导弹击中一艘美国油轮，称该船起火。美方未立即确认；若属实将加剧霍尔木兹航运风险。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-8',
    title: '阿塞拜疆称两人因伊朗方向导弹/无人机受伤',
    date: '2026-06-16T10:15:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 40.41, lng: 49.87 },
    description: '阿塞拜疆官方称来自伊朗方向的导弹或无人机落在机场附近，造成两人受伤。冲突溢出效应波及高加索地区。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-9',
    title: '美国国会共和党人阻止叫停对伊空袭的议案',
    date: '2026-06-16T14:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9, lng: -77.0 },
    description: '国会共和党人阻止了旨在叫停美国对伊朗空袭的议案；美伊战争进入第六天，伊朗向以色列发射新一波导弹。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-10',
    title: '斯里兰卡称正努力保障第二艘伊朗船船员安全',
    date: '2026-06-16T11:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 6.93, lng: 79.85 },
    description: '美潜艇攻击伊朗舰艇后，部分伊朗船员在斯里兰卡医院救治。斯里兰卡表示正努力保障另一艘伊朗船只上人员的生命安全。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-11',
    title: '以军发言人：已做好数周对伊行动准备，地面部队不太可能部署',
    date: '2026-06-14T16:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 32.0853, lng: 34.7818 },
    description: '以色列国防军发言人表示，以方已为持续数周的对伊朗军事行动做好准备，但不太可能部署地面部队；依赖空袭与远程打击。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-12',
    title: '滞留海湾旅客改道陆路或经第三国返程，部分航班恢复',
    date: '2026-06-15T12:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 25.28, lng: 51.52 },
    description: '海湾多国领空关闭或受限后大量旅客滞留；部分人改道陆路或经阿曼、土耳其等第三国返程，报道称起飞时「大家欢呼」。',
    source: 'reuters',
  },
  // ---------- BBC 来源（2026-06-14 周二）----------
  {
    id: 'evt-bbc-1',
    title: '以军空袭德黑兰总统府及领导层大院',
    date: '2026-06-14T10:07:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.6892, lng: 51.389 },
    description: '以色列国防军称空军打击了伊朗政权「领导层大院」，向总统府与最高国家安全委员会投下「大量弹药」，并击中一所军事训练机构及「其他关键政权设施」。以军称已故最高领袖霍梅尼曾使用该大院。',
    source: 'bbc',
    link: 'https://www.bbc.com/news/live/cy0dp1l57nxt',
  },
  {
    id: 'evt-bbc-2',
    title: '伊朗红新月会：死亡人数升至 787 人',
    date: '2026-06-14T09:51:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗红新月会称，自美以周六发动袭击以来，伊朗境内已有 787 人死亡。人权组织 HRANA 报告 742 名平民丧生，其中 176 名为儿童。伊朗议会卫生委员会成员称 9 家医院遭袭，以军回应甘地医院「并非以医院为目标」。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-3',
    title: 'BBC 核实：德黑兰东部发生多起爆炸',
    date: '2026-06-14T09:56:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.72, lng: 51.52 },
    description: 'BBC Verify 确认德黑兰省帕迪斯（德黑兰以东）出现爆炸与浓烟的新视频。卫星图显示烟柱区域，具体目标尚未判定。以军此前称在德黑兰与贝鲁特实施「同步打击」。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-4',
    title: '驻伊记者：德黑兰「每一片」都遭打击，大巴扎成废墟',
    date: '2026-06-14T09:44:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗境内记者对 BBC 表示，自周六以来德黑兰「每一片」都遭到美以打击，包括通信塔、广播站与城市大巴扎，后者已被「夷为废墟」。他认为这是「对军事与平民的系统性攻击」。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-5',
    title: 'BBC 核实：纳坦兹核设施卫星图显示新损毁',
    date: '2026-06-14T10:53:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.72, lng: 51.73 },
    description: 'BBC Verify 复核情报公司卫星图，伊朗中部纳坦兹核设施内三栋建筑遭击中，据分析与「地下燃料浓缩综合体的人员与车辆入口」相关。国际原子能机构评估「预计无放射性后果」。',
    source: 'bbc',
    link: 'https://www.bbc.com/news/articles/cdxzzkkkwjqo',
  },
  {
    id: 'evt-bbc-6',
    title: '英国首班撤侨包机将「未来数日」从阿曼起飞',
    date: '2026-06-14T12:32:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 23.61, lng: 58.59 },
    description: '英国外交大臣库珀向下议院表示，政府包机将「未来数日」从马斯喀特起飞。截至周二上午已有 13 万英国公民在中东「登记 presence」计划中注册。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-7',
    title: 'BBC 核实：阿联酋富查伊拉油港起火与损毁',
    date: '2026-06-14T12:29:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 25.12, lng: 56.36 },
    description: 'BBC Verify 核查视频与卫星图，阿曼湾沿岸富查伊拉石油码头发生火灾。运营方 VTTI 称已「鉴于最新事态」预防性暂停作业。卫星显示至少一座储罐受损、周围有燃烧痕迹，NASA 卫星在当日 09:00 当地时检测到热信号。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-8',
    title: '以军对黎巴嫩 80 余城镇发布新撤离警告',
    date: '2026-06-14T11:05:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.8547, lng: 35.8623 },
    description: '以军阿拉伯媒体发言人阿德莱在 X 上列出黎巴嫩多地，要求居民撤离并「不要返回」，至少远离所列地点 1000 米，并警告靠近伊朗支持的真主党「人员与设施」者将面临生命危险。名单包括提尔、宾特朱拜勒等 80 余城镇。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-9',
    title: '以色列拦截新一轮伊朗打击，全国拉响避难警报',
    date: '2026-06-14T11:09:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 32.0853, lng: 34.7818 },
    description: '以军称伊朗向以色列发动新一轮导弹袭击，防御系统正在「拦截威胁」，要求居民进入避难所并「留待进一步通知」。特拉维夫等多地报告响起警报。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-10',
    title: '加沙凯雷姆·沙洛姆口岸自袭击以来首次重开',
    date: '2026-06-14T11:21:00Z',
    type: 'diplomatic',
    faction: 'israel',
    location: { lat: 31.23, lng: 34.27 },
    description: '以色列称已重开与加沙地带的主要过境点凯雷姆·沙洛姆，为人道物资进入战乱地带的关键路线。联合国与援助机构此前警告口岸关闭导致加沙食品与燃料迅速耗尽。以方称关闭系因「导弹威胁」危及以巴工人。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-11',
    title: '英国考虑派遣 HMS 邓肯号赴地中海护卫塞浦路斯基地',
    date: '2026-06-14T11:44:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 34.59, lng: 32.99 },
    description: '英国政府正考虑将 HMS 邓肯号派往地中海，国防消息人士称尚未最终决定。该 45 型驱逐舰主要用于防空，可能用于加强遭伊朗无人机袭击的塞浦路斯 RAF 阿克罗蒂里基地周边安全。',
    source: 'bbc',
  },
  {
    id: 'evt-bbc-12',
    title: '阿曼拦截两架无人机，第三架坠毁于塞拉莱港附近',
    date: '2026-06-14T12:09:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 17.02, lng: 54.09 },
    description: '阿曼国家通讯社称，该国西南部佐法尔地区拦截两架无人机，第三架在西南部最大港口塞拉莱港附近坠毁。阿曼称无人员伤亡。',
    source: 'bbc',
  },
  // ---------- CNN 来源 ----------
  {
    id: 'evt-cnn-1',
    title: '美军战机在科威特坠毁，CNN 地理定位证实靠近阿里·萨利姆基地',
    date: '2026-06-13T14:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 29.35, lng: 47.52 },
    description: 'CNN 核实视频显示一架战机在科威特境内起火尾旋坠毁，落点距美军阿里·萨利姆基地约 10 公里。画面中的双发战机与 F-15E 相符，坠机原因及所属空军尚未确认。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-2',
    title: '英国从塞浦路斯空军基地撤离家属，此前遭无人机袭击',
    date: '2026-06-13T08:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 34.59, lng: 32.99 },
    description: '周日夜间一架单向攻击无人机击中塞浦路斯英军阿克罗蒂里基地，造成轻微破坏。英国国防部称撤离家属为「预防措施」，基地仍全面运作，并已加强雷达、反无人机与 F-35 等防御。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-3',
    title: '德黑兰再遭轰炸，圣城桑达杰遭导弹袭击致 3 人死亡',
    date: '2026-06-13T06:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗首都德黑兰周一早晨再次传出爆炸，塔斯尼姆称西部城市桑达杰居民区遭导弹袭击。IRNA 称桑达杰袭击致 3 人死亡。德黑兰甘地医院及阿瓦士附近医院在袭击中受损，病人被转移。以军称打击了「德黑兰中部伊朗恐怖政权目标」。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-4',
    title: '以军空袭黎巴嫩首都及南部，至少 31 人死亡、140 余人受伤',
    date: '2026-06-13T12:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.8547, lng: 35.8623 },
    description: '黎巴嫩卫生部称以军对黎南部和贝鲁特的空袭已致至少 31 人死亡、140 余人受伤，其中约 20 人死于贝鲁特南郊。以军确认打击了「贝鲁特地区真主党高级恐怖分子」及「黎南部真主党核心指挥官」。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-5',
    title: '科威特炼油厂遭飞溅弹片击中，两名工人受伤',
    date: '2026-06-13T04:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 29.08, lng: 48.17 },
    description: '科威特国家通讯社称，米纳·艾哈迈迪石油设施周一凌晨遭坠落弹片击中，两名工人受伤送医，炼油厂日产能 34.6 万桶未受影响。发言人称应急小组已启动快速响应，设施无重大物质损坏。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-6',
    title: '美国驻科威特使馆要求公民就地避难',
    date: '2026-06-13T10:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 29.38, lng: 47.99 },
    description: '美国驻科威特使馆发布警告，要求美国公民在导弹与无人机威胁持续期间就地避难，「不要前往使馆，留在住所最低层、远离窗户」。科威特称防空系统在哈瓦利省鲁迈西耶与萨尔瓦附近拦截了「大部分经海路接近的敌对无人机」。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-7',
    title: '霍尔木兹海峡油轮遇袭，航运威胁升级',
    date: '2026-06-13T09:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 26.5, lng: 56.5 },
    description: '德国赫伯罗特暂停霍尔木兹海峡通行；阿曼外海油轮「Skylight」遇袭。伊朗半官方媒体称一艘油轮在「未经授权通过霍尔木兹海峡」后遭袭并正在沉没，海峡航运面临严重干扰。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-8',
    title: '特朗普：对伊「大浪」攻势尚未到来，战争或持续四至五周',
    date: '2026-06-13T18:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 35.69, lng: 51.42 },
    description: '特朗普对 CNN 表示，美国对伊朗的「大浪」攻击尚未到来；战争目标包括摧毁伊朗导弹能力、歼灭其海军、终结核计划并阻止其武装代理人。特朗普称战争可能持续四至五周，并称伊朗对阿拉伯国家的袭击是「最大意外」。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-9',
    title: '伊朗女校遭袭逾百学童丧生，CNN 核查现场画面',
    date: '2026-06-12T15:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 35.70, lng: 51.42 },
    description: '伊朗官方媒体称一所女子小学遭袭，逾 150 名女童死亡、多人受伤。CNN 对手机拍摄的现场画面进行了调查核实。国际舆论关注平民伤亡。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-10',
    title: '三名美军人员在科威特疑似无人机袭击中阵亡',
    date: '2026-06-13T02:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 29.35, lng: 47.52 },
    description: '消息人士称，三名美军人员在科威特境内疑似无人机袭击中阵亡。特朗普警告称根据五角大楼预估，可能还有更多军人伤亡。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-11',
    title: '真主党加入冲突，以军基地遭导弹与无人机报复',
    date: '2026-06-12T20:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 32.8, lng: 35.0 },
    description: '伊朗支持的黎巴嫩真主党称对以军基地发动袭击「为最高领袖之死复仇」。以军与真主党在黎以边境交火，以方誓言加强对黎巴嫩打击。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-12',
    title: '美英称击沉九艘伊朗海军舰艇，伊海军总部遭重创',
    date: '2026-06-12T12:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 26.5, lng: 56.0 },
    description: '特朗普称美军已击沉九艘伊朗海军舰艇并「基本摧毁」其海军总部。美国中央司令部称周六遭袭的一艘伊朗军舰「正在阿曼湾沉没」。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-13',
    title: '英法德同意与美协同应对伊朗导弹攻击',
    date: '2026-06-13T14:30:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 51.5074, lng: -0.1278 },
    description: '德国、英国、法国表示同意与美国及盟友协同应对伊朗导弹攻击。英国同意美方请求，允许美军使用其军事基地对伊朗导弹阵地实施行动。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-14',
    title: '伊朗外长喊话美国民众「夺回国家」，伊方拒绝与美谈判',
    date: '2026-06-13T16:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗外长称「美国人民值得更好，应夺回自己的国家」，呼应特朗普对伊朗民众的类似表述。伊朗最高国安官员拉里贾尼称「不会与美国谈判」。特朗普称伊朗新领导层「想谈」，白宫高官称其「最终」会与潜在新领导层接触。',
    source: 'cnn',
  },
  {
    id: 'evt-cnn-15',
    title: '伊媒展示地下无人机机队与隧道储备',
    date: '2026-06-13T11:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗官方 affiliated 媒体发布视频，展示地下隧道中成排存放的无人机及装于发射架上的无人机，墙壁饰有革命标志，凸显伊方非对称战力。',
    source: 'cnn',
  },
  // ---------- 国家通讯社、中东/欧美/日韩主要媒体（中东局势报道）----------
  {
    id: 'evt-afp-1',
    title: '法新社：伊朗称将报复「侵略者」，不排除关闭霍尔木兹',
    date: '2026-06-14T08:20:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗外交部通过法新社发表声明，称将对「侵略者」采取一切必要回应，并称若局势继续升级不排除「对霍尔木兹海峡通行采取措施」。',
    source: 'afp',
  },
  {
    id: 'evt-xinhua-1',
    title: '新华社：中方呼吁有关各方冷静克制，避免局势进一步升级',
    date: '2026-06-14T07:15:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 39.9042, lng: 116.4074 },
    description: '外交部发言人表示，中方对中东局势深表关切，呼吁有关各方冷静克制，通过对话协商解决分歧，避免采取导致局势进一步升级的行动。',
    source: 'xinhua',
  },
  {
    id: 'evt-xinhua-2',
    title: '新华社：王毅就中东局势同多国外长通电话，强调反对单边军事行动',
    date: '2026-06-14T05:30:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 39.9042, lng: 116.4074 },
    description: '新华社报道，中共中央政治局委员、外交部长王毅应约同伊朗、沙特、阿联酋等国外长通电话，阐明中方主张维护伊核协议、反对单边军事行动、防止人道主义灾难的立场。',
    source: 'xinhua',
  },
  {
    id: 'evt-xinhua-3',
    title: '新华社：中国驻伊朗、以色列使馆发布安全提醒',
    date: '2026-06-13T22:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 35.6892, lng: 51.389 },
    description: '新华社记者从外交部领保中心获悉，中国驻伊朗、以色列使馆已发布安全提醒，建议在当地中国公民密切关注局势、加强防范、必要时及时撤离。',
    source: 'xinhua',
  },
  {
    id: 'evt-xinhua-4',
    title: '新华社：专家称霍尔木兹局势若持续将推高我国进口能源成本',
    date: '2026-06-14T09:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 26.2235, lng: 56.3765 },
    description: '新华社援引国家发改委能源所专家称，我国自中东经霍尔木兹海峡的原油进口占比逾四成，若海峡封锁长期化，将推高进口成本并考验战略储备与多元化供应能力。',
    source: 'xinhua',
  },
  {
    id: 'evt-xinhua-5',
    title: '新华社：中方在安理会呼吁立即停火、避免平民伤亡',
    date: '2026-06-13T20:45:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 40.7128, lng: -74.006 },
    description: '新华社联合国电，中国常驻联合国代表在安理会中东局势紧急会议上发言，呼吁有关各方立即停火止战、保护平民、通过对话解决分歧，反对任何加剧紧张的单边行动。',
    source: 'xinhua',
  },
  {
    id: 'evt-xinhua-6',
    title: '新华社：中国红十字会向伊朗红新月会提供人道主义援助',
    date: '2026-06-14T12:20:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 35.6892, lng: 51.389 },
    description: '新华社报道，中国红十字会决定向伊朗红新月会提供紧急人道主义物资援助，用于救助受冲突影响的民众，并呼吁国际社会加大人道救援力度。',
    source: 'xinhua',
  },
  {
    id: 'evt-reuters-1',
    title: '路透：OPEC+ 称将密切跟踪霍尔木兹局势，必要时评估产量',
    date: '2026-06-14T11:00:00Z',
    type: 'diplomatic',
    faction: 'iran',
    location: { lat: 26.2235, lng: 50.5876 },
    description: '路透援引 OPEC+ 内部人士称，产油国将密切跟踪霍尔木兹海峡与波斯湾供应风险，若出现持续性断供将评估增产或释放备用产能。',
    source: 'reuters',
  },
  {
    id: 'evt-ap-1',
    title: '美联社：美国务院敦促公民立即离开黎巴嫩与以色列',
    date: '2026-06-14T09:30:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 33.8547, lng: 35.8623 },
    description: '美国国务院通过美联社发布旅行警告，敦促在黎巴嫩与以色列的美国公民立即离开，称当地安全形势不可预测且可能迅速恶化。',
    source: 'ap',
  },
  {
    id: 'evt-tass-1',
    title: '塔斯社：俄外长称美以行动破坏地区稳定，呼吁安理会介入',
    date: '2026-06-13T18:00:00Z',
    type: 'diplomatic',
    faction: 'iran',
    location: { lat: 55.7558, lng: 37.6173 },
    description: '俄罗斯外长拉夫罗夫通过塔斯社表示，美以对伊朗的军事行动严重破坏地区稳定，俄方将推动安理会就停火与降级进行讨论。',
    source: 'tass',
  },
  {
    id: 'evt-kyodo-1',
    title: '共同社：日本政府考虑追加撤侨与经阿曼中转方案',
    date: '2026-06-14T04:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 35.6762, lng: 139.6503 },
    description: '共同社报道，日本政府鉴于中东局势升级，正考虑扩大撤侨范围并探讨经阿曼等第三国中转的包机方案，与英方协调使用马斯喀特。',
    source: 'kyodo',
  },
  {
    id: 'evt-aljazeera-1',
    title: '半岛电视台：加沙人道走廊在冲突升级后再次受阻',
    date: '2026-06-14T10:30:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 31.5017, lng: 34.4668 },
    description: '半岛电视台驻加沙记者报道，凯雷姆·沙洛姆口岸在短暂重开后因以伊交火再次关闭，人道物资进入加沙的通道受阻。',
    source: 'al_jazeera',
  },
  {
    id: 'evt-alarabiya-1',
    title: '阿拉比亚：沙特与阿联酋呼吁各方克制，强调海湾安全',
    date: '2026-06-13T14:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 24.7136, lng: 46.6753 },
    description: '阿拉比亚电视台报道，沙特与阿联酋外交部发表联合声明，呼吁有关各方克制，避免冲突外溢，并强调海湾国家安全与航道畅通的重要性。',
    source: 'al_arabiya',
  },
  {
    id: 'evt-times-israel-1',
    title: '以色列时报：以军称已摧毁黎南部真主党多处指挥节点',
    date: '2026-06-14T12:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.2667, lng: 35.2033 },
    description: '以色列时报援引以军声明称，过去 24 小时内以军空袭摧毁了黎巴嫩南部真主党多处指挥所与弹药库，真主党向以北部发射了数十枚火箭。',
    source: 'times_of_israel',
  },
  {
    id: 'evt-irna-1',
    title: '伊通社：伊朗革命卫队称击落多架来袭无人机',
    date: '2026-06-14T09:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗伊斯兰共和国通讯社报道，革命卫队防空部队在德黑兰及伊斯法罕等地击落多架「敌对无人机」，并称将坚决回应任何侵略。',
    source: 'irna',
  },
  {
    id: 'evt-press-tv-1',
    title: 'Press TV：伊朗总统称将捍卫主权，不向「霸凌」屈服',
    date: '2026-06-13T16:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '伊朗 Press TV 播出总统声明，称伊朗将捍卫国家主权与尊严，不会向「西方与犹太复国主义霸凌」屈服，并呼吁民众团结。',
    source: 'press_tv',
  },
  {
    id: 'evt-nyt-1',
    title: '纽约时报：美国情报评估伊朗短期内难以大规模封锁海峡',
    date: '2026-06-14T06:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 38.9072, lng: -77.0369 },
    description: '纽约时报援引美国情报官员称，评估认为伊朗短期内难以对霍尔木兹海峡实施大规模封锁，但零星袭击与布雷风险上升。',
    source: 'nyt',
  },
  {
    id: 'evt-dw-1',
    title: '德国之声：欧盟召开紧急外长会讨论中东与能源供应',
    date: '2026-06-14T13:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 50.8503, lng: 4.3517 },
    description: '德国之声报道，欧盟召开紧急外长会议，讨论美以伊冲突对地区安全与欧洲能源供应的影响，以及人道与撤侨协调。',
    source: 'dw',
  },
  {
    id: 'evt-nhk-1',
    title: 'NHK：日本经产省称将确保原油与 LNG 稳定供应',
    date: '2026-06-14T02:30:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 35.6762, lng: 139.6503 },
    description: 'NHK 报道，日本经济产业省表示将与美国及产油国协调，确保日本原油与 LNG 供应稳定，必要时动用国家储备。',
    source: 'nhk',
  },
  {
    id: 'evt-yonhap-1',
    title: '韩联社：韩国政府启动中东局势应急机制，考虑释放石油储备',
    date: '2026-06-14T03:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 37.5665, lng: 126.978 },
    description: '韩联社报道，韩国政府召开紧急会议启动中东局势应急机制，产业部称若油价持续飙升将考虑释放部分石油储备以稳定国内供应。',
    source: 'yonhap',
  },
  {
    id: 'evt-kbs-1',
    title: 'KBS：韩股因中东风险与油价双杀大幅低开',
    date: '2026-06-14T01:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 37.5665, lng: 126.978 },
    description: 'KBS 财经报道，首尔股市因中东局势升级与国际油价跳涨大幅低开，韩元兑美元走弱，炼化与航空板块领跌。',
    source: 'kbs',
  },
  {
    id: 'evt-yomiuri-1',
    title: '读卖新闻：日经指数因避险情绪大跌，资金流入黄金与日元',
    date: '2026-06-14T02:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 35.6762, lng: 139.6503 },
    description: '读卖新闻报道，东京股市因中东冲突升级与油价上涨大幅下挫，避险资金流入黄金与日元，出口股与能源相关股承压。',
    source: 'yomiuri',
  },
  {
    id: 'evt-hard-1',
    title: '伊朗革命卫队宣布对「领袖殉道」进行多线报复',
    date: '2026-06-13T14:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 35.6892, lng: 51.389 },
    description: '革命卫队司令萨拉米通过国家电视台称，将对美以目标实施「多线、多阶段」报复，包括以色列境内、美军基地及海湾盟国设施；真主党与也门胡塞已同步加大袭击。',
    source: 'press_tv',
  },
  {
    id: 'evt-hard-2',
    title: '伊拉克民兵袭击美驻叙基地，美军 F-15E 坠毁科威特附近',
    date: '2026-06-13T11:30:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 29.35, lng: 47.52 },
    description: '伊拉克伊斯兰抵抗组织对叙利亚坦夫与阿萨德美军基地发射火箭；同日美空军一架 F-15E 在科威特阿里·萨利姆基地附近坠毁，两名飞行员丧生，美方称正在调查是否与敌方火力有关。',
    source: 'bbc',
  },
  {
    id: 'evt-hard-3',
    title: 'IAEA：纳坦兹核查受限，呼吁各方保障核设施安全',
    date: '2026-06-14T15:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 33.72, lng: 51.73 },
    description: '国际原子能机构总干事称，纳坦兹等设施遭袭后核查员进入受限，呼吁冲突各方遵守国际法、避免针对民用核设施；强调目前评估无放射性泄漏。',
    source: 'bbc',
  },
  {
    id: 'evt-hard-4',
    title: '沙特、阿联酋关闭部分领空，多国航空公司改道',
    date: '2026-06-13T08:00:00Z',
    type: 'political',
    faction: 'us',
    location: { lat: 24.7, lng: 46.7 },
    description: '沙特民航局宣布暂时关闭东部省部分空域；阿联酋、巴林等跟进调整航线。阿联酋航空、卡塔尔航空等取消或改道经伊朗、伊拉克的航班，亚洲—欧洲航线绕行成本上升。',
    source: 'reuters',
  },
  {
    id: 'evt-hard-5',
    title: '以色列战时内阁批准扩大黎巴嫩地面行动',
    date: '2026-06-14T13:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.8547, lng: 35.8623 },
    description: '以战时内阁一致同意国防军「推进并占领黎巴嫩南部更多战略要地」以压制真主党火箭与反坦克火力；加兰特称行动将分阶段、与对伊打击并行。',
    source: 'times_of_israel',
  },
  {
    id: 'evt-hard-6',
    title: '胡塞武装称袭击红海与亚丁湾多艘商船及美军舰',
    date: '2026-06-13T16:00:00Z',
    type: 'military',
    faction: 'iran',
    location: { lat: 12.8, lng: 43.2 },
    description: '也门胡塞武装发言人称，为声援伊朗对红海与亚丁湾「与以色列相关」船只及美军舰发动无人机与导弹袭击；美军中央司令部称拦截多枚反舰弹，一艘商船轻微受损。',
    source: 'al_jazeera',
  },
  {
    id: 'me-inc-jun-1',
    title: '霍尔木兹海峡油轮通行量下降',
    date: '2026-06-15T08:00:00Z',
    type: 'political',
    faction: 'iran',
    location: { lat: 26.57, lng: 56.4 },
    description: '保险费率飙升致部分船东改道',
    source: '公开态势整理',
  },
  {
    id: 'me-inc-jun-2',
    title: '以色列北部火箭弹警报频发',
    date: '2026-06-14T20:00:00Z',
    type: 'military',
    faction: 'israel',
    location: { lat: 33.0, lng: 35.5 },
    description: '黎以边境交火升级',
    source: '公开态势整理',
  },
  {
    id: 'me-inc-jun-3',
    title: '沙特宣布临时增产稳市场',
    date: '2026-06-13T12:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 24.71, lng: 46.72 },
    description: 'OPEC+ 内部协调增产配额',
    source: '公开态势整理',
  },
  {
    id: 'me-inc-jun-4',
    title: '美军中央司令部增派航母战斗群',
    date: '2026-06-12T10:00:00Z',
    type: 'military',
    faction: 'us',
    location: { lat: 25.0, lng: 55.0 },
    description: '波斯湾前沿部署加强',
    source: '公开态势整理',
  },
  {
    id: 'me-inc-jun-5',
    title: '联合国呼吁红海航运安全',
    date: '2026-06-11T14:00:00Z',
    type: 'diplomatic',
    faction: 'us',
    location: { lat: 15.0, lng: 43.0 },
    description: '安理会讨论护航机制',
    source: '公开态势整理',
  },
]
