// 中东社交媒体热门帖 — LIFEOS-005 阶段3 第七批
// 迁自 Iran socialMediaData.ts，80 条真实账号热帖(特朗普/伊朗官方/IDF/BBC 等)。
import type { SocialMediaPost } from '@/types/middleeast';

export const MIDEAST_SOCIAL: SocialMediaPost[] = [
  // ————— 社媒账号（特朗普、伊朗官方、伊朗驻华使馆、IDF、BBC 等）；路透社内容仅在关键事件模块 —————
  {
    id: 'sm-idf-2',
    platform: 'x_twitter',
    authorName: 'Israel Defense Forces',
    handle: 'IDF',
    authorTitle: '以色列国防军官方',
    avatar: '🇮🇱',
    content: 'IDF prepared for weeks-long campaign against Iran. Ground forces deployment unlikely, spokesperson says. idf.il',
    publishedAt: '2026-03-03T16:00:00Z',
    hotRank: 1,
    likes: 198000,
    shares: 52000,
    comments: 8900,
    verified: true,
    faction: 'israel',
    link: 'https://www.reuters.com/world/middle-east/israel-prepared-weeks-long-iran-campaign-unlikely-deploy-ground-forces-2026-03-03/',
  },
  {
    id: 'sm-bbc-2',
    platform: 'x_twitter',
    authorName: 'BBC News',
    handle: 'BBCNews',
    authorTitle: 'BBC 新闻',
    avatar: '📺',
    content: 'Satellite images show Iranian navy and nuclear sites hit by US-Israeli strikes. IRINS Makran among vessels damaged.',
    publishedAt: '2026-03-04T08:00:00Z',
    hotRank: 2,
    likes: 145000,
    shares: 41000,
    comments: 5600,
    verified: true,
    link: 'https://www.bbc.com/news/articles/cdxzzkkkwjqo',
  },
  {
    id: 'sm-weibo-4',
    platform: 'weibo',
    authorName: '央视新闻',
    handle: 'cctvnews',
    authorTitle: '央视新闻官方微博',
    avatar: '📺',
    content: '【波斯湾局势】伊朗称击中美国油轮，美方未确认。斯里兰卡称正保障第二艘伊朗船船员安全。中方呼吁防止局势升级。',
    publishedAt: '2026-03-05T15:00:00Z',
    hotRank: 3,
    likes: 312000,
    shares: 98000,
    comments: 12800,
    verified: true,
  },
  {
    id: 'sm-telegram-irna-2',
    platform: 'telegram',
    authorName: 'IRNA 伊朗伊斯兰共和国通讯社',
    handle: 'IRNA_News',
    authorTitle: '官方通讯社',
    avatar: '🇮🇷',
    content: '革命卫队：我方在波斯湾击中一艘美国油轮。美国及其盟友必须停止对伊朗的侵略，否则将面临更大回应。',
    publishedAt: '2026-03-05T12:45:00Z',
    hotRank: 4,
    likes: 78000,
    shares: 36000,
    comments: 14200,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-trump-7',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Congress must not tie our hands. Iran hit our tanker—we need to hit back harder. No more weak responses.',
    publishedAt: '2026-03-05T13:20:00Z',
    hotRank: 5,
    likes: 523000,
    shares: 156000,
    comments: 42100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-aljazeera-2',
    platform: 'x_twitter',
    authorName: 'Al Jazeera English',
    handle: 'AJEnglish',
    authorTitle: '半岛电视台英文',
    avatar: '📺',
    content: 'Azerbaijan latest to report Iranian drone strike. Conflict spillover spreads to South Caucasus. ajenglish.com',
    publishedAt: '2026-03-05T10:30:00Z',
    hotRank: 6,
    likes: 68000,
    shares: 19000,
    comments: 4100,
    verified: true,
  },
  // ————— 特朗普 X 账号（高热度）—————
  {
    id: 'sm-trump-1',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: '伊朗必须立即停止对以色列的袭击。美国与以色列站在一起。我们不会允许德黑兰政权威胁我们的盟友。God Bless Israel.',
    publishedAt: '2026-03-03T14:22:00Z',
    hotRank: 13,
    likes: 892000,
    shares: 234000,
    comments: 67100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-2',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: '刚刚与内塔尼亚胡总理通话。以色列有权自卫。伊朗的核设施必须受到监督——不能让他们拥有核武器。Period.',
    publishedAt: '2026-03-03T11:45:00Z',
    hotRank: 14,
    likes: 567000,
    shares: 189000,
    comments: 42100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-3',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: '油价涨了是因为拜登和民主党对伊朗软弱。我任内我们制裁伊朗、承认耶路撒冷、促成阿以和平。现在一切都在倒退。',
    publishedAt: '2026-03-02T20:10:00Z',
    hotRank: 15,
    likes: 412000,
    shares: 98000,
    comments: 28900,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-4',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: '美国航母在哪里？我们必须在波斯湾展示力量。伊朗只懂实力。',
    publishedAt: '2026-03-03T08:30:00Z',
    hotRank: 16,
    likes: 356000,
    shares: 87000,
    comments: 22100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-5',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: '德黑兰的袭击是野蛮的。文明世界必须团结起来反对这个政权。Pray for Israel. Pray for the region.',
    publishedAt: '2026-03-03T06:15:00Z',
    hotRank: 17,
    likes: 298000,
    shares: 76000,
    comments: 18500,
    verified: true,
    faction: 'us',
  },
  // ————— 以色列官方 / 内塔尼亚胡 —————
  {
    id: 'sm-netanyahu-1',
    platform: 'x_twitter',
    authorName: 'Benjamin Netanyahu',
    handle: 'netanyahu',
    authorTitle: '以色列总理',
    avatar: '🇮🇱',
    content: 'We have the right to defend ourselves. Iran and its proxies will not dictate our future. The IDF will protect every Israeli citizen.',
    publishedAt: '2026-03-03T13:50:00Z',
    hotRank: 18,
    likes: 445000,
    shares: 156000,
    comments: 38900,
    verified: true,
    faction: 'israel',
  },
  {
    id: 'sm-idf-1',
    platform: 'x_twitter',
    authorName: 'Israel Defense Forces',
    handle: 'IDF',
    authorTitle: '以色列国防军官方',
    avatar: '🇮🇱',
    content: 'IDF targeted regime leadership compounds in Tehran. We will continue to strike those who seek to destroy us. Updates: idf.il',
    publishedAt: '2026-03-03T10:05:00Z',
    hotRank: 19,
    likes: 312000,
    shares: 92000,
    comments: 26700,
    verified: true,
    faction: 'israel',
  },
  {
    id: 'sm-netanyahu-2',
    platform: 'x_twitter',
    authorName: 'Benjamin Netanyahu',
    handle: 'netanyahu',
    authorTitle: '以色列总理',
    avatar: '🇮🇱',
    content: '与拜登总统、特朗普前总统及欧洲领导人保持密切协调。以色列不寻求 escalation，但绝不会容忍对平民的袭击。',
    publishedAt: '2026-03-03T09:20:00Z',
    hotRank: 20,
    likes: 198000,
    shares: 54000,
    comments: 14200,
    verified: true,
    faction: 'israel',
  },
  // ————— 伊朗官方 / 高层 —————
  {
    id: 'sm-khamenei-1',
    platform: 'x_twitter',
    authorName: 'Khamenei.ir',
    handle: 'khamenei_ir',
    authorTitle: '伊朗最高领袖办公室',
    avatar: '🇮🇷',
    content: 'The Zionist regime and America will pay for every drop of blood. Our response will be decisive. Resistance continues.',
    publishedAt: '2026-03-03T12:40:00Z',
    hotRank: 21,
    likes: 278000,
    shares: 125000,
    comments: 45300,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irna-1',
    platform: 'telegram',
    authorName: 'IRNA 伊朗伊斯兰共和国通讯社',
    handle: 'IRNA_News',
    authorTitle: '官方通讯社',
    avatar: '🇮🇷',
    content: '红新月会最新：美以袭击以来伊朗境内死亡人数升至 787 人。德黑兰、伊斯法罕、纳坦兹等多地遭袭。国际社会必须制止战争罪。',
    publishedAt: '2026-03-03T09:51:00Z',
    hotRank: 22,
    likes: 89000,
    shares: 42000,
    comments: 18900,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-presstv-1',
    platform: 'x_twitter',
    authorName: 'Press TV',
    handle: 'PressTV',
    authorTitle: '伊朗 Press TV 英文',
    avatar: '🇮🇷',
    content: 'BREAKING: Multiple explosions reported in Tehran. Israeli strikes hit presidential compound, state media says. Live updates: presstv.ir',
    publishedAt: '2026-03-03T10:07:00Z',
    hotRank: 23,
    likes: 156000,
    shares: 67000,
    comments: 22100,
    verified: true,
    faction: 'iran',
    link: 'https://www.presstv.ir/',
  },
  {
    id: 'sm-irgc-1',
    platform: 'telegram',
    authorName: 'IRGC 伊斯兰革命卫队',
    handle: 'IRGC_Official',
    authorTitle: '革命卫队官方频道',
    avatar: '🇮🇷',
    content: '我们向以色列占领区发射了新一轮导弹。侵略者必须明白：每一次袭击都会得到成倍回应。',
    publishedAt: '2026-03-03T11:09:00Z',
    hotRank: 24,
    likes: 112000,
    shares: 58000,
    comments: 16700,
    verified: true,
    faction: 'iran',
  },
  // ————— 国际媒体 / 通讯社 —————
  {
    id: 'sm-cnn-1',
    platform: 'x_twitter',
    authorName: 'CNN',
    handle: 'CNN',
    authorTitle: 'CNN 国际',
    avatar: '📺',
    content: 'LIVE: Israel strikes Tehran in major escalation. Iran reports casualties. Follow our live coverage: cnn.com/world',
    publishedAt: '2026-03-03T10:15:00Z',
    hotRank: 25,
    likes: 187000,
    shares: 72000,
    comments: 12400,
    verified: true,
  },
  {
    id: 'sm-bbc-1',
    platform: 'x_twitter',
    authorName: 'BBC News',
    handle: 'BBCNews',
    authorTitle: 'BBC 新闻',
    avatar: '📺',
    content: 'Iran death toll rises to 787 after US-Israel attacks - Red Crescent. BBC Verify assesses damage at Natanz nuclear site. bbc.in/mideast',
    publishedAt: '2026-03-03T09:55:00Z',
    hotRank: 26,
    likes: 165000,
    shares: 61000,
    comments: 9800,
    verified: true,
    link: 'https://www.bbc.com/news/live/cy0dp1l57nxt',
  },
  {
    id: 'sm-aljazeera-1',
    platform: 'x_twitter',
    authorName: 'Al Jazeera English',
    handle: 'AJEnglish',
    authorTitle: '半岛电视台英文',
    avatar: '📺',
    content: 'Tehran resident to Al Jazeera: "Every part of the city has been hit." Bazaar in ruins, communications down. Our correspondents on the ground: ajenglish.com',
    publishedAt: '2026-03-03T09:44:00Z',
    hotRank: 28,
    likes: 134000,
    shares: 52000,
    comments: 18700,
    verified: true,
  },
  {
    id: 'sm-nyt-1',
    platform: 'x_twitter',
    authorName: 'The New York Times',
    handle: 'nytimes',
    authorTitle: '纽约时报',
    avatar: '📰',
    content: 'U.S. and Israel launched coordinated strikes on Iran, targeting leadership and nuclear facilities. What we know so far. nyti.ms/iran',
    publishedAt: '2026-03-03T09:30:00Z',
    hotRank: 29,
    likes: 142000,
    shares: 48000,
    comments: 11200,
    verified: true,
  },
  {
    id: 'sm-axios-1',
    platform: 'x_twitter',
    authorName: 'Axios',
    handle: 'axios',
    authorTitle: 'Axios 新闻',
    avatar: '📰',
    content: 'Biden briefed on Iran strikes. White House: "We support Israel\'s right to self-defense." European capitals call for de-escalation. axios.com',
    publishedAt: '2026-03-03T11:00:00Z',
    hotRank: 30,
    likes: 76000,
    shares: 28000,
    comments: 6400,
    verified: true,
  },
  // ————— 政要 / 评论员 —————
  {
    id: 'sm-biden-1',
    platform: 'x_twitter',
    authorName: 'Joe Biden',
    handle: 'JoeBiden',
    authorTitle: '美国第46任总统',
    avatar: '🇺🇸',
    content: 'Spoke with PM Netanyahu. Our commitment to Israel\'s security is ironclad. We are working with allies to prevent further escalation and protect civilians.',
    publishedAt: '2026-03-03T12:20:00Z',
    hotRank: 31,
    likes: 198000,
    shares: 42000,
    comments: 28900,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-sullivan-1',
    platform: 'x_twitter',
    authorName: 'Jake Sullivan',
    handle: 'JakeSullivan46',
    authorTitle: '美国国家安全顾问',
    avatar: '🇺🇸',
    content: 'We are in close contact with Israel, Gulf partners, and European allies. Our focus: avoid regional war, ensure humanitarian access, hold Iran accountable.',
    publishedAt: '2026-03-03T10:50:00Z',
    hotRank: 32,
    likes: 67000,
    shares: 22000,
    comments: 5100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-weibo-1',
    platform: 'weibo',
    authorName: '央视新闻',
    handle: 'cctvnews',
    authorTitle: '央视新闻官方微博',
    avatar: '📺',
    content: '【中东局势】美以对伊朗多地发动袭击，伊朗红新月会称死亡人数升至 787 人。中方呼吁有关各方冷静克制，通过对话解决分歧。',
    publishedAt: '2026-03-03T16:00:00Z',
    hotRank: 33,
    likes: 234000,
    shares: 89000,
    comments: 15600,
    verified: true,
  },
  {
    id: 'sm-weibo-2',
    platform: 'weibo',
    authorName: '人民日报',
    handle: 'people_daily',
    authorTitle: '人民日报',
    avatar: '📰',
    content: '外交部：中方对中东局势升级深表关切，反对任何加剧紧张的行为。呼吁落实联合国安理会相关决议，维护地区和平稳定。',
    publishedAt: '2026-03-03T15:30:00Z',
    hotRank: 34,
    likes: 187000,
    shares: 72000,
    comments: 12300,
    verified: true,
  },
  {
    id: 'sm-telegram-cnn-1',
    platform: 'telegram',
    authorName: 'CNN International',
    handle: 'cnn_intl',
    authorTitle: 'CNN 国际 Telegram',
    avatar: '📺',
    content: 'UK to send HMS Duncan to Mediterranean; France urges citizens to leave Lebanon. Evacuation flights from Oman "in coming days."',
    publishedAt: '2026-03-03T12:32:00Z',
    hotRank: 35,
    likes: 42000,
    shares: 18000,
    comments: 3400,
    verified: true,
  },
  {
    id: 'sm-times-israel-1',
    platform: 'x_twitter',
    authorName: 'Times of Israel',
    handle: 'TimesofIsrael',
    authorTitle: '以色列时报',
    avatar: '📰',
    content: 'Israel reopens Kerem Shalom crossing to Gaza for first time since attacks. UN welcomes move, urges more aid routes. timesofisrael.com',
    publishedAt: '2026-03-03T11:21:00Z',
    hotRank: 36,
    likes: 54000,
    shares: 15000,
    comments: 4200,
    verified: true,
    faction: 'israel',
  },
  {
    id: 'sm-ft-1',
    platform: 'x_twitter',
    authorName: 'Financial Times',
    handle: 'FT',
    authorTitle: '金融时报',
    avatar: '📰',
    content: 'Brent crude surges as Iran-Israel conflict raises supply fears. Analysts: "Risk premium could push oil to $100+ if Hormuz disrupted." on.ft.com/oil',
    publishedAt: '2026-03-03T08:55:00Z',
    hotRank: 37,
    likes: 62000,
    shares: 24000,
    comments: 3800,
    verified: true,
  },
  {
    id: 'sm-trump-6',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Remember: I moved the Embassy to Jerusalem. I brokered the Abraham Accords. Weak leadership got us here. We need strength in the White House.',
    publishedAt: '2026-03-02T18:00:00Z',
    hotRank: 38,
    likes: 412000,
    shares: 89000,
    comments: 32100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-dw-1',
    platform: 'x_twitter',
    authorName: 'DW News',
    handle: 'dwnews',
    authorTitle: '德国之声',
    avatar: '📺',
    content: 'Germany, France call for immediate ceasefire. Scholz: "Civilian suffering must end." EU to discuss additional sanctions on Iran. dw.com',
    publishedAt: '2026-03-03T13:10:00Z',
    hotRank: 39,
    likes: 48000,
    shares: 16000,
    comments: 2900,
    verified: true,
  },
  {
    id: 'sm-ap-1',
    platform: 'x_twitter',
    authorName: 'The Associated Press',
    handle: 'AP',
    authorTitle: '美联社',
    avatar: '📰',
    content: 'AP: Israel orders evacuations in 80+ Lebanese towns. Hezbollah infrastructure targeted. UN peacekeepers on high alert. apnews.com',
    publishedAt: '2026-03-03T11:05:00Z',
    hotRank: 40,
    likes: 52000,
    shares: 19000,
    comments: 4100,
    verified: true,
  },
  {
    id: 'sm-weibo-3',
    platform: 'weibo',
    authorName: '环球网',
    handle: 'huanqiucom',
    authorTitle: '环球网',
    avatar: '📰',
    content: '中东局势持续升级：德黑兰、纳坦兹等多地遇袭，国际油价跳涨。专家称若霍尔木兹海峡受阻，全球能源供应将受严重影响。',
    publishedAt: '2026-03-03T14:20:00Z',
    hotRank: 41,
    likes: 98000,
    shares: 45000,
    comments: 8700,
    verified: true,
  },
  {
    id: 'sm-afp-1',
    platform: 'x_twitter',
    authorName: 'AFP News Agency',
    handle: 'AFP',
    authorTitle: '法新社',
    avatar: '📰',
    content: 'Fujairah oil terminal fire: satellite imagery shows damage. VTTI suspends operations. NASA FIRMS detected thermal anomaly. afp.com',
    publishedAt: '2026-03-03T12:29:00Z',
    hotRank: 42,
    likes: 38000,
    shares: 14000,
    comments: 2200,
    verified: true,
  },
  {
    id: 'sm-afp-2',
    platform: 'x_twitter',
    authorName: 'AFP News Agency',
    handle: 'AFP',
    authorTitle: '法新社',
    avatar: '📰',
    content: 'Azerbaijan: two injured by drones/missiles from Iran direction. Conflict spillover to South Caucasus. afp.com',
    publishedAt: '2026-03-05T10:30:00Z',
    hotRank: 43,
    likes: 42000,
    shares: 12000,
    comments: 2100,
    verified: true,
  },
  {
    id: 'sm-weibo-5',
    platform: 'weibo',
    authorName: '参考消息',
    handle: 'cankaoxiaoxi',
    authorTitle: '参考消息',
    avatar: '📰',
    content: '美伊战事进入第六天：共和党阻止叫停空袭议案，伊朗称击中美国油轮。斯里兰卡保障伊朗船员，阿塞拜疆称遭无人机致伤。',
    publishedAt: '2026-03-05T16:00:00Z',
    hotRank: 44,
    likes: 156000,
    shares: 52000,
    comments: 8900,
    verified: true,
  },
  {
    id: 'sm-telegram-bbc',
    platform: 'telegram',
    authorName: 'BBC News',
    handle: 'bbcnews',
    authorTitle: 'BBC 新闻 Telegram',
    avatar: '📺',
    content: 'UK considers sending HMS Duncan to Mediterranean. France to send frigate and air defences to Cyprus. RAF shot down Iranian drone over Jordan.',
    publishedAt: '2026-03-03T14:00:00Z',
    hotRank: 45,
    likes: 38000,
    shares: 15000,
    comments: 2800,
    verified: true,
  },
  {
    id: 'sm-nyt-2',
    platform: 'x_twitter',
    authorName: 'The New York Times',
    handle: 'nytimes',
    authorTitle: '纽约时报',
    avatar: '📰',
    content: 'Poll: Only 1 in 4 Americans support U.S. strikes on Iran. Trump and Netanyahu war aims show signs of divergence. nyti.ms',
    publishedAt: '2026-03-04T20:00:00Z',
    hotRank: 46,
    likes: 98000,
    shares: 32000,
    comments: 7600,
    verified: true,
  },
  {
    id: 'sm-idf-3',
    platform: 'x_twitter',
    authorName: 'Israel Defense Forces',
    handle: 'IDF',
    authorTitle: '以色列国防军官方',
    avatar: '🇮🇱',
    content: 'IDF strikes Hezbollah targets in Beirut and southern Lebanon. Evacuation orders issued for 80+ towns. idf.il',
    publishedAt: '2026-03-03T11:10:00Z',
    hotRank: 47,
    likes: 125000,
    shares: 38000,
    comments: 5400,
    verified: true,
    faction: 'israel',
  },
  // ————— 特朗普 X 账号（大量新增）—————
  {
    id: 'sm-trump-8',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'The Fake News says I want regime change. I want Iran to STOP attacking our allies and STOP building nukes. Simple. We will destroy their capability—that\'s the mission.',
    publishedAt: '2026-03-05T09:00:00Z',
    hotRank: 49,
    likes: 445000,
    shares: 112000,
    comments: 28900,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-9',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Just spoke with Bibi. Israel has every right to defend itself. Iran started this—we will finish it. No nuclear weapons for Tehran. EVER.',
    publishedAt: '2026-03-04T22:30:00Z',
    hotRank: 50,
    likes: 512000,
    shares: 134000,
    comments: 35600,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-10',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Oil is up because of Iran and the Middle East mess. Under me we were energy dominant. We will be again. Drill, baby, drill.',
    publishedAt: '2026-03-04T18:45:00Z',
    hotRank: 51,
    likes: 398000,
    shares: 98000,
    comments: 22100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-11',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Democrats want to tie our military\'s hands. They voted to stop the air campaign. Thank you to Republicans for standing with our troops and Israel.',
    publishedAt: '2026-03-05T15:00:00Z',
    hotRank: 52,
    likes: 567000,
    shares: 145000,
    comments: 42100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-12',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Iran hit our tanker. We hit back. That\'s how it works. No more Obama-style apologies. America First.',
    publishedAt: '2026-03-05T12:00:00Z',
    hotRank: 53,
    likes: 623000,
    shares: 178000,
    comments: 52100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-13',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Praying for the families of our fallen soldiers in Kuwait. We will not forget their sacrifice. Iran will pay a heavy price.',
    publishedAt: '2026-03-02T20:00:00Z',
    hotRank: 54,
    likes: 712000,
    shares: 198000,
    comments: 45200,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-14',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'The Iran deal was a disaster. I got us out. Now we\'re finishing the job. No nukes in Iran. Period.',
    publishedAt: '2026-03-03T11:00:00Z',
    hotRank: 55,
    likes: 489000,
    shares: 125000,
    comments: 31200,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-15',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Saudi and the Gulf need to step up. We protect them—they need to support the mission. No more free rides.',
    publishedAt: '2026-03-04T14:00:00Z',
    hotRank: 56,
    likes: 356000,
    shares: 89000,
    comments: 28700,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-16',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'CNN and the rest are rooting for Iran. They always side against America. Don\'t believe the fake news. We are winning.',
    publishedAt: '2026-03-03T16:30:00Z',
    hotRank: 57,
    likes: 534000,
    shares: 156000,
    comments: 62300,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-17',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Natanz, Fordow—we know where every site is. Iran cannot hide. We have the best intelligence in the world.',
    publishedAt: '2026-03-03T10:15:00Z',
    hotRank: 58,
    likes: 412000,
    shares: 102000,
    comments: 24100,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-18',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Hezbollah, Houthis, Iraqi militias—all Iran\'s proxies. We are hitting the head of the snake. Cut the head, the body dies.',
    publishedAt: '2026-03-02T19:00:00Z',
    hotRank: 59,
    likes: 478000,
    shares: 118000,
    comments: 29800,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-19',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Four to five weeks. That\'s the estimate. Then Iran\'s military and nuclear threat will be eliminated. We have the resolve.',
    publishedAt: '2026-03-02T18:30:00Z',
    hotRank: 60,
    likes: 398000,
    shares: 95000,
    comments: 26700,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-20',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Moving the Embassy to Jerusalem was the right call. Abraham Accords—my achievement. Weak leadership undid it. We\'re fixing that now.',
    publishedAt: '2026-03-01T22:00:00Z',
    hotRank: 61,
    likes: 445000,
    shares: 108000,
    comments: 31200,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-21',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'Our sailors and pilots are the best in the world. Submarine took out an Iranian ship that attacked us. That\'s deterrence.',
    publishedAt: '2026-03-05T08:00:00Z',
    hotRank: 62,
    likes: 523000,
    shares: 132000,
    comments: 38900,
    verified: true,
    faction: 'us',
  },
  {
    id: 'sm-trump-22',
    platform: 'x_twitter',
    authorName: 'Donald J. Trump',
    handle: 'realDonaldTrump',
    authorTitle: '美国第47任总统',
    avatar: '🇺🇸',
    content: 'God Bless the United States. God Bless Israel. We will prevail. 🇺🇸 🇮🇱',
    publishedAt: '2026-03-03T08:00:00Z',
    hotRank: 63,
    likes: 678000,
    shares: 212000,
    comments: 52100,
    verified: true,
    faction: 'us',
  },
  // ————— 伊朗官方账号（大量新增）—————
  {
    id: 'sm-khamenei-2',
    platform: 'x_twitter',
    authorName: 'Khamenei.ir',
    handle: 'khamenei_ir',
    authorTitle: '伊朗最高领袖办公室',
    avatar: '🇮🇷',
    content: 'The blood of our martyrs will not be forgotten. The resistance axis will continue. Israel and America will regret their crimes.',
    publishedAt: '2026-03-02T15:00:00Z',
    hotRank: 64,
    likes: 312000,
    shares: 145000,
    comments: 52100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-khamenei-3',
    platform: 'telegram',
    authorName: 'Khamenei.ir',
    handle: 'khamenei_ir',
    authorTitle: '伊朗最高领袖办公室',
    avatar: '🇮🇷',
    content: '每一滴殉道者的鲜血都将得到回应。我们的人民团结一致，侵略者将付出代价。抵抗阵线不会屈服。',
    publishedAt: '2026-03-01T20:00:00Z',
    hotRank: 65,
    likes: 198000,
    shares: 89000,
    comments: 34200,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irna-3',
    platform: 'telegram',
    authorName: 'IRNA 伊朗伊斯兰共和国通讯社',
    handle: 'IRNA_News',
    authorTitle: '官方通讯社',
    avatar: '🇮🇷',
    content: '纳坦兹核设施遭袭：国际原子能机构评估无放射性泄漏。伊方谴责针对民用核设施的战争罪，将保留追究权利。',
    publishedAt: '2026-03-03T11:00:00Z',
    hotRank: 66,
    likes: 125000,
    shares: 56000,
    comments: 18900,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irna-4',
    platform: 'x_twitter',
    authorName: 'IRNA',
    handle: 'IRNA_News',
    authorTitle: '伊通社英文',
    avatar: '🇮🇷',
    content: 'Red Crescent: 787 dead in Iran since US-Israel attacks. 9 hospitals hit. Civilian infrastructure destroyed. World must stop this genocide.',
    publishedAt: '2026-03-03T09:55:00Z',
    hotRank: 67,
    likes: 178000,
    shares: 72000,
    comments: 28100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irna-5',
    platform: 'telegram',
    authorName: 'IRNA 伊朗伊斯兰共和国通讯社',
    handle: 'IRNA_News',
    authorTitle: '官方通讯社',
    avatar: '🇮🇷',
    content: '外交部：美国与以色列对伊朗的侵略违反国际法。我们呼吁联合国安理会召开紧急会议，追究战争责任。',
    publishedAt: '2026-03-02T14:00:00Z',
    hotRank: 68,
    likes: 98000,
    shares: 42000,
    comments: 15600,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-presstv-2',
    platform: 'x_twitter',
    authorName: 'Press TV',
    handle: 'PressTV',
    authorTitle: '伊朗 Press TV 英文',
    avatar: '🇮🇷',
    content: 'LIVE: Revolutionary Guards hit US oil tanker in Persian Gulf. "US aggression will be met with decisive response." presstv.ir',
    publishedAt: '2026-03-05T12:50:00Z',
    hotRank: 69,
    likes: 156000,
    shares: 68000,
    comments: 22400,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-presstv-3',
    platform: 'x_twitter',
    authorName: 'Press TV',
    handle: 'PressTV',
    authorTitle: '伊朗 Press TV 英文',
    avatar: '🇮🇷',
    content: 'Tehran bazaar in ruins. Hospitals bombed. 176 children dead. This is not "targeted strike"—this is war crime. ICC must act. presstv.ir',
    publishedAt: '2026-03-03T12:00:00Z',
    hotRank: 70,
    likes: 198000,
    shares: 85000,
    comments: 31200,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irgc-2',
    platform: 'telegram',
    authorName: 'IRGC 伊斯兰革命卫队',
    handle: 'IRGC_Official',
    authorTitle: '革命卫队官方频道',
    avatar: '🇮🇷',
    content: '波斯湾：我海军对侵犯我国水域的美国油轮实施打击。任何侵略行为都将遭到成倍报复。',
    publishedAt: '2026-03-05T13:00:00Z',
    hotRank: 71,
    likes: 134000,
    shares: 62000,
    comments: 19800,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-irgc-3',
    platform: 'telegram',
    authorName: 'IRGC 伊斯兰革命卫队',
    handle: 'IRGC_Official',
    authorTitle: '革命卫队官方频道',
    avatar: '🇮🇷',
    content: '我们向以色列占领区发射了新一轮导弹。特拉维夫、海法等地的防空系统无法阻挡我们的决心。为领袖复仇。',
    publishedAt: '2026-03-03T11:15:00Z',
    hotRank: 72,
    likes: 145000,
    shares: 71000,
    comments: 22100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-iran-mfa-1',
    platform: 'x_twitter',
    authorName: 'Iran Foreign Ministry',
    handle: 'Iran_MFA',
    authorTitle: '伊朗外交部',
    avatar: '🇮🇷',
    content: 'US & Israel launched aggression against our sovereignty. We reserve the right to self-defense under UN Charter. International community must condemn this act.',
    publishedAt: '2026-03-01T12:00:00Z',
    hotRank: 73,
    likes: 112000,
    shares: 48000,
    comments: 16700,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-iran-mfa-2',
    platform: 'telegram',
    authorName: '伊朗外交部',
    handle: 'Iran_MFA',
    authorTitle: '伊朗外交部',
    avatar: '🇮🇷',
    content: '阿米尔-阿卜杜拉希扬外长：美国民众应看清谁在制造战争。我们愿与尊重国际法的国家对话，但不会在炮火下谈判。',
    publishedAt: '2026-03-02T16:00:00Z',
    hotRank: 74,
    likes: 89000,
    shares: 38000,
    comments: 14200,
    verified: true,
    faction: 'iran',
  },
  // ————— 微博：伊朗驻华使馆（大量新增）—————
  {
    id: 'sm-weibo-iran-1',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '【严正声明】美国与以色列对伊朗发动军事袭击，造成大量平民伤亡。伊朗保留根据《联合国宪章》进行自卫的权利。我们呼吁国际社会谴责这一侵略行径。',
    publishedAt: '2026-03-01T18:00:00Z',
    hotRank: 75,
    likes: 234000,
    shares: 98000,
    comments: 25600,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-2',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '伊朗红新月会最新数据：自美以袭击以来，伊朗境内已有 787 人遇难，其中 176 名为儿童。9 家医院遭袭。我们呼吁人道主义停火与公正调查。',
    publishedAt: '2026-03-03T10:00:00Z',
    hotRank: 76,
    likes: 312000,
    shares: 125000,
    comments: 32100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-3',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '纳坦兹核设施遭袭后，国际原子能机构评估无放射性后果。伊朗的核计划是和平的，受 IAEA 监督。对民用核设施的袭击是战争罪。',
    publishedAt: '2026-03-03T12:00:00Z',
    hotRank: 77,
    likes: 198000,
    shares: 78000,
    comments: 18900,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-4',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '感谢中国网友对伊朗人民的关心与支持。中方一贯主张通过对话解决分歧、反对单边军事行动。我们期待与所有爱好和平的国家一道，维护地区稳定。',
    publishedAt: '2026-03-02T14:30:00Z',
    hotRank: 78,
    likes: 456000,
    shares: 156000,
    comments: 42100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-5',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '【澄清】所谓「伊朗首先袭击」的说法不符合事实。美国与以色列于 3 月 1 日对伊朗发动大规模空袭，我们是在行使自卫权。',
    publishedAt: '2026-03-02T09:00:00Z',
    hotRank: 79,
    likes: 278000,
    shares: 112000,
    comments: 28900,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-6',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '德黑兰大巴扎是联合国教科文组织认定的文化遗产。其被毁是文明之殇。我们呼吁保护文化遗产，追究针对平民与文化的战争责任。',
    publishedAt: '2026-03-03T15:00:00Z',
    hotRank: 80,
    likes: 189000,
    shares: 72000,
    comments: 19800,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-7',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '伊朗外交部发言人：我们愿在相互尊重、平等的基础上与各方对话。但对话不能在被轰炸的同时进行。美国必须停止侵略。',
    publishedAt: '2026-03-04T11:00:00Z',
    hotRank: 81,
    likes: 156000,
    shares: 62000,
    comments: 16700,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-8',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '革命卫队声明：我方在波斯湾对侵犯我水域的美国油轮实施合法自卫。美国长期在波斯湾军事存在，威胁地区安全。',
    publishedAt: '2026-03-05T14:00:00Z',
    hotRank: 82,
    likes: 198000,
    shares: 78000,
    comments: 22100,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-9',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '【答网友问】关于撤侨：建议在伊中国公民关注外交部及使馆通知，避免前往高风险区域。使馆将全力提供领事协助。',
    publishedAt: '2026-03-03T16:00:00Z',
    hotRank: 83,
    likes: 125000,
    shares: 45000,
    comments: 12300,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-10',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '伊朗是《不扩散核武器条约》缔约国，核活动接受 IAEA 核查。将伊朗核计划污名化是战争借口。我们反对核武器，支持中东无核化。',
    publishedAt: '2026-03-02T20:00:00Z',
    hotRank: 84,
    likes: 167000,
    shares: 68000,
    comments: 15600,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-11',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '中国外交部多次呼吁各方冷静克制。我们赞赏中方立场。中东稳定符合包括中国、伊朗在内各国的利益。',
    publishedAt: '2026-03-04T09:00:00Z',
    hotRank: 85,
    likes: 289000,
    shares: 98000,
    comments: 23400,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-12',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '伊斯法罕、设拉子、阿瓦士……我们的城市正在遭受轰炸。这不是「精准打击」，这是对一国主权与平民的系统性攻击。',
    publishedAt: '2026-03-03T08:00:00Z',
    hotRank: 86,
    likes: 212000,
    shares: 85000,
    comments: 19800,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-13',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '联合国秘书长古特雷斯呼吁停火。我们支持通过政治途径解决危机。但停火必须是双向的，侵略必须停止。',
    publishedAt: '2026-03-02T22:00:00Z',
    hotRank: 87,
    likes: 145000,
    shares: 56000,
    comments: 12300,
    verified: true,
    faction: 'iran',
  },
  {
    id: 'sm-weibo-iran-14',
    platform: 'weibo',
    authorName: '伊朗驻华使馆',
    handle: 'IranEmbassyChina',
    authorTitle: '伊朗伊斯兰共和国驻华大使馆官方微博',
    avatar: '🇮🇷',
    content: '伊朗人民历经制裁与战争威胁，始终捍卫国家主权。我们感谢全球正义声音对侵略的谴责。真理与正义终将胜利。',
    publishedAt: '2026-03-05T10:00:00Z',
    hotRank: 88,
    likes: 267000,
    shares: 102000,
    comments: 28900,
    verified: true,
    faction: 'iran',
  },
]
