/**
 * 中东区域 · 种子事件数据 — LIFEOS-005 阶段2
 *
 * ⚠ 占位/示例：这些是中东关键地理监测点（航道/海峡）的结构化占位标记，
 * 用于打通"区域 → 数据 → 地图渲染"链路，**非真实情报**。
 * 阶段3 由 Iran 真实数据层（api/mock/targets）替换。
 */

import type { EventDetail } from '@/types/geo';

export const MIDEAST_SEED_EVENTS: EventDetail[] = [
  {
    id: 'me-hormuz',
    title: '霍尔木兹海峡 · 航道监测点',
    source: '公开态势整理 · 航运监测',
    timestamp: '2026-06-16T13:30:00Z',
    location: [56.3, 26.6],
    impact_level: 'high',
    category: 'waterways',
    description: '关键能源航道监测占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-bab',
    title: '曼德海峡 · 航道监测点',
    source: '公开态势整理 · 航运监测',
    timestamp: '2026-06-15T15:10:00Z',
    location: [43.3, 12.6],
    impact_level: 'medium',
    category: 'waterways',
    description: '关键航道过境风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-suez',
    title: '苏伊士运河 · 航道监测点',
    source: '公开态势整理 · 航运监测',
    timestamp: '2026-06-14T20:25:00Z',
    location: [32.35, 30.0],
    impact_level: 'medium',
    category: 'waterways',
    description: '运河通行与通航风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-basra',
    title: '巴士拉港 · 经济与通道韧性监测',
    source: '公开态势整理 · 港口与贸易',
    timestamp: '2026-06-16T10:05:00Z',
    location: [48.55, 30.5],
    impact_level: 'high',
    category: 'economic',
    description: '一带一路节点（港口/装卸/过境）占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-earthquake',
    title: '土耳其东南部 · 地震与余震预警',
    source: '公开态势整理 · 自然灾害',
    timestamp: '2026-06-15T07:20:00Z',
    location: [43.2, 37.0],
    impact_level: 'high',
    category: 'natural',
    description: '地震活动与余震风险占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-sandstorm',
    title: '伊拉克北部 · 沙尘暴与能见度预警',
    source: '公开态势整理 · 气象监测',
    timestamp: '2026-06-16T08:45:00Z',
    location: [51.0, 25.0],
    impact_level: 'medium',
    category: 'weather',
    description: '极端天气（沙尘暴）对航运/通行影响占位点（阶段3 接真实数据）',
  },
  {
    id: 'me-tehran-hotspot',
    title: '德黑兰 · 政治与安全热点',
    source: '公开态势整理 · 安全监测',
    timestamp: '2026-06-16T11:20:00Z',
    location: [51.42, 35.69],
    impact_level: 'critical',
    category: 'hotspots',
    description: '地区冲突核心政治中心，外交与军事信号敏感',
  },
  {
    id: 'me-riyadh-economic',
    title: '利雅得 · 欧佩克+产量政策监测',
    source: 'OPEC',
    timestamp: '2026-06-16T14:00:00Z',
    location: [46.72, 24.71],
    impact_level: 'high',
    category: 'economic',
    description: '原油定价与减产协议风向标',
  },
  {
    id: 'me-gaza-conflicts',
    title: '加沙地带 · 人道与冲突监测',
    source: '公开态势整理 · 冲突监测',
    timestamp: '2026-06-15T16:00:00Z',
    location: [34.47, 31.5],
    impact_level: 'critical',
    category: 'conflicts',
    description: '人道停火谈判与跨境安全态势',
  },
  {
    id: 'me-beirut-hotspot',
    title: '贝鲁特 · 黎巴嫩安全热点',
    source: '公开态势整理 · 热点',
    timestamp: '2026-06-15T12:30:00Z',
    location: [35.5, 33.89],
    impact_level: 'high',
    category: 'hotspots',
    description: '真主党与以黎边境紧张态势',
  },
  {
    id: 'me-red-sea',
    title: '红海 · 商船袭击与绕行监测',
    source: '公开态势整理 · 航运安全',
    timestamp: '2026-06-16T09:00:00Z',
    location: [42.0, 15.0],
    impact_level: 'high',
    category: 'waterways',
    description: '胡塞武装威胁下商船改道好望角，运价抬升',
  },
  {
    id: 'me-natanz-nuclear',
    title: '纳坦兹 · 核设施监测点',
    source: 'IAEA',
    timestamp: '2026-06-14T10:00:00Z',
    location: [51.73, 33.72],
    impact_level: 'critical',
    category: 'nuclear',
    description: '铀浓缩设施，国际核查与制裁焦点',
  },
  {
    id: 'me-dimona-nuclear',
    title: '迪莫纳 · 核设施参考点',
    source: '公开态势整理 · 战略',
    timestamp: '2026-06-13T08:00:00Z',
    location: [35.15, 31.0],
    impact_level: 'high',
    category: 'nuclear',
    description: '以色列未加入 NPT 的核能力争议焦点',
  },
  {
    id: 'me-dubai-economic',
    title: '迪拜 · 区域金融与转口贸易',
    source: '公开态势整理 · 经济指标',
    timestamp: '2026-06-16T13:30:00Z',
    location: [55.27, 25.2],
    impact_level: 'high',
    category: 'economic',
    description: '冲突背景下资本流动与航运保险成本',
  },
  {
    id: 'me-aden-waterway',
    title: '亚丁湾 · 反海盗与护航监测',
    source: 'IMO',
    timestamp: '2026-06-15T20:00:00Z',
    location: [45.0, 12.8],
    impact_level: 'medium',
    category: 'waterways',
    description: '多国海军护航与商船保险费率',
  },
  {
    id: 'me-turkey-earthquake',
    title: '土耳其东南部 · 地震余震监测',
    source: 'USGS / AFAD',
    timestamp: '2026-06-15T07:20:00Z',
    location: [38.0, 37.0],
    impact_level: 'high',
    category: 'natural',
    description: '2023 大地震后基础设施重建与余震风险',
  },
  {
    id: 'me-syria-conflicts',
    title: '叙利亚 · 多方势力交织监测',
    source: '公开态势整理 · 冲突',
    timestamp: '2026-06-14T14:00:00Z',
    location: [36.28, 33.51],
    impact_level: 'high',
    category: 'conflicts',
    description: '俄、伊朗、土耳其及地方武装多方博弈',
  },
  {
    id: 'me-jordan-water',
    title: '亚喀巴湾 · 约旦港口与通道监测',
    source: '公开态势整理 · 航运',
    timestamp: '2026-06-16T08:30:00Z',
    location: [35.0, 29.5],
    impact_level: 'medium',
    category: 'waterways',
    description: '红海危机下替代港口负荷上升',
  },
  {
    id: 'me-cairo-diplomatic',
    title: '开罗 · 加沙人道斡旋监测',
    source: '公开态势整理 · 外交',
    timestamp: '2026-06-15T11:00:00Z',
    location: [31.24, 30.04],
    impact_level: 'high',
    category: 'conflicts',
    description: '埃及居中协调人道走廊与停火谈判',
  },
  {
    id: 'me-kuwait-economic',
    title: '科威特城 · 欧佩克+政策信号',
    source: 'OPEC',
    timestamp: '2026-06-16T15:00:00Z',
    location: [47.97, 29.37],
    impact_level: 'medium',
    category: 'economic',
    description: '减产延期与补偿性减产讨论',
  },
  {
    id: 'me-oman-waterway',
    title: '马斯喀特 · 阿曼湾替代航线',
    source: '公开态势整理 · 航运',
    timestamp: '2026-06-15T17:00:00Z',
    location: [58.54, 23.61],
    impact_level: 'medium',
    category: 'waterways',
    description: '部分油轮改道阿曼湾规避霍尔木兹风险',
  },
  {
    id: 'me-iraq-weather',
    title: '巴士拉 · 沙尘与能见度预警',
    source: '公开态势整理 · 气象',
    timestamp: '2026-06-16T06:00:00Z',
    location: [47.78, 30.51],
    impact_level: 'medium',
    category: 'weather',
    description: '沙尘影响南部油田作业与港口装卸',
  },
  {
    id: 'me-yemen-redsea',
    title: '荷台达港 · 红海人道与航运',
    source: '公开态势整理 · 热点',
    timestamp: '2026-06-14T12:00:00Z',
    location: [42.95, 14.8],
    impact_level: 'high',
    category: 'hotspots',
    description: '胡塞控制区港口，人道物资与袭击风险交织',
  },
  {
    id: 'me-qatar-lng',
    title: '拉斯拉凡 · 全球最大 LNG 基地',
    source: '公开态势整理 · 能源',
    timestamp: '2026-06-16T12:00:00Z',
    location: [51.55, 25.92],
    impact_level: 'high',
    category: 'economic',
    description: '欧洲与亚洲抢气推升现货溢价',
  },
  {
    id: 'me-israel-military',
    title: '内瓦提姆空军基地 · 军事动态',
    source: '公开态势整理 · 军事',
    timestamp: '2026-06-15T20:30:00Z',
    location: [34.69, 31.21],
    impact_level: 'high',
    category: 'military',
    description: '以军远程打击与防空拦截前沿节点',
  },
  {
    id: 'me-abu-dhabi-bases',
    title: '阿布扎比 · 美军前沿基地群',
    source: '公开态势整理 · 基地',
    timestamp: '2026-06-16T11:00:00Z',
    location: [54.37, 24.45],
    impact_level: 'high',
    category: 'bases',
    description: '达夫拉基地与区域防空部署',
  },
  {
    id: 'me-erbil-military',
    title: '埃尔比勒 · 库尔德地区军事态势',
    source: '公开态势整理 · 军事',
    timestamp: '2026-06-15T14:30:00Z',
    location: [44.01, 36.19],
    impact_level: 'medium',
    category: 'military',
    description: '伊拉克北部美军与联军存在',
  },
  {
    id: 'me-sanaa-conflicts',
    title: '萨那 · 也门内战前沿',
    source: '公开态势整理 · 冲突',
    timestamp: '2026-06-14T10:00:00Z',
    location: [44.21, 15.35],
    impact_level: 'high',
    category: 'conflicts',
    description: '胡塞与沙特领导的联军对峙',
  },
  {
    id: 'me-amman-diplomatic',
    title: '安曼 · 地区外交斡旋中心',
    source: '公开态势整理 · 外交',
    timestamp: '2026-06-16T09:00:00Z',
    location: [35.93, 31.95],
    impact_level: 'medium',
    category: 'conflicts',
    description: '约旦居中协调加沙与叙利亚议题',
  },
  {
    id: 'me-fujairah-waterway',
    title: '富查伊拉 · 绕过霍尔木兹的石油港',
    source: '公开态势整理 · 航运',
    timestamp: '2026-06-16T13:45:00Z',
    location: [56.35, 25.12],
    impact_level: 'high',
    category: 'waterways',
    description: '阿联酋东岸港口，霍尔木兹替代装船点',
  },
  {
    id: 'me-kirkuk-economic',
    title: '基尔库克 · 伊拉克北部油田',
    source: '公开态势整理 · 能源',
    timestamp: '2026-06-15T16:00:00Z',
    location: [44.39, 35.47],
    impact_level: 'medium',
    category: 'economic',
    description: '产区安全与出口管道运营',
  },
  {
    id: 'me-lebanon-weather',
    title: '黎巴嫩海岸 · 风暴潮预警',
    source: '公开态势整理 · 气象',
    timestamp: '2026-06-16T05:00:00Z',
    location: [35.5, 33.9],
    impact_level: 'low',
    category: 'weather',
    description: '冬季风暴影响港口与难民营地',
  },
  {
    id: 'me-sanctions-iran',
    title: '德黑兰 · 制裁与金融通道监测',
    source: 'OFAC',
    timestamp: '2026-06-16T12:30:00Z',
    location: [51.42, 35.69],
    impact_level: 'high',
    category: 'sanctions',
    description: '影子舰队与第三国转运网络',
  },
  {
    id: 'me-jun-hormuz',
    title: '霍尔木兹海峡 · 通行风险升级',
    source: '公开态势整理 · 航运监测',
    timestamp: '2026-06-15T08:00:00Z',
    location: [56.4, 26.57],
    impact_level: 'critical',
    category: 'waterways',
    description: '油轮保险费率飙升，部分船东绕行',
  },
  {
    id: 'me-jun-riyadh',
    title: '利雅得 · OPEC+ 产量政策',
    source: '公开态势整理 · 能源',
    timestamp: '2026-06-14T12:00:00Z',
    location: [46.72, 24.71],
    impact_level: 'high',
    category: 'economic',
    description: '减产延期与亚洲买家需求博弈',
  },
  {
    id: 'me-jun-gaza',
    title: '加沙地带 · 人道危机监测',
    source: '公开态势整理 · 热点',
    timestamp: '2026-06-15T06:00:00Z',
    location: [34.47, 31.5],
    impact_level: 'critical',
    category: 'hotspots',
    description: '援助通道与停火谈判敏感',
  },
  {
    id: 'me-jun-redsea',
    title: '红海 · 商船袭击风险',
    source: '公开态势整理 · 冲突',
    timestamp: '2026-06-14T18:00:00Z',
    location: [43.0, 15.0],
    impact_level: 'critical',
    category: 'conflicts',
    description: '胡塞武装威胁与护航编队部署',
  },
  {
    id: 'me-jun-bab',
    title: '曼德海峡 · 航运改道监测',
    source: '公开态势整理 · 航运',
    timestamp: '2026-06-13T10:00:00Z',
    location: [43.33, 12.58],
    impact_level: 'critical',
    category: 'waterways',
    description: '绕行好望角成本上升',
  },
  {
    id: 'me-jun-dubai',
    title: '迪拜 · 金融与转口贸易',
    source: '公开态势整理 · 经济',
    timestamp: '2026-06-15T14:00:00Z',
    location: [55.27, 25.2],
    impact_level: 'high',
    category: 'economic',
    description: '区域冲突下资本流动监测',
  },
  {
    id: 'me-jun-syria',
    title: '叙利亚 · 多方势力博弈',
    source: '公开态势整理 · 冲突',
    timestamp: '2026-06-12T08:00:00Z',
    location: [36.28, 33.51],
    impact_level: 'high',
    category: 'conflicts',
    description: '俄伊以多方军事存在',
  },
  {
    id: 'me-jun-iraq-oil',
    title: '巴士拉 · 伊拉克石油出口',
    source: '公开态势整理 · 能源',
    timestamp: '2026-06-14T08:00:00Z',
    location: [47.78, 30.5],
    impact_level: 'high',
    category: 'economic',
    description: '南部油田产能与管道安全',
  },
  {
    id: 'me-jun-yemen',
    title: '也门 · 胡塞武装海上威胁',
    source: '公开态势整理 · 军事',
    timestamp: '2026-06-13T16:00:00Z',
    location: [44.2, 15.35],
    impact_level: 'high',
    category: 'military',
    description: '反舰无人机与导弹袭击',
  },
  {
    id: 'me-jun-turkey',
    title: '伊斯坦布尔 · 黑海粮食走廊',
    source: '公开态势整理 · 外交',
    timestamp: '2026-06-11T12:00:00Z',
    location: [28.98, 41.01],
    impact_level: 'medium',
    category: 'waterways',
    description: '土耳其斡旋区域运输通道',
  },
];
