// 中东外交反应 — LIFEOS-005 阶段3 第六批
// 迁自 Iran conflictData.ts(diplomaticActors)，21 个国家/组织对冲突的立场与反应。
import type { DiplomaticActor } from '@/types/middleeast';

export const MIDEAST_DIPLOMACY: DiplomaticActor[] = [
  // ————— 中国与俄罗斯 —————
  {
    id: 'dip-cn',
    name: '中国',
    nameEn: 'China',
    type: 'country',
    region: 'china_russia',
    flag: '🇨🇳',
    stance: 'condemn_escalation',
    stanceLabel: '反对升级、呼吁克制',
    reactions: [
      { date: '2026-03-05', statement: '外交部：对波斯湾油轮遇袭、阿塞拜疆遭无人机等溢出效应表示关切，呼吁防止冲突外溢。', source: '新华社' },
      { date: '2026-03-03', statement: '商务部：将加强与中东能源供应方协调，保障进口多元化；必要时动用储备稳定市场。', source: '新华社' },
      { date: '2026-03-02', statement: '外交部：对美以军事行动导致地区局势升级深表关切，呼吁有关各方冷静克制，通过对话解决分歧。', source: '新华社' },
      { date: '2026-03-01', statement: '王毅：中方反对任何单边军事行动，主张维护伊核协议与中东稳定。', source: '外交部' },
    ],
  },
  {
    id: 'dip-ru',
    name: '俄罗斯',
    nameEn: 'Russia',
    type: 'country',
    region: 'china_russia',
    flag: '🇷🇺',
    stance: 'condemn_escalation',
    stanceLabel: '谴责美以、支持伊方立场',
    reactions: [
      { date: '2026-03-03', statement: '俄驻联合国代表：将推动安理会就「美国与以色列对伊朗的侵略」召开紧急会议，要求追究战争责任。', source: '塔斯社' },
      { date: '2026-03-02', statement: '俄外交部强烈谴责美国与以色列对伊朗的「侵略」，称将推动安理会讨论。', source: '塔斯社' },
      { date: '2026-03-01', statement: '拉夫罗夫：莫斯科反对颠覆主权国家政权，呼吁立即停火。', source: '俄外交部' },
    ],
  },
  // ————— 欧洲 —————
  {
    id: 'dip-eu',
    name: '欧盟',
    nameEn: 'European Union',
    type: 'org',
    region: 'europe',
    flag: '🇪🇺',
    stance: 'support_us_israel',
    stanceLabel: '与美协同应对伊朗导弹',
    reactions: [
      { date: '2026-03-02', statement: '欧盟与英法德同意与美国及盟友协同应对伊朗导弹攻击，支持「恢复地区稳定」。', source: 'BBC/CNN' },
      { date: '2026-03-01', statement: '博雷利：对冲突外溢深表担忧，呼吁各方避免平民伤亡。', source: '欧盟对外行动署' },
    ],
  },
  {
    id: 'dip-uk',
    name: '英国',
    nameEn: 'United Kingdom',
    type: 'country',
    region: 'europe',
    flag: '🇬🇧',
    stance: 'support_us_israel',
    stanceLabel: '允许美军使用基地、支援行动',
    reactions: [
      { date: '2026-03-03', statement: '库珀：政府包机将自阿曼撤侨；英方同意美方使用英军事基地对伊朗导弹阵地行动。', source: 'BBC' },
      { date: '2026-03-02', statement: '苏纳克政府批准美军使用英国基地，遭工党批评「未获议会充分授权」。', source: 'BBC' },
      { date: '2026-03-02', statement: '英国防部：HMS 邓肯号可能派往地中海，加强塞浦路斯基地防空。', source: 'BBC' },
    ],
  },
  {
    id: 'dip-de',
    name: '德国',
    nameEn: 'Germany',
    type: 'country',
    region: 'europe',
    flag: '🇩🇪',
    stance: 'support_us_israel',
    stanceLabel: '与盟国协同、关切能源与难民',
    reactions: [
      { date: '2026-03-02', statement: '德方同意与美及盟友协同应对伊朗导弹威胁，同时强调需避免冲突进一步扩大。', source: '德新社' },
    ],
  },
  {
    id: 'dip-fr',
    name: '法国',
    nameEn: 'France',
    type: 'country',
    region: 'europe',
    flag: '🇫🇷',
    stance: 'support_us_israel',
    stanceLabel: '支持盟国、呼吁保护平民',
    reactions: [
      { date: '2026-03-02', statement: '法国与美英德协调立场，支持对伊朗导弹威胁的应对，并呼吁保护平民与民用设施。', source: '法新社' },
    ],
  },
  // ————— 中东与海湾 —————
  {
    id: 'dip-sa',
    name: '沙特阿拉伯',
    nameEn: 'Saudi Arabia',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇸🇦',
    stance: 'neutral',
    stanceLabel: '谨慎中立、美使馆遭袭',
    reactions: [
      { date: '2026-03-02', statement: '美驻沙特使馆遭疑似伊朗无人机袭击，沙特未直接表态站队，强调「地区稳定」。', source: 'CNN' },
    ],
  },
  {
    id: 'dip-ae',
    name: '阿联酋',
    nameEn: 'UAE',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇦🇪',
    stance: 'neutral',
    stanceLabel: '中立、机场关闭与撤侨',
    reactions: [
      { date: '2026-03-03', statement: '富查伊拉油港起火，阿联酋加强防空；多国自迪拜等地撤侨。', source: 'BBC Verify' },
    ],
  },
  {
    id: 'dip-qa',
    name: '卡塔尔',
    nameEn: 'Qatar',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇶🇦',
    stance: 'mediate',
    stanceLabel: '斡旋与调停',
    reactions: [
      { date: '2026-03-02', statement: '卡塔尔作为美伊沟通渠道之一，表示愿为「任何严肃的降级与稳定努力」提供便利。', source: '路透' },
    ],
  },
  {
    id: 'dip-eg',
    name: '埃及',
    nameEn: 'Egypt',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇪🇬',
    stance: 'condemn_escalation',
    stanceLabel: '反对升级、关切加沙与难民',
    reactions: [
      { date: '2026-03-02', statement: '埃及呼吁各方克制，强调拉法口岸等人道通道不应因冲突而关闭。', source: '埃及外交部' },
    ],
  },
  {
    id: 'dip-tr',
    name: '土耳其',
    nameEn: 'Turkey',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇹🇷',
    stance: 'neutral',
    stanceLabel: '批评双方、强调北约与自身安全',
    reactions: [
      { date: '2026-03-02', statement: '埃尔多安批评「外部军事干预」加剧乱局，同时强调因吉尔利克等基地对北约的重要性。', source: '安纳多卢' },
    ],
  },
  {
    id: 'dip-om',
    name: '阿曼',
    nameEn: 'Oman',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇴🇲',
    stance: 'mediate',
    stanceLabel: '调停与撤侨中转',
    reactions: [
      { date: '2026-03-03', statement: '阿曼称伊朗对「任何严肃降级努力」持开放态度；英国首班撤侨包机将自马斯喀特起飞。', source: 'BBC' },
    ],
  },
  {
    id: 'dip-in',
    name: '印度',
    nameEn: 'India',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇮🇳',
    stance: 'neutral',
    stanceLabel: '关切能源与侨民、谨慎表态',
    reactions: [
      { date: '2026-03-03', statement: '印度外交部：对局势升级深表关切，呼吁克制；约 900 万侨民在中东，政府启动撤侨登记与包机协调。', source: 'PTI' },
      { date: '2026-03-02', statement: '印度石油部：正与沙特、阿联酋、伊拉克等保持沟通，保障原油供应；必要时释放战略储备。', source: '印度时报' },
    ],
  },
  {
    id: 'dip-jo',
    name: '约旦',
    nameEn: 'Jordan',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇯🇴',
    stance: 'condemn_escalation',
    stanceLabel: '反对升级、关切难民与边境',
    reactions: [
      { date: '2026-03-02', statement: '约旦外交部：反对任何导致地区全面战争的行为，强调需保护平民与民用设施；约旦境内已接收大量叙利亚与伊拉克难民。', source: '约旦通讯社' },
    ],
  },
  {
    id: 'dip-pk',
    name: '巴基斯坦',
    nameEn: 'Pakistan',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇵🇰',
    stance: 'condemn_escalation',
    stanceLabel: '呼吁克制、关切侨民与能源',
    reactions: [
      { date: '2026-03-03', statement: '巴外交部：对中东局势升级深表关切，呼吁各方克制；在 Gulf 务工人员众多，已启动领事协助与撤侨登记。', source: '巴通社' },
      { date: '2026-03-02', statement: '总理府：巴基斯坦与伊朗、沙特等保持沟通，支持通过对话解决分歧，反对军事升级。', source: '黎明报' },
    ],
  },
  {
    id: 'dip-id',
    name: '印度尼西亚',
    nameEn: 'Indonesia',
    type: 'country',
    region: 'middle_east_gulf',
    flag: '🇮🇩',
    stance: 'condemn_escalation',
    stanceLabel: '反对升级、呼吁停火',
    reactions: [
      { date: '2026-03-02', statement: '印尼外交部：对美以伊冲突导致平民伤亡表示遗憾，呼吁立即停火；作为穆斯林人口大国关注中东稳定。', source: '安塔拉' },
    ],
  },
  // ————— 国际组织 —————
  {
    id: 'dip-un',
    name: '联合国',
    nameEn: 'UN',
    type: 'org',
    region: 'international_org',
    flag: '🇺🇳',
    stance: 'condemn_escalation',
    stanceLabel: '呼吁停火与保护平民',
    reactions: [
      { date: '2026-03-05', statement: '安理会就「波斯湾航运安全与平民保护」举行闭门磋商；秘书长发言人重申反对任何针对民用航运的袭击。', source: 'UN News' },
      { date: '2026-03-03', statement: '联合国人道协调厅：伊朗、黎巴嫩、加沙等地平民伤亡激增，呼吁开放人道走廊与医疗准入。', source: 'UN News' },
      { date: '2026-03-02', statement: '古特雷斯：对中东局势急剧升级深表震惊，呼吁立即停火、保护平民与民用设施。', source: 'UN News' },
      { date: '2026-03-01', statement: '安理会举行紧急会议，多国谴责针对主权国家的「斩首」与军事升级。', source: '联合国' },
    ],
  },
  {
    id: 'dip-opec',
    name: '欧佩克 / 石油输出国组织',
    nameEn: 'OPEC',
    type: 'org',
    region: 'international_org',
    flag: '🛢️',
    stance: 'neutral',
    stanceLabel: '关切供应与油价',
    reactions: [
      { date: '2026-03-03', statement: 'OPEC+关注霍尔木兹海峡与波斯湾供应风险，称将评估市场状况；国际油价与天然气价格大幅波动。', source: '路透/ BBC' },
    ],
  },
  {
    id: 'dip-iaea',
    name: '国际原子能机构',
    nameEn: 'IAEA',
    type: 'org',
    region: 'international_org',
    flag: '☢️',
    stance: 'neutral',
    stanceLabel: '核查纳坦兹等设施、评估辐射',
    reactions: [
      { date: '2026-03-03', statement: 'IAEA 评估纳坦兹等设施遭袭后「预计无放射性后果」，将继续核查。', source: 'BBC Verify' },
    ],
  },
  // ————— 宗教势力（逊尼派与什叶派） —————
  {
    id: 'dip-sunni',
    name: '逊尼派（阿拉伯世界主流）',
    nameEn: 'Sunni',
    type: 'religious',
    region: 'religious',
    flag: '☪️',
    stance: 'neutral',
    stanceLabel: '多数国家谨慎、避免选边',
    reactions: [
      { date: '2026-03-02', statement: '沙特、阿联酋、埃及等逊尼派主导国家多持谨慎中立，既依赖美国安全承诺又担忧与伊朗全面对抗。', source: '综合' },
      { date: '2026-03-01', statement: '部分逊尼派宗教人士呼吁「团结抵御外敌」，但各国政府避免公开站队美以或伊朗。', source: '半岛' },
    ],
  },
  {
    id: 'dip-shia',
    name: '什叶派（伊朗、真主党、伊拉克民兵等）',
    nameEn: 'Shia axis',
    type: 'religious',
    region: 'religious',
    flag: '🕌',
    stance: 'support_iran',
    stanceLabel: '支持伊朗、真主党参战',
    reactions: [
      { date: '2026-03-01', statement: '黎巴嫩真主党宣布对以军基地发动报复「为哈梅内伊复仇」；伊拉克民兵声援伊朗。', source: 'CNN/BBC' },
      { date: '2026-03-01', statement: '什叶派宗教领袖多谴责美以行动，呼吁支持伊朗政权。', source: '综合' },
    ],
  },
]
