// 中东军事设施 — LIFEOS-005 阶段3 第四批
// 迁自 Iran conflictData.ts(facilities)，含基地/雷达/核/海军等 39 处，可上地图。
import type { Facility } from '@/types/middleeast';

export const MIDEAST_FACILITIES: Facility[] = [
  // ————— 美军及盟军基地 —————
  {
    id: 'fac-udeid',
    name: '乌代德空军基地',
    position: { lat: 25.1172, lng: 51.315 },
    faction: 'us',
    type: 'base',
    forces: ['美国空军', 'C4ISR', '加油机/轰炸机'],
    troopEstimate: '约 10,000+',
    weapons: ['THAAD', '爱国者', 'F-22', 'F-35', 'B-1'],
    notes: '美军中央司令部前沿枢纽，卡塔尔',
  },
  {
    id: 'fac-ali-salem',
    name: '阿里·萨利姆空军基地',
    position: { lat: 29.35, lng: 47.52 },
    faction: 'us',
    type: 'base',
    forces: ['美国空军', '陆军'],
    troopEstimate: '约 15,000',
    weapons: ['爱国者', 'F-15E', 'F-16', '阿帕奇'],
    notes: '科威特，距 F-15E 坠机点约 10km；曾遭无人机威胁',
  },
  {
    id: 'fac-dhafra',
    name: '阿尔达夫拉空军基地',
    position: { lat: 24.2483, lng: 54.5477 },
    faction: 'us',
    type: 'base',
    forces: ['美国空军', '阿联酋空军'],
    troopEstimate: '约 5,000',
    weapons: ['F-35A', 'F-16', 'U-2', '全球鹰'],
    notes: '阿联酋阿布扎比附近',
  },
  {
    id: 'fac-navcent',
    name: '美国海军第五舰队 / 巴林总部',
    position: { lat: 26.2235, lng: 50.5876 },
    faction: 'us',
    type: 'naval',
    forces: ['美国海军', '海军陆战队'],
    troopEstimate: '约 7,000+',
    weapons: ['宙斯盾舰', '濒海战斗舰', '海上巡逻机'],
    notes: '巴林，中央司令部海军司令部；周边曾遭袭',
  },
  {
    id: 'fac-incirlik',
    name: '因吉尔利克空军基地',
    position: { lat: 36.9939, lng: 35.4241 },
    faction: 'us',
    type: 'base',
    forces: ['美国空军', '土耳其空军'],
    troopEstimate: '约 3,000',
    weapons: ['F-16', '核武储存设施', '加油机'],
    notes: '土耳其阿达纳，北约南翼',
  },
  {
    id: 'fac-akrotiri',
    name: '英国皇家空军阿克罗蒂里基地',
    position: { lat: 34.59, lng: 32.99 },
    faction: 'us',
    type: 'airfield',
    forces: ['英国皇家空军', '美军可用'],
    troopEstimate: '约 3,500',
    weapons: ['F-35', '台风', '雷达与反无人机系统'],
    notes: '塞浦路斯，2026-03 遭无人机袭击后撤离家属',
  },
  {
    id: 'fac-al-asad',
    name: '阿萨德空军基地',
    position: { lat: 32.6692, lng: 42.3752 },
    faction: 'us',
    type: 'base',
    forces: ['美国空军', '陆军'],
    troopEstimate: '约 2,000',
    weapons: ['爱国者', 'F-16', '无人机'],
    notes: '伊拉克安巴尔省',
  },
  {
    id: 'fac-tanf',
    name: '坦夫基地',
    position: { lat: 33.35, lng: 38.83 },
    faction: 'us',
    type: 'base',
    forces: ['美国陆军', '联军'],
    troopEstimate: '约 200',
    weapons: ['火炮', '直升机', '反坦克'],
    notes: '叙利亚南部边境 55km 禁区',
  },
  {
    id: 'fac-fujairah',
    name: '富查伊拉石油码头/港区',
    position: { lat: 25.12, lng: 56.36 },
    faction: 'us',
    type: 'base',
    forces: ['海上安保'],
    troopEstimate: '少量',
    weapons: ['近防'],
    notes: '阿联酋，BBC 核实 2026-03 起火与损毁',
  },
  // ————— 以色列 —————
  {
    id: 'fac-ramon',
    name: '拉蒙空军基地',
    position: { lat: 30.7761, lng: 34.6669 },
    faction: 'israel',
    type: 'airfield',
    forces: ['以色列空军'],
    troopEstimate: '多中队',
    weapons: ['F-15I', 'F-16I', '防空'],
    notes: '内盖夫，主要打击与训练枢纽',
  },
  {
    id: 'fac-nevatim',
    name: '内瓦提姆空军基地',
    position: { lat: 31.2089, lng: 34.8814 },
    faction: 'israel',
    type: 'airfield',
    forces: ['以色列空军'],
    troopEstimate: '多中队',
    weapons: ['F-35I', 'F-16', '加油机'],
    notes: 'F-35I 主要部署点',
  },
  {
    id: 'fac-hatzerim',
    name: '哈泽里姆空军基地',
    position: { lat: 31.2381, lng: 34.6892 },
    faction: 'israel',
    type: 'airfield',
    forces: ['以色列空军'],
    troopEstimate: '多中队',
    weapons: ['F-16', '无人机'],
    notes: '飞行员与无人机训练',
  },
  {
    id: 'fac-tel-nof',
    name: '特尔诺夫空军基地',
    position: { lat: 31.8397, lng: 34.8214 },
    faction: 'israel',
    type: 'airfield',
    forces: ['以色列空军', '特种'],
    troopEstimate: '多中队',
    weapons: ['F-15', 'F-16', '加油机'],
    notes: '中部重要枢纽',
  },
  {
    id: 'fac-palmachim',
    name: '帕尔马希姆基地',
    position: { lat: 31.8961, lng: 34.6883 },
    faction: 'israel',
    type: 'naval',
    forces: ['以色列海军', '航天'],
    troopEstimate: '约 1,000+',
    weapons: ['萨尔级', '导弹艇', '卫星发射'],
    notes: '海上与航天设施',
  },
  {
    id: 'fac-dimona',
    name: '迪莫纳',
    position: { lat: 31.0833, lng: 35.0833 },
    faction: 'israel',
    type: 'nuclear',
    weapons: ['核研发设施'],
    notes: '内盖夫核设施',
  },
  // ————— 伊朗及代理人 —————
  {
    id: 'fac-t4',
    name: 'T-4 空军基地（叙）',
    position: { lat: 34.5236, lng: 37.6304 },
    faction: 'iran',
    type: 'airfield',
    forces: ['伊斯兰革命卫队航空'],
    troopEstimate: '数百',
    weapons: ['无人机', '短程弹道导弹'],
    notes: '叙利亚霍姆斯省，多次遭以军打击',
  },
  {
    id: 'fac-imam-ali',
    name: '伊玛目阿里基地',
    position: { lat: 33.12, lng: 47.45 },
    faction: 'iran',
    type: 'base',
    forces: ['伊斯兰革命卫队', '圣城旅'],
    troopEstimate: '约 2,000+',
    weapons: ['弹道导弹', '无人机', '防空'],
    notes: '伊拉克境内，IRGC 区域枢纽',
  },
  {
    id: 'fac-khatam',
    name: '哈塔姆·安比亚防空总部',
    position: { lat: 35.6892, lng: 51.389 },
    faction: 'iran',
    type: 'base',
    forces: ['伊斯兰革命卫队航空航天'],
    troopEstimate: '约 5,000+',
    weapons: ['霍达德', '巴瓦尔-373', '雷达网'],
    notes: '德黑兰，伊防空与导弹指挥中枢',
  },
  {
    id: 'fac-bushehr',
    name: '布什尔核电站',
    position: { lat: 28.8344, lng: 50.9472 },
    faction: 'iran',
    type: 'nuclear',
    weapons: ['民用反应堆'],
    notes: '波斯湾沿岸民用核设施',
  },
  {
    id: 'fac-natanz',
    name: '纳坦兹核设施',
    position: { lat: 33.72, lng: 51.73 },
    faction: 'iran',
    type: 'nuclear',
    forces: ['原子能组织'],
    troopEstimate: '技术/安保',
    weapons: ['离心机', '浓缩设施'],
    notes: 'BBC 核实 2026-03 多栋建筑遭损毁',
  },
  {
    id: 'fac-fordow',
    name: '福尔多地下浓缩设施',
    position: { lat: 34.88, lng: 50.99 },
    faction: 'iran',
    type: 'nuclear',
    forces: ['原子能组织'],
    troopEstimate: '技术/安保',
    weapons: ['离心机'],
    notes: '库姆附近地下设施',
  },
  {
    id: 'fac-bandar-abbas',
    name: '阿巴斯港海军基地',
    position: { lat: 27.1832, lng: 56.2666 },
    faction: 'iran',
    type: 'naval',
    forces: ['伊朗海军', '革命卫队海军'],
    troopEstimate: '约 5,000+',
    weapons: ['护卫舰', '快艇', '反舰导弹'],
    notes: '霍尔木兹海峡北侧，海军主要据点',
  },
  {
    id: 'fac-chabahar',
    name: '恰巴哈尔港/基地',
    position: { lat: 25.2919, lng: 60.6431 },
    faction: 'iran',
    type: 'naval',
    forces: ['伊朗海军'],
    troopEstimate: '约 1,000+',
    weapons: ['舰艇', '岸防'],
    notes: '阿曼湾，战略港口',
  },
  {
    id: 'fac-isfahan',
    name: '伊斯法罕核技术/研发设施',
    position: { lat: 32.6546, lng: 51.6680 },
    faction: 'iran',
    type: 'nuclear',
    weapons: ['研发', '转化'],
    notes: '核燃料循环相关',
  },
  {
    id: 'fac-parchin',
    name: '帕尔钦军事基地/导弹研发',
    position: { lat: 35.52, lng: 51.77 },
    faction: 'iran',
    type: 'missile',
    forces: ['伊斯兰革命卫队'],
    weapons: ['导弹研发', '高爆测试'],
    notes: '德黑兰东南，IAEA 关注站点',
  },
  {
    id: 'fac-shahid-hemmat',
    name: '沙希德·哈马内导弹工业',
    position: { lat: 32.38, lng: 51.45 },
    faction: 'iran',
    type: 'missile',
    weapons: ['弹道导弹', '航天'],
    notes: '伊斯法罕省，中程导弹生产',
  },
  {
    id: 'fac-qom-radar',
    name: '库姆预警雷达站',
    position: { lat: 34.64, lng: 50.88 },
    faction: 'iran',
    type: 'radar',
    weapons: ['早期预警雷达'],
    notes: '福尔多附近，防空预警',
  },
  // ————— 科威特/海湾 —————
  {
    id: 'fac-mina-ahmadi',
    name: '米纳·艾哈迈迪炼油/港区',
    position: { lat: 29.08, lng: 48.17 },
    faction: 'us',
    type: 'base',
    forces: ['安保/美方协调'],
    troopEstimate: '少量',
    weapons: ['近防'],
    notes: '科威特，2026-03 遭弹片击中、工人受伤',
  },
  {
    id: 'fac-shiraz',
    name: '设拉子空军基地',
    position: { lat: 29.54, lng: 52.59 },
    faction: 'iran',
    type: 'airfield',
    forces: ['伊朗空军', '伊斯兰革命卫队航空'],
    troopEstimate: '约 2,000+',
    weapons: ['F-14', 'F-4', 'F-5', '防空', '无人机'],
    notes: '伊朗南部主要空军枢纽，可覆盖波斯湾与霍尔木兹',
  },
  {
    id: 'fac-erbil',
    name: '埃尔比勒机场/联军协调点',
    position: { lat: 36.19, lng: 44.09 },
    faction: 'us',
    type: 'base',
    forces: ['美国陆军', '联军顾问'],
    troopEstimate: '约 1,000',
    weapons: ['防空', '直升机', 'C-RAM'],
    notes: '伊拉克库区，反恐与对伊态势监视',
  },
  // ————— 新增：美军/盟军 —————
  {
    id: 'fac-muwaffak',
    name: '穆瓦法克·萨尔蒂空军基地',
    position: { lat: 31.972, lng: 36.784 },
    faction: 'us',
    type: 'airfield',
    forces: ['约旦空军', '美国空军轮驻'],
    troopEstimate: '约 2,500',
    weapons: ['F-16', '爱国者', '雷达'],
    notes: '约旦扎尔卡附近，联军打击 ISIS 时常用',
  },
  {
    id: 'fac-prince-sultan',
    name: '苏尔坦王子空军基地',
    position: { lat: 24.07, lng: 47.58 },
    faction: 'us',
    type: 'base',
    forces: ['沙特空军', '美国空军可选'],
    troopEstimate: '约 5,000+',
    weapons: ['F-15SA', '爱国者', 'THAAD', '全球鹰'],
    notes: '沙特利雅得东南，曾为美军中东指挥节点',
  },
  {
    id: 'fac-azraq',
    name: '阿兹拉克联合行动基地',
    position: { lat: 32.30, lng: 36.45 },
    faction: 'us',
    type: 'base',
    forces: ['美国陆军', '联军'],
    troopEstimate: '约 1,500',
    weapons: ['爱国者', '直升机', '无人机'],
    notes: '约旦东部，反恐与边境监视',
  },
  // ————— 新增：以色列 —————
  {
    id: 'fac-ovda',
    name: '奥夫达空军基地',
    position: { lat: 29.56, lng: 34.96 },
    faction: 'israel',
    type: 'airfield',
    forces: ['以色列空军'],
    troopEstimate: '多中队',
    weapons: ['F-16', 'F-15', '加油机', '防空'],
    notes: '内盖夫南部，远程打击与训练',
  },
  {
    id: 'fac-haifa',
    name: '海法海军基地',
    position: { lat: 32.82, lng: 35.00 },
    faction: 'israel',
    type: 'naval',
    forces: ['以色列海军'],
    troopEstimate: '约 1,000+',
    weapons: ['萨尔级', '海豚级潜艇', '岸防'],
    notes: '地中海东岸主要军港',
  },
  // ————— 新增：伊朗 —————
  {
    id: 'fac-tabriz',
    name: '大不里士空军基地',
    position: { lat: 38.13, lng: 46.28 },
    faction: 'iran',
    type: 'airfield',
    forces: ['伊朗空军', '革命卫队航空'],
    troopEstimate: '约 1,500+',
    weapons: ['F-14', 'F-4', 'F-5', '防空', '无人机'],
    notes: '西北部枢纽，面向高加索与土耳其方向',
  },
  {
    id: 'fac-ahvaz',
    name: '阿瓦士空军基地',
    position: { lat: 31.34, lng: 48.76 },
    faction: 'iran',
    type: 'airfield',
    forces: ['伊朗空军'],
    troopEstimate: '约 1,000+',
    weapons: ['F-4', 'F-5', '防空'],
    notes: '胡齐斯坦省，靠近伊拉克边境',
  },
  {
    id: 'fac-lavan',
    name: '拉万岛海军/石油设施',
    position: { lat: 26.81, lng: 53.25 },
    faction: 'iran',
    type: 'naval',
    forces: ['伊朗海军', '革命卫队海军'],
    troopEstimate: '数百',
    weapons: ['快艇', '岸防', '雷达'],
    notes: '波斯湾岛屿，油库与海上前哨',
  },
  {
    id: 'fac-bandar-lengeh',
    name: '伦格港海军/岸防',
    position: { lat: 26.56, lng: 54.88 },
    faction: 'iran',
    type: 'naval',
    forces: ['革命卫队海军'],
    troopEstimate: '约 500+',
    weapons: ['快艇', '反舰导弹', '岸防'],
    notes: '霍尔木兹海峡北侧，扼守航道',
  },
  {
    id: 'fac-aludeid',
    name: '乌代德空军基地',
    position: { lat: 25.12, lng: 51.32 },
    faction: 'us',
    type: 'airfield',
    forces: ['美中央司令部'],
    notes: '海湾地区最大美军基地',
  },
  {
    id: 'fac-basra-oil',
    name: '巴士拉石油终端',
    position: { lat: 30.5, lng: 47.78 },
    faction: 'iraq',
    type: 'naval',
    notes: '伊拉克南部原油出口枢纽',
  },
  {
    id: 'fac-aden-port',
    name: '亚丁港',
    position: { lat: 12.8, lng: 45.03 },
    faction: 'yemen',
    type: 'naval',
    notes: '红海—亚丁湾咽喉港口',
  },
  {
    id: 'fac-jeddah-port',
    name: '吉达伊斯兰港',
    position: { lat: 21.48, lng: 39.17 },
    faction: 'sa',
    type: 'naval',
    notes: '红海最大港口，朝觐物流枢纽',
  },
  {
    id: 'fac-haifa-port',
    name: '海法港',
    position: { lat: 32.82, lng: 34.99 },
    faction: 'israel',
    type: 'naval',
    notes: '以色列最大海港',
  },
]
